### ISSUE TITLE
TypeScript error when using redux middleware

### ISSUE THREAD

**Issue by pReya** [pmndrs/zustand#1001]
Hey lovely zustand community,

I've read the documentation about using the redux middleware and how to use TypeScript with zustand. However I'm having trouble combining the two. Here is my minimal example to reproduce my problem:

```TypeScript
import create from "zustand";
import { redux } from "zustand/middleware";

export const actionTypes = {
  INCREMENT_MOVE_COUNTER: "INCREMENT_MOVE_COUNTER",
  INCREMENT_PAIR_COUNTER: "INCREMENT_PAIR_COUNTER",
};

interface StoreType {
  moveCounter: number;
  pairCounter: number;
}

const initialState: StoreType = {
  moveCounter: 0,
  pairCounter: 0,
};

const reducer = (state, action) => {
  switch (action.type) {
    case actionTypes.INCREMENT_MOVE_COUNTER: {
      return { ...state, moveCounter: state.moveCounter + 1 };
    }
    case actionTypes.INCREMENT_PAIR_COUNTER: {
      return { ...state, pairCounter: state.pairCounter + 1 };
    }
  }
};

export const useStore = create<StoreType>()(redux(reducer, initialState));
```

This will give me a very long TypeScript error on the last line, that I can't figure out how to interpret.

```
Argument of type 'StateCreator<Write<any, ReduxState<any>>, [], [["zustand/redux", any]], Write<any, ReduxState<any>>>' is not assignable to parameter of type 'StateCreator<StoreType, [], [["zustand/redux", any]], StoreType>'.
  Type 'StateCreator<Write<any, ReduxState<any>>, [], [["zustand/redux", any]], Write<any, ReduxState<any>>>' is not assignable to type '(setState: (partial: StoreType | Partial<StoreType> | ((state: StoreType) => StoreType | Partial<StoreType>), replace?: boolean) => void, getState: GetState<...>, store: StoreApi<...>, $$storeMutations: []) => StoreType'.
```

Any hints how I might be able to solve this?

**Comment by dai-shi** [comment]
@pReya You can check working version here: https://github.com/pmndrs/zustand/blob/main/tests/middlewareTypes.test.tsx

See how this works: https://tsplay.dev/WPRR5N

@devanshj Is `useBorkenStore` type fixable, or intended?

**Comment by pReya** [comment]
@dai-shi Thanks for the hint! It makes sense, that the redux middleware does not need the curried call and the generic type, since these can be coerced from the redux middleware call.

**Comment by devanshj** [comment]
> @devanshj Is useBorkenStore type fixable, or intended?

It's intended. It's complaining because the final state type would also have a `dispatch` which isn't present in the type passed to the curried `create`. Your version is the correct way to solve the problem but alternatively it can be solved like this too: https://tsplay.dev/WY44gm.

I'll edit the ts doc to mention that along with `combine`, when using `redux` too you shouldn't pass the state type.

**Comment by dai-shi** [comment]
> Your version is the correct way to solve the problem but alternatively it can be solved like this too: https://tsplay.dev/WY44gm.

Oh, I see. store type and reducer state type is different.
Hm, type assertion is unavoidable: https://tsplay.dev/Wz55Em

Thanks for clarification.

**Comment by devanshj** [comment]
> type assertion is unavoidable

Yes you'd have to make the assertion hence this fix is not recommended
