### ISSUE TITLE
TypeError: dispatcher.useSyncExternalStore is not a function

### ISSUE THREAD

**Issue by differentMonster** [pmndrs/zustand#1026]
```
TypeError: dispatcher.useSyncExternalStore is not a function

  19 |     const categorySlug = query.categorySlug
  20 | 
> 21 |     const addToCart = useCart((state) => state.addToCar
```t)

i am having this error when using zustand in component, how to fix this ? i am on nextjs, with react 18.1 package, being looking into website for this problem, but there is so less infomation about it.

**Comment by dai-shi** [comment]
That sounds very weird. Can you double check if it's using `react-dom>=18`?
You might want to create a nextjs app with zustand from scratch, which should work, and then you add things until you get the same error.

**Comment by dai-shi** [comment]
If you have further questions, please open a [new discussion](https://github.com/pmndrs/zustand/discussions/new).

**Comment by feuersteiner** [comment]
hi, same thing is happening to me on react 18.2.

I am calling the store in a controller ts file, then calling the controller in a tsx view.

This worked perfectly when the view is a pure react component, but now the error happens while using the canvas (using react-babylon, the react implementation of babylonjs)

here's the error happening :
<img width="607" alt="image" src="https://user-images.githubusercontent.com/18667704/185016963-d9a07642-9d81-44de-a293-dc29246c9f69.png">

**Comment by tuoxiansp** [comment]
Met the same problem while using react-pixi-fiber.

**Comment by feuersteiner** [comment]
thanks for the update @tuoxiansp 

the root of the issue from my side is how react-babylon-js handles its internal component state (because it is not a purely react component, it is coupled with babylonjs).

my fix was simply to list the state higher up to the Babylon component, and passing the changes as props inside that component, it solved it for me.

example:

instead of :
```typescript 
state = useStore(someState)

return <Model props={state} />
```

it became :
```typescript 
state = useStore(someState)

return <BabylonJS>
 <Model props={state} />
</BabylonJS>
```
hope it helps

**Comment by kresli** [comment]
> > Met the same problem while using react-pixi-fiber.
> 
> Resolved: just upgrade the version of the react-reconciler from 0.26.2 to 0.29 .
> 
> Seems like React will use `useSyncExternalStore` from reconciler, but the old version of reconciler does not contain the `useSyncExternalStore` .
> 
> Also I noticed that zustand was using a shim for `useSyncExternalStore`. I guess it doesn't work on the environment that contains both old and new versions of reconciler.

Same issue for me with react-pixi-fiber but above doesn't fixed the issue for me

**Comment by ekologic** [comment]
> > > Met the same problem while using react-pixi-fiber.
> > 
> > 
> > Resolved: just upgrade the version of the react-reconciler from 0.26.2 to 0.29 .
> > Seems like React will use `useSyncExternalStore` from reconciler, but the old version of reconciler does not contain the `useSyncExternalStore` .
> > Also I noticed that zustand was using a shim for `useSyncExternalStore`. I guess it doesn't work on the environment that contains both old and new versions of reconciler.
> 
> Same issue for me with react-pixi-fiber but above doesn't fixed the issue for me

Hitting the same issue here, were you able to fix this?

**Comment by dai-shi** [comment]
Downgrading to React 17 would probably fix. (until react-pixi-fiber supports React 18)

**Comment by SrBrahma** [comment]
@michalochman care to check this? I am also having this issue when accessing a Zustand store inside a component that is inside a `<Stage/>`.

**Comment by NumanAnees** [comment]
I am facing the same issue.

### dependencies:
      "react": "^18.2.0",
      "react-dom": "^18.2.0"

**Comment by ovoloshchenko** [comment]
> thanks for the update @tuoxiansp
> 
> the root of the issue from my side is how react-babylon-js handles its internal component state (because it is not a purely react component, it is coupled with babylonjs).
> 
> my fix was simply to list the state higher up to the Babylon component, and passing the changes as props inside that component, it solved it for me.
> 
> example:
> 
> instead of :
> 
> ```ts
> state = useStore(someState)
> 
> return <Model props={state} />
> ```
> 
> it became :
> 
> ```ts
> state = useStore(someState)
> 
> return <BabylonJS>
>  <Model props={state} />
> </BabylonJS>
> ```
> 
> hope it helps

for anyone out here in August 2024 - this is the solution that worked for me
for me this issue was happening while using react-pdf library
thank you @feuersteiner !
