### ISSUE TITLE
Basic example from docs not working

### ISSUE THREAD

**Issue by mdodell** [pmndrs/zustand#1037]
Hey y'all,

New to Zustand here. I'm trying out the docs, and created [a basic example](https://codesandbox.io/s/confident-stitch-l2fkgp?file=/pages/index.js) in Code Sandbox to showcase my issue. My sandbox is in NextJS - but the same error happens in a standard React app.

Here is what the basic example looks like: 

```javascript
import create from "zustand";

export default function IndexPage() {
  const useStore = create((set) => ({
    bears: 0,
    increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),
    removeAllBears: () => set({ bears: 0 })
  }));

  const bears = useStore((state) => state.bears);
  const increasePopulation = useStore((state) => state.increasePopulation);

  return (
    <div>
      <h1>{bears}</h1>
      <button onClick={increasePopulation}>increase population</button>
    </div>
  );
}

```

However, calling `increasePopulation` doesn't increase the values of bears. Is there something I'm missing from the documentation/an error that I'm making?

**Comment by duanwei913** [comment]
@mdodell You need to create the store outside of component, and subscribe to the store update within the component using `useStore`

**Comment by dai-shi** [comment]
@duanwei913 Thanks!

@mdodell Closing as resolved.
