### ISSUE TITLE
only one argument is being passed if multiple variables are imported as destructured object

### ISSUE THREAD

**Issue by antonibartula** [pmndrs/zustand#1054]
const {stateVariable1, stateVariable2, updateVariable1} = myStore(store => ({
        stateVariable1: store.stateVariable1 ,
        stateVariable2: store.stateVariable2,
        updateVariable1: store.updateVariable1,
    }))

updateVariable1(arg1, arg2)

the problem is that if I import variables to my component this way the function inside the store 
will only read 1st argument and ignore the second one. 

is it intended behavior or a bug?

**Comment by dai-shi** [comment]
If you have further questions, please open a [new discussion](https://github.com/pmndrs/zustand/discussions/new).
