### ISSUE TITLE
create<T>()() misunderstanding

### ISSUE THREAD

**Issue by httpete** [pmndrs/zustand#1060]
According to the Typescript.md:
The difference when using TypeScript is instead of writing create(...), you have to write create<T>()(...) where T would be type of the state so as to annotate it.

First, I don't understand what the ()() is doing, it seems to be related to currying (something I don't ever use) (sorry my ignorance) , secondly it seems to work fine without that. Must we change our create calls to have the ()() ?

Also, it would be better to use type only imports in zustand/context to separate the types from the functions like this:

//context.ts
```

import {
  createContext as reactCreateContext,
  createElement,
  useContext,
  useMemo,
  useRef,
  type ReactNode,
} from 'react';
import {
  useStore,
  type EqualityChecker,
  type State,
  type StateSelector,
  type StoreApi,
} from 'zustand';

**Comment by dai-shi** [comment]
In terms of JS implementation, it's just like this:
```js
const create = (createState) => createState ? createImpl(createState) : createImpl
```

https://github.com/pmndrs/zustand/blob/b06a8a017d92ed58ce5fb2f14c13b88b37d2b215/src/react.ts#L75-L77

It's a workaround to allow type inference. I know it's confusing. It's a technique by TS experts. 😎

**Comment by devanshj** [comment]
Also the explanation for the currying is given in the "Why that currying `()(...)`?" section of the doc, it's a popular workaround for https://github.com/microsoft/TypeScript/issues/10571.

**Comment by httpete** [comment]
Thanks for the lesson gents appreciate it
