### ISSUE TITLE
Bug in `shallow` when comparing dates

### ISSUE THREAD

**Issue by nvie** [pmndrs/zustand#1064]
Shallow treats dates incorrectly:

```ts
shallow(new Date('1970-01-01'), new Date('2022-07-08'))  // => true 🤯 
```

These dates are obviously not the same.

This is due to the fact that Dates have no enumerable keys, and as such `Object.keys(new Date())` returns `[]`. So it technically even compares true against `[]`:

```ts
shallow(new Date(), [])   // => true 🤯  
```

This is not only true for Dates, but would be a problem for any object that has no enumerable keys.

Even if this isn't considered a bug, it's inconsistent in this way:

```ts
shallow(new Date(), new Date())  // true
shallow([new Date()], [new Date()])  // false
```

In similar vein:

```ts
shallow({}, [])  // true 🤔 
```

**Comment by dai-shi** [comment]
I think it's originally designed for comparing two plain objects (or two arrays).
If you are interested fixing it, you could try it.

However, this makes me feel that we could deprecate `shallow` entirely and educate people to use other libraries such as lodash.

What I would do instead is to restrict what it supports.
```ts
export default function shallow<T extends unknown[], U extends unknown[]>(objA: T, objB: U): boolean
export default function shallow<T extends Record<string, unknown>, U extends Record<string, unknown>>(objA: T, objB: U): boolean
```
TS Playground: https://tsplay.dev/w8E2MN

**Comment by nvie** [comment]
Ah, I see — that makes a lot of sense if those are the only intended use cases. When I saw [these unit tests](https://github.com/pmndrs/zustand/blob/74de9eb6ba665333845986d305b97046b1fd3f91/tests/shallow.test.tsx#L4-L13) they seemed to imply this function was intended to handle more than just the array/object cases and also handle simple object identity. But if it's okay to explicitly declare the only intended use cases are arrays/objects, then I agree that the TypeScript solution is probably the way 👍
