### ISSUE TITLE
Store factory typings

### ISSUE THREAD

**Issue by Hrach-H** [pmndrs/zustand#1100]
So I'm trying to create a store factory which will essentially adds just one helper method to the initial state object:

```
import create, { type State } from "zustand";
import { combine, persist } from "zustand/middleware";

export const createPreferencesStore = <TState extends State>(initialState: TState, storageKey = "preferences") =>
  create(
    persist(
      combine(initialState, (setState) => ({
        setPreference: <TKey extends keyof TState>(key: TKey, value: TState[TKey]) => {
          setState({ [key]: value } as unknown as Partial<TState>);
        },
      })),
      { name: storageKey }
    )
  );
```

Before the last update everything worked fine, but now I have an error: _"TS4023: Exported variable 'createPreferencesStore' has or is using name 'StorePersist' from external module ".../node_modules/zustand/middleware/persist" but cannot be named."_ I understand that you have removed the StorePersist type from the exports? Is there any way to type the factory? I also think that the "as unknown as Partial<TState>" is not the correct way to type the function.

**Comment by dai-shi** [comment]
Thanks for reporting.
This is an unexpected regression with #1012.
I thought the refactor doesn't change anything, but it's not true. interfaces are hard for me.
Let me open a PR quickly.

**Comment by dai-shi** [comment]
Can you try #1101?
https://ci.codesandbox.io/status/pmndrs/zustand/pr/1101
Visit ☝️ and find "Local Install Instructions"

**Comment by Hrach-H** [comment]
It is fixed! 
Thank you for reacting so quickly :)

**Comment by dai-shi** [comment]
#1101 is closed.

Can you try #1106?
https://ci.codesandbox.io/status/pmndrs/zustand/pr/1106

**Comment by Hrach-H** [comment]
Sorry, completely forgot about it. Will try it out tomorrow.
