### ISSUE TITLE
setState failing after rc1 to rc2 update

### ISSUE THREAD

**Issue by reintroducing** [pmndrs/zustand#1115]
I'm using `store.setState` in some Cypress tests to set up my store externally. This is my code:
```js
import set from 'lodash/set';
import {useUserStore} from 'user/store';

const onOrgSwitch = () => {
    const {activeOrg} = useUserStore.getState();
    
    useUserStore.setState(set(activeOrg, 'planType', 'PACE'));
};
```
in rc2 it no longer works and the state is not updated and my tests fail. This is a snippet from a test file obviously but I can confirm this is the portion that is no longer working across multiple tests that do basically the same thing. Downgrading to rc1 fixes the issue and all the tests pass.

**Comment by reintroducing** [comment]
@dai-shi tagging you only to see if you have any input on my question above and so that you don't miss it if possible. thank you.

**Comment by reintroducing** [comment]
@dai-shi sorry, i don't mean to spam this, but I found something else thats interesting. I added this button to my component (which is using the store as well):
```js
<button
    data-test="new-toggle"
    onClick={() => {
        const {activeOrg} = useUserStore.getState();
        
        useUserStore.setState(set(activeOrg, 'planType', 'PACE'));
    }}
>
    Change
</button>
```
When I run my app and click that button, the store updates and the UI rerenders accordingly based on the `planType` in the `activeOrg` in the store. However, when I use Cypress to programmatically click that button using its `data-test` ID, the UI for this mounted component inside of the Cypress test does not change as I expect it to. It's almost as if, when running in Cypress, the store is detached from the component when using `getState()` and `setState()`. I'm not sure if I'm explaining this properly or if any of this makes sense as its pretty stream of consciousness, but thats where I'm netting out now.

**Comment by reintroducing** [comment]
lol, ok sorry, i PROMISE im not trying to spam you, but basically I think I figured out that what is happening is that, in the code above, the store is getting properly updated, but the component is not recognizing the update and not re-rendering therefore the UI does not reflect the new state. I have a useEffect listening for planType changes which then sets something on the component state to trigger the re-render, but because planType state update is not being listened for when setting it externally like above, the component is just not doing that re-render as expected. If I force the update in a timeout it works as expected and the UI updates based on the new planType.
```js
<button
    data-test="new-toggle"
    onClick={() => {
        const {activeOrg} = useUserStore.getState();
        
        useUserStore.setState(set(activeOrg, 'planType', 'PACE'));

        setTimeout(() => {
            setKey(Date.now()); // this state update of the `key` triggers the re-render and new planType is reflected in the UI
        }, 1000);
    }}
>
    Change
</button>
```

**Comment by dai-shi** [comment]
So, it has nothing to do with the difference between rc.1 and rc.2, right?
There's no JS code change between them.

**Comment by reintroducing** [comment]
@dai-shi correct, it happens in rc1 as well. I did upgrade cypress from 10.1 to 10.31 as part of this upgrade but I am not sure why it worked in the prior version and not the newest. I’m just not certain why there is the divergence of the store from the test variant to the non-test environment.

**Comment by dohomi** [comment]
@dai-shi this seems not to be fully covered yet. Here I can have still a typing interference issue:

```ts
import create from 'zustand'
import shallow from "zustand/shallow";

type RefetchState = {
    refetchTimestamp: string
}
export const useRefetchState = create<RefetchState>()(set => ({
    refetchTimestamp: ''
}))

export const useRefetchTimestamp = () => useRefetchState(state => state.refetchTimestamp, shallow)
// ERROR: TS2322: Type 'string' is not assignable to type 'Record<string, any>'.
```

**Comment by reintroducing** [comment]
@dai-shi I was able to resolve this by changing the way I'm setting the state object which is great, but given the below code, i'm confused by one works and the other doesn't (see inline comments):
```js
import { useEffect, useState } from "react";
import set from "lodash/set";
import { useUserStore } from "./store";

function App() {
  const [date, setDate] = useState(new Date());
  const firstName = useUserStore((state) => state.firstName);
  const lastName = useUserStore((state) => state.lastName);
  const { id, planType } = useUserStore((state) => state.activeOrg);
  const onClick = () => {
    const { activeOrg } = useUserStore.getState();
    const newOrg = set(activeOrg, "planType", "bar");

    // these two logs produce the same result
    console.log({ activeOrg: { ...activeOrg, planType: "bar" } });
    console.log({ activeOrg: newOrg });

    // this works as expected, the planType and date in the render below change accordingly
    useUserStore.setState({ activeOrg: { ...activeOrg, planType: "bar" } });
    // this does not work, the planType and date in the render below remain unchanged
    // useUserStore.setState({ activeOrg: newOrg });
  };

  useEffect(() => {
    setDate(new Date());
  }, [planType]);

  return (
    <div className="App">
      <p data-test="name">
        Hello {firstName} {lastName}
      </p>
      <p data-test="id">Org ID: {id}</p>
      <p data-test="plan">Plan Type: {planType}</p>
      <p data-test="date">Date: {date.toISOString()}</p>
      <button onClick={onClick}>Change App Date</button>
    </div>
  );
}

export default App;
```

**Comment by dai-shi** [comment]
I think you are mutating state, which is prohibited usage. It's same as how `useState` works.

```jsx
const Component = () => {
  const [state, setState] = useState({ foo: 1 })
  const handleClick = () => {
    const newState = set(state, 'foo', 2)
    setState(newState) // 👈 this doesn't trigger re-render
  }
  ...
}
```

**Comment by reintroducing** [comment]
@dai-shi youre absolutely right, ugh, I thought set returned s new object but it’s altering the object and thus the state is being mutated like you said. I apologize for all this noise, I think I’ve just been looking at this for too long and when it worked as originally written in my app there was probably a bug elsewhere that was making it pass. Thanks for letting me spam you here :)

**Comment by dai-shi** [comment]
For immutable updates, you could use mergeRight or something from ramda.
See also this wiki page: https://github.com/pmndrs/zustand/wiki/Updating-nested-state-object-values

**Comment by reintroducing** [comment]
Yeah, I looked over your docs and if this becomes an issue in my app (the state isn’t nested enough right now nor am I doing so many mutations that this is an issue I need to solve at this stage), I’ll probably opt for immer as it has a nice API and is lightweight. For now just destructuring a level or two deep isn’t bothering me that badly, especially since I’m doing most of it in test files rather than application code. 

Thanks for spitballing with me though, much appreciated.
