### ISSUE TITLE
Broken `PersistOptions['partialize']`

### ISSUE THREAD

**Issue by Rawnly** [pmndrs/zustand#1127]
I just bumped from `rc-1` to `rc-4` and found out that now the `partialize` func in the `persist` middleware is not returning a `Partial<State>` anymore. The only workaround i found right now is to cast the entire options object to `PersistOptions<State, Partial<State>>` and then cast it again to `any`.

Is this intended? Maybe I'm using the `partialize` func in the wrong way.. Shouldn't it be used to filter keys that have to bes stored?

An example impl below:

```ts
interface State {
	pageTitle?: string
	sidebarOpen: boolean
}

/* simplified (without setters) too keep it short */
const useLayoutState = create(
	persist<State>(
		set => ({
			sidebarOpen: true,
		}),
		{
			name: 'layout-state',
			partialize: ({ sidebarOpen }) => ({
				sidebarOpen,
			}),
		} as PersistOptions<State, Partial<State>> as any
	)
);
```

**Comment by dai-shi** [comment]
Related PR: #1051 

Hm, your example seems just fine without type assertions: https://tsplay.dev/NBylbw

**Comment by Rawnly** [comment]
> Related PR: #1051
> 
> Hm, your example seems just fine without type assertions: [tsplay.dev/NBylbw](https://tsplay.dev/NBylbw)

Uhm sorry, i over simplified the example, in my app i have some keys in the `State` interface which are not optional but i don't want them to be stored.

Something like [the following](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAYygUwIY2XAZlCI4BEAXgK4DOMqAdgCYEDcAUKJLHAN5xjJRnAVwAvtlz5i5SrQD0IYDRoAbZAHdUKBo2ZUMULKgSYAypQwdGcLqgDmyACrAYSgFxwKUYFStMLfGsgBGagDy3FQu-hAQStRMgppSAFSuLArAWMDINHAAFMoOABYQJPBkyDA6ZACUcDCRcADWyMhgcA6uhWwJUowIEFQC5MgAMqgAnkUwxuiYALyIKNPZ5lw8fBQAPFMYAHxLFhbZpTDVM9s57Mv7yX6BUCHIYTVQJMgANJdCle9XF1cWVKgQMgXAQFGMJgBaCjTAjfP5gNQwYCoVJEYHna4BYKhT5wU7nD5XXxYu6hOFXQRfD5xCyVRiVJhAA)
```ts
interface State {
	pageTitle: string;
	sidebarOpen: boolean;
}
```

**Comment by dai-shi** [comment]
Ah, I see.

Here's the right fix: https://tsplay.dev/mbBzbm

**Comment by Rawnly** [comment]
Thanks! Now is fine! You might want to update the [docs](https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data#partialize) too 🎉

**Comment by dai-shi** [comment]
Oops, forgot to link to the new docs.
https://github.com/pmndrs/zustand/blob/main/docs/persisting-store-data.md
Can you send a PR, if it can be improved?
