### ISSUE TITLE
useStore + selectors that return functions with Preact

### ISSUE THREAD

**Issue by birtles** [pmndrs/zustand#1137]
I tried updating to v4 on a Preact project today but I'm hitting issues with a selector that returns a function while using `useStore`. It appears that Preact is deciding to execute said function.

I've debugged this using Preact but I suspect it could apply to React too.

Following is my debugging which is probably a bit verbose but hopefully helps somewhat.

In Preact, `useState` is defined as:

```js
export function useState(initialState) {
  currentHook = 1;
  return useReducer(invokeOrReturn, initialState);
}
```

where `useReducer` is:

```js
export function useReducer(reducer, initialState, init) {
  const hookState = getHookState(currentIndex++, 2);
  hookState._reducer = reducer;
  if (!hookState._component) {
    hookState._value = [
      !init ? invokeOrReturn(undefined, initialState) : init(initialState),

      (action) => {
        const nextValue = hookState._reducer(hookState._value[0], action);
        if (hookState._value[0] !== nextValue) {
          hookState._value = [nextValue, hookState._value[1]];
          hookState._component.setState({});
        }
      },
    ];

    hookState._component = currentComponent;
  }

  return hookState._value;
}
```

and `invokeOrReturn` is:

```js
function invokeOrReturn(arg, f) {
  return typeof f == 'function' ? f(arg) : f;
}
```

As a result, when you call the `setState` callback, you effectively call the `dispatch` callback from the reducer, i.e.

```js
(action) => {
  const nextValue = hookState._reducer(hookState._value[0], action);
  if (hookState._value[0] !== nextValue) {
    hookState._value = [nextValue, hookState._value[1]];
    hookState._component.setState({});
  }
};
```

Now, `_reducer` here is `invokeOrReturn` so if the state (`action`) you pass in is a function, it will be executed with the current state (`hookState._value[0]`) as the argument.

So far, so good. This matches React's definition of `setState` so hopefully nothing Preact-specific this far.

When we use the new `useStore` function from v4 we get a call to `useSyncExternalStoreWithSelector` which uses the shim from the `use-sync-external-store` package but it ultimately ends up calling into Preact's version of `useSyncExternalStore` which is defined as follows:

```js
export function useSyncExternalStore(subscribe, getSnapshot) {
  const [state, setState] = useState(getSnapshot);

  // TODO: in suspense for data we could have a discrepancy here because Preact won't re-init the "useState"
  // when this unsuspends which could lead to stale state as the subscription is torn down.

  useEffect(() => {
    return subscribe(() => {
      setState(getSnapshot());
    });
  }, [subscribe, getSnapshot]);

  return state;
}
```

Notice the use of `useState` here.

Now, in zustand I have a store defined using the following function.

```js
export const createEditStore = () =>
  createStore<Immutable<EditState>>((set) => ({
    cardState: { kind: 'init' },
    dispatch: (event: EditEvent) => {
      set(
        produce((state: EditState) => {
          state.cardState = reduce({
            event,
            state: state.cardState,
            dispatch: state.dispatch,
          });
      );
    },
  }));
```

This allows fetching the `dispatch` function off the state in order to mutate it with actions that run through a separate reducer.

Accordingly there is a selector for that:

```js
export const getDispatch = (state: EditState) => state.dispatch;
```

which we can use as follows:

```js
const editStore = React.useContext(EditStoreContext);
const dispatch = useStore(editStore, getDispatch);
```

In the definition of `dispatch`, the call to `set` (`setState`) ends up triggering all listeners on the store--all of which are defined using `useSyncExternalStore` so presumably they are the places I'm using `useStore`.

They go to run the call to `setState(getSnapshot())` in Preact's definition of `useSyncExternalStore` which in turn runs `useReducer` passing in the result of the selector, which, in this case, is a function.

Preact sees a function being passed to `setState` and proceeds to execute it.

I've sunk an hour or two into this so far so I'll take a break for now, but let me know if you need minimal test case in order to reproduce it and I'll try to make time in the next few days for it.

**Comment by birtles** [comment]
I've filed https://github.com/preactjs/preact/issues/3632 over in the Preact repo since I suspect this is a Preact bug after all.

**Comment by dai-shi** [comment]
I wonder if it works if preact doesn't provide uSES.

**Comment by birtles** [comment]
> I wonder if it works if preact doesn't provide uSES.

I think so. It looks like this has now been [fixed upstream in Preact](https://github.com/preactjs/preact/pull/3633). I've applied the fix locally and it appears to resolve this issue.

I guess we can close this and wait for the next Preact release unless you have an idea of how to work around it in the interim.

**Comment by dai-shi** [comment]
Sounds good! Thanks for your investigation.
