### ISSUE TITLE
Persist middleware and SSR/SSG

### ISSUE THREAD

**Issue by kinoadr** [pmndrs/zustand#1145]
Hello 👋

I would like to know how, in your NextJS or any SSR/SSG project, did you use the persist middleware.

I have this issue on my project where the state persisted in the localstorage is retrieved before NextJS hydration. This means, the SSR/SSG render differs from the first client-side render, which causes the React tree to be out of sync.

My solution for this problem is to defer zustand hydration using a new option on the persist middleware. [Here is my custom persist middleware.](https://github.com/kinoadr/zustand/commit/d9f62ed58fa11cbc7a55e30354e6c58ac090cf71)

I resolve the given promise when I know the first client-side render is done. This triggers the persisted state to hydrate.

What do you think ?

**Comment by PAXANDDOS** [comment]
I also have just migrated to Zustand on my NextJS project, used the `persist middleware`, and then encountered severe problems including hydration, my head is aching now😵 
Hope your or any other solution gets implemented soon!

**Comment by AnatoleLucet** [comment]
Probably a dup of #510.
If you want to wait until the code is executed on the client, you can wrap your storage and include your logic in the `getItem` method. See [this comment](https://github.com/pmndrs/zustand/issues/583#issuecomment-975550065) for a practical example

**Comment by kinoadr** [comment]
Thank you @AnatoleLucet. I reworked the implementation of my custom persist middleware and use the given promise at the storage level, as your comment suggest. It looks like [this](https://gist.github.com/kinoadr/9766a45293ac9102471d96f218bd5eaa).

That being said, I look forward an "official" solution to this problem.

**Comment by AnatoleLucet** [comment]
Looks good!

> That being said, I look forward an "official" solution to this problem.

There's already a few ways to achieve what you want by using "official" APIs. For instance, you can create a [custom storage engine](https://github.com/pmndrs/zustand/blob/main/docs/persisting-store-data.md#how-can-i-use-a-custom-storage-engine), a wrapper middleware (like you did), or wait for [hydration directly in your components](https://github.com/pmndrs/zustand/blob/main/docs/persisting-store-data.md#how-can-i-check-if-my-store-has-been-hydrated).
I don't think this middleware needs more options to handle SSR/SSG frameworks. By somehow "creating" your own solution for your specific use case, you can handle hydration precisely the way you want.

Though i'm not saying i'm not open for suggestions, i just think adding a new option to "wait before hydrating" would be redundant since you can get exactly the same behavior by overriding/wrapping your storage's `setItem` method (which is not a hack).

**Comment by kinoadr** [comment]
From my perspective, I created my own solution to a not really specific but rather common problem.

The purpose of Zustand as a library is, in my opinion, to be able to delegate the implementation of a given set of features. As I understand whether or not SSR/SSG implementation should be included in this set of features is yet to be defined.

My only suggestion here is then to consider adding a more straightforward way to deal with SSR/SSG constraints. 😄

**Comment by charkour** [comment]
My team ran into the same issue that @kinoadr. We fixed the issue by using the `persist` middleware with a custom `getStorage` implementation. The key was to make `getitem` a true async function. This is because the [toThenable](https://github.com/pmndrs/zustand/blob/main/src/middleware/persist.ts#L96) is not an instance of Promise and Next.js will [not properly defer initializing](https://github.com/vercel/next.js/blob/canary/packages/next/server/render.tsx#L950) the zustand store.

```ts
getStorage: () => ({
  // Returning a promise from getItem is necessary to avoid issues with hydration
  getItem: async (name: string) => localStorage.getItem(name),
  setItem: (name: string, value: string) => localStorage.setItem(name, value),
  removeItem: (name: string) => localStorage.removeItem(name),
}),
```

I hope this helps. Thanks.

**Comment by toniopelo** [comment]
@charkour  Your fix is not working on my end with `next@12.2.4` `react@18.2.0` and `zustand@4.0.0`.
What version are you using ?
I'm not sure if I'm doing something wrong but it seems that on the really first draw, `zustand` already did the hydration of the store even when `getItem` is async.
A simple `console.log` after the `useStore` hook shows that it's hydrated since the beginning.
The only way I had this working was to put a `setTimeout` inside the `getItem` function like this
```ts
        getItem: (name: string) =>
          new Promise((res) => {
            // res(localStorage.getItem(name))
            setTimeout(() => res(localStorage.getItem(name)), 2000)
          }),
```

Consequence is the error we all know and love:
```
Error: Hydration failed because the initial UI does not match what was rendered on the server.
```

**Comment by charkour** [comment]
Hi @toniopelo, thanks for your workaround.

I'm using `next@12.2.2` `react@17.0.2` and `zustand@3.7.2` so it could very well be the fact I'm on old versions. Once I update my versions, I can let you know.

**Comment by admapop** [comment]
@AnatoleLucet Can we have a dedicated example for SSR? None of the examples on all these various issues have worked so far. I think it's clear it's becoming more and more a core issue with this library.

**Comment by admapop** [comment]
> @charkour Your fix is not working on my end with `next@12.2.4` `react@18.2.0` and `zustand@4.0.0`. What version are you using ? I'm not sure if I'm doing something wrong but it seems that on the really first draw, `zustand` already did the hydration of the store even when `getItem` is async. A simple `console.log` after the `useStore` hook shows that it's hydrated since the beginning. The only way I had this working was to put a `setTimeout` inside the `getItem` function like this
> 
> ```ts
>         getItem: (name: string) =>
>           new Promise((res) => {
>             // res(localStorage.getItem(name))
>             setTimeout(() => res(localStorage.getItem(name)), 2000)
>           }),
> ```
> 
> Consequence is the error we all know and love:
> 
> ```
> Error: Hydration failed because the initial UI does not match what was rendered on the server.
> ```
> 
> #### For those who end up in the same situation, I did this as a workaround
> ```ts
> const emptyState = {
>   where: {
>     places: [],
>   },
>   what: {
>     filters: {},
>   },
>   setPlaces: () => {
>     return
>   },
>   setFilters: () => {
>     return
>   },
> }
> const usePersistedStore = create(
>   persist<State>(
>     (set) => ({
>       where: {
>         places: [],
>       },
>       what: {
>         filters: {},
>       },
>       setPlaces: (newPlaces) =>
>         set({
>           where: {
>             places: newPlaces,
>           },
>         }),
>       setFilters: (filters) =>
>         set({
>           what: {
>             filters,
>           },
>         }),
>     }),
>     {
>       name: 'search-storage',
>     },
>   ),
> )
> 
> // This a fix to ensure zustand never hydrates the store before React hydrates the page
> // else it causes a mismatch between SSR/SSG and client side on first draw which produces an error
> export const useStore = ((selector, compare) => {
>   const store = usePersistedStore(selector, compare)
>   const [hydrated, setHydrated] = useState(false)
>   useEffect(() => setHydrated(true), [])
> 
>   return hydrated ? store : selector(emptyState)
> }) as typeof usePersistedStore
> ```
> 
> Not ideal of course, but better than a `setTimeout` 😛

Encountering the same issue as this. Whatever I try, store is always hydrated on first client render.

**Comment by a-toms** [comment]
A tided and deduplicated version:

```js
import create from 'zustand'
import { persist } from 'zustand/middleware'
import { useEffect, useState} from "react";


const emptyState = (set, get) => ({
  user: {
    isSignedIn: false,
  },
  setUser: async(userData) => {
    set({ user: {...userData} })
  },
  resetUser: () => {
    set({ user: {} })
  },
})

const usePersistedStore = create(
    persist(
        emptyState, 
        {name: 'user-storage'}
    ),
)

export const useHydratedStore = ((selector, compare) => {
  /*
  This a fix to ensure zustand never hydrates the store before React hydrates the page.
  Without this, there is a mismatch between SSR/SSG and client side on first draw which produces
  an error.
   */
  const store = usePersistedStore(selector, compare)
  const [isHydrated, setHydrated] = useState(false)
  useEffect(() => setHydrated(true), [])
  return isHydrated ? store : selector(emptyState)
})```

**Comment by laclance** [comment]
any one have a typed example please? I am also using slices, ie:
```export default create<Store>()(
  persist(
    (...a) => ({
      ...createCounterSlice(...a),
      ...createValueSlice(...a)
    }),
    { name: "boundStore" }
  )
);```

**Comment by MaheeGamage** [comment]
Apart from creating custom Zustand store components, this can tackle with HOC (or NextJS Layout) that wrap the main react component and waits till the first `useEffect` hook fire.
```
import { useEffect, useState } from "react"

const CustomLayout = ({ children }) => {

    const [isHydrated, setIsHydrated] = useState(false);

    //Wait till NextJS rehydration completes
    useEffect(() => {
        setIsHydrated(true);
    }, []);

    return (
        <> 
            {isHydrated ? ( <div>{children}</div> ) : <div>Loading...</div>}
        </>

export default CustomLayout;
```

**Comment by adriannecris** [comment]
Any updates on this issue? I'm currently following @MaheeGamage implementation but in _app.tsx,

**Comment by dohomi** [comment]
Just curious to know: is there a storage which might work client and server side? currently I am using localStorage and wrap my app with `next/dynamic` and ssr:false

**Comment by evgeny-rov** [comment]
If you are trying to use browser API it makes sense that you would have to wait for next to hydrate the page before trying to access localStorage, which means what you probably want is a CSR page or client-only component. 

My solution is to keep the page SSR, dynamically load the component that uses the client store, and render it on that page.
Which is what also suggested in the Next.js [docs](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr).

> To dynamically load a component on the client side, you can use the ssr option to disable server-rendering. This is useful if an external dependency or component relies on browser APIs like window.

```js
import dynamic from 'next/dynamic'

const DynamicHeader = dynamic(() => import('../components/header'), {
  ssr: false,
})
```

**Comment by dai-shi** [comment]
Closing as some workarounds are provided.

**Comment by pixelass** [comment]
Using TypeScript and Context.

I am using it like this, which has been working nicely so far: https://github.com/pixelass/pwa-template/blob/3601d4c542bec5da4a424d9f23727d52a3afeeb2/src/ions/store/index.ts

All related files: https://github.com/pixelass/pwa-template/tree/3601d4c542bec5da4a424d9f23727d52a3afeeb2/src/ions/store

Usage in `_app.tsx`: https://github.com/pixelass/pwa-template/blob/3601d4c542bec5da4a424d9f23727d52a3afeeb2/src/pages/_app.tsx#L43-L46

It uses React Context to store the mounted state, but that could also be stored in zustand or something smaller (e.g. [Jotai](https://github.com/pmndrs/jotai))

**Comment by ThomasF85** [comment]
Building on @pixelass solution, using Next 13 with App Router I am doing this:

Building a custom createStore function that returns the useStore hook and a Provider:
```js
import { persist } from "zustand/middleware";
import { create } from "zustand";
import { createContext, useContext, useEffect, useState } from "react";

export function createPersistedStore(createStore, persistOptions) {
  const StoreContext = createContext({ mounted: false });

  const StoreProvider = ({ children }) => {
    const [mounted, setMounted] = useState(false);
    useEffect(() => setMounted(true), []);

    return (
      <StoreContext.Provider value={mounted}>{children}</StoreContext.Provider>
    );
  };

  const usePersistedStore = create(persist(createStore, persistOptions));

  const initialState = createStore(
    () => {},
    () => createStore(() => {})
  );

  const useStore = (selector, compare) => {
    const store = usePersistedStore(selector, compare);
    const mounted = useContext(StoreContext);

    return mounted ? store : selector(initialState);
  };

  useStore.getState = usePersistedStore.getState;
  useStore.setState = usePersistedStore.setState;

  return { useStore, StoreProvider };
}
```

Initializing the store and provider:
```js
"use client";

import { createPersistedStore } from "./createPersistedStore";

export const { useStore, StoreProvider } = createPersistedStore(
  (set, get) => ({
    ...
  }),
  {
    name: "my-store"
  }
);
```

Using the Provider in the RootLayout component:
```js
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className={styles.main}>
          <StoreProvider>{children}</StoreProvider>
        </main>
      </body>
    </html>
  );
}
```

**Comment by kirkbushell** [comment]
> Building on @pixelass solution, I am doing this:
> 
> Building a custom createStore function:
> 
> ```js
> import { persist } from "zustand/middleware";
> import { create } from "zustand";
> import { useEffect } from "react";
> 
> export function createPersistedStore(createStore, persistOptions) {
>   const usePersistedStore = create(persist(createStore, persistOptions));
> 
>   const useMounted = create(() => false);
> 
>   const initialState = createStore(
>     () => {},
>     () => createStore(() => {})
>   );
> 
>   const useStore = (selector, compare) => {
>     const store = usePersistedStore(selector, compare);
>     const mounted = useMounted();
> 
>     useEffect(() => {
>       if (!mounted) {
>         useMounted.setState(true);
>       }
>     }, []);
> 
>     return mounted ? store : selector(initialState);
>   };
> 
>   useStore.getState = usePersistedStore.getState;
>   useStore.setState = usePersistedStore.setState;
> 
>   return useStore;
> }
> ```
> 
> Usage:
> 
> ```js
> import { createPersistedStore } from "./createPersistedStore";
> 
> export const useStore = createPersistedStore(
>   (set, get) => ({
>     ...
>   }),
>   {
>     name: "my-app-storage",
>   }
> );
> ```

This look like the right approach to me, however - it doesn't appear to be working. I get the following error:

```
TypeError: Cannot use 'in' operator to search for 'getStorage' in undefined
```

At this line:

```javascript
const usePersistedStore = create(persist(createStore, persistOptions));

```

**Comment by kirkbushell** [comment]
@ThomasF85 excuse my ignorance, but how are you then using the store across your app? useStore needs a reference to the store, which is creating a store, so it's circular?

**Comment by kirkbushell** [comment]
> Building on @pixelass solution, I am doing this:
> 
> Building a custom createStore function:
> 
> ```js
> import { persist } from "zustand/middleware";
> import { create } from "zustand";
> import { useEffect } from "react";
> 
> export function createPersistedStore(createStore, persistOptions) {
>   const usePersistedStore = create(persist(createStore, persistOptions));
> 
>   const useMounted = create(() => false);
> 
>   const initialState = createStore(
>     () => {},
>     () => createStore(() => {})
>   );
> 
>   const useStore = (selector, compare) => {
>     const store = usePersistedStore(selector, compare);
>     const mounted = useMounted();
> 
>     useEffect(() => {
>       if (!mounted) {
>         useMounted.setState(true);
>       }
>     }, []);
> 
>     return mounted ? store : selector(initialState);
>   };
> 
>   useStore.getState = usePersistedStore.getState;
>   useStore.setState = usePersistedStore.setState;
> 
>   return useStore;
> }
> ```
> 
> Usage:
> 
> ```js
> import { createPersistedStore } from "./createPersistedStore";
> 
> export const useStore = createPersistedStore(
>   (set, get) => ({
>     ...
>   }),
>   {
>     name: "my-app-storage",
>   }
> );
> ```

This should be the answer, and should be part of the Zustand codebase!
