### ISSUE TITLE
set function expects 3-4 parameters when used with devtools middleware (typescript)

### ISSUE THREAD

**Issue by SimonMueller** [pmndrs/zustand#1156]
**Expected**
When using `create` function with the devtools middleware i expect the store `set` function to work in the same way as it does without the middleware and produce no compilation error.

**Actual**

When using `create` function with the devtools middleware typescript emits a compilation error as it expects 3-4 params for the `set` function which is unexpected for me.

**Example to reproduce**

```javascript
import create from "zustand";
import { devtools } from "zustand/middleware";
import { immer } from "zustand/middleware/immer";

interface BearState {
  bears: number;
  increase: (by: number) => void;
}

const works = create<BearState>()((set) => ({
  bears: 0,
  increase: (by) => set((state) => ({ bears: state.bears + by })),
}));

const alsoWorks = create<BearState>()(
    immer((set) => ({
        bears: 0,
        increase: (by) => set((state) => ({ bears: state.bears + by })),
    }))
);


// Compilation Error at the call of "set((state) ...": TS2554: Expected 3-4 arguments, but got 1.
const doesntWork = create<BearState>()(
  devtools((set) => ({
    bears: 0,
    increase: (by) => set((state) => ({ bears: state.bears + by })),
  }))
);
```

**Versions**

typescript: 4.1.3
zustand: 4.0.0

**Comment by SimonMueller** [comment]
looks like a duplicate of: https://github.com/pmndrs/zustand/issues/1013

**Comment by dai-shi** [comment]
> looks like a duplicate of: #1013

yeah, closing.
