### ISSUE TITLE
Demo code-sandbox not working

### ISSUE THREAD

**Issue by ionif** [pmndrs/zustand#1158]
The live demo does not currently compile:

<img width="1288" alt="Screen Shot 2022-07-29 at 12 19 57 PM" src="https://user-images.githubusercontent.com/19884625/181811345-73674032-5279-442b-a751-1e89da004e97.png">

**Comment by dai-shi** [comment]
Thanks for reporting.

@rnike Can you investigate it? Maybe we should lock dependency versions in package.json (removing `^`).

**Comment by dai-shi** [comment]
See https://github.com/pmndrs/react-three-fiber/discussions/2402#discussioncomment-3270482 for a fix.

**Comment by rnike** [comment]
my mistake, I'll make a pr for it
