### ISSUE TITLE
TypeError: vanillaExports is not a function    

### ISSUE THREAD

**Issue by ShravanSunder** [pmndrs/zustand#1168]
Problem
- I'm using zustand v4 in a library (eth-hooks, written in typescript).   
- When i used this package in a vite app that (uses rollup to build and serve)

i get this error 
```
TypeError: vanillaExports is not a function
    at createImpl (index.js:20:51)
    at chunk-64K5LCRV.js:1:10870
```

zustand is part of the dependencies of this app.  if i don't have zustand as part of the dependencies i get 
```
TypeError: zustandExports is not a function
```

Any others thoughts on how to approach this issue?  i'm using tsup (esbuild) to build my library and vite to build the app. Should i make zustand a peer dependency in my library?

**Comment by ShravanSunder** [comment]
How can i import create (the react version) as a named import?  I think default imports and esbuild could be a culprit.  @dai-shi

**Comment by dai-shi** [comment]
vite should support ESM, and I expected it to pick `./esm/index.js`. But, if you are getting the error, does it pick `./index.js`? Curious how it happens. We may misunderstand something around "exports".

**Comment by ShravanSunder** [comment]
it seems to work in `vite dev mode (vite uses esbuild)`, but not `vite build`.  i'll try out the index.js

**Comment by dai-shi** [comment]
Interesting. Thanks for clarifying. So, `vite dev` and `vite build` behaves differently. Sounds like you can reproduce the issue without zustand?

**Comment by ShravanSunder** [comment]
> Interesting. Thanks for clarifying. So, `vite dev` and `vite build` behaves differently. Sounds like you can reproduce the issue without zustand?

@dai-shi 
Without zustand it seems to work with no issues.  I recently just added zustand into this library and app and have this error.  

when i try to use index.js in the library to import zustand i get this error
```
      pluginName: 'vite:dep-pre-bundle',
      text: 'Missing "./index.js" export in "zustand" package'
```

i am wondering if its because how my library builds and if its incompatible with how zustand is built?  i'm using esbuild with tsup to build eth-hooks

**Comment by ShravanSunder** [comment]
So it looks like its because of the way the zustand import is compiled by `esbuild`.  If i make tsup use rollup instead, there are no issues

cc: @dai-shi

**Comment by dai-shi** [comment]
Thanks for the investigation!

`./index.js` is CJS and `./esm/index.js` is ESM. I think you want to use the latter.
To make sure if ESM is really used, you can try deleting `node_modules/zustand/index.js` or something.

`vite dev` uses `esbuild`, right? wonder why tsup with esbuild goes wrong.
