### ISSUE TITLE
zustand v4 + Preact produces intermittent failures

### ISSUE THREAD

**Issue by birtles** [pmndrs/zustand#1178]
Now that this issue with Preact identified in #1137 (https://github.com/preactjs/preact/issues/3632) has been fixed and [Preact 10.10.1](https://github.com/preactjs/preact/releases/tag/10.10.1) has been released I was hoping to update to Zustand v4 but I've come across another issue.

Specifically, the definition of `useSyncExternalStore` in Preact is:

```js
export function useSyncExternalStore(subscribe, getSnapshot) {
  const [state, setState] = useState(getSnapshot);

  useEffect(() => {
    return subscribe(() => {
      setState(() => getSnapshot());
    });
  }, [subscribe, getSnapshot]);

  return state;
}
```

The trouble is with this definition is that it relies on `useEffect`. This can cause the `subscribe` function to be run too late.

For example, on the initial render, `useSyncExternalStore` and hence `useStore` returns the result of `getSnapshot` immediately. However, if the store is updated before effects are run, the `subscribe()` callback will not yet have been run and components relying on `useStore` will not be re-rendered since they are not yet registered as listeners of the store.

Due to this, our playwright tests running using the `webkit` project experienced very frequent failures after attempting to update to Zustand v4. The `chrome` and `firefox` tests appear to pass. (WebKit typically tries to reduce reflows on page load so this result is somewhat understandable.)

If I change Preact to use `useLayoutEffect`, the tests pass.

I'm not sure what the expected behavior for `useSyncExternalStore` is, so I'm not sure if this is a Preact bug or not. Presumably it is? If so, I'm happy to file it.

In the interim, I wonder if there is a convenient way to have Zustand to force the shimmed version of `useSyncExternalStore` to be used?

**Comment by dai-shi** [comment]
yeah, I wonder if this happens with the shim.
can you somehow undefine `useSyncExternalStore` from preact?
I would use `patch-package`.

**Comment by birtles** [comment]
> yeah, I wonder if this happens with the shim.
> can you somehow undefine `useSyncExternalStore` from preact?
> I would use `patch-package`.

Thanks!

I was going to try that but I saw something similar has been reported on Preact as https://github.com/preactjs/preact/issues/3654 and should be fixed by https://github.com/preactjs/preact/pull/3655.

Testing locally, it appears to work. I notice that PR also fairly closely matches the logic in `use-sync-external-store`'s shim code so hopefully it's correct.

I think we can close this issue for now and assume it is a Preact bug.
