### ISSUE TITLE
Redux middleware types are not exported

### ISSUE THREAD

**Issue by Shwvi** [pmndrs/zustand#1182]
I caught the ts error 4023 ⬇️
![image](https://user-images.githubusercontent.com/50517848/183837275-4f758dd7-0b4a-4f20-bcf9-36de5ea071a4.png)
Because the redux middleware types are not exported.
![image](https://user-images.githubusercontent.com/50517848/183792268-868f61b7-3362-4e7b-bcad-d74ac61c88a6.png)
I have seen one similar issue #1100, so could you please fix these type error?

**Comment by dai-shi** [comment]
https://github.com/pmndrs/zustand/blob/cf46b424551fd319dafb5fd56c48b3eb4d1959f0/src/middleware/redux.ts#L11-L13
It should be already fixed in the latest version.

**Comment by Shwvi** [comment]
> https://github.com/pmndrs/zustand/blob/cf46b424551fd319dafb5fd56c48b3eb4d1959f0/src/middleware/redux.ts#L11-L13
> 
> 
> It should be already fixed in the latest version.

The type ReduxState is not exported causing that variable 'useMyUserProfileExtension' has or is using name 'ReduxState' from external module "..../node_modules/zustand/middleware/redux" but cannot be named.

So shouldn't the type be exported? 

> https://github.com/pmndrs/zustand/blob/cf46b424551fd319dafb5fd56c48b3eb4d1959f0/src/middleware/redux.ts#L11-L13

like...

```ts
export type ReduxState<A extends Action> = { 
   dispatch: StoreRedux<A>['dispatch'] 
 } 
```

**Comment by dai-shi** [comment]
> I caught the ts error 4023 ⬇️ ![image](https://user-images.githubusercontent.com/50517848/183837275-4f758dd7-0b4a-4f20-bcf9-36de5ea071a4.png) Because the redux middleware types are not exported. ![image](https://user-images.githubusercontent.com/50517848/183792268-868f61b7-3362-4e7b-bcad-d74ac61c88a6.png) I have seen one similar issue #1100, so could you please fix these type error?

The problem was internal `interface`, which we no longer have. So, you shouldn't get 4023 error. Please update the library.

**Comment by Shwvi** [comment]
> 

OK, thanks. :)
