### ISSUE TITLE
Multiple `undefined` sections with broken links in the docs website

### ISSUE THREAD

**Issue by pedrossdemelo** [pmndrs/zustand#1191]
[Example](https://docs.pmnd.rs/zustand/v4-migration)

I would fix it myself but I couldn't find the repo for the docs website

**Comment by dai-shi** [comment]
docs content is here: https://github.com/pmndrs/zustand/tree/main/docs
docs website is there: https://github.com/pmndrs/website/tree/docs

**Comment by sewera** [comment]
This is an old issue, so I'll close it now.

For reference the full guide on contributing to the documentation
with all the info about where to find applicable repositories and branches
can be found in the [/CONTRIBUTING.md](https://github.com/pmndrs/zustand/blob/main/CONTRIBUTING.md) file.

Github also conveniently links the contributing guidelines at the bottom
of each issue:

<img width="528" alt="contributing guidelines link" src="https://user-images.githubusercontent.com/18354178/219379321-5582614c-1a65-4dca-95d3-744ceda54183.png">
