### ISSUE TITLE
Immer middleware not exported

### ISSUE THREAD

**Issue by Wiz1991** [pmndrs/zustand#1209]
```ts
export * from './middleware/redux';
export * from './middleware/devtools';
export * from './middleware/subscribeWithSelector';
export * from './middleware/combine';
export * from './middleware/persist';
```
These are the middlewares being exported and that do show up when trying to import them. Immer is not here, making it impossible to import. 
When doing:
```ts
import { immer } from 'zustand/middleware/immer'
```
I get the following error: 
```
Loading module from “http://localhost:5173/node_modules/.vite/deps/zustand_middleware_immer.js?v=df421ac0” was blocked because of a disallowed MIME type (“”)
```

**Comment by Wiz1991** [comment]
Fixed. 
After debugging for a bit more i discovered that the source code is using immer while not having it as a dependecy. So after installing immer, it's all working correctly. 

But this is off, shouldn't immer be added as a dep on zustand?

**Comment by dai-shi** [comment]
immer is listed as a peer dependency. because it's not always used, it shouldn't be a normal dependency.

**Comment by Wiz1991** [comment]
> 

Is that why its not exported like the rest of the middleware?

**Comment by dai-shi** [comment]
Yeah, exactly.
Otherwise, people have to install immer without using it.
