### ISSUE TITLE
(middlware/persist): Limitations are not documented

### ISSUE THREAD

**Issue by C-Otto** [pmndrs/zustand#1210]
Based on #618 and #652 there are limitations to what can be stored. Aside from the actual reasons for this limitation, users should be made aware of this. If this can be done using the typesystem for TypeScript users, that'd be great (I'm used to Java). If not, please add a big fat warning so that users don't run into issues. Without proper documentation, there's no way to know if the code you're going to write is going to work. Trial-and-error isn't a viably alternative for me, YMMV.

From #618:

> By default, persist serializes the state using JSON.stringify.
Unfortunately JSON doesn't fit very well with Sets and Maps.

To me that sounds like a bug, not a documentation issue. If JSON doesn't do what you need it to do, don't use JSON (or fix it).

**Comment by lkdm** [comment]
Should absolutely be documented.

If you want to use Maps or Sets, as a workaround you can convert objects that you know should be a Set or Map back into that, on load. We had to do this for one of our projects.

However, I recommend just using Arrays and `Record<string, unknown>` (object) types in your stores and persist.

**Comment by dai-shi** [comment]
With #1463, we will be able to customize storage to support Maps and Sets.

If anyone has ideas for more improvements, please feel free to open PRs.

**Comment by C-Otto** [comment]
Until #1463 is done, please document this behaviour so that users are not surprised. To me, using sets and maps isn't any different from using other data structures (and primitives). This doesn't match zustand's expectation/offering, causing frustration.

**Comment by C-Otto** [comment]
I stopped using JS/TS for my projects. Others might be interested in this, though.
