### ISSUE TITLE
[documentation update] Missing images & dead links audit

### ISSUE THREAD

**Issue by chrisk-7777** [pmndrs/zustand#1216]
Core conversation here: https://github.com/pmndrs/zustand/discussions/1033

There are missing images (like on the introduction page) and dead links (like on the v4 migration page).
The person on this issue should (manually) scan through the docs pages looking for missing images or broken links.

A single PR should be able to apply all the fixes

Blocked by: https://github.com/pmndrs/zustand/issues/1215

**Comment by chrisk-7777** [comment]
@lowellwashere2020 I can't assign it to you via Github, but I'll assume you're working on this one :)

**Comment by lowellwashere2020** [comment]
@chrisk-7777 Indeed. I'm on it.

**Comment by chrisk-7777** [comment]
Hi @drcmda , would you happen to know what the content of https://codesandbox.io/s/amazing-kepler-swxol was originally? It is referenced a few times in the Zustand docs but is no longer available. 

I haven't had much luck plucking it from waybackmachine.

**Comment by lowellwashere2020** [comment]
> Hi @drcmda , would you happen to know what the content of https://codesandbox.io/s/amazing-kepler-swxol was originally? It is referenced a few times in the Zustand docs but is no longer available.
> 
> I haven't had much luck plucking it from waybackmachine.

I haven't been able to find it either. I asked in the discord as well.
