### ISSUE TITLE
Document for state with URL hash.

### ISSUE THREAD

**Issue by guymoon** [pmndrs/zustand#1254]
### Discussed in https://github.com/pmndrs/zustand/discussions/1251

Add a state with URL Hash using `persist` middleware accepts custom storage like hashStorage.

**Comment by guymoon** [comment]
I work on this. Thank you!

**Comment by vadimshvetsov** [comment]
Hey @guymoon, thanks for this example that looks interesting on the zustand docs page.

Do you have any idea why it doesn't work even in this [codesandbox example](https://codesandbox.io/s/zustand-state-with-url-hash-demo-pn20n5?file=/src/store/index.ts)? When we refresh page url hash just updates to the initial state.
