### ISSUE TITLE
redux-middleware sandbox link broken

### ISSUE THREAD

**Issue by KaiSpencer** [pmndrs/zustand#1300]
The [link](https://codesandbox.io/s/amazing-kepler-swxol) to the example for redux-middleware shows 
Sandbox not found
<img width="1441" alt="Screenshot 2022-09-17 at 16 23 43" src="https://user-images.githubusercontent.com/51139521/190864318-1d5d3fd0-d777-4ecb-83e4-03f5306f6243.png">

**Comment by chrisk-7777** [comment]
I'll get this removed as per the comment here: https://github.com/pmndrs/zustand/pull/1231#issuecomment-1229575111

From wayback machine I think it might have been originally under drcmda's account (https://github.com/pmndrs/zustand/issues/1216#issuecomment-1236031336)

**Comment by chrisk-7777** [comment]
Addressed by #1302 

Thanks @KaiSpencer !
