### ISSUE TITLE
[Documentation] Link Issue for TS - `create` without curried workaround

### ISSUE THREAD

**Issue by kevin51jiang** [pmndrs/zustand#1313]
The sidebar on the [TypeScript page](https://docs.pmnd.rs/zustand/guides/typescript) leads to https://docs.pmnd.rs/zustand/guides/typescript#create-without-curried-workaround

When clicked on, it goes nowhere. However, if you go to 
https://docs.pmnd.rs/zustand/guides/typescript#undefined-without-curried-workaround it links to the proper section. 

This probably has something to do with the "`" tags around "create" in the header. 

![image](https://user-images.githubusercontent.com/33907581/192146524-d88c13ee-3ece-45f9-9160-32deb41a4272.png)

**Comment by dai-shi** [comment]
@chrisk-7777 can take a look?

**Comment by chrisk-7777** [comment]
Sure, assigned to myself. Thanks @kevin51jiang

**Comment by chrisk-7777** [comment]
Closed by merged PR here: https://github.com/pmndrs/website/pull/253#event-7479886533
