### ISSUE TITLE
Cannot find module 'immer' from 'node_modules/zustand/middleware/immer.js'

### ISSUE THREAD

**Issue by leandroluk** [pmndrs/zustand#1345]
Hello, I'm using zustand together with the immer middleware according to the code below:

```typescript
import zustand from 'zustand'
import { immer } from 'zustand/middleware/immer'

type CounterStore = {
  counter: number
  increment(): void
  decrement(): void
}

export const counterStore = zustand(immer<CounterStore>((set) => ({
  counter: 0,
  increment(){ set(state => state.counter++) },
  decrement(){ set(state => state.counter--) }
})))
```

But when I try to run tests using jest I get this error:

```shell
 FAIL  tests/pages/index.spec.tsx
  ● Test suite failed to run

    Cannot find module 'immer' from 'node_modules/zustand/middleware/immer.js'

    Require stack:
      node_modules/zustand/middleware/immer.js
      src/store/counterStore.ts
      src/store/index.ts
      src/pages/index.tsx

    However, Jest was able to find:
        './immer.d.ts'
        './immer.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'mjs', 'cjs', 'jsx', 'ts', 'tsx', 'json', 'node'].

    See https://jestjs.io/docs/configuration#modulefileextensions-arraystring
```

Jest is using the default "moduleFileExtensions" configuration as you can see in the error and the file having the "js" extension should be exported without any problem.

Has anyone caught this error?

**Comment by leandroluk** [comment]
Looking at the middleware code I saw that it imports the immer, and I thought it was not necessary to install it and that it was already internally in zustand because of the middleware. To solve the problem just install the immer

**Comment by Rec0iL99** [comment]
@leandroluk even I had faced this issue before and installing `immer` explicitly in my project did do the job. 

@dai-shi can this be solved by moving `immer` from the devDeps to first level deps in the library's `package.json`?
This would be helpful since the people using zustand need not explicitly install immer in their projects to use the immer middleware from zustand since immer would come installed with zustand out of the box.

**Comment by dai-shi** [comment]
Using `immer` is optional. Maybe quite a few people use it, but from the library perspective, it's not necessary. See also: https://github.com/pmndrs/zustand/blob/94dec53d9a0d061dd950d325ffe84d6fa1feb0ee/docs/guides/updating-state.md#deeply-nested-object

(fwiw, I personally wouldn't use immer with zustand.)

**Comment by dai-shi** [comment]
I think it's a doc issue. We don't yet have docs about `immer` middleware?

**Comment by Rec0iL99** [comment]
We do have docs on the `immer` middleware.
https://github.com/pmndrs/zustand/blob/main/docs/integrations/updating-draft-states.md

I think we need to add a section in the doc where we ask the user to install `immer`, if they want to use `immer` with `zustand`.

**Comment by dai-shi** [comment]
Ah, we do. Good. Yes, please open a PR.

**Comment by linonetwo** [comment]
Sometimes just bundler/packer don't support mjs, as immer start using it.

For example, in React native you need to:

```sh
npx expo customize metro.config.js
```

```js
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname);
const {
  resolver: { sourceExts },
  resolver,
} = config;

module.exports = {
  ...config,
  resolver: {
    ...resolver,
    sourceExts: [...sourceExts, 'mjs'],
  },
};
```
