### ISSUE TITLE
The example for createSelectors no longer works in zustand 4.1.3

### ISSUE THREAD

**Issue by jrobeson** [pmndrs/zustand#1389]
As seen here: https://github.com/pmndrs/zustand/blob/main/docs/guides/auto-generating-selectors.md and in the linked [codesandbox](https://codesandbox.io/s/zustand-auto-generate-selectors-forked-7wzsuz?file=/src/selectors.ts).  

Just set zustand to the latest version (4.1.3 as of this moment) and you'll see the type errors

**Comment by jrobeson** [comment]
maybe examples like this should be part of the test suite somehow. I'm not sure how that would work though.

**Comment by dai-shi** [comment]
Thanks for reporting. Looks like this is because the change in v4.1.0 #1144 and #1199.
From the library perspective, it's an intentional change.
Let's update the example. 
How's this: https://codesandbox.io/s/zustand-auto-generate-selectors-forked-y1zfso?file=/src/selectors.ts

**Comment by jrobeson** [comment]
works for me. my only suggestion is to explicitly type `s` in `(store.use as any)[k] = () => store((s) => s[k as keyof typeof s]);` 

Otherwise, it's nice. thanks :)

**Comment by dai-shi** [comment]
You are welcome to open a PR. I'll also let the doc/website team know and see if someone can take it.
