### ISSUE TITLE
Middleware that does not mutate the store cannot be composed with middleware that does (not)

### ISSUE THREAD

**Issue by joebobmiles** [pmndrs/zustand#1407]
Hi, I'm working on updating [zustand-middleware-yjs](/joebobmiles/zustand-middleware-yjs) to the latest version of Zustand. One of my tests is to verify composing middleware still works, and TypeScript is giving the following type error when I compose the Yjs middleware with the Immer middleware:

```
Argument of type 'StateCreator<Store, [], [["zustand/immer", never]], Store>' is not assignable to parameter of type 'StateCreator<Store, [], [], Store>'.
  Type 'StateCreator<Store, [], [["zustand/immer", never]], Store>' is not assignable to type '{ $$storeMutators?: [] | undefined; }'.
    Types of property '$$storeMutators' are incompatible.
      Type '[["zustand/immer", never]] | undefined' is not assignable to type '[] | undefined'.
        Type '[["zustand/immer", never]]' is not assignable to type '[]'.
          Source has 1 element(s) but target allows only 0.
```

From the docs I know there are two ways to type a middleware: the 'no mutation' style and the 'with mutation' style. The yjs middleware does not mutate the store, so I've opted for the former when choosing the types:

```ts
type Yjs = <
  T extends unknown,
  InMutators extends [StoreMutatorIdentifier, unknown][] = [],
  OutMutators extends [StoreMutatorIdentifier, unknown][] = []
>(
  doc: Y.Doc,
  name: string,
  creator: StateCreator<T, InMutators, OutMutators>,
) => StateCreator<T, InMutators, OutMutators>;

type YjsImpl = <T extends unknown>(
  doc: Y.Doc,
  name: string,
  creator: StateCreator<T, [], []>,
) => StateCreator<T, [], []>;
```

However, I also notice that while the Immer middleware technically _doesn't_ mutate the store, it still uses the later 'with mutation' style of typing. The two styles are incompatible according to TypeScript, but as far as I've seen, the documentation doesn't warn you from trying to compose middleware that use the different styles.

So are the two styles supposed to be compatible and is this a bug? Or are they incompatible and middleware intended to be composed together should always default to the 'with mutation' style of typing, and it's not documented?

**Comment by dai-shi** [comment]
@devanshj Could you help on this?

**Comment by devanshj** [comment]
Middlewares that change the store type and the middlewares that don't change the store type are compatible with each other.

I'll require a minimal reproduction of the error you're seeing to help you out, you can use the typescript playground (tip: you can use `declare const yjs: YourType` instead of writing the full implementation there), or a codesandbox, or if none of that works then a git repository.

Also immer does change the store type, `setState` in particular, you can check the source.

**Comment by joebobmiles** [comment]
Here's a reproduction in [TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAYygUwIY2QGjgbzgZRnWQGEV1ptDpkBZAVyJmgEkATZAOxmADNhkUOAF84vKBBBwARAC96AZyKc20gNwAoUJFi44oEIJFiJUuYuVsA9CGBs2AG2QB3VCisHB6reGjwAVHCoCnAAmiaSMgCeAFYK3howUWDIYXFwALxwADwacHAAKnDIAB4YKiH0nADWnBDOnJh5cCycDEzQIaXlbCEA2tQo7RRQ7Fw8-ILYVbX1nAC6ffOZcEtN+QDyjMPMUF1lXL2rg3SMI2PcfAJQ0zV1DYvLWUsaAHwAFM1sEAgAXGEAOgAIj91nBOKhDP8lFBgJwAOZgpBoXb-QjEMgo6DZArYVo7TrYLYwAl7V5NACUmVeBCYpHIuxxeLaZ12CiJ21ZnVemg0Vn8iWSqVCcRY4AcKxxxQOFTgM3unA+Xx+-1CwNBzQhULgMLhiOayJGaLpmJGTNW82wS3JGipGRp6IwpsZuItVvmPI0-isGg0HAQDjcqQQEE4SjgsQUqrivKSKVpNBWOANECqMH+nHoIAARlNmnDkYZuP93naaQA3CB2JrCXmGjDZE5K-KRz75fKcFyAkEIUtg-LSCSSaT9-QgQxQNvt-LvBTIGBluDvZPT6chtP-AAMo+nBZQRfTS7LzVX7bnMHes7px9Pp+XMnX3Gk0LpAMf8AA1HAAIzYYQUikdxECkTzgED8hAilNCAA)

**Comment by devanshj** [comment]
You're missing the extra `()` after `create` as shown in the typescript docs, [it works fine with it](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAYygUwIY2QGjgbzgZRnWQGEV1ptDpkBZAVyJmgEkATZAOxmADNhkUOAF84vKBBBwARAC96AZyKc20gNwAoUJFi44oEIJFiJUuYuVsA9CGBs2AG2QB3VCisHB6reGjwAVHCoCnAAmiaSMgCeAFYK3howUWDIYXFwALxwADwacHAAKnDIAB4YKiH0nADWnBDOnJh5cCycDEzQIaXlbCEA2tQo7RRQ7Fw8-ILYVbX1nAC6ffOZcEtN+QDyjMPMUF1lXL2rg3SMI2PcfAJQ0zV1DYvLWUsaAHwAFM1sEAgAXGEAOgAIj91nBOKhDP8lFBgJwAOZgpBoXb-QjEMgo6DZArYVo7TrYLYwAl7V5NACUmVeBCYpHIuxxeLaZ12CiJ21ZnVemg0Vn8iWSqVCcRY4AcKxxxQOFTgM3unA+Xx+-1CwNBzQhULgMLhiOayJGaLpmJGTNW82wS3JGipGRp6IwpsZuItVvmPI0-isGg0HAQDjcqQQEE4SjgsQUqrivKSKVpNBWOANECqMH+nHoIAARlNmnDkYZuP93naaQA3CB2JrCXmGjDZE4fCmffKR1v5cEuQEghClsH5aQSSTSAf6ECGKAdztwd4KZAwMuz5MzmchtP-AAMY5nBZQRfTs7LzVXnfnMHec7px9Pp-eeGk6+40mhdIBT-gAGo4ABGbDCCkKR3EQKRPOBQPyUCKU0IA).

---

@dai-shi I'd suggest adding an issue template that looks something like this...

Please fill this template if you're filling an issue for TypeScript, if not then remove it
- [ ] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or codesandbox with a minimal reproduction
- [ ] I've read the [typescript guide](https://github.com/pmndrs/zustand/blob/main/docs/guides/typescript.md), in particular that `create` is to be used as `create<T>()(...)` and not `create<T>(...)`.

I think we've come across many people falling for these mistakes so it makes sense to prompt them before they open an issue.

Again only a suggestion, please do what you see right.

**Comment by joebobmiles** [comment]
> I've read the [typescript guide](https://github.com/pmndrs/zustand/blob/main/docs/guides/typescript.md), in particular that create is to be used as create<T>()(...) and not create<T>(...).

I guess that's what I get for not paging through change notes and jumping from 3.5 to 4. It is devilishly easy to gloss over that initial parenthesis or even mistake it for a typo if you don't read that introductory paragraph.

Thanks for the help!

**Comment by devanshj** [comment]
Yes I understand, it's a bit unintuitive without the docs... Hence my suggestion has always been that we only have one way of writing it ie with extra parenthesis, in that case users won't need docs (as you'll have to call `create` with no parameters first or else it won't type-check).

**Comment by dai-shi** [comment]
> @dai-shi I'd suggest adding an issue template that looks something like this...

Yeah, let's do that.
