### ISSUE TITLE
Zustand produces SyntaxError in Chrome<66 (optional catch binding)

### ISSUE THREAD

**Issue by mskrzypek** [pmndrs/zustand#1427]
## SyntaxError in older browsers due to optional catch binding not transpiled

Zustand codebase utilizes "optional catch binding" JS feature (eg. here: https://github.com/pmndrs/zustand/blob/main/src/middleware/devtools.ts#L163) which is [ECMAScript Stage 4 proposal](https://github.com/tc39/proposal-optional-catch-binding) and is not supported in Chrome versions less than 66: https://caniuse.com/?search=optional%20catch%20binding

Probably due to wrong babel configuration, `try {} catch {}` syntax is not correctly transpiled to `try {} catch (e) {}`. This should be done automatically by [@babel/preset-env](https://babeljs.io/docs/en/babel-preset-env#modules) which contains [@babel/plugin-proposal-optional-catch-binding](https://babeljs.io/docs/en/babel-plugin-proposal-optional-catch-binding), but is not: https://unpkg.com/browse/zustand@4.1.4/esm/middleware.js

Wrong syntax produces "SyntaxError" in browsers like Chrome 65:

> Uncaught SyntaxError: Unexpected token {

![syntax](https://user-images.githubusercontent.com/777087/201734146-ea5b750e-e466-4ecf-9415-653506d962e5.png)

![image](https://user-images.githubusercontent.com/777087/201735327-500c3ce0-e292-4e70-b738-a5fc45c5b3bd.png)

**Comment by dai-shi** [comment]
Nice catch. Thanks for reporting.
Seems like you are using esm, not cjs.
cjs target is old browser, but esm target is modern.
I don't think it's easy to change the config only for this.

That said, it's the only one place we use optional catch binding (and I was a bit anxious), so let's change the source code.
Would you like to open a PR?
