### ISSUE TITLE
Zustand store in React context with Suspense causes server-client mismatch

### ISSUE THREAD

**Issue by max-ch9i** [pmndrs/zustand#1470]
## Summary

A combination of suspense, client context and zustand causes a server-client mismatch error. If suspense is removed, the behaviour is as expected.

The app structure overview:
```
<ContextProvider>: client component
- <Suspense>
-- <NavigationProvider>: server component
--- <Navigation>: client component
- <PageComponents>: client component
```

My guess as to what is happening:
1. On the server,  `<Navigation>` renders with theme `system`
2. On the client, `<PageComponents>` renders first and in `useEffect` updates theme to `dark`
3. Then, after a delay in `<Suspense>`, `<NavigationProvider>` renders `<Navigation>`, which receives theme `dark`
4. Mismatch error

## Link to reproduction

https://stackblitz.com/edit/nextjs-ydmeqq?file=app%2Flayout.js

## Check List

Please do not ask questions in issues.

- [x] I understand this is not a question.

**Comment by dai-shi** [comment]
> My guess as to what is happening:

In such a case, I don't think there's anything zustand can do.
Can you reproduce the issue without zustand? With `useState` or maybe with `useRef`. I think you can open an issue in nextjs repo.

Let's keep this issue open for a while.

**Comment by dai-shi** [comment]
Hmm, maybe we need to use `useSyncExternalStore` to reproduce it..

**Comment by dai-shi** [comment]
Changing store is invalid, and `useEffect` is required.
https://stackblitz.com/edit/nextjs-d1oqcx?file=app%2Fpage.js

I guess, you need suspense to reproduce the issue.
And, yeah, `getServerState` can be a solution.

**Comment by dai-shi** [comment]
No, it doesn't.
https://stackblitz.com/edit/nextjs-98e2ub?file=app%2FContextProvider.js

**Comment by dai-shi** [comment]
Ah, nice catch.

Then, I think the issue can be reproduced with useSyncExternalStore without zustand.

**Comment by OlegLustenko** [comment]
@JacobWeisenburger beware of this

![Screenshot_20230402-224903.png](https://user-images.githubusercontent.com/11524061/229375610-c619a7a6-3415-4ef2-86e9-2911f8a778ac.png)
