### ISSUE TITLE
Should shallow equality compare the order between two Sets?

### ISSUE THREAD

**Issue by impeiran** [pmndrs/zustand#1473]
Hi ~ thanks to your great works ! My question is the title you see
https://github.com/pmndrs/zustand/blob/0736a1c8bb54f5af3a5abc9ac043cf3abfc83004/src/shallow.ts#L25-L33
Here init the store
```typescript
const useBearStore = create((set) => ({
  bears: new Set(),
  updateBears: () => set((state) => ({
      bears: new Set(shuffle(...state.bears)) 
  })),
}))
```

And then get bears. It seems like bears would not update after the Set of bears being shuffled.
```typescript
import shallow from 'zustand/shallow'

const { bears } = useBearStore(
  (state) => ({ bears: state.bears }),
  shallow
)
```

**Comment by dai-shi** [comment]
https://en.wikipedia.org/wiki/Set_(abstract_data_type)
A set shouldn't depend on the order.
If you care the order, please consider using an array.
