### ISSUE TITLE
devtools order in documentation is wrong

### ISSUE THREAD

**Issue by martin-mok-hextrust** [pmndrs/zustand#1489]
## Summary
In https://docs.pmnd.rs/zustand/guides/typescript  
It said 

> we recommend using devtools middleware as last as possible. For example, when you use it with immer as a middleware, it should be immer(devtools(...)) and not devtools(immer(...)).

So I wonder if e.g. `devtools(immer(persist(...)))`should be the correct one.

## Link to reproduction
In https://docs.pmnd.rs/zustand/guides/typescript

**Comment by dai-shi** [comment]
I think "last" means inner most?
Can @devanshj confirm?

**Comment by devanshj** [comment]
The docs are correct. Here "last" means "last to mutate the store". There's also an example given precisely because the word "last" can be ambiguous here.

**Comment by martin-mok-hextrust** [comment]
So last means outer most?

**Comment by dai-shi** [comment]
No, the docs are correct. Especially the example. Closing.

**Comment by krystian50** [comment]
I've got the same confusion. The docs says 

> we recommend using devtools middleware as last as possible

And says this is the correct implementation

>  immer(devtools(...))

Which makes me wonder what is the definition of last. It's written last, but runs first. It's a bit confusing, but if you read 

> Hence using devtools at the end makes sure that no middlewares mutate setState before it

you can figure out what an author means. 

And a few lines before you have the example

>  devtools(persist(f, { name: 'bearStore' }))

Which now runs last, but is written first.

**Comment by dai-shi** [comment]
We had a similar discussion lately on Discord.
There seems to be some inconsistencies.
Let's make `middlewareTests.test.tsx` the source of truth, and update docs. (If some patterns are missing updating `middlewareTests.test.tsx` is also welcome.)
Would you like to open a PR?
