### ISSUE TITLE
Could not resolve immer

### ISSUE THREAD

**Issue by csulit** [pmndrs/zustand#1493]
## Summary

I followed the docs for the use of immer but I'm getting this error:

`optional-peer-dep:__vite-optional-peer-dep:immer:zustand:1 Uncaught Error: Could not resolve "immer" imported by "zustand". Is it installed?
    at optional-peer-dep:__vite-optional-peer-dep:immer:zustand:1:7`

My store:

```
import create from 'zustand';
import { immer } from 'zustand/middleware/immer';
import { ChatSessionStore } from '../typings';

const useChatSessionStore = create(
  immer<ChatSessionStore>((set) => ({
    chatSession: null,
  }))
);

export default useChatSessionStore;
```

## Check List

NodeJS: v16.17
Zustand: 4.1.5

- [x] I understand this is not a question.

**Comment by dai-shi** [comment]
can you install immer?
https://github.com/pmndrs/zustand/blob/4a99653967bd0ada4ed1a4bd77dc64eefdaf98ff/docs/integrations/immer-middleware.md#installation

**Comment by csulit** [comment]
> can you install immer? https://github.com/pmndrs/zustand/blob/4a99653967bd0ada4ed1a4bd77dc64eefdaf98ff/docs/integrations/immer-middleware.md#installation

Disregard my first reply. It works now I have to restart my VSCode.

**Comment by dai-shi** [comment]
🎉
