### ISSUE TITLE
Typescript Error when using Immer with custom "Reset Multiple Stores" function

### ISSUE THREAD

**Issue by KevinMusgrave** [pmndrs/zustand#1494]
## Summary

I'm using the `create` function defined in [this guide for resetting all stores](https://github.com/pmndrs/zustand/blob/main/docs/guides/how-to-reset-state.md). When I wrap a store with immer, I get a typescript error.

## Link to reproduction

The following sandbox is forked from the advanced example in the 'reset-state' guide.

https://codesandbox.io/s/zustand-with-immer-reset-all-stores-tme1b4

The typescript error is:

```
Argument of type 'StateCreator<StateSalmon & ActionsSalmon, [], [["zustand/immer", never]], StateSalmon & ActionsSalmon>' is not assignable to parameter of type 'StateCreator<StateSalmon & ActionsSalmon, [], [], StateSalmon & ActionsSalmon> | StoreApi<StateSalmon & ActionsSalmon>'.
  Type 'StateCreator<StateSalmon & ActionsSalmon, [], [["zustand/immer", never]], StateSalmon & ActionsSalmon>' is not assignable to type 'StateCreator<StateSalmon & ActionsSalmon, [], [], StateSalmon & ActionsSalmon>'.
    Type 'StateCreator<StateSalmon & ActionsSalmon, [], [["zustand/immer", never]], StateSalmon & ActionsSalmon>' is not assignable to type '{ $$storeMutators?: [] | undefined; }'.
      Types of property '$$storeMutators' are incompatible.
        Type '[["zustand/immer", never]] | undefined' is not assignable to type '[] | undefined'.
          Type '[["zustand/immer", never]]' is not assignable to type '[]'.
            Source has 1 element(s) but target allows only 0.ts(2345)
```

## Check List

Please do not ask questions in issues.

- [x] I understand this is not a question.

Please fill this template if you're filling an issue regarding TypeScript.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction. Or some other way of reproduction if these two don't suffice.
- [x] I've read the [typescript guide](https://github.com/pmndrs/zustand/blob/main/docs/guides/typescript.md), in particular that `create` is to be used as `create<T>()(...)` and not `create<T>(...)`.

**Comment by dai-shi** [comment]
It's because we don't follow "in particular that `create` is to be used as `create<T>()(...)`".

Should we remove the old example from the docs?
cc @Cuppachino @dbritto-dev

**Comment by KevinMusgrave** [comment]
Where should the additional `()` be applied in this case?

**Comment by dai-shi** [comment]
https://tsplay.dev/mZQBaN should be a workaround. I haven't tried if it really works.

Anyone, please open a PR to fix the doc. Thanks.

**Comment by dbritto-dev** [comment]
Hey peeps  what about this approach ? -> https://codesandbox.io/s/zustand-with-immer-reset-all-stores-forked-ouowtt?file=/src/App.tsx

CC: @dai-shi @KevinMusgrave

**Comment by dbritto-dev** [comment]
Hey peeps here's the other way to achieve the same -> https://codesandbox.io/s/zustand-with-immer-reset-all-stores-forked-nyet3f?file=/src/App.tsx

**Comment by dbritto-dev** [comment]
I can add an example for that and also update the previous ones to use the new typing approach so we can keep consistency between docs and examples

**Comment by dai-shi** [comment]
Yeah, that looks good too. Thanks! Please go ahead.

**Comment by KevinMusgrave** [comment]
Thank you, it works
