### ISSUE TITLE
default import for shallow is not working since 4.3.0

### ISSUE THREAD

**Issue by moklick** [pmndrs/zustand#1528]
## Summary

Since 4.3.0 `import shallow from 'zustand/shallow'` is not working anymore. 

## Link to reproduction

https://codesandbox.io/s/admiring-feather-0r46z8?file=/src/index.ts

**Comment by dai-shi** [comment]
Oh, nice catch. It's because we have two exports, the bundler produces different outputs.

**Comment by dai-shi** [comment]
#1531 fixes it: https://codesandbox.io/s/crazy-surf-bh6x7l

**Comment by stijnvanhulle** [comment]
@dai-shi I'm also having the same issue when using Commonjs(mainly for Jest now) with 4.3.0.

The vanilla export is with version 4.3.0 not resolving, see https://codesandbox.io/s/zustand-vanilla-cjs-3e9m52

**Comment by dai-shi** [comment]
@stijnvanhulle 
Does #1531 resolve it?
https://ci.codesandbox.io/status/pmndrs/zustand/pr/1531
Find "Local Install Instructions" ☝️

**Comment by stijnvanhulle** [comment]
@dai-shi Yes your latest commit fixes my issue 👍🏼

**Comment by stijnvanhulle** [comment]
@dai-shi Yes your latest commit fixes my issue 👍🏼
