### ISSUE TITLE
[Design bug / type issue][Middleware/persist] Overstrict type for persist serialization

### ISSUE THREAD

**Issue by ReillyBova** [pmndrs/zustand#1535]
## Background
The current `persist` middleware type for serialization output to the cache solution is `string`. This matches the output type of `JSON.stringify()`, which is the default serialization function.

While this makes sense as a default type, there is no strict implementation reason for `persist` to serialize to / deserialize from a `string` type. In fact, recasting the persist middleware in Typescript to use a different serialization intermediate type works just fine.... but recasting like this is extremely messy

```ts
interface ICustomPersistOptions<State, CacheState, ISerializedState>
    extends Omit<PersistOptions<State, CacheState>, "getStorage" | "serialize" | "deserialize"> {
    getStorage?: () => IStateStorage<ISerializedState>;
    serialize?: (state: IStorageValue<CacheState>) => ISerializedState;
    deserialize?: (serializedState: ISerializedState) => IStorageValue<CacheState>;
}

type CustomPersist = <
    State,
    CacheState,
    ISerializedState,
    Mps extends [StoreMutatorIdentifier, unknown][] = [],
    Mcs extends [StoreMutatorIdentifier, unknown][] = [],
    U = State
>(
    makeStore: StateCreator<State, [...Mps, ["zustand/persist", unknown]], Mcs>,
    options?: ICustomPersistOptions<State, CacheState, ISerializedState>
) => StateCreator<State, Mps, [["zustand/persist", U], ...Mcs]>;

const persistMiddleware = persist as CustomPersist;
```

## Problem Statement
While the `string` type is sufficient for basic cache solutions, it's not flexible enough for all use-cases, and I think it's inappropriate for the library to artificially enforce this limited type ("artificial", as there is no type limitation in zustand's implementation for persist serialization). This also seems to break from Zustand's general unopinionated philosophy/vibe. After all, Zustand is a store solution, not a caching solution!

A good example is the popular [`localForage` cache library](https://github.com/localForage/localForage) using IndexedDB as its cache middleware. With this setup, it's possible to cache modern ES6 types like `Maps` and `Sets` (at least from the perspective of a cached store author).

Unfortunately, there is no easy/clean way to pass these modern types along to the cache layer via a serialized `string` type that zustand requires.

## Proposed Solution
I propose two possible solutions:

1. Retype the serialized intermediate type from `string` to something more generic (with `string` as the default type,  matching the output of `JSON.stringify`). This generic type will also need to be part of the contract for `getStorage`. Looking at the internal implementation, this should be fairly straightforward / a small change.

2. Add an option to skip simply serialization, since another way to view this issue is that the cache library has its own, more robust/advanced serialization strategy, and we want to defer to that. This is still requires a type change to `getStorage`.

## Link to reproduction
Not a runtime issue

## Check List

Please do not ask questions in issues.

- [x] I've already opened a [discussion](https://github.com/pmndrs/zustand/discussions) before opening this issue.
    -  **N/A** (not a question)
    
Please fill this template if you're filling an issue regarding TypeScript.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction. Or some other way of reproduction if these two don't suffice.
    -  **N/A** (not a runtime bug)
- [x] I've read the [typescript guide](https://github.com/pmndrs/zustand/blob/main/docs/guides/typescript.md), in particular that `create` is to be used as `create<T>()(...)` and not `create<T>(...)`.

**Comment by dai-shi** [comment]
Thanks for the suggestion.
`serialized` is deprecated for exactly the reason you mention.
Please use the new `storage` option. If you have question how to use it, feel free to ask. We also look for contributors to improve docs.
