### ISSUE TITLE
Immer `setState` infers state from `getState`

### ISSUE THREAD

**Issue by chrisvander** [pmndrs/zustand#1620]
## Summary

The Immer middleware infers the type `nextStateOrUpdater` for `setState` from `getState`:

```ts
type StoreImmer<S> = S extends {
    getState: () => infer T;
    setState: infer SetState;
} ? SetState extends (...a: infer A) => infer Sr ? {
    setState(nextStateOrUpdater: T | Partial<T> | ((state: Draft<T>) => void), shouldReplace?: boolean | undefined, ...a: SkipTwo<A>): Sr;
} : never : never;
```

This is typically not a problem unless you're using a middleware like [chrisvander/zustand-computed](https://github.com/chrisvander/zustand-computed), where the state returned by `getState` *differs* from what is allowed to be set via `setState`. In the case of the computed middleware, `getState` returns additional keys beyond what the user is allowed to modify.

## Link to reproduction

[Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzXAvnAMyghDgCIAvAVwGcYMA7AEzIChRJZE4m0A3GBAgAbGnkLFSlWvWYB6EMCZNhaAO4Z0bDtHhJQINFHFES5anUZMFSles1o5Bo9vC7uyEmCrYmJyeYyVgC0nuA+aCysrDAAnmA4AMqC6HAAvIiscCgQVAwwAFxwDFQgAEZGWXDADMhFABQAlOkAfHB8EEpVvHVwTa3tnUysuNFxCXAAwl4RTMnQOBkIVZ55MIkAjkUl5ZWjrAR5yDDAEAw54djJWGj1lthF8+iNRdOXkU84y9noMFRQ52+2Rya02RXuaAAdKt8nAAFRwuAAJgANFVRvtPAw6HBaGhPukUOgbgAeT4tJr1br8QQiGhU4EXby+BmMvo0NAwZppNr1IFskH5IoARjRAuyNV6-R5cA5MHqd3o2G5vKQMMKsqVUPVcAA1HBhXhGo0xeKeg0VbLOQqIZa+YKNRDoblYcEDUaTVVGbhPQKwsz8VqvXBGlVQ6HWFicXjPgBJECGYwZVCYbBklJoCmNVm8ARCUSs7L+2aF4HOKA2zl2-ls9Ui00CyUW1rBgVym1ay018VwORyOBoAAeGHAqjgamAMAAFnB44m4IplKoNOhW+KnTrdRlhWvvb6zWgpZb24qbtWHeCtc61nA3Yaffu94-gcWrkHGaHsuHojGM5C5dc2D2uqYIGgADGBRq9v2RjEFArC-gsc5GP+nKAbcaouusWzgZBPrQbKU65MIfhThgfA4LB0BAA)

## Check List

Please do not ask questions in issues.

- [x] I've already opened a [discussion](https://github.com/pmndrs/zustand/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

Please check this if you're filing an issue regarding TypeScript.

- [x] I've read the [typescript guide](https://github.com/pmndrs/zustand/blob/main/docs/guides/typescript.md), in particular that `create` is to be used as `create<T>()(...)` and not `create<T>(...)`.

**Comment by dai-shi** [comment]
Thanks for reporting. How can you solve this?

**Comment by dai-shi** [comment]
Closing this for now. Please continue discussion in #1621.
