### ISSUE TITLE
TypeError: store.getState is not a function

### ISSUE THREAD

**Issue by ikotsov** [pmndrs/zustand#1710]
## Summary
Hello,

I am following [this guide](https://docs.pmnd.rs/zustand/guides/testing) in order to achieve resetting state between my tests.

My project is in React Native and I am using jest for testing.

Unfortunately, it is not clear in the docs how should I use the store created in `zustand.ts` file in `__mocks__` folder. I suppose that just by adding it, it will work automatically. Is this correct?

The code of `zustand.ts` file is this:
```
// eslint-disable-next-line import/no-extraneous-dependencies
import { act } from '@testing-library/react-native';
import { StateCreator } from 'zustand';

const { create: actualCreate } = jest.requireActual('zustand');

// a variable to hold reset functions for all stores declared in the app
const storeResetFns = new Set<() => void>();

// when creating a store, we get its initial state, create a reset function and add it in the set
export const create = <S>(createState: StateCreator<S>) => {
  const store = actualCreate(createState);
  const initialState = store.getState();
  storeResetFns.add(() => store.setState(initialState, true));
  return store;
};

// Reset all stores after each test run
beforeEach(async () => {
  await act(() =>
    storeResetFns.forEach(resetFn => {
      resetFn();
    })
  );
});

```

I get this error: TypeError: store.getState is not a function

<img width="573" alt="Screenshot 2023-03-23 at 12 04 14 PM" src="https://user-images.githubusercontent.com/15989223/227170160-92f7e363-c0bd-49e2-b35d-a2805abedcc3.png">

My store and tests setup is like this:

```
type State = {
  passengers: number;
  actions: {
    addPassenger: () => void;
    removePassenger: () => void;
  };
};

export const useStore = create<State>()(set => ({
  passengers: 1,
  actions: {
    addPassenger: () => set(state => ({ passengers: state.passengers + 1 })),
    removePassenger: () => set(state => ({ passengers: state.passengers - 1 }))
  }
}));

export const usePassengers = () => useStore(state => state.passengers);

// ... and then in my test file

test('1 passenger has been added as a default selection', () => {
  const { result } = renderHook(() => usePassengers());

  expect(result.current).toBe(1);
});


```

I also looked at [previous issues](https://github.com/pmndrs/zustand/issues?q=is%3Aissue+TypeError%3A+store.getState+is+not+a+function+is%3Aclosed), but there is not any obvious solution to this.

Based on [this proposal](https://github.com/pmndrs/zustand/issues/271), alternatively I have to do a manual reset for each one of the test files I write, which is not ideal.

Is there any idea how I can fix this type error?

## Check List

Please do not ask questions in issues.

- [x] I've already opened a [discussion](https://github.com/pmndrs/zustand/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [ ] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

Please check this if you're filing an issue regarding TypeScript.

- [x] I've read the [typescript guide](https://github.com/pmndrs/zustand/blob/main/docs/guides/typescript.md), in particular that `create` is to be used as `create<T>()(...)` and not `create<T>(...)`.

**Comment by dai-shi** [comment]
Let's re-open when we have some ideas in #1709.
