### ISSUE TITLE
Replace flag resulting in setValue is not a function

### ISSUE THREAD

**Issue by Badhan-abhishek** [pmndrs/zustand#1784]
## Summary
First of all thank you for this library.
I have persisted state with replace hook to clear the state. Once clearState function is called, the setValue (or any other function from store) is resulting in `not a function` error.
Versions: 
 -  "next": "13.3.1",
 - "zustand": "^4.3.7"

## Link to reproduction
https://github.com/Badhan-abhishek/zustand-repro

## Check List

Please do not ask questions in issues.

- [X] I've already opened a [discussion](https://github.com/pmndrs/zustand/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [X] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction. 

  - Note sure if github counts

Please check this if you're filing an issue regarding TypeScript.

- [] I've read the [typescript guide](https://github.com/pmndrs/zustand/blob/main/docs/guides/typescript.md), in particular that `create` is to be used as `create<T>()(...)` and not `create<T>(...)`.

**Comment by dbritto-dev** [comment]
@Badhan-abhishek you shouldn't replace the whole state, if you do that you need to keep in mind that you are deleting `setValue`.

Current state before calling `clearStore`

```ts
{ value, setValue }
```
Current state after calling `clearStore` using `set` with `replace: true`

```ts
{ value }
```

**Comment by Badhan-abhishek** [comment]
Thank you for replying instantly,
This is very good explanation. This fixed my issue

```typescript
clearStore() {
    set(
        (s) => ({
            ...s,
            value: "",
         }),
        true
);
```

I will try to create a PR for explanation in the docs.
