### ISSUE TITLE
Values from Maps won't be persisted on react-native (AsyncStorage)

### ISSUE THREAD

**Issue by exotexot** [pmndrs/zustand#1828]
```
export const useDocumentState = create(
  persist(
    immer((set, get) => ({
      // DOCUMENT STATES

      state1: new Map([
        ["88", "value1"],
        ["89", "value2"],
      ]),
      state2: "hello",
   

      initAll: () => {
        const newStates = new Map([
          ["88", "value1"],
          ["89", "value2"],
        ])

        console.log(newStates.has("88")) 

        return set({
            state1: newStates,
            state2: "world",
	 })
      },

    })),
    {
      name: "@DOCUMENT_STATES",
      storage: createJSONStorage(() => AsyncStorage),
    },
  ),
)
```

## Summary
I found a bug where values which are stored in a Map, won't persist using AsyncStorage on react-native.
In an example, I'm calling the initAll function, which stores two values state1 and state2.

When I restart the app, I can successfully retrieve the the new value from state2 (String), whereas state1 appears to be an empty Object / and not even a Map:

 "state1": {}

This also leads to a crash when calling newStates.has("88"):
 TypeError: iterator method is not callable

https://github.com/pmndrs/zustand/pull/1763 doesn't seem to fix it for me.

**Comment by exotexot** [comment]
Of course only now I found the corresponding section in your documentation:
https://docs.pmnd.rs/zustand/integrations/persisting-store-data#how-do-i-use-it-with-map-and-set

However, in the example you seem to define / hardcode the field which uses the map. e.g. ("transactions").
However, in my state I wanna have two sets and one normal object as state fields... it looks like than this won't work, will it?

**Comment by exotexot** [comment]
Okay. Sorry for spamming.
https://github.com/pmndrs/zustand/pull/1763#issuecomment-1534779266 acutally solved my issue...

**Comment by dai-shi** [comment]
If anyone has an idea to improve docs, please feel free to open a PR.
