### ISSUE TITLE
Zustand breaks @react-google-maps/api for some reason

### ISSUE THREAD

**Issue by DavidArutiunian** [pmndrs/zustand#1934]
### Discussed in https://github.com/pmndrs/zustand/discussions/1900

<div type='discussions-op-text'>

<sup>Originally posted by **DavidArutiunian** June 28, 2023</sup>
Hey!

I've spend hours trying to find out why this happens. In short, for some reason google maps break when adding `zustand` dependency. Here is a reproduction of that issue -> https://codesandbox.io/s/zustand-google-maps-ykgkx2

You can try to comment out `L:33` and `_points` variable in `L:54` and cluster will be rendered. This is not a case when using zustand stores. There may be some side effect in `zustand`'s code (or vice versa), but I haven't found anything.</div>

**Comment by magicspon** [comment]
heyo,

Not sure why it's not working, but if you move the points hook to a parent component it works as expected 

https://codesandbox.io/s/zustand-google-maps-forked-gp7mdq?file=/src/App.js

**Comment by dai-shi** [comment]
Please use #1900 for further discussion.

**Comment by dai-shi** [comment]
(I wish to have more visibility. Maybe, we should try creating a meta issue for active discussions.)

**Comment by DavidArutiunian** [comment]
> heyo,
> 
> Not sure why it's not working, but if you move the points hook to a parent component it works as expected
> 
> https://codesandbox.io/s/zustand-google-maps-forked-gp7mdq?file=/src/App.js

Yeah, this work but the if any component inside `GMap` uses zistand store, then it breaks again

**Comment by DavidArutiunian** [comment]
> Please use #1900 for further discussion.

Unfortunately, I haven't got any answer
