### ISSUE TITLE
@babel/runtime dependency while consuming Zustand with Typescript

### ISSUE THREAD

**Issue by gersomvg** [pmndrs/zustand#200]
When importing Zustand in a typescript (node CLI) project, I'm getting this error:

```
Error: Cannot find module '@babel/runtime/regenerator'
Require stack:
- /Users/me/projects/project/node_modules/zustand/index.cjs.js
```

There seem to be an `index.js` and an `index.cjs.js`, with Typescript importing the latter. The index.cjs.js requires @babel/runtime. My Node version is 12.x and my tsconfig looks like this:
```
{
    "compilerOptions": {
        "lib": ["es2019", "es2020.promise", "es2020.bigint", "es2020.string"],
        "module": "commonjs",
        "target": "es2019",
        "strict": true,
        "esModuleInterop": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true,
        "jsx": "react"
    }
}
```

I rather not change my tsconfig or Node version, unless there is a compelling reason. Is it correct that for my case I need to install `@babel/runtime` as a dependency? I would expect not to, since `tsc` should probably take care of everything?

Thanks!

**Comment by dai-shi** [comment]
It might be better if you could use the ESM build `index.js`. Not sure how to configure your env. Can anyone else help here?

**Comment by gersomvg** [comment]
I would expect Typescript to get that one, since I have "esModuleInterop" enabled and I'm using the import syntax `import create from 'zustand';`

When I do `import create from 'zustand/index'` it takes the non-cjs version, but then I get this error:
```
/Users/gersomvanginkel/projects/wallpaper-creator/node_modules/zustand/index.js:1
import { useReducer, useRef, useEffect, useLayoutEffect } from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by dai-shi** [comment]
I see. To use the ESM build, `module` has to be `ES2015`, `ES2020` or `ESNext`.
https://www.typescriptlang.org/tsconfig#module
But, that's something you don't want...

**Comment by gersomvg** [comment]
The `module` option is for the _output_ module format right? Since that's in the context of Node 12 it has to be CommonJS I think.

I lack knowledge of why Typescript can't just consume the ESModule and turn it into CommonJS, but this seems like something that shouldn't be a problem.

**Comment by dai-shi** [comment]
> The module option is for the output module format right?

No, the output is `target`, I guess. (I might be wrong. I never used TS for node projects.)
If you are ok to test, would you try `module: "es2015"` and `moduleResolution: "node"`?

> I would expect the cjs.js file to not depend on Babel in the context of Typescript. Does that make sense?

It does make sense. However, the cjs build is historically for IE11, which I guess requires to depend on babel runtime.
There's no one size fits all.

**Comment by gersomvg** [comment]
Thanks for the quick replies and the help 💯 

I thought `target` refers to what Javascript features in general are supported in the target environment (es5, es6, mostly the same between node/browser), where `module` just refers to module resolution (different between browser vs. older node vs. newer node etc.). Anyway, this I something that I keep googling all the time 😅 

`moduleResolution: "node"` doesn't do anything unfortunately.

**Comment by dai-shi** [comment]
So, does `module: "es2015" works for you?
(I mean, "commonjs" for nodejs ts projects makes sense in general.)

First time to hear about ink users using zustand. Nice!

**Comment by gersomvg** [comment]
Unfortunately not :( Together with `moduleResolution: "node"` it breaks on the import syntax in my own files:

```
/Users/me/projects/cli-project/bin/cli.tsx:1
import React from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Without `moduleResolution` every file breaks as expected, for example because it can't resolve node modules.

**Comment by dai-shi** [comment]
My bad. `module` is for output... `target` is for output too.

> ```
> SyntaxError: Cannot use import statement outside a module
> ```

I'm not sure why this happens then.

**Comment by dai-shi** [comment]
Oh.. because it's in node_modules.

**Comment by gersomvg** [comment]
Ok, I get the dilemma. I think there might be a solution out there, but I don't have experience with building packages so I don't know what it is.

A few thoughts:
- Should the `npm i @babel/runtime` also be mentioned in the intro of the readme?
- Can we put it behind a browser check? e.g.: `if (typeof window !== 'undefined') require('@babel/runtime/..')`

**Comment by dai-shi** [comment]
Thanks for the suggestions.

I'm not sure if we should mention in the readme for various subtle reasons.
- We want to keep the readme small if it's reasonable.
- It used to have a note about cjs build for IE11, which is now removed.
- The user base of cjs build for node env must be small, as far as we know.
- The missing babel/runtime error is clear about how to fix. (Though, it feels strange as you said.)

I agree this should be improved for node users, but I don't have any ideas either.
It's not about the zustand source code, but about bundle config. (rollup.config.js)
If someone has a suggestion how to enable the browser check in the bundle, it will be considered.

Sorry for the inconvenience.

**Comment by gersomvg** [comment]
I fully understand we should not make things more complex on the outer side. Would the `typeof window !== 'undefined'` check work? That does solve it for node.. And also for server rendering apps (not sure if it's a problem there)?

**Comment by dai-shi** [comment]
No, I don't think `typeof window` check works. It will still require babel/runtime in the bundle. Please try it if you are curious.

SSR apps are fine as long as they use bundlers like webpack.

**Comment by JeremyRH** [comment]
We can inline @babel/runtime/regenerator in certain builds so the user doesn't need it as a peer dependency. This adds some size to those builds and loses the benefit of reusing @babel/runtime/regenerator elsewhere in the user's project.

Zustand can get rid of @babel/runtime/regenerator by converting the generator function to a plain function:
```ts
// For backward compatibility (No TS types for this)
useStore[Symbol.iterator] = function() {
  console.warn(
    '[useStore, api] = create() is deprecated and will be removed in v4'
  )
  const items = [useStore, api] as const
  return {
    next() {
      return {
        done: items.length === 0,
        value: items.shift()
      }
    }
  }
}
```

**Comment by dai-shi** [comment]
@JeremyRH Hey, thanks for chiming in.
We could convert it by hand, but I suspect that would increase the size of `dist/index.js` which is for say 99% users.
Embedding babel/runtime is possible but as you say there's no plus. We should just ask @gersomvg in install it at their end.
The only reasonable solution seems `dist/index.node.js` but that will raise another discussion how to specify it in package.json.
(I wonder if rollup can produce .mjs build.)

**Comment by JeremyRH** [comment]
Yeah, rollup can produce .mjs builds. Look at [Recoil's rollup config](https://github.com/facebookexperimental/Recoil/blob/ea81288f1e1a94084a7523875382bca8454a1c2e/rollup.config.js#L58). It has a few outputs they've received requests for.

**Comment by ImedAdel** [comment]
I had the exact error with Next.js, TypeScript, and Zustand. After some backtracking, I found that the error started happening when I removed `react-spring`. I just added it back and the error is gone. It's been 4 hours and I don't think I'll be looking for the why :smile:

**Comment by dai-shi** [comment]
@ImedAdel Actually, I didn't expect this issue happens in nextjs (originally reported as node cli). We would need to do something. Do you know if this is only issue with nextjs + typescript? I mean, does it repro with nextjs + javascript?

**Comment by ImedAdel** [comment]
My setup is a bit complicated and since I'm already moving away from it, you shouldn't really focus on my issue :)

I built and ran the Dockerfile locally and it's working without any errors. The `@babel/runtime` error only occurred when the Docker image is deployed using Nomad. I haven't tried that again. It could be a problem somewhere with the cache.

**Comment by dai-shi** [comment]
Thanks. OK, let's keep this issue open for a while and see somebody reports anything.

**Comment by dai-shi** [comment]
#334 is related.

**Comment by barbogast** [comment]
Looks like with v3.5.2 @babel/runtime/regenerator is no longer needed as zustand no longer uses async/await in its codebase.

**Comment by dai-shi** [comment]
Oh, yes. That was one my huge motivation on #403.
