### ISSUE TITLE
State is deprecated, but still used in Docs

### ISSUE THREAD

**Issue by dinogomez** [pmndrs/zustand#2024]
## Summary
State is deprecated but is still shown and used in the docs.
![image](https://github.com/pmndrs/zustand/assets/41871666/a081c677-6fca-4be1-bd11-c1f3a3696d91)

Docs

![image](https://github.com/pmndrs/zustand/assets/41871666/51dba6ee-f732-47d5-9c44-adf9b1f9442e)

## Link to reproduction

https://docs.pmnd.rs/zustand/guides/updating-state

https://github.com/pmndrs/zustand/blob/main/docs/guides/updating-state.md

**Comment by dai-shi** [comment]
Would you like to open a PR to fix it?

**Comment by OshriAsulin** [comment]
Hi @dai-shi , I will be happy to open pr of this issue but really I didn't understanding the bug

**Comment by OshriAsulin** [comment]
I thinking @dinogomez got this error because it didn't create this next type in the image

<img width="124" alt="צילום מסך 2023-09-03 130822" src="https://github.com/pmndrs/zustand/assets/114335827/3c3499c2-9e00-451a-8370-3345a97f36a8">

**Comment by dai-shi** [comment]
I'm not sure either but there remains deprecated State type from zustand in docs, right?

**Comment by OshriAsulin** [comment]
Right, he remains the docs, but I checked this issue and I worked according to the docs and I didn't get this as an error

My test:

<img width="594" alt="צילום מסך 2023-09-03 132713" src="https://github.com/pmndrs/zustand/assets/114335827/6b971638-e94a-49c5-9543-01237fb93abb">
<img width="441" alt="צילום מסך 2023-09-03 132736" src="https://github.com/pmndrs/zustand/assets/114335827/2d53720a-41b7-48c6-8c95-9cf6a2930eea">

**Comment by dai-shi** [comment]
It looks good.

**Comment by dinogomez** [comment]
Hi @dai-shi  and @OshriAsulin , I am just starting to learn Zustand and Typescript, so I wont be able to help much. I just noticed the deprecation warning when I was following the docs in vscode. 

After following Oshi's reproduction I found that it was because I used a different name for state i.e `userState` that caused it.
![image](https://github.com/pmndrs/zustand/assets/41871666/7085e269-8c17-4b80-be6e-d6feec12397c)

After I renamed it properly it worked without warnings.

![image](https://github.com/pmndrs/zustand/assets/41871666/1b5b0425-e7be-452e-a412-89b667bccdf7)

So the docs were fine, it was just a mistake on my end. Sorry for taking moments of your time and thank you for the help as well. Since everything is good ill be closing the issue. Working with zustand is such a good dev experience and really helped me with my state management issues. Cheers!

**Comment by dai-shi** [comment]
Okay, so there are no deprecated `State` types remained in docs.

**Comment by OshriAsulin** [comment]
Right, but I founded another issue in this is snnipet code-
Please describe what you expected to happen when using the `shallow` in this example from the docs-

<img width="506" alt="image" src="https://github.com/pmndrs/zustand/assets/114335827/cc22965a-5b59-4c12-8c3e-01759d82088e">

when I tried to use it I got an error-
<img width="391" alt="צילום מסך 2023-09-03 133301" src="https://github.com/pmndrs/zustand/assets/114335827/10e75710-e63c-4fc8-8920-e62108b67f9a">

**Comment by OshriAsulin** [comment]
And when I hide this `shallow` is working fine
<img width="506" alt="image" src="https://github.com/pmndrs/zustand/assets/114335827/1ea01331-e0d8-436f-b0de-5873e2547704">

**Comment by OshriAsulin** [comment]
I will happy to work on this issue @dai-shi  let me to know if I can to do that.

**Comment by dai-shi** [comment]
`shallow` should be there, because the selector L26 creates a new array. Not sure what is your suggestion about improving the description, but please feel free to open a PR and discuss based on it (though, in the end we may decide not to merge.)

**Comment by OshriAsulin** [comment]
I mean for improving,  because the `shallow` is making an error so remove him from the example of the docs.
@dai-shi

**Comment by dai-shi** [comment]
Do you mean adding `import { shallow } from 'zustand/shallow'` improves it?

**Comment by OshriAsulin** [comment]
> Do you mean adding `import { shallow } from 'zustand/shallow'` improves it?

Yes, It's resolved the issue.

But it does not exist in the docs

https://github.com/pmndrs/zustand/assets/114335827/29ae4c2d-3d77-4dcb-8952-efbd759df21c

**Comment by OshriAsulin** [comment]
So I thought about two options-
1 Add the imports to `create` and to `shalllow` as in the following example -
```javascript
import { create } from 'zustand'
import { shallow } from 'zustand/shallow'
```
2 Remove the `shallow` to avoid user errors

@dai-shi  let me to know which solution you want I implement?

**Comment by dai-shi** [comment]
Add import statements, because removing `shallow` is wrong (even if the error seems to go away.)
