### ISSUE TITLE
Website not fully displayed on mobile

### ISSUE THREAD

**Issue by stfnsr** [pmndrs/zustand#203]
Hi!
In search for docs I was just looking at the Zustand website (on an iPhone SE 3020), and it wasn’t usable (only partially visible) in landscape and portrait orientation. (Screenshots attached)
Is the code for the Site on GitHub?

![16C31870-EF65-4ECB-AA8D-1A6D69769631](https://user-images.githubusercontent.com/4975791/95012985-6740be00-063d-11eb-8f13-a249a07cff1c.png)

![D43485EE-8282-4173-B5AE-EC0B3C57639E](https://user-images.githubusercontent.com/4975791/95012983-6445cd80-063d-11eb-8be5-5088a8a275e0.png)

**Comment by dai-shi** [comment]
> Is the code for the Site on GitHub?

Yes, it's the `examples` folder.

**Comment by zcoderboy** [comment]
How can I contribute and fix this ?

**Comment by dai-shi** [comment]
If you have an idea to fix it, please draft a PR.

**Comment by stfnsr** [comment]
![FBF9EC19-6072-4522-BB9C-7D2BC8B74B4F](https://user-images.githubusercontent.com/4975791/95144601-58f7bc80-0779-11eb-9ef0-cedcb8d1cc2f.png)
(On phone, same one as in opening this issue here)

**Comment by stfnsr** [comment]
![88F437AB-64D0-4B7C-9354-6950143A95CA](https://user-images.githubusercontent.com/4975791/95144745-b2f88200-0779-11eb-92f7-b9183eaebe58.png)
![7EB1419E-6156-4D9D-B706-18D645C0A349](https://user-images.githubusercontent.com/4975791/95144746-b429af00-0779-11eb-933b-322a26b724ac.png)
Landscape mode before/after.
Didn’t even expect this to work 😅

**Comment by dai-shi** [comment]
Fixed by #204.
