### ISSUE TITLE
bug: `temp` directory isn't exist in website repository

### ISSUE THREAD

**Issue by OshriAsulin** [pmndrs/zustand#2030]
In CONTRIBUTING.md has a mention of the `temp` directory in the website repository, but I checked and it doesn't exist

https://github.com/pmndrs/zustand/blob/main/CONTRIBUTING.md

<img width="679" alt="צילום מסך 2023-09-06 165135" src="https://github.com/pmndrs/zustand/assets/114335827/79c34bde-1d4c-4fb3-9537-0580dd973ed6">

**Comment by dai-shi** [comment]
Sometimes you may have to remove it, but you don't need to unless it exists, right?

**Comment by OshriAsulin** [comment]
Ok, I understand it now
Thank you for the answer
@dai-shi
