### ISSUE TITLE
Lazy store

### ISSUE THREAD

**Issue by thgh** [pmndrs/zustand#205]
Hi, is there a way to only initialize the store at the moment that a component has used it? And is there a way to have a callback when there are no active listeners? `svelte/store` has this and is quite similar to zustand.

My usecase is a graphql subscription that is only needed temporarily.

**Comment by dai-shi** [comment]
> is there a way to only initialize the store at the moment that a component has used it?

https://github.com/pmndrs/zustand/issues/128#issuecomment-703916901
Does this comment help?

> And is there a way to have a callback when there are no active listeners?

I don't think so, but if you are explicitly subscribing, you should have control.
Not sure if I understand the use case. code snippet might help for further discussion.

**Comment by thgh** [comment]
I ended up creating a custom store, it only starts 1 graphql subscription even though multiple components use it at the same time. It can also cleanup nicely. Here is the gist of it:
```ts
let listeners = []
let profile = { loading: true }
let observer = null
export function useProfile() {
  const forceUpdate = React.useReducer(x => x + 1, 0)[1]
  useEffect(() => {
    if (!listeners.length) {
      observer = graphqlSubscription.subscribe(data => {
        profile = data
        listeners.forEach(cb => cb())
      })
    }
    listeners.push(forceUpdate)
    return () => {
      listeners.splice(listeners.indexOf(forceUpdate), 1)
      if (!listeners.length) {
        observer.unsubscribe()
      }
    }
  }, [forceUpdate])
  return profile
}
```

The equivalent with svelte/store would look like this:

```ts
import { writable } from 'svelte/store'
const profile = writable({ loading: true }, set => {
  const observer = graphqlSubscription.subscribe(set)
  return () => observer.unsubscribe()
})
```

**Comment by dai-shi** [comment]
So, if I were to do something like this, it could be non lazy store, but with listener count.

```jsx
const useStore = create((set, get) => ({
  profile: { loading: true },
  observer: null,
  listeners: 0,
  subscribe: () => {
    let { listeners, observer } = get()
    listeners += 1
    if (listeners === 1) {
      observer = graphqlSubscription.subscribe(profile => set({ profile }))
    }
    set({ listeners, observer })
  },
  unsubscribe: () => {
    let { listeners, observer } = get()
    listeners -= 1
    if (listeners === 0) {
      observer.unsubscribe()
      observer = null
    }
    set({ listeners, observer })
  },
}))

const selectProfile = (state) => state.profile

const useProfile = () => {
  const profile = useStore(selectProfile)
  useEffect(() => {
    useStore.getState().subscribe()
    return () => useStore.getState().unsubscribe()
  }, [])
  return profile
}
```

Just an idea... There might be a better way, like subscribe function returning unsubscribe function.

**Comment by dai-shi** [comment]
@thgh Can close this?

**Comment by thgh** [comment]
Sure!

I'm probably not going to get to it, but would you be interested to merge a PR that adds an export `createLazy` that wraps create?

**Comment by dai-shi** [comment]
I'm not sure if I understand what `createLazy` is like, but in general, we would be strict about making breaking changes and adding new core features, as we think the api is basically complete. A PR for middleware would be appreciated (although, I can't say for sure if it would be merged at this point.)
