### ISSUE TITLE
devtools.d.ts node_modules/zustand/middleware/devtools.d.ts:33:42 - error TS2312: An interface can only extend an object type or intersection of object types with statically known members.

### ISSUE THREAD

**Issue by GabLeRoux** [pmndrs/zustand#2101]
## Summary

A change between zustand 4.4.1 and zustand 4.4.2 seem to broke something in `middleware/devtools.d.ts` 👀 

> node_modules/zustand/middleware/devtools.d.ts:33:42 - error TS2312: An interface can only extend an object type or intersection of object types with statically known members.

```bash
npm run build
```
```
> vite-zustand-config-issue@0.0.0 build
> tsc && vite build

node_modules/zustand/esm/middleware/devtools.d.ts:33:42 - error TS2312: An interface can only extend an object type or intersection of object types with statically known members.

33 export interface DevtoolsOptions extends Config {
                                            ~~~~~~


Found 1 error in node_modules/zustand/esm/middleware/devtools.d.ts:33
```

## Link to reproduction

Project that reproduces issue:

https://github.com/GabLeRoux/vite-zustand-config-issue
There is a github action that builds the project. You can see it's failing on the `main` branch.

I've created a PR on that same project that demonstrate that this issue doesn't happen when freezing the version to 4.4.1:
https://github.com/GabLeRoux/vite-zustand-config-issue/pull/1

## Check List

Please do not ask questions in issues.

- [ ] I've already opened a [discussion](https://github.com/pmndrs/zustand/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

Please check this if you're filing an issue regarding TypeScript.

- [x] I've read the [typescript guide](https://github.com/pmndrs/zustand/blob/main/docs/guides/typescript.md), in particular that `create` is to be used as `create<T>()(...)` and not `create<T>(...)`.

**Comment by dai-shi** [comment]
Can you try #2099?

See also: https://github.com/pmndrs/zustand/pull/1991#issuecomment-1746618630

**Comment by GabLeRoux** [comment]
Tested here:
https://github.com/GabLeRoux/vite-zustand-config-issue/pull/2

The build passed so it seems to be working 👍
