### ISSUE TITLE
Updating State - "Best Practice" Question

### ISSUE THREAD

**Issue by dudiharush** [pmndrs/zustand#211]
Hi, have a quesioin regarding reusing state update logic.
I want my state update logic to be in the store only, where the state + actions are, and i'm looking for a "best practice" of reusing a function that updates part of the state, in Mobx State Tree, for example, the store is built of smaller parts that i can reuse in different places. is it possible to do it in zustand?

MST ex:
```
// reusable logic part
const Todo = types
    .model("Todo", {
        title: types.string,
        done: false
    })
    .actions(self => ({
        toggle() {
            self.done = !self.done
        }
    }))

// using the reusable update logic
const Store = types.model("Store", {
    todos: types.array(Todo)
})

**Comment by dai-shi** [comment]
This would be one of best practices.

```js
import create from 'zustand'

const createActions = (set) => ({
  setTitle: (title) => set({ title }),
  toggle: () => set(prev => ({ done: !prev.done })),
})

const useStore = create((set) => ({
  title: 'foo',
  done: false,
  ...createActions(set),
}))
```

To apply this approach to `todos` array, there would be some options. I'm not sure if there's something called like best practice.

We've discussed something about namespacing in #178. For todos array, I'd expect something simpler.

**Comment by dudiharush** [comment]
Thanks for the fast response! i'm looking for a solution where the state and the actions are in the same reused function, like in the mst example. is there a reason why you separated them?

**Comment by dai-shi** [comment]
zustand is basically unopinionated, but it's easy if you have actions right under the state because the default behavior of `set` is shallow merging.

Now, if I'd try something you would expect, it'd be:

```js
const createTodo = (set) => ({
  title: '',
  done: false,
  setTitle: (title) => set({ title }),
  toggle: () => set(prev => ({ done: !prev.done }),
})

const createStore = create((set) => ({
  todos: {},
  addTodo: () => {
    const id = nanoid()
    const setTodo = (update) => {
      set(prev => {
        if (typeof update === 'function') {
          update = update(prev.todos[id])
        }
        return { todos: { ...prev.todos, [id]: { ...prev.todos[id], ...update } } }
      })
    }
    const todo = createTodo(setTodo)
    set(prev => ({ todos: { ...prev.todos, [id]: todo }))
  }
})
```

...but, I don't think this is something you really expect.

**Comment by dudiharush** [comment]
Looks like it could work, but that's an unmaintainable code. In the docs there is no example that shows how it handles nested state. Would you use this lib if you had to update nested state?

**Comment by dai-shi** [comment]
As far as I heard, many zustand users use immer for nested state.

**Comment by dkgrieshammer** [comment]
I use it also for deeply nested state but would surely use immer as a helper

**Comment by dai-shi** [comment]
I just re-opened #178, hoping someone put some efforts.

**Comment by dai-shi** [comment]
Let's close this one as #178 should cover this.

**Comment by feuersteiner** [comment]
Hey @dai-shi thanks for your response to the question.
I have been reading the issue and I found an answer for a question I was going to ask about best practices.

say we have an array of objects as state, what would be better: 
### 1) have one setter in the store then deal with the operations outside

```
// in the store
const store = create<StoreType>((set) => ({
array...
setArray...
})

// in the controller

createObject(object)
retrieveObject(id)
updateObject(id)
deleteObject(id)
```

### 2) create the functions in the store

```
// in the store
const store = create<StoreType>((set) => ({
array...
setArray...
createObject...
retrieveObject...
updateObject...
deleteObject...
})
```

---------------

reading the issue your recommendation is the latter, do I understand correctly ?

**Comment by dai-shi** [comment]
People seem to like putting actions in a store, which is more self contained as a store variable.
Lately, I like a new pattern to define actions in a store module (because it allows code splitting.)
https://github.com/pmndrs/zustand/blob/main/docs/practice-with-no-store-actions.md

At this point, it's unopinionated. Does this answer your question? Feel free to [open a new discussion](https://github.com/pmndrs/zustand/discussions/new).

**Comment by feuersteiner** [comment]
answers perfectly. All I wanted to know is if there's some penalties to either (especially in a high store update environment) (questions I had, if it were all inside a contained store, would a function call trigger unnecessary re-renders.... that type of problem).
どうもありがとうございます

**Comment by feuersteiner** [comment]
@dai-shi the problem that rises from putting actions in a store is a very long file sometimes that is not easy to ready, even though putting controllers in separate files with custom hooks can be cumbersome, it still guarantees readability.
