### ISSUE TITLE
offline support 

### ISSUE THREAD

**Issue by cnx-piyush** [pmndrs/zustand#214]
I wanted to know if zustand support offline where the state can be stored in localstorage  . I was hoping a plugin would be super useful in this case

**Comment by dai-shi** [comment]
Do you mean persistence support? Does #76 look relevant?

**Comment by cnx-piyush** [comment]
@dai-shi This is exactly what I was looking for . Thanks and I am closing the issue .

**Comment by dai-shi** [comment]
A note for anyone: We could add some functions to support persistence in middleware.ts. Feel free to open an issue for discussions.
