### ISSUE TITLE
Testing using Zustand & Jest

### ISSUE THREAD

**Issue by oli06** [pmndrs/zustand#215]
Hello,
does Zustand support testing?

E.g. I want to check, if the store is updated after clicking a button using a test framework like jest:

```ts
const { selectedTime } = useTimeStore((state) => state);
const currentTime = new Date();

const submitButton = getByRole("button", {
  name: "Set time",
});
  
fireEvent.click(submitButton);
expect(currentTime == selectedTime);
```

**Comment by dai-shi** [comment]
Hi, not quite sure if I understand the specific problem, but do you need to mock Date?
I'm not particularly experienced in zustand & jest, but it seems nothing prevents it. I hope someone chime in on this topic.

**Comment by olavoparno** [comment]
> Hello,
> does Zustand support testing?
> 
> E.g. I want to check, if the store is updated after clicking a button using a test framework like jest:
> 
> ```ts
> const { selectedTime } = useTimeStore((state) => state);
> const currentTime = new Date();
> 
> const submitButton = getByRole("button", {
>   name: "Set time",
> });
>   
> fireEvent.click(submitButton);
> expect(currentTime == selectedTime);
> ```

Hey, mister, I think there are multiple ways to check wether something's been called within a store.

One way:

```js
const {result, waitForNextUpdate} = renderHook(() => useHookUsingStore());
result.current.hookActions.getSomeList();

await waitForNextUpdate();

const [first] = result.current.myList;
expect(first.myId).toEqual(1);
```

Or you could mock the very store implementation like so:
```js
const spyFakeSchemeFromHell = jest.fn();

// Mocking implementation
usePlatformStore.mockImplementation((state) => {
    return state({
      alertOptions: null,
      setAlertOptions: spyFakeSchemeFromHell,
    });
});

const spyFakeSchemeFromHell = jest.fn();

// Mocking return value
usePlatformStore.mockReturnValue({
  alertOptions: {
    message: 'Test Message',
    type: 'warning',
    timeout: 10,
  },
  setAlertOptions: jest.fn(),
});
```

**Comment by oli06** [comment]
Thank you @olavoparno !
I used the first approach and it works like a charm.
