### ISSUE TITLE
The reactNode is stored in the store, sometimes causing the component to lose update.

### ISSUE THREAD

**Issue by vaynevayne** [pmndrs/zustand#2155]
## Summary
As shown in the figure, when I put the children into sotre, there seems to be a problem with the childen taken out, and I cannot use it under control. 

<img width="633" alt="image" src="https://github.com/pmndrs/zustand/assets/124666577/701e157a-5756-4ead-9295-7a354fc5d31f">

I have three questions
1. Items do not pass in pageProvider, but directly pass in tabs, then both switches work normally.  Is this a zustand problem?

## Link to reproduction
https://stackblitz.com/edit/react-r32udm-pvtuoe?file=PageLayout.tsx

## Check List

Please do not ask questions in issues.

- [x] I've already opened a [discussion](https://github.com/pmndrs/zustand/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

Please check this if you're filing an issue regarding TypeScript.

- [x] I've read the [typescript guide](https://github.com/pmndrs/zustand/blob/main/docs/guides/typescript.md), in particular that `create` is to be used as `create<T>()(...)` and not `create<T>(...)`.

**Comment by dai-shi** [comment]
👉 #2156
