### ISSUE TITLE
I can't update state with new data from Tanstack Query

### ISSUE THREAD

**Issue by devoren** [pmndrs/zustand#2186]
## Summary
Hey! Thank you for awesome library ❤️ 
I have a form. When I update the form, onSuccess returns the new updated data. I don't understand why my state isn't updating. I don't know why its not updating, because i have the same logic inside useEffect and it works

## Link to reproduction
```
updateStore(
  {
    id: store.id,
    ...data
  },
  {
    onSuccess: (data) => {
    // if i set store like this, not working
    setStore(data.response.ressult.store)
     
    // if i set store like this, works
    setStore({
        ...store,
        ...data,
      });

      Notice.Success(data.result.message);
    },
  }
);

```

**Store**
```
interface StoresState {
  store: IStore | null;
  setStore: (store: IStore | null) => void;
}

export const useStoresStore = create<StoresState>()(
  persist(
    (set) => ({
      store: null,
      setStore: (store) => set(() => ({ store })),
      clearStore: () => set({ store: null }),
    }),
    {
      name: "stores-zsg",
    }
  )
);

```

## Check List

Please do not ask questions in issues.

- [x] I've already opened a [discussion](https://github.com/pmndrs/zustand/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [ ] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

Please check this if you're filing an issue regarding TypeScript.

- [x] I've read the [typescript guide](https://github.com/pmndrs/zustand/blob/main/docs/guides/typescript.md), in particular that `create` is to be used as `create<T>()(...)` and not `create<T>(...)`.

**Comment by SaadNiaziDev** [comment]
> Any solution mate? ran into same problem. State not updating

Edit:: My mistake. data was inside another data :P
