### ISSUE TITLE
Question on persisting store data when navigating to new route

### ISSUE THREAD

**Issue by stefanlenoach** [pmndrs/zustand#220]
Apologies in advance for what's probably a noob question. I'm navigating to a new route (`/` -> `/todos`) and my store data  is getting cleared. How can I navigate to a new route and persist my store data? To give a little more context I'm using NextJS and navigating via Next's < Link > component.

**Comment by dai-shi** [comment]
Hi, do you create the store globally?
Also, check out #182 discussions, but it's rather technical.
My example https://github.com/pmndrs/zustand/issues/182#issuecomment-692038432 might help.

**Comment by stefanlenoach** [comment]
Thanks @dai-shi, your comment was very helpful.

**Comment by dai-shi** [comment]
Wonder if that solves your issue totally. Feel free to ask some more questions. Otherwise, can close this? @stefanlenoach

**Comment by stefanlenoach** [comment]
Really appreciate you trying to help, thank you. I was able to solve my problem without using a global store, but I still tried implementing what I saw in the example you mentioned. It looked like the example was implying I need to pass the current state of the store into `getServerSideProps` to then receive the previous page's store state as props, am I right on that? If so, it seems like a kind of roundabout way to do something that should be easy. Maybe I'm missing something?

**Comment by dai-shi** [comment]
Well, that example was specifically trying to illustrate the SSR usage. So, if you don't need, it's overcomplicated.

If you are just working on CSR, I suppose just creating a store should work. So in that sense, I don't think I understand your problem.

**Comment by stefanlenoach** [comment]
I tried creating the store in _app.tsx but it still acted the same way; whenever I go to another page the store gets wiped clean. Apologies for the miscommunication, quite possible I'm misunderstanding something.

**Comment by dai-shi** [comment]
I presume you are creating a store inside render or something, but not certain.
It would be good for you to create a minimal codesandbox example to share the problem.

**Comment by stefanlenoach** [comment]
Hey @dai-shi  I don't know how I missed this but it looks like the persist middleware is exactly what I need to solve this, sorry for the trouble!

**Comment by dai-shi** [comment]
Good. Let me close this issue. If you find any other concerns or questions. Feel free to file a new issue.
