### ISSUE TITLE
Update state in a function

### ISSUE THREAD

**Issue by kickbk** [pmndrs/zustand#221]
This should be easy, so I'm probably missing something.
I know how to update the state using the useStore hook inside a React component, but how do I update the store inside a functional component?

```
export function handleDeepLink(event) {
  const setUser = useStore((state) => state.setUser); << // Not allowed
```

**Comment by dai-shi** [comment]
Hi, `const setUser = useStore((state) => state.setUser)` seems correct if I guess the state shape correctly. So, I feel like I misunderstand your question. Would you explain again how you want to update the store?

**Comment by kickbk** [comment]
Hi @dai-shi I get this eslint error: `"React Hook "useStore" is called in function "handleDeepLink" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter.eslintreact-hooks/rules-of-hooks"`
I thought to just rename it with a capital letter, but then I get another error `[Unhandled promise rejection: Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:]`

**Comment by dai-shi** [comment]
> how do I update the store inside a functional component?

So, you want to update the store **outside** a component, correct?

Here's what you want:

```js
export function handleDeepLink(event) {
  const setUser = useStore.getState().setUser;
```

**Comment by kickbk** [comment]
outside! Arrr... sorry. Been a long day. Thank you, that works perfectly.

**Comment by dai-shi** [comment]
You are welcome!

**Comment by anastely** [comment]
Hey @dai-shi , I'm facing the same issue!
I do it like this pattern but actually not work as expected!

>  const setUser = useStore.getState().setUser;

I want to add/remove an item to an array"Favorite List", so when I use them in a function not work 'it just adds an item to the array but the expected behavior if this item exists not add it but remove!
So it's added a duplicated items,

**BUT**
when I use the same functions inside the React Component "FC"
it works very well!!

**Inside React FC**  (Work)
```

const Home = ()=>{ 
....

  const favoriteProductsList = useFavoriteProducts(
    (state) => state.favoriteProducts,
  );
  const setInFavorite = useFavoriteProducts((state) => state.setInFavorite);
  const removeFromFavorite = useFavoriteProducts(
    (state) => state.removeFromFavorite,
  );
  const addToFavorite = (favItem: ProductsProps) => {
    if (
      !favoriteProductsList.some(
        (alreadyFavorite) => alreadyFavorite.id === favItem.id,
      )
    ) {
      setInFavorite(item);
    } else {
      removeFromFavorite(item);
    }
  };
  ....
}
```

Separate Function (Not Work)

```

const favoriteProductsList = useFavoriteProducts.getState().favoriteProducts;
const setInFavorite = useFavoriteProducts.getState().setInFavorite;
const removeFromFavorite = useFavoriteProducts.getState().removeFromFavorite;

export const addToFavorite = (item: ProductsProps) => {
  if (
    !favoriteProductsList.some(
      (alreadyFavorite) => alreadyFavorite.id === item.id,
    )
  ) {
    setInFavorite(item);
    console.log('setInFavorite?'); 
  } else {
    removeFromFavorite(item);
    console.log('removeFromFavorite?');
  }
};

```

**Comment by dai-shi** [comment]
@anastely 
`getState()` is not reactive. So, you need to call it inside the non reactive function.
```ts
const setInFavorite = useFavoriteProducts.getState().setInFavorite;
const removeFromFavorite = useFavoriteProducts.getState().removeFromFavorite;

export const addToFavorite = (item: ProductsProps) => {
  const favoriteProductsList = useFavoriteProducts.getState().favoriteProducts;
  if (
    !favoriteProductsList.some(
      (alreadyFavorite) => alreadyFavorite.id === item.id,
    )
  ) {
    setInFavorite(item);
    console.log('setInFavorite?'); 
  } else {
    removeFromFavorite(item);
    console.log('removeFromFavorite?');
  }
};
```

**Comment by anastely** [comment]
@dai-shi yeah it's work!
But what's `non reactive function` exactly means?

**Comment by dai-shi** [comment]
@anastely I mean functions that are not called on re-render, or simply `non render function`.

**Comment by anastely** [comment]
@dai-shi hmm but why you did not add `​setInFavorite​ & ​removeFromFavorite​` inside it too

**Comment by dai-shi** [comment]
@anastely You can add them inside too. It's working because they never change in your use case.
