### ISSUE TITLE
Infinite Re render on calling a store method

### ISSUE THREAD

**Issue by prophet1996** [pmndrs/zustand#226]
On calling a store method the component is being re rendered
'''
import React from 'react';
import useFSStore from '../hooks/useFS';

const MKDIR: React.FC<{args:string[]}> = ({ args }:{args :string[]}) => {
  const { fs, mkdir } = useFSStore();
  return (<div>..</div>);
};

MKDIR.whyDidYouRender = true;

export default MKDIR;
'''

**Comment by prophet1996** [comment]
const initialFSState: FSState = {
  fs: [{
    name: '/',
    children: [],
    id: '/',
  }],
  permission: PERMISSION.ROOT,
  currentDir: '/',
};

const store = (set) => ({
  fs: initialFSState,
  mkdir: ({ name }) => set((state) => {
    // const { currentDir, fs: { children = [] } } = state;
    // const queue :FileState[][] = [];
    // queue.push(children);
    // while (queue.length > 0) {
    //   const currChildren = queue.pop();
    //   const childQueue:FileState[] = [];
    //   currChildren?.forEach((currChild) => {
    //     if (currentDir === currChild?.id) {
    //       currChild?.children.push({
    //         name,
    //         children: [],
    //         id: nanoid(),
    //       });
    //       return;
    //     }
    //     currChild?.children.forEach((child :FileState) => childQueue.push(child));
    //   });
    //   if (childQueue.length > 0) queue.push(childQueue);
    // }
    console.log(name, state);
  }),
});

export default create(store);

**Comment by dai-shi** [comment]
Hi, looks like it's a bit hard to guess the problem for me or someone. Would you try to create a repro with codesandbox? The repro should be small and focus the point. You may find a solution while creating a repro.

**Comment by prophet1996** [comment]
@dai-shi , i'll create a Sandbox, thanks for reply :+1:

**Comment by prophet1996** [comment]
Hi @dai-shi,
https://codesandbox.io/s/objective-hypatia-u4fvv?file=/src/useFS.js
here's  a reproduction

**Comment by dai-shi** [comment]
Thanks for the reproduction. It's small and easy to read.
The issue is not specific to zustand. In react, you want to wrap side-effect code with useEffect. mutating global state is a side effect.
Here's the fix: https://codesandbox.io/s/trusting-https-oz8bl?file=/src/mkdir.js

**Comment by prophet1996** [comment]
Thanks for the having a look. Great work btw on the lib
