### ISSUE TITLE
Best way to combine stores in multiple files

### ISSUE THREAD

**Issue by sepehr500** [pmndrs/zustand#228]
Does anybody have a good way of combining multiple smaller stores in multiple files into a single store?

**Comment by dai-shi** [comment]
You can combine multiple **store creators** into a single one to create a store.

```js
import createStoreA from '...'
import createStoreB from '...'

const useStore = create((set, get, api) => ({
  ...createStoreA(set, get, api),
  ...createStoreB(set, get, api),
}))
```

Disclaimer: I didn't test it.

**Comment by sepehr500** [comment]
Nice! Any idea how the types would work?

**Comment by dai-shi** [comment]
Good question. I'd expect it would work with type annotation, but not sure if type inference would work. Please give it a try.

**Comment by sepehr500** [comment]
It works! thanks.

**Comment by victorwpbastos** [comment]
> It works! thanks.

How did you make it work with types?

**Comment by FlorianGoussin** [comment]
Hello, I know this issue is closed, but I tried to follow it and I ended up with some errors. I started a thread on stackoverflow:
https://stackoverflow.com/questions/76444458/combine-two-stores-with-react-and-zustang
Could someone help me with that?

**Comment by dbritto-dev** [comment]
> Hello, I know this issue is closed, but I tried to follow the solution that seems to work for [sepehr500](https://github.com/sepehr500) and I ended up with some errors. I started a thread on stackoverflow:
> https://stackoverflow.com/questions/76444458/combine-two-stores-with-react-and-zustang
> Could someone help me with that? 

Please create a discussion so I can help you on that thread
