### ISSUE TITLE
Enable configuration of store prototype

### ISSUE THREAD

**Issue by HarrisonB** [pmndrs/zustand#231]
Right now, all store updates boil down to a call like
```javascript
Object.assign({}, oldState, newState)
```
assuming you're not overriding the old state. However, this precludes the store from being able to inherit behavior from a prototype.

A nice API for this might be to either specify the base object (i.e. the first param in the `Object.assign` call demonstrated above) or to customize the entire overriding logic, in the event that `Object.assign` does not satisfy your use-cases.

I know of the existing middleware API but I feel like this is a useful feature in its own right and might be a bit more elegant in certain situations (e.g. one could simply call `super` when needing logic from some "base" function)

**Comment by dai-shi** [comment]
We had a discussion before finalizing v3 api about removing Object.assign completely as it's an opinionated logic. However, given the most of use cases (and docs) are having action functions in the state, we decided to keep the behavior. So, `replace` is introduced to avoid the behavior.

Now, my question is how many people need this feature of copying prototype.
If it's small (which I'd expect) we recommend the use of `replace` or middleware as you implied.
On the other hand, if there's 100% backward compatible way with very little extra bundle size increase, we could consider adding the logic by default. I'm not sure about this.

Does it make sense?

**Comment by dai-shi** [comment]
Closing as stale.
