### ISSUE TITLE
Devtools not working

### ISSUE THREAD

**Issue by GreatState** [pmndrs/zustand#232]
My store

```
import { devtools } from 'zustand/middleware'
const useStore = create<IState>(
  devtools(set => ({
    appConfig: {},
    filters: {
      dispatch: args => set(state => filtersReducer(state, args)),
      data: null,
      status: null,
      error: null,
    },
  }))
)

```

i get TypeError: api.devtools.subscribe is not a function

![image](https://user-images.githubusercontent.com/35596657/98302268-00078800-1fb4-11eb-8a7e-8cc21fc8d374.png)

api.devtools.subscribe

runnning  "zustand": "^3.1.3"

**Comment by dai-shi** [comment]
It looks nothing weird to me. Would you try creating a codesandbox repro?

**Comment by GreatState** [comment]
strangley it works in firefox. Tried reinstalling redux dev tools in chrome but still the same

**Comment by dai-shi** [comment]
closing this as stale.
