### ISSUE TITLE
Migrating from Context (questions)

### ISSUE THREAD

**Issue by miladdev85** [pmndrs/zustand#235]
Zustand looks amazing but I need some help figuring out how to migrate from Context to Zustand in my hobby project.
I have Auth & User Provider via Context right now. How would I best switch from Context to Zustand? I'm using React Native.

```
<AuthProvider>
        <UserProvider>
              <BottomTabProvider>{children}</BottomTabProvider>
        </UserProvider>
</AuthProvider>
```

UserProvider has a useEffect for making a API request to download user object if Auth is true;

```
useEffect(() => {
    const getUser = async () => {
      try {
        const res = await axios.get(url, {
          withCredentials: true,
        });
        setUser({
          firstName: res.data.name.first,
        });
        setLoading(false);
      } catch (err) {}
    };
    if (auth) {
      getUser();
    }
  }, [auth, url]);
```

**Comment by dai-shi** [comment]
It depends on how you change `auth`, but I would assume something like this.

```js
const useStore = create(set => ({
  auth: false,
  user: null,
  userLoading: false,
  enableAuth: async () => {
    try {
      set({ auth: true, userLoading: true })
      const res = await axios.get(url, {
        withCredentials: true,
      });
      set({
        user: { firstName: res.data.name.first },
        userLoading: false,
      );
    } catch (err) {}
  }
}))
```

(Now, it looks there's less reason to have `auth`.)

**Comment by miladdev85** [comment]
Thank you 🙏🏼
Is there any recommendation to use one or multiple stores? Let's say me useAuthStore contains dynamic urls and I would like to use these urls in my useUserStore - is that possible? Or is it better to have one, maybe huge, store so everything is accessible?

**Comment by dai-shi** [comment]
It is totally valid to create multiple stores for different things. (It would help code splitting.)
If you are dealing with a single concept, I think one store would be good, and that's what I heard from developers.
For your use case, auth and user are from the same domain, so a single store would fit well as they are accessible. However, it is totally up to you.

**Comment by miladdev85** [comment]
Really appreciate your help here! I do however have a few more questions...
I'm reading `locale` from user object which is in my store. This value will not change after the user has logged in. 
How should I bring it in my component that needs it:

`const localeSelector = (state) => state.user.locale`

or

` const locale = useStore((state) => state.user.locale)`
 
Should I prefer other "read method" if the value will change?

**Comment by dai-shi** [comment]
Most recommended:
```js
const localeSelector = (state) => state.user.locale // outside components
const locale = useStore(localeSelector)
```

Fine if you want to colocate:
```js
const locale = useStore(useCallback((state) => state.user.locale, []))
```

Works (but not recommended in the future version):
```js
const locale = useStore((state) => state.user.locale)
```

----
> Should I prefer other "read method" if the value will change?

sorry, I don't get this question. can elaborate?

**Comment by miladdev85** [comment]
Thank you 🙏 
What I meant was, does it matter if the value from store will change during the component lifecycle? Am I subscribing to any changes no matter which method I use to import from store?

**Comment by dai-shi** [comment]
Still not confident if I get it, but the store value can be updated anywhere (except for the render body), and the hook will be properly notified the changes.

**Comment by dai-shi** [comment]
Assuming this is resolved, let me close this.
