### ISSUE TITLE
overview of the zustand API

### ISSUE THREAD

**Issue by alphabetabc** [pmndrs/zustand#2386]
### Discussed in https://github.com/pmndrs/zustand/discussions/2385

<div type='discussions-op-text'>

<sup>Originally posted by **alphabetabc** March  4, 2024</sup>
There is no API overview in the documentation, which is not friendly to beginners. Here is a simple list of APIs 

![image](https://github.com/pmndrs/zustand/assets/29876424/eaf38772-5661-436b-b0c7-7ef165642602)
</div>

**Comment by dai-shi** [comment]
Continue discussions in #2385
