### ISSUE TITLE
Multiple versions of the same state on one component but with different values?

### ISSUE THREAD

**Issue by Jaja0624** [pmndrs/zustand#239]
My app has three versions of each of my two stores. 2 of them are the same (duplicates) and the last one is not the same. Not all components are reading the same version... I'm not very experienced with React so I am not sure if this is a common issue with React state in general?

![image](https://user-images.githubusercontent.com/31715149/98894041-c07be880-2458-11eb-8f88-58d3e95660b4.png)

**Comment by dai-shi** [comment]
Hi, would you elaborate what's the problem you are seeing and how we can reproduce?

---
Investigating `useStore` in React DevTools is not very useful unless one is debugging the library itself. (This reminds me that we would like to add `useDebugValue` in useStore.)

**Comment by Jaja0624** [comment]
There are three versions of the same state. Two of them are expanded. My components are using different versions so there is no state consistency. 

Here is one component's state. This component is using the last version.
![image](https://user-images.githubusercontent.com/31715149/99031608-56cd0e80-252c-11eb-93d8-6b517c566153.png)

Here is another component's state. This component is probably also using the last version but you can see it is different even though it is using the same store.
![image](https://user-images.githubusercontent.com/31715149/99031542-2d13e780-252c-11eb-8f11-62dd49b3c0ac.png)

**Comment by dai-shi** [comment]
> So my root component (App.tsx) state is not the same as all my other components. 

That sounds weird. Would you be able to create a small reproduction in codesandbox?

**Comment by Jaja0624** [comment]
I tried creating a code sand box but I am getting error. Can you help me out. https://codesandbox.io/s/sweet-wildflower-kro4r?file=/src/App.js:0-323.

Have u seen this issue before? (Client sets state but state does not change)

**Comment by Jaja0624** [comment]
To give u an idea, this is my state code which I believe is correct.

```
    spotifyProfile: undefined,
    setSpotifyProfile: (spotifyProfile: any) => { 
        console.log("setting spotify profile", spotifyProfile)
        set({spotifyProfile : spotifyProfile})
    },
```

**Comment by dai-shi** [comment]
Here's the fixed version: https://codesandbox.io/s/determined-frog-prr9h

I suppose you just need some minor changes. Let me know if something is not very clear.

**Comment by dai-shi** [comment]
Closing as resolved.
