### ISSUE TITLE
Expose previous value in subscribe

### ISSUE THREAD

**Issue by Tirzono** [pmndrs/zustand#240]
It would be very useful to also have access to the previous value when subscribing to the store:

```javascript
const unsub2 = useStore.subscribe((paw, previousPaw) => console.log(paw, previousPaw), state => state.paw)
```

**Comment by dai-shi** [comment]
Hi, thanks for opening this up.

@dios-david suggested as mitigation in #234 and I think it's ok: https://github.com/pmndrs/zustand/pull/234#issuecomment-723390078 (at least without selector/equalityFn)
