### ISSUE TITLE
Versioned Persist Middleware

### ISSUE THREAD

**Issue by jvonasek** [pmndrs/zustand#243]
Hi, thanks for your great work on this library.

I made an update to the persist middleware to add version property to the stored state.
Would it be a good addition to the core library, or is it out of the scope?

Code here: https://gist.github.com/jvonasek/c6838243f205815077be032b1fa2e521

Works like usual, but with new verison property in the persist middleware options
```javascript
const useStore = create<State>(
  persist(
    (set) => ({
      theme:  Theme.Light,
      setTheme: (theme: Theme) => set(() => ({ theme })),
    }),
    {
      name: 'theme',
      version: 1,
    }
  )
)
```
Produces this state in the storage
```json
{
  "theme": "light",
  "_version": 1
}
```

If I change the shape of my state to something like this
```javascript
type State = {
  themes: [Theme, SubTheme]
  setThemes: (theme: Theme, subTheme: SubTheme) => void
}
```
My  state would normally become this, or if I didn't rename the theme property to themes, it would even break the application
```json
{
  "themes": ["dark","navy"],
  "theme": "light"
}
```
However, if I increase the version property in my persist state creator to 2, the original state will be purged and recreated
```json
{
  "themes": ["dark","navy"],
  "_version": 2
}
```

This can be further iterated on and add migration support, however I feel that's probably better as an external middleware.
Inspired by redux-persist

**Comment by dai-shi** [comment]
@AnatoleLucet thoughts?

**Comment by AnatoleLucet** [comment]
Funny, I ended up doing the exact same thing before we implemented a built-in persist middleware in Zustand. The only diff is that I created some kind of middleware passed through the options to transform old versions to newer ones.

But yes, I don't think this is a bad idea. Though we probably shouldn't create a middleware like I did, it rapidly makes everything messy.

**Comment by jvonasek** [comment]
> Though we probably shouldn't create a middleware like I did, it rapidly makes everything messy.

I agree, migrations can get messy and persist middleware with migration support to transform stored state would proably be better as an external plugin.

I think this is simple solution and helps with local storage polution when something in the app changes, which might lead to issues.

Downside is that the stored state will be lost, but you would have to purge it somehow anyway, if you change the shape of your state.
