### ISSUE TITLE
Updating state doesn't trigger a component rerender

### ISSUE THREAD

**Issue by GRA0007** [pmndrs/zustand#244]
👋 So I have set up a simple store, keeping track of an array of objects, and I have one action that edits just one of those objects based on an ID parameter.
```js
// Format of the list of objects
list: [
  {
    id: '123',
    // other data
  },
  // other objects
],
editItem: (id, newItem) => set(state => {
  return {
    list: state.list.map(item => {
      if (item.id == id) {
        return newItem;
      }
      return item;
    }),
  };
}),
// more actions
```

I have a component that is using this `list`, which reflects the data in just one of the objects, and so I'm using the following code to get that inside my component function:
```js
// 'id' is passed through my navigation
const items = useStore(state => state.list);
const item = items.find(i => i.id == id);
```

I'm displaying a property from my `item` in that component, but my problem occurs when I call that `editItem` action from another screen, my original component doesn't rerender. I'm sure that Zustand is updating the state correctly, because a `subscribe` listener on my `items` array gets called every time it updates.

Any help would be very appreciated; not sure if I'm just missing something or if this is an issue with Zustand.

**Comment by Tirzono** [comment]
> but my problem occurs when I call that `editItem` action from another screen

Just to avoid confusion: do you mean `editItem` from another component or from another browser screen/tab?

Anyway, it looks like your selector is wrong, you want `state.list` instead of `state.items`:

```javascript
// 'id' is passed through my navigation
const items = useStore(state => state.list);
const item = items.find(i => i.id == id);
```

**Comment by GRA0007** [comment]
Good pickup, sorry I was abstracting away my code and missed that. I'm coding a React Native app using React Navigation, so I mean a separate screen in the app.

**Comment by dai-shi** [comment]
From the description, there seems to be no issues. So, next is you want to try creating a repro in codesandbox?

**Comment by onygami** [comment]
[Here a todo list I built.](https://codesandbox.io/s/quirky-panini-yv9wp?file=/src/App.tsx) It has a score for each todo item, when I increment the score, in the console you can see that the store updates. But the parent component does not re render. If you add another todo item, only then the previous actions are reflected.

**Comment by dai-shi** [comment]
@onygami You need to update state immutably. Here's the fix:
https://codesandbox.io/s/inspiring-mountain-z93fi?file=/src/useTodos.ts

**Comment by dai-shi** [comment]
Let me close this issue as the original question is stale.

@onygami If you have a follow up comment, feel free to post it here.

**Comment by onygami** [comment]
@dai-shi Thanks, that was dumb of me, I thought a simple return will update state immutably.

**Comment by dai-shi** [comment]
Or, if you used [immer middleware](https://github.com/pmndrs/zustand#middleware), your code would also work.

(tbh, if one has preference on mutation style, I'd recommend [valtio](https://github.com/pmndrs/valtio) instead.)

**Comment by CoderJaez** [comment]
I having the same issue on not rendering component after a state change in zustand.

**Comment by dai-shi** [comment]
You probably want to open a new discussion: https://github.com/pmndrs/zustand/discussions/new
