### ISSUE TITLE
Persist middleware in server rendered environments

### ISSUE THREAD

**Issue by RobbyUitbeijerse** [pmndrs/zustand#245]
Hi there!

While working with the new persist middleware I figured using it in a server rendered environment (in my case, next.js) it would throw as the default localStorage api expectedly isn't available on the server.

This was easily fixed by passing a dummy storage api but I wondered whenever this should actually be a default within zustand to not confuse users adopting the new middleware within a next.js/nuxt.js project. Not entirely sure whenever this is intended or can be considered a 'bug', but it might help new users if it would not break any server render by default.

here is an example of what I did in my app

```
const dummyStorageApi = {
  getItem: () => null,
  setItem: () => undefined,
}

const useStore = create(
  persist(
    set => ({
      user: null,
      updateUser: user => set({ user }),
    }),
    {
      name: 'someStoragekey',
      storage: typeof window !== 'undefined' ? window.localStorage : dummyStorageApi,
    },
  ),
)

```

**Comment by dai-shi** [comment]
Hm, it was me who suggested to avoid `typeof window` check, because it's not very deterministic. Your suggestion is convincing. Let me try to check localStorage directly.
