### ISSUE TITLE
persist middleware fails after two refreshes

### ISSUE THREAD

**Issue by tylershuster** [pmndrs/zustand#264]
I'm scratching my head on this one — the persist middleware seems to work fine. I can set state properties and they follow me around the app. When I refresh, all my data is there. But when I refresh *again*, the state resets to its initial state. Any idea why this happens?

**Comment by AnatoleLucet** [comment]
Hi, can you send the related code? 🙏

**Comment by tylershuster** [comment]
Sure:
```tsx
import React, { ReactNode } from "react";
import create, { State }  from 'zustand';
import { persist } from 'zustand/middleware';
import produce from 'immer';
import { BackgroundConfig, RemoteContentPolicy } from "~/types/local-update";

export interface LocalState extends State {
  hideAvatars: boolean;
  hideNicknames: boolean;
  remoteContentPolicy: RemoteContentPolicy;
  dark: boolean;
  background: BackgroundConfig;
  omniboxShown: boolean;
  suspendedFocus?: HTMLElement;
  toggleOmnibox: () => void;
  set: (fn: (state: LocalState) => void) => void
};

const useLocalState = create<LocalState>(persist((set, get) => ({
  dark: false,
  background: undefined,
  hideAvatars: false,
  hideNicknames: false,
  remoteContentPolicy: {
    imageShown: true,
    audioShown: true,
    videoShown: true,
    oembedShown: true,
  },
  omniboxShown: false,
  suspendedFocus: undefined,
  toggleOmnibox: () => set(produce(state => {
    state.omniboxShown = !state.omniboxShown;
    if (state.suspendedFocus) {
      state.suspendedFocus.focus();
      state.suspendedFocus = undefined;
    } else {
      state.suspendedFocus = document.activeElement;
      state.suspendedFocus.blur();
    }
  })),
  set: fn => set(produce(fn))
}), {
  name: 'localReducer'
}));

function withLocalState<P, S extends keyof LocalState>(Component: any, stateMemberKeys?: S[]) {
  return React.forwardRef((props: Omit<P, S>, ref) => {
    const localState = stateMemberKeys ? useLocalState(
      state => stateMemberKeys.reduce(
        (object, key) => ({ ...object, [key]: state[key] }), {}
      )
    ): useLocalState();
    return <Component ref={ref} {...localState} {...props} />
  });
}

export { useLocalState as default, withLocalState };
```

**Comment by AnatoleLucet** [comment]
This is probably because you're trying to store `document.activeElement` in the state. `persist` serialize your state in json to store it in a storage.
![](https://i.gyazo.com/dc464295ae313bce5c296c8aff5915ed.png)

Can you retry with some lines of `toggleOmnibox` commented?

**Comment by AnatoleLucet** [comment]
That actually raises an interesting point. We should probably check the state and only keep the json friendly values.

**Comment by tylershuster** [comment]
I tried what you said and it didn't work, but it got me thinking down another route that led me to the solution. Perhaps it will help you.

In the root `<App />`, which is wrapped with `withLocalState` there is this code:
```tsx
componentDidMount() {
    ...
    this.themeWatcher = window.matchMedia('(prefers-color-scheme: dark)');
    this.props.set(state => {
       state.dark = this.themeWatcher.matches;
    });
  ...
}
```

Removing the `this.props.set` code caused the problem to disappear.

**Comment by tylershuster** [comment]
Interested if you have an explanation for this but I'll close the issue.

**Comment by AnatoleLucet** [comment]
Well, I'm unable to reproduce your issue, so I can really try to understand why. Though I think this is more of a js gotcha than an issue with the middleware.
Anyway, happy to hear that you've found the source 🎉

**Comment by kevinxh** [comment]
If anyone is running into this issue, it might be that you are using `partialize` and renamed the key in storage. TIL you can't rename key in `partialize`
