### ISSUE TITLE
Persist middleware api

### ISSUE THREAD

**Issue by AnatoleLucet** [pmndrs/zustand#267]
Follow up of https://github.com/pmndrs/zustand/pull/248#issuecomment-752130586. The idea is to make an api to interact with `persist`.

#### Change the options
```js
useMyStore.persist.setOptions({
  getStorage: () => sessionStorage,
})
```
This `setOptions` could be useful to, for example, choose a storage at runtime if the use check a box or something. It could also be used to change the name of the storage as needed here: https://github.com/pmndrs/zustand/pull/248#issuecomment-752130586

#### Clear storage data
```js
useMyStore.persist.clearStorage()
```

#### On demand rehydration (see #374)
```js
useMyStore.persist.rehydrate()
```

**Comment by Daiz** [comment]
So while I imagine the implementation here shouldn't be too complicated by simply extending the api along the lines of this:

```typescript
type PersistApi = {
  persist: {
    setOptions: () => void;
    clearStorage: () => void;
    rehydrate: () => Promise<void>;
  };
};

export const persist = <S extends State>(
  config: StateCreator<S>,
  options: PersistOptions<S>
) => (set: SetState<S>, get: GetState<S>, api: StoreApi<S> & PersistApi): S => {

  /* ... */

  const rehydrate = async () => { /* the existing rehydrate function */ }

  api.persist = {
    setOptions: () => { /* implementation */ },
    clearStorage: () => { /* implementation */ },
    rehydrate,
  };

  /* ... */
};
```

But one issue I see here is the TypeScript story for middleware API extensions. How do we make it so that this doesn't result in red squigglies?

```typescript
type State = {
  fishes: number;
  addAFish: () => void;
}

export const useStore = create<State>(
  persist(
    (set, get) => ({
      fishes: 0,
      addAFish: () => set({ fishes: get().fishes + 1 }),
    }),
    {
      name: "food-storage", // unique name
      getStorage: () => sessionStorage, // (optional) by default the 'localStorage' is used
    }
  )
);

useStore.persist.clearStorage();
//       ^^^^^^^
// Property 'persist' does not exist on type 'UseStore<State>'
```

Ideally, I imagine this would have some sort of automatic typing solution where middleware can augment the return type, but as a workaround, something like this would do as well:

```diff
- export default function create<TState extends State>(
+ export default function create<TState extends State, TMiddlewareApi = {}>(
  createState: StateCreator<TState> | StoreApi<TState>
- ): UseStore<TState> { /* ... */ }
+ ): UseStore<TState> & TMiddlewareApi { /* ... */ }
```

And then you could do this:

```typescript
import { persist, PersistApi } from "zustand/middleware";

export const useStore = create<State, PersistApi>(/* ... */);
// useStore is now of type UseStore<State> & PersistApi

useStore.persist.clearStorage();
// no more TypeScript error here
```

As said, having to manually type your middleware APIs like this wouldn't be ideal, but it would work and would even support multiple middleware easily (as you could just do `create<State, FooApi & BarApi & BazApi>`).

Thoughts?

**Comment by AnatoleLucet** [comment]
For the "raw" implementation, that's pretty much what I had in mind.

@dai-shi any thoughts to make the return type of `create` dynamic?

**Comment by dai-shi** [comment]
Yeah, this is requested before for redux middleware: #212 
So, tbh I'm not sure if an ideal (type safe) solution is possible. Even if not ideal, there should be room for improvement like suggested.
Personally, I'm not motivated to investigate it (I think middleware is bad at types by its design and I'm not skilled enough), but if someone can try, I'm happy to review (and learn it).

**Comment by Daiz** [comment]
Middleware API extensions are definitely a hairy problem for typing. In which case, if there's no motivation to investigate an "automatic" typing solution at this time, I think it would be a good idea to move forward with the manual typing solution I proposed above where the middleware API definitions are exported and the consumer must pass them in as a second type parameter to `create`. After all, this problem ultimately doesn't really affect JS usage and if someone eventually does come up with a better type solution for TypeScript I imagine it shouldn't be a major code change for existing consumers of middleware API typings (just removal of an additional type parameter), so having the functionality available would definitely be an improvement over not having it even if the TypeScript story isn't perfect.

**Comment by dai-shi** [comment]
Would manual typing the same as type assertion, technically?

```ts
export const useStore = create<State, PersistApi>(/* ... */);
// the above is equivalent to the below
export const useStore = create<State>(/* ... */) as UseStore<State> & PersistApi;
```

I'm a bit worried because the former looks type-safe, which is not true with "manual" typing, and it can cause runtime error. In other words, it's just _hiding_ the type assertion in the library, which doesn't sound right.

Maybe it's like type correctness vs. developer experience. What do you think?

**Comment by Daiz** [comment]
You're right - the proposed approach is essentially just a type assertion. The benefit of doing it as a type parameter is that you don't need to import the UseStore type manually, but considering how you'd be importing the Middleware API types anyway it wouldn't be a big stretch to do so anyway, in which case the suggested approach might as well be "use type assertion like this if you're using middleware with API extensions". In which case the main thing needed to make things work would be to a) define and export middleware API types from the relevant modules and b) document the necessary type assertion for `create` in the readme.

**Comment by dai-shi** [comment]
Yeah, that sounds good to me.
