### ISSUE TITLE
Search does not work on docs WWW

### ISSUE THREAD

**Issue by mpoweredo** [pmndrs/zustand#2675]
<img width="2228" alt="Zrzut ekranu 2024-08-11 o 16 20 20" src="https://github.com/user-attachments/assets/166ee135-af44-49be-b053-1501f97ce7ef">

**Comment by dai-shi** [comment]
@abernier Will #2674 fix the search feature?

**Comment by abernier** [comment]
this screenshot comes from https://pmndrs.github.io/zustand right?

**Comment by abernier** [comment]
ok, on https://pmndrs.github.io/zustand/ yes!
![image](https://github.com/user-attachments/assets/f24b7b08-5bdf-4863-818c-90c69e05d8b4)
