### ISSUE TITLE
Zustand, Next.js, localStorage

### ISSUE THREAD

**Issue by orbor** [pmndrs/zustand#268]
Excuse me, in fact this is not an issue, this is a beginner's question.

I'm using Zustand with Next.js, and trying to set an initial value from localStorage in const useStore.

E.g. if exist in local storage - set it from local storage, if not - let it be integer 1.

Tried your example from Github:
```
import create from "zustand"
import { persist } from "zustand/middleware"

export const useStore = create(persist(
  (set, get) => ({
    fish: 0,
    addAFish: () => set({ fish: get().fish + 1 })
  }),
  {
    name: "food-storage", // unique name
    storage: sessionStorage, // (optional) default is 'localStorage'
  }
))
```

[Tried RobbyUitbeijerse solution](https://github.com/pmndrs/zustand/issues/245#issue-749551108).

I'm receiving an error:
```
error - ReferenceError: localStorage is not defined
(or window is not defined) in 2nd case...
at /home/nnnn/nnnn/node_modules/zustand/middleware.js:104:45
```

It's obviously SSR related and I'll be very gratefull for any hint.

Everything I need is to set above mentioned 'fish' (or bears from main example) from local storage (if such key exist in local storage) or to set some default value if such key does not exist in local storage.

**Comment by AnatoleLucet** [comment]
Hey, the current example on the readme doesn't work for ssr since `sessionStorage` is not defined on the server. This is discussed in #248 (I'll draft a pr soon to fix this).

> Tried RobbyUitbeijerse solution.

It works on my side. Can you share your code?

**Comment by AnatoleLucet** [comment]
Closing this for now, I'll reopen if it turns out to be a bug.
