### ISSUE TITLE
[jest] Testing with @testing-library/react-hooks

### ISSUE THREAD

**Issue by xD3CODER** [pmndrs/zustand#272]
Hi, 

First thank's for this amazing library !

I have an issue when I try to test some store with [@testing-library/react-hooks](https://github.com/testing-library/react-hooks-testing-library)

I get this error even if I wrap my updating state call  in `act()`. 

```
   console.error
      Warning: An update to TestHook inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
```

My code:

```
it('should pass if user logged', () => {
  const { result, waitForNextUpdate } = renderHook(() =>
    userStore((state) => state)
  )

  act(() => result.current.setUserLogged(true))

...
})
```

Thank's

**Comment by 3nvi** [comment]
I tried and couldn't reproduce this behavior. Is there a chance you can add a concrete example that can reproduce this behavior?

**Comment by xD3CODER** [comment]
While I was creating a reproducible demo, I noticed that the error was related to the proposed mock implementation #271 The issue disappear when I remove the mock

I forgot to mention that I am in an Expo environment

**Comment by 3nvi** [comment]
Ah gotcha. Yeah this snippet is not yet polished. It just serves as a proposal in case the zustand team is interested in integrating.

I've personally tried it with React and I didn't get any warnings, so it might be related to react-native/expo. My best guess would be to wrap the firing of the `resetFn` with an act like so:

```tsx
// You could also wrap the entire loop with `act` 
afterEach(() => {
  storeResetFns.forEach(resetFn => {
    act(() => resetFn())
  });
});
```

although I find it weird how a cleaning function outside of React could produce this 😞

**Comment by xD3CODER** [comment]
@3nvi I confirm that it works, thank's for your help

**Comment by 3nvi** [comment]
> @3nvi I confirm that it works, thank's for your help

Cheers! Is there anything more to do with regards to this issue or should it be closed?

**Comment by jgplaidypus** [comment]
Can we make this change to this page https://github.com/pmndrs/zustand/wiki/Testing.

I feel this should be part of setting up the mock.

**Comment by ivancuric** [comment]
I would like to just comment that I've came across the same issue. It works with the setup on the [wiki page](https://github.com/pmndrs/zustand/wiki/Testing), but only in a Create React App project.

I was getting the same errors in a non-CRA project so I made 2 repos that reproduce the issue:
https://github.com/ivancuric/jest-repro
https://github.com/ivancuric/jest-repro-2

The issue went away when I switched jest to use `testRunner: 'jest-circus/runner'` like in CRA.

I propose documenting this in the wiki, or at least updating it with the `act(() => resetFn())` like in https://github.com/pmndrs/zustand/issues/272#issuecomment-756059996

**Comment by dai-shi** [comment]
Sounds good. Would you update the wiki please?

**Comment by ivancuric** [comment]
Will do.

**Comment by ivancuric** [comment]
I updated the wiki. Didn't know anyone could do it without a PR of some sort.

**Comment by italodeandra** [comment]
For future reference, Valtio also has this same problem and `jest-circus/runner` fixed it (where act didn't).

(I ended up here while looking for a solution for valtio, so someone else might as well)
