### ISSUE TITLE
[Feedback Request] Does Zustand v5-rc work for you?

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/zustand#2741]
## How to Install

```bash
npm i zustand@next
```

## Migration Guide

https://github.com/pmndrs/zustand/blob/main/docs/migrations/migrating-to-v5.md

## How to respond

Add comments to this issue or add reactions to this issue comment.

👍 : I've tested v5-rc and it works fine for me.
👎 : I've tested v5-rc and found an issue. < Comment below!
👀 : I'll try it later.

**Comment by pavitra-infocusp** [comment]
Is it intentional to push an RC release to the latest?
![image](https://github.com/user-attachments/assets/c3c641de-ba15-498b-a633-a33705528255)

Anyways, my app doesn't work. It crashed when I open the page :(
```
Unexpected Application Error!
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (http://localhost:5173/node_modules/.vite/deps/chunk-HHZE2HUH.js?v=9df50b02:19659:19)
    at scheduleUpdateOnFiber (http://localhost:5173/node_modules/.vite/deps/chunk-HHZE2HUH.js?v=9df50b02:18533:11)
    at dispatchSetState (http://localhost:5173/node_modules/.vite/deps/chunk-HHZE2HUH.js?v=9df50b02:12403:15)
    at update (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=54cc688f:14580:11)
    at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=54cc688f:14583:7
    at commitHookEffectListMount (http://localhost:5173/node_modules/.vite/deps/chunk-HHZE2HUH.js?v=9df50b02:16915:34)
    at commitLayoutEffectOnFiber (http://localhost:5173/node_modules/.vite/deps/chunk-HHZE2HUH.js?v=9df50b02:17002:23)
    at commitLayoutMountEffects_complete (http://localhost:5173/node_modules/.vite/deps/chunk-HHZE2HUH.js?v=9df50b02:17980:17)
    at commitLayoutEffects_begin (http://localhost:5173/node_modules/.vite/deps/chunk-HHZE2HUH.js?v=9df50b02:17969:15)
    at commitLayoutEffects (http://localhost:5173/node_modules/.vite/deps/chunk-HHZE2HUH.js?v=9df50b02:17920:11)
```

**Comment by dai-shi** [comment]
Yes, this is the last resort I can think of to get some feedback. [related tweet](https://x.com/dai_shi/status/1834873207884857370)
Thanks for reporting. 
@pavitra-infocusp Can you try this? https://github.com/pmndrs/zustand/blob/b93e11681d7b70c60dc99ae5296216a066f466b7/docs/migrations/migrating-to-v5.md?plain=1#L92

**Comment by pavitra-infocusp** [comment]
@dai-shi I have updated the comment above with how I use zustand. It's a new and simple app. Do I have to provide a Fallback for all selectors? That would be so unnecessary, wouldn't it be?

**Comment by pavitra-infocusp** [comment]
So `array == bad` is the problem, because it creates a new array on each render?

**Comment by pavitra-infocusp** [comment]
```diff
-const [searchValue, setSearchValue] = useStore((state) => [state.searchValue, state.setSearchValue]);
+const searchValue = useStore((state) => state.searchValue);
+const setSearchValue = useStore((state) => state.setSearchValue);
```

Is this the only way to make the selector references stable? Is it possible to group them together to reduce boilerplate and function calls?

**Comment by dbritto-dev** [comment]
@pavitra-infocusp sure

```ts
const [searchValue, setSearchValue] = useStore(useShallow((state) => [state.searchValue, state.setSearchValue]));
```

**Comment by pavitra-infocusp** [comment]
Thanks @dai-shi and @dbritto-dev. Zustand v5 is now working fine.

**Comment by Olfdev** [comment]
I was having troubles as well on 5.0.0 rc2 where v4.5.5 was working fine (or at least, not telling me there was issues but was running fine). I'm not sure how to fix them even though I spent a few hours trying to find the culprit.

1. Warning: The result of getSnapshot should be cached to avoid an infinite loop
2. Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

I had to use useShallow, that's it. Now I need to go see what this is all about to understand why this suddenly happened.

`const {
		tables,
		fetchTables,
	} = useUserStore((state) => ({
		tables: state.tables,
		fetchTables: state.fetchTables,
	}));`
	
	to
	
	`const {
		tables,
		fetchTables,
	} = useUserStore(useShallow(state) => ({
		tables: state.tables,
		fetchTables: state.fetchTables,
	})));`

**Comment by dai-shi** [comment]
Thanks for reporting! This is a bit unexpected to me, as my assumption was it can cause the infinite loop even in v4. I think we need to clarify this in the v5 migration guide.

**Comment by mehimanshupatil** [comment]
typescript error when using with immer middleware and slice pattern.
error location Inside Immer callback, where function arguments are being spread (...a)
[reproducible example](https://codesandbox.io/p/sandbox/zustand-v5-z7d2fd)
```
Types of parameters 'shouldReplace' and 'replace' are incompatible.
Type 'true' is not assignable to type 'false'.
```

**Comment by dai-shi** [comment]
Thanks reporting. #2580 is the related PR.
@Yonom Can you investigate it please? We need a test too.

**Comment by cuquo** [comment]
Everything works with the RC. I tried previous versions, and the only additional step I needed to take was to avoid having a fallback to empty arrays. With the React compiler, there was an issue with react.Ref when I created the Store context. However, that was fixed by the React team some weeks ago.

**Comment by dbritto-dev** [comment]
@Yonom here you go -> https://tsplay.dev/N57P9W

**Comment by wuarmin** [comment]
In development everything works, but in production build I get weird and hard to debug errors:

![Screenshot from 2024-09-24 20-09-58](https://github.com/user-attachments/assets/534ea594-c7b7-43b3-b334-51f44f32a853)

**Comment by dbritto-dev** [comment]
@wuarmin would you mind creating a minimal repro on stackblitz? I'd be happy to help

**Comment by dai-shi** [comment]
https://react.dev/errors/185

It seems like unstable selector result. I wonder why it doesn't happen in development.

**Comment by wuarmin** [comment]
> @wuarmin would you mind creating a minimal repro on stackblitz? I'd be happy to help

Buh, I'm pretty busy at the moment. I will try, but I probably won't be able to do this repro this week.


> It seems like unstable selector result. I wonder why it doesn't happen in development.

Yes, it was pretty sobering when I deployed and then nothing worked anymore. I searched for a long time until I found out that zustand had something to do with it. 

This is the zustand store that triggers the error in the prod area, among other things:

```javascript
import { create } from "zustand";
import { useQuery, keepPreviousData } from "@tanstack/react-query";
import { gql } from "graphql-request";
import { apiClient } from "@/features/query";
import { Order } from "@/graphql/fragments";

const query = gql`
  query FilteredOrders($after: String, $first: Int, $query: OrdersQueryInput!) {
    filteredOrders(after: $after, first: $first, query: $query) {
      totalCount
      nodes {
        ...Order
      }
    }
  }
  ${Order}
`;

export const statusCategories = [
  { id: "all", name: "Alle" },
  { id: "action_required", name: "Aktion erforderlich" },
];

const afterForPage = (page, itemsPerPage) => String((page - 1) * itemsPerPage);

const pageParams = (page, itemsPerPage) => ({
  after: afterForPage(page, itemsPerPage),
  first: itemsPerPage,
});

const paginationFilterState = (set, get) => ({
  filterItems: { statusCategory: "action_required" },
  filters: [],
  sort: [{ id: "id", desc: true }],
  rowSelection: {},
  page: 1,
  actions: {
    applyFilters: (filters) => set({ filters, page: 1 }),
    applyFilterItem: (id, value) => {
      const newFilterItems = { ...get().filterItems, [id]: value };
      if (!value) {
        delete newFilterItems[id];
      }
      set({ filterItems: newFilterItems, page: 1 });
    },
    goToPage: (page) => set({ page, rowSelection: {} }),
    sort: (sort) => set({ sort }),
    applyRowSelection: (rowSelection) => set({ rowSelection }),
  },
});

const useQueryStore = create(paginationFilterState);

const useFilter = () =>
  useQueryStore(({ filters, filterItems }) => {
    return {
      ...filters.reduce((acc, { id, value }) => ({ ...acc, [id]: value }), {}),
      ...filterItems,
    };
  });
export const useFilterItems = () =>
  useQueryStore(({ filterItems }) => filterItems);
export const useFilters = () => useQueryStore(({ filters }) => filters);
export const usePage = () => useQueryStore(({ page }) => page);
export const useRowSelection = () =>
  useQueryStore(({ rowSelection }) => rowSelection);
export const useSort = () => useQueryStore(({ sort }) => sort);
export const useQueryActions = () => useQueryStore((state) => state.actions);

export function useOrders({ itemsPerPage = 100 } = {}) {
  const filter = useFilter();
  const page = usePage();
  const sort = useSort();

  return useQuery({
    queryKey: ["orders", "list", filter, sort, page, itemsPerPage],
    placeholderData: keepPreviousData,
    queryFn: async () => {
      return apiClient
        .rq(query, {
          ...pageParams(page, itemsPerPage),
          query: { filter, sort },
        })
        .then((data) => ({
          totalPages: Math.ceil(data.filteredOrders.totalCount / itemsPerPage),
          records: data.filteredOrders.nodes,
        }));
    },
  });
}
``

@dai-shi Do you see a problem.

Thanks

**Comment by dai-shi** [comment]
```js
  useQueryStore(({ filters, filterItems }) => {
    return {
      // ...
    };
  });
  ```
is creating a new object every time which causes infinite loops.

**Comment by pavitra-infocusp** [comment]
@dai-shi I think the docs have to be updated as well to not encourage this kind of usages

https://zustand.docs.pmnd.rs/apis/create#updating-state-based-on-previous-state:~:text=const%20%5Bage%2C%20setAge%5D%20%3D%20useAgeStore((state)%20%3D%3E%20%5Bstate.age%2C%20state.setAge%5D)

![image](https://github.com/user-attachments/assets/4c4d40cf-a7b1-47ec-b7ef-d55f458cb5c0)

**Comment by dai-shi** [comment]
Wow, I didn't notice that. @dbritto-dev Can you fix?

**Comment by dbritto-dev** [comment]
@dai-shi sure. BTW, we talked about that in `useStore`

**Comment by wuarmin** [comment]
> is creating a new object every time which causes infinite loops.
Thanks @dai-shi 

What's the best way to rewrite this:

```js
const useFilter = () =>
  useQueryStore(({ filters, filterItems }) => {
    return {
      ...filters.reduce((acc, { id, value }) => ({ ...acc, [id]: value }), {}),
      ...filterItems,
    };
  });
```

**Comment by dai-shi** [comment]
It's tricky. proxy-memoize may help, but I think you should at least separate to `useFilters` and `useFilterItems`. Then, half of the problem is solved, but then if we are changing the signature anyway, it's breaking, so you should also consider avoid `reduce` completely. Hm, maybe this works.

```js
const useFilters = () => {
  const filters = useQueryStore((state) => state.filters);
  return filters.reduce((acc, { id, value }) => ({ ...acc, [id]: value }), {});
};
const useFilterItems = () => useQueryStore((state) => state.filterItems);
```

**Comment by Yonom** [comment]
re: @mehimanshupatil @dai-shi 

Minimal example - works in v4, breaks in v5

```ts
import { create, StateCreator } from "zustand";
import { immer } from "zustand/middleware/immer";

interface Slice1 {
  foo: string;
}

interface Slice2 {
  bar: string;
}

const createSlice1: StateCreator<Slice1, [], [], Slice1> = (set) => ({
  foo: "test",
});

export const useBoundStore = create<Slice1 & Slice2>()(
  immer((...a) => ({
    ...createSlice1(...a),
  }))
);
```

Fix in v5:

```ts
const createSlice1: StateCreator<Slice1 & Slice2, [], [], Slice1> = (set) => ({
```

The first parameter of StateCreator now requires the entire correct type of the store. I think this is a bug?

I unfortunately don't have the bandwidth in the next two weeks to investigate why. Help is appreciated!

**Comment by dai-shi** [comment]
> Is the StateCreator's first parameter supposed to contain the entire type of the store?

Yes, I believe so. (And, yes, I noticed in some cases, it can be a Partial of it.)
So, I think the docs can be improved. @dbritto-dev What do you think?

**Comment by dbritto-dev** [comment]
@dai-shi v5 looks good to me, some people think that the slice only get the slice state instead the whole store state when actually you get the whole store state

**Comment by dai-shi** [comment]
@dbritto-dev 

https://github.com/pmndrs/zustand/blob/6b29015c3b9fdf5a5aa08b69811044f90c0f8d1b/docs/guides/typescript.md?plain=1#L416

Should that be `BearSlice & FishSlice & SharedSlice`?

**Comment by dai-shi** [comment]
It should work in v5 and v4 too (v4 doesn't loop infinitely, but still causes extra rerenders without this fix.)
What's important is the selector result being stable.

**Comment by wuarmin** [comment]
> It should work in v5 and v4 too (v4 doesn't loop infinitely, but still causes extra rerenders without this fix.) What's important is the selector result being stable.

Oh, I understand. So following should work too:
```js
const useFilter = () => {
  const filters = useQueryStore(({ filters }) => filters);
  const filterItems = useQueryStore(({ filterItems }) => filterItems);

  return {
    ...filters.reduce((acc, { id, value }) => ({ ...acc, [id]: value }), {}),
    ...filterItems,
  };
};
```

**Comment by dbritto-dev** [comment]
@wuarmin yeah, that's the way to solve it. I'll add to `learn` section a new doc to talk about "How to make the selector result stable"

**Comment by cpatti97100** [comment]
Hi just installed zustand here for the first time and got version `5.0.0-rc.2`. can I still use the docs at https://zustand.docs.pmnd.rs? thanks!

**Comment by dbritto-dev** [comment]
@cpatti97100 sure, we added new docs for APIs and Hooks recently

**Comment by Flaain** [comment]
Hello, can someone help me resolve this error?

![image](https://github.com/user-attachments/assets/793444c9-cf92-4adf-8490-f8fd60f8ea55)

I have no idea where this error appears and why. Here just a couple examples how i use stores:

This is for local stores:

```ts 
export const ConversationContext = React.createContext<StoreApi<ConversationStore>>(null!);

export const useConversation = <U>(selector: (state: ConversationStore) => U) => {
    const store = React.useContext(ConversationContext);

    if (!store) throw new Error('useConversation must be used within a ConversationProvider');

    return useStoreWithEqualityFn(store, selector, shallow);
}
    
    export const ConversationProvider = ({ children }: { children: React.ReactNode }) => {
    const { id: recipientId } = useParams() as { id: string };
    const { socket } = useSocket();
    
    const { 0: store } = React.useState(() => createStore<ConversationStore>((set, get) => ({
        data: null!,
        error: null,
        actions: conversationActions(set, get),
        isPreviousMessagesLoading: false,
        isRecipientTyping: false,
        isRefetching: false,
        status: "loading",
    })))
    
    // another code
    
    return (
        <ConversationContext.Provider value={store}>
            {children}
        </ConversationContext.Provider>
    );
};
```

I think something wrong with useStoreWithEqualityFn cuz of error path but im not sure why
And this is for global stores:

```ts
export const useLayout = createWithEqualityFn<LayoutStore>(() => ({
    drafts: new Map(),
    isSheetOpen: false
}), shallow);
```

im using ```{"zustand": "^5.0.0-rc.2"}```

**Comment by dai-shi** [comment]
Thanks everyone for giving feedback!

https://github.com/pmndrs/zustand/releases/tag/v5.0.0
