### ISSUE TITLE
Question about memoize selector for many components

### ISSUE THREAD

**Issue by dohomi** [pmndrs/zustand#277]
Hello,

```ts
type AppStore = {
  settings: Partial<GlobalStoryblok>
  page: Partial<PageStoryblok>
  drawerVariant: DrawerProps['variant']
}

export const useAppStore = create<AppStore>(() => ({
  settings: {},
  page: {},
  drawerVariant: 'temporary'
}))

// memoize the selectors for component-reuse
export const settingsSelector = (state: AppStore) => state.settings
export const pageSelector = (state: AppStore) => state.page
export const pageSettingsSelector = (state: AppStore) => ({
  settings: state.settings,
  page: state.page
})

// sample component
function Component(){
  const settings = useAppStore(settingsSelector)
}
```

Is this the recommended way of using Zustand with TypeScript? I am migrating away from `react-hooks-global-state` and several React context approaches to keep the code more clean. The selectors are re-used over many files in the codebase. Thanks for feedback!

**Comment by dai-shi** [comment]
It looks good except that `pageSettingsSelector` creates a new object every time, so you would need to either specify `shallow`, or use the hook twice (I personally recommend the latter).

```js
// use shallow
function Component(){
  const pageSettings = useAppStore(pageSettingsSelector, shallow)
  // ...
}

// use the hook twice
function Component(){
  const page = useAppStore(pageSelector)
  const settings = useAppStore(settingsSelector)
  // ...
}
```

**Comment by dohomi** [comment]
@dai-shi I was currently using the `shallow` function as second argument. But actually you are right its not necessary and probably with just 3 values in the Store kind of an overhead. 
Thanks for this lib !

**Comment by dohomi** [comment]
@dai-shi as you are the maintainer of `react-hooks-global-state` aren't both libs trying to solve the same problem? I found the NextJS example which brought me to Zustand and I had the feeling it seems to be fairly similar.

**Comment by dai-shi** [comment]
@dohomi Correct and good point. As I started maintaining zustand, there's an overlap between the two. I will probably rewrite `react-hooks-global-state` based on zustand and provide the same api, when we reach the next major version (which will likely use `useMutableSource`).

**Comment by dohomi** [comment]
I see. What currently confuses me is the use of a provider in the official NextJS example: https://github.com/vercel/next.js/blob/canary/examples/with-zustand/pages/_app.js#L8 
Is that actually necessary or what is the main purpose of wrapping the state in a provider?

**Comment by dai-shi** [comment]
You might want to read a full story in #182.
In short, we need a React context in nextjs, otherwise state is kept across sessions.

**Comment by dohomi** [comment]
@dai-shi do I understand it right: the React context is necessary in NextJS for a potential user authentification in SSR? My use case is more to populate specific SSG props to all components in my React component tree (some settings which are fetched via getStaticProps and spread to all components via Zustand). For this a wrapping context might not be necessary as far I can see right now

**Comment by dai-shi** [comment]
I guess that's correct. It's not only for authentication, but if shared data is fine, it should be ok.

**Comment by dai-shi** [comment]
closing as resolved. see also #375.
