### ISSUE TITLE
Not available storage fails silently

### ISSUE THREAD

**Issue by loweisz** [pmndrs/zustand#283]
Hello there 👋 , 

First of all, I really really like zustand as a state management tool and I'm a big fan of it. 
I just noticed one small thing. When using the `persist` middleware to add the state to the `localStorage` or `sessionStorage` and the application doesn't allow to access it for example when used in an SSR application, the error or the fact that is not available is not notified to the user or the developer.

This means it fails silently and when you are not checking the storage yourself you might expect it being saved, but it's not. 

I think by adding some `warning` or information within the console here in the `middleware.ts` file like this could save some debugging time: 
```
try {
  storage = getStorage()
} catch (e) {
 console.warn("You try to persist your state, but the storage is currently not available in your application")
}
```

**Comment by AnatoleLucet** [comment]
Hey @loweisz, I didn't think about a use case where you'd need to know. But now that you've opened this issue, I guess you're fetching some data on the server and trying to store it (or at least a part of it) using persist?

A warning could be nice, though it probably would be annoying if you have a lot of `persist` stores. Maybe a warning if you try to set the store while the storage is not available could be better?

**Comment by loweisz** [comment]
Hi, @AnatoleLucet thanks for the fast reply. 
Exactly, I was using it to fetch data and add it to my store on the server, which I was persisting. Obviously, it should be clear to me that persisting something on the server-side is not possible. That's why I wouldn't consider this a bug or a must-have. I just thought it might be nice if the library gives you a hint that the persisting won't work in those cases. 

Adding it to the `setState` function would be totally fine as this is the place where it is failing 👍

**Comment by luchopcerra** [comment]
Hi! first of all, i want to say that i also think zustand is great! 
I found the same issue trying out _persist_ feature, but in mi case i just wanna persist user input data.  

I'm using nextjs so i wanna skip persist feature when doing SSR. Is there a clean way to do so ?
Thanks in advance

**Comment by AnatoleLucet** [comment]
@luchopcerra what do you mean by "skipping persist feature when doing SSR"? You don't want your data to be stored in your storage on the server? If so, you're probably using a storage available on the server. May I ask what it is or an example?

**Comment by luchopcerra** [comment]
Thanks for answer me @AnatoleLucet 
I'm already using zustand for certain user data entered by forms, and now i wanna spit this into multiple pages.
for doing so, i was trying out persist feature (to avoid having to develop write endpoints at the backend).
 but in any case, i don't want this set and get operations to be executed at SSR, rather i want to be browser only.

**Comment by AnatoleLucet** [comment]
I assume you're using the default [`sessionStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) which is not available on the server since it's a [web api](https://developer.mozilla.org/en-US/docs/Web/API).
As you can see [here](https://github.com/pmndrs/zustand/blob/master/src/middleware.ts#L188-L194) we don't use the storage if it's not available, so if you set some data in your zustand store on the server (while ssr a page), it'll not be stored in your storage since the storage is not available on the server (your zustand store will still work as expected though).
The point that @loweisz raised, is that we should probably alert the user / dev if the store is set while the storage is not available.

**Comment by AnatoleLucet** [comment]
Ah! What version of zustand are you using?

**Comment by luchopcerra** [comment]
> Ah! What version of zustand are you using? This is something that has been fixed since 3.3.0 (see #275)

Perfect! i was using 3.2.0 so i was behind [#275](https://github.com/pmndrs/zustand/pull/275)

**Comment by muhsarip** [comment]
> I assume you're using the default [`sessionStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) which is not available on the server since it's a [web api](https://developer.mozilla.org/en-US/docs/Web/API).
> As you can see [here](https://github.com/pmndrs/zustand/blob/master/src/middleware.ts#L188-L194) we don't use the storage if it's not available, so if you set some data in your zustand store on the server (while ssr a page), it'll not be stored in your storage since the storage is not available on the server (your zustand store will still work as expected though).
> The point that @loweisz raised, is that we should probably alert the user / dev if the store is set while the storage is not available.

im sorry, im quite new in js ssr, can you recommend the tutorial about js sessionStorage? thank you.

**Comment by AnatoleLucet** [comment]
> im sorry, im quite new in js ssr, can you recommend the tutorial about js sessionStorage? thank you.

The MDN doc: https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage
Just remember that this is a WebAPI, so it's not available in Node (if you're using something like Next, your ssr processes are in Node, so `sessingStorage` is unavailable when ssr-ing a page).

**Comment by dai-shi** [comment]
I think you want to open a [new discussion](https://github.com/pmndrs/zustand/discussions/new).
