### ISSUE TITLE
Unsubscribe from state changes

### ISSUE THREAD

**Issue by patrickap** [pmndrs/zustand#289]
Hi first of all you're doing a great job here!

I think it could be helpful to have a way to unsubscribe from state changes. What do you think?

All the best

**Comment by dai-shi** [comment]
Do you mean state changes but component doesn't re-render?
It's called "transient updates": https://github.com/pmndrs/zustand#transient-updates-for-often-occuring-state-changes

(Or, is it about `store.subscribe()`?

**Comment by patrickap** [comment]
Oh, I just read in the readme that it already works. Somehow I had no type information here. Can therefore be closed. Thank you!

**Comment by dai-shi** [comment]
good if that worked. closing.
