### ISSUE TITLE
The typescript guide is wrong

### ISSUE THREAD

**Issue by GuichiZhao** [pmndrs/zustand#2896]
I believe the section [Basic usage](https://zustand.docs.pmnd.rs/guides/typescript#basic-usage) from the typescript guide is completely wrong

The reason why "Why can't we simply infer the type from the initial state" is wrong per the typescript guide, it has **nothing to do with invariant**, the real reason is that we **do not provide any useful information** for TS engine does the pattern matching

If we provide proper information
```
declare const create: <T>(f: (get: () => T) => T) => T
const a = create(() => 'hello') //const a: string
```
We can see clearly that a is inferred as a `number` rather than `unknown` as the typescript guide said. 

> So, as long as the generic to be inferred is invariant (i.e. both covariant and contravariant), TypeScript will be unable to infer it.

 Let me speak aloud about how TS engine think

When the typescript engine sees `() => 'hello'` it tries to pattern match `(get: () => T) => T` and it figures out that if it binds `T` with `string`, it will match both.
Note that because the `()=>'hello'` provides no param, the TS engine will not bother to match the argument, it will just let it go
Remember that `()=>sting` is perfectly assignable to `(a:number)=>string` (but no the other way)

However, if we put an argument as a get param,
```
declare const create: <T>(f: (get: () => T) => T) => T
const a = create((_) => 'hello') // const a: unknown
```

TS engine can not bind T properly, but it is not because of a chicken and egg problem as the guide said

> TypeScript wonders. It's like that chicken or egg problem. At the end TypeScript, gives up and infers T as unknown.

Let us think aloud again, the TS engine tries to match
`(_) => 'hello'` and `(get: () => T) => T` it sees the parameter is not empty as in the previous example, so it **DOES** try to match it, so the problem becomes:
match `_` with `() => T`, there is no hint with `_` at all, so it is inferred as `unknown`

If we annotate it to hint the typescript, it works again
```
declare const create: <T>(f: (get: () => T) => T) => T
const a = create((_: (s: string) => string) => 'hello') //const a: unknown
```

Similar behavior can be observed in Promise
```
const x = new Promise((resolve) => {
  resolve(11)
}) //const x: Promise<unknown>
```
The Promise can not be bound properly because when TS tries to pattern match the arguments, it finds no hint at all, **AGAIN nothing to do with "invariant"**

If we provide the TS engine with some hint, it will work again
```
const x = new Promise((resolve: (s: number) => void) => {
  resolve(11)
}) //const x: Promise<number>
```

Reproduction Link
https://www.typescriptlang.org/play/?#code/CYUwxgNghgTiAEYD2A7AzgF0XKGQC54AeAFQD4AKAM0IoHMQNaBKeAXjPhNY6585IAoZOixR22ELhAUKAfVppCmGAEsUdfvBXrN7TgHIAFiAgQkB5oOsjM8AB4SUIAO7wACjCQBbVWhkUcGhIEABuBPAUSvAoAK7eAEYgMFqhSKrAWgDegvDwQSHhFACMxVYAvsxAA

If the idea is approved, I am happy to issue a PR to fix the documentation

**Comment by dai-shi** [comment]
Please keep discussing in #2895.
