### ISSUE TITLE
Marketing site performance

### ISSUE THREAD

**Issue by SpicyPete** [pmndrs/zustand#290]
The marketing site [seen here](zustand.surge.sh) performs terribly due to the background animation.  

This causes clicking the counter example to take 0.5-1s to update, which is not a good look for the library.

**Comment by dai-shi** [comment]
hm, it doesn't happen in my browser. what's your env?

**Comment by SpicyPete** [comment]
Brave - Version 1.19.88 Chromium: 88.0.4324.96 (Official Build) (64-bit)

**Comment by dai-shi** [comment]
thanks.

does anyone have a similar issue and/or an idea for the reason?

**Comment by eliseumds** [comment]
Yeah, performs terribly on Chrome 89 here too, top-of-the-line MBP 16". It's fine on FF and Safari.

**Comment by dai-shi** [comment]
Thanks for reporting.

Could anyone investigate it? it's in the repo: https://github.com/pmndrs/zustand/tree/master/examples

**Comment by Jarred-Sumner** [comment]
While it feels fine on my computer and appears to be running at 60fps, it seems that its dropping frames:
![image](https://user-images.githubusercontent.com/709451/110174760-74f99b80-7db5-11eb-964c-16a401e9a9d3.png)

I imagine the effect is more pronounced for computers with integrated graphics

**Comment by rdhox** [comment]
Work fine for me on firefox, safari and chrome.

**Comment by SpicyPete** [comment]
Seems to be working on Brave browser after the recent browser updates.  Closing issue.  Great site, looks great.
