### ISSUE TITLE
Devtools Bug

### ISSUE THREAD

**Issue by ragokan** [pmndrs/zustand#296]
Hello, when I try to import 'devtools' from 'zustand/middleware' as it is declared in docs, I receive errors.

![image](https://user-images.githubusercontent.com/63511519/107005691-26021b80-67a1-11eb-8626-6f64a67022cc.png)

![image](https://user-images.githubusercontent.com/63511519/107005720-2d292980-67a1-11eb-8133-df62e9d7ff1f.png)

My Packages:
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "zustand": "^3.3.1"

**Comment by dai-shi** [comment]
esbuild? does anyone have any experience/idea/hint?

**Comment by ragokan** [comment]
> esbuild? does anyone have any experience/idea/hint?

Well, I don't know if it has something in common but I do use Vite, let me try with 'create-react-app' and comment again.

**Comment by ragokan** [comment]
Last edit, the error was due to lack of the dependencies shown in bottom picture. When I added them, everything worked well.
![image](https://user-images.githubusercontent.com/63511519/107065794-3d1b2a80-67ee-11eb-8906-9e26fa82f6e7.png)

Thank you @dai-shi for that fast response, I am closing this issue.
