### ISSUE TITLE
Add more docs and examples for Persist middleware

### ISSUE THREAD

**Issue by rohitpotato** [pmndrs/zustand#300]
I think there should be examples to show how exactly to use the `persist middleware` configuration for a common use-case. For example, there is no way to know how to clear data from `localStorage` (or any persist mechanism), how to use the `onRehydrateStorage` for common use cases. 

I am not sure if it has been discussed here but store first returns the initial state before fetching the state from storage, how to handle those situations?

Let me know your thoughts!

@dai-shi  @AnatoleLucet

**Comment by AnatoleLucet** [comment]
We've already discussed with @dai-shi the writing of a wiki page which should act as `persist`'s documentation. But we haven't started working on it yet.

> I am not sure if it has been discussed here but store first returns the initial state before fetching the state from storage, how to handle those situations?

`onRehydrateStorage` was originally introduced for this purpose, see #258 for an example.

We can probably use this issue to get common use cases from users so we can add some to the future wiki.
#258 and #299 are a good starts. If anyone stumbles onto this issue, don't hesitate to share an unobvious use case that could be useful to others so we can add it to the doc.

**Comment by rohitpotato** [comment]
Thanks @AnatoleLucet for your reply. I still think #258 doesn't clearly illustrates how to use this in a regular react component. Just to clarify, to handle a use case like waiting for `zustand` to get changes from storage we'll need to import 2 things and add that to each store's configuration.

 I was wondering if something like `PersistGate` was possible with `zustand` or maybe another approach out of the box?

**Comment by AnatoleLucet** [comment]
> I was wondering if something like PersistGate was possible with zustand or maybe another approach out of the box?

There's currently nothing like `PersistGate`, but it could be a nice feature to add. Though you could probably do something similar with another zustand store which could act as the gate.

**Comment by rohitpotato** [comment]
> > I was wondering if something like PersistGate was possible with zustand or maybe another approach out of the box?
> 
> There's currently nothing like `PersistGate`, but it could be a nice feature to add. Though you could probably do something similar with another zustand store which could act as the gate.

I see, I think something like this can end up in the docs too. So people can implement their versions of Persist Gate.

**Comment by AnatoleLucet** [comment]
The full documentation of the middleware is now available at https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data.
Feel free to give any feedback

**Comment by stazrad** [comment]
@AnatoleLucet middleware docs are great! Are they for a specific version of zustand? I seem to be getting `undefined` when checking for `.persist` on the store object on zustand `3.6.0` 😖

**Comment by AnatoleLucet** [comment]
@stazrad yeah, the api (`useStore.persist.*`) has been introduced in 3.6.3. I added a note in the doc.
Thanks for the feedback.

**Comment by stazrad** [comment]
@AnatoleLucet fwiw [semantic versioning suggests](https://semver.org/) that `x.x.PATCH` versions are for bug fixes and new functionality should be introduced in a `x.MINOR.x` release 🤷

**Comment by dai-shi** [comment]
Closing this. We have a doc in docs folder. More examples would be nice. Anyone volunteers?
