### ISSUE TITLE
Zombie child, yet again

### ISSUE THREAD

**Issue by ratoi-crysty** [pmndrs/zustand#302]
There still seems to be the issue of zombie child. It requires some special criteria to reproduce:

1) The state needs to have initial value
2) The delete action, needs to be async called in regards to the event handler (Ex.: wrap the action call inside a setTimeout)
3) This is reproducible only on the elements that were present in the initial state.

Note, that the same scenario is not reproducible while using redux with hooks.

Repo to reproduce: https://github.com/ratoi-crysty/zustand-zombie-child

**Comment by dai-shi** [comment]
Thanks for the repro.
This seems the same as what we discussed in #286.
The quick fix is: https://codesandbox.io/s/fast-shadow-12726?file=/src/components/example/list.tsx:631-660

> Note, that the same scenario is not reproducible while using redux with hooks.

This, I'm not sure why though.

**Comment by ratoi-crysty** [comment]
Yup! It seemed related to that and as you pointed out in your codebox, using `unstable_batchedUpdates`, will do the trick.

But I still have one question though.

What would be the downsides of moving the subscription from the useEffect to directly in the hook call? (Ex.: [index.tsx](https://github.com/ratoi-crysty/zustand/blob/2f390721b7a3eda5f5edfaf852c7918b4e2f4d92/src/index.ts#L103))
This way, the listeners will be added in the same order as the component tree render order, therefore, avoiding having the child listener called before the parent. In this case, it should dramatically reduce, if not eliminate, the problem with the zombie child, as the parent will be rendered before the child.

**Comment by ratoi-crysty** [comment]
As for the scenario when using react-redux. It seems that they are already using it. In the subscription file [(Subscription.js)](https://github.com/reduxjs/react-redux/blob/a9235530f4799dd4b2acb3cc65e9caf32efbc44b/src/utils/Subscription.js#L21) they are using `batch` to wrap the all the listeners calls. By default, the the batch function is `unstable_batchedUpdates`. This is set in [index.js](https://github.com/reduxjs/react-redux/blob/a9235530f4799dd4b2acb3cc65e9caf32efbc44b/src/index.js#L14)

**Comment by dai-shi** [comment]
> What would be the downsides of moving the subscription from the useEffect to directly in the hook call?

That would be a side effect in render, which is never recommended in react.
In legacy mode, it would work, but in concurrent mode, it will be really problematic.
It may subscribe to the store and never unsubscribe from it, in some scenarios.

**Comment by ratoi-crysty** [comment]
Thanks for your answer. It makes sense.

As for the scenario when using react-redux. It seems that they are already using it. In the subscription file [(Subscription.js)](https://github.com/reduxjs/react-redux/blob/a9235530f4799dd4b2acb3cc65e9caf32efbc44b/src/utils/Subscription.js#L21) they are using `batch` to wrap the all the listeners calls. By default, the the batch function is `unstable_batchedUpdates`. This is set in [index.js](https://github.com/reduxjs/react-redux/blob/a9235530f4799dd4b2acb3cc65e9caf32efbc44b/src/index.js#L14)

Maybe we should add the functionality to allow passing a batching method when creating a store, this way, it should prevent the zombie-child issue and also improve performance as it will call all listeners of that store inside one batch (if that is done outside the react event, like setTimeout). And having it optional, it will not add any breaking changes. 

What's your opinion on this?

**Comment by dai-shi** [comment]
> As for the scenario when using react-redux. It seems that they are already using it. In the subscription file [(Subscription.js)](https://github.com/reduxjs/react-redux/blob/a9235530f4799dd4b2acb3cc65e9caf32efbc44b/src/utils/Subscription.js#L21) they are using `batch` to wrap the all the listeners calls. By default, the the batch function is `unstable_batchedUpdates`. This is set in [index.js](https://github.com/reduxjs/react-redux/blob/a9235530f4799dd4b2acb3cc65e9caf32efbc44b/src/index.js#L14)

Ah, nice finding. I thought I saw this before, but I was searching `batchedUpdates` today and nothing found. 😓

**Comment by dai-shi** [comment]
We could try using batchedUpdates, but it'd be not easy to make bundles for react-dom and react-native. I wonder if v4 #160 will solve this issue eventually...

Oh, `setBatch` is totally opt-in. I missed it. That might work. Would you like to work on it?

But, then, the DX is not very good, isn't it? The workaround in #286 seems easier to me.

**Comment by ratoi-crysty** [comment]
After giving further thoughts, I think that having a `setBatch` will probably not add allot of value. Because, if you manually wrap your action (in my example, `deleteItem`) inside the batching method, that will automatically wrap all the listeners calls inside id, as zustand will do this synchronously. And therefore, have the same value as a `setBatch` method. Another way to id, is to manually wrap the `set` method in the store creator and only use the wrapped method to update the state, this will also have the same effect as `setBatch`.

What do you think? Do you see any value in implementing a `setBatch`? Probably something that I have missed? 
If not, then you could close the issue, as it works as expected.

**Comment by dai-shi** [comment]
Yeah, that's what I meant by "DX is not very good". I don't think it's worth the effort, at this point. But let us keep this in mind.

For now, it would be best for us to add a small section about the workaround in readme.md. Would you or anyone like to work on it? cc @martonlanga @Tirzono .

(I will close this issue a bit later.)

**Comment by ratoi-crysty** [comment]
@dai-shi let me know if this is ok

**Comment by drcmda** [comment]
one question @dai-shi didn't @JeremyRH find a way to do this without batchedupdates? i remember he told me we can now remove it. the trouble is mostly that we're using two reconcilers: react-dom and r3f. 

our middleware currently looks like this:

```jsx
import { Renderer } from 'react-three-fiber'
import { unstable_batchedUpdates } from 'react-dom'

const batched = (config: StateCreator<BuerliState>) => (
  set: SetState<BuerliState>,
  get: GetState<BuerliState>,
  api: any,
) => config(args => unstable_batchedUpdates(() => Renderer.batchedUpdates(() => set(args))), get, api)
```

if there is any way to avoid this we would be very happy ...

**Comment by JeremyRH** [comment]
To fix this in non-concurrent mode without batchedupdates, you need to ensure a parent's `setState` is called before its children's `setState`. There are many ways to do that. I did it by keeping track of render order (mutating an array during render) and it didn't work in concurrent mode.
Someone should be able to figure out a solution but it might involve doing different things in concurrent mode.

**Comment by dai-shi** [comment]
> if there is any way to avoid this we would be very happy ...

well, this looks to me the easiest and the cleanest.

I'm interested if #160 fixes this issue from the ground. Otherwise, the current solution would be good in total.

> I did it by keeping track of render order (mutating an array during render)

My assumption is this doesn't work very well performance-wise even in legacy mode.

**Comment by drcmda** [comment]
just switching to blocking would also take of it right? that would be a good solution if it did.

**Comment by dai-shi** [comment]
AFAIU, you would need `batchedUpdates` in non-react callbacks, if you needed to ensure top-down updates, even in legacy mode.
I expect the future version of react may fix this and that's why it's `unstable_`.

**Comment by drcmda** [comment]
it says here that both blocking and cm autobatch https://reactjs.org/docs/concurrent-mode-adoption.html#feature-comparison

**Comment by dai-shi** [comment]
Oh, you mean Blocking Mode which is the one between CM and LM. I missed that part of your comment.

> In Blocking Mode and Concurrent Mode, all setStates are batched by default.

This, I'm not sure. Hopefully, they batch multiple setStates called in async but in a short period?

**Comment by JeremyRH** [comment]
> btw react automatically batches in blocking and concurrent mode, has anyone tested if the problem persists?
Last I tested, using `ReactDom.unstable_batchedUpdates` prevented the zombie child issue. This should mean the problem wont persist in blocking or concurrent mode.

**Comment by dai-shi** [comment]
I feel like this is not a real issue from the library perspective. React may behave differently in the future as we discussed.
The case we need `unstable_batchedUpdates` is rare as I understand, and adding it to `setState` by default doesn't sound correct to me, but not very sure. AFAIR, react-redux had it by default, but it's now opt-in.

A new middleware to modify set might be an option if there's a certain demand.

btw, react doesn't seem to have Blocking Mode any longer.

**Comment by meglio** [comment]
Could someone help me understand the following. In the readme, there is this example:

<img width="544" alt="image" src="https://user-images.githubusercontent.com/282177/124879611-8e814d00-e00c-11eb-9c03-4586f821cbc4.png">

What I can't understand is why `unstable_batchedUpdates()` is used in location A and not in location B?

Consider the following example:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/282177/124879802-c4263600-e00c-11eb-8030-86a68cc83bce.png">

Here, the callback is a function that the api wrapper will call when an ajax request is complete. Yet it is declared in location B, not somewhere outside.

In my particular example, what part exactly should I wrap with `unstable_batchedUpdates()`? -- many thanks

**Comment by dai-shi** [comment]
The readme doesn't recommend having `unstable_batchedUpdates()` in "B", because `increaseFishes` can be called from react callbacks. You should use it where you are sure that it's non-react callback.

In your case, if `onSuccess` is non-react callback and if you are facing the zombine problem, you can surely put it there.

**Comment by meglio** [comment]
Thanks. How do I distinguish a non-react callback from a react-callback? Not sure I have a clear understanding of this term's meaning.

**Comment by meglio** [comment]
Almost clear! The last bit that's confusing is this: 
Would a Promise's `than()` callback be still classified a non-react callback even if the Promise is created inside the `onClick()` react callback?

**Comment by dai-shi** [comment]
> Would a Promise's then() callback be still classified a non-react callback even if the Promise is created inside the onClick() react callback?

yes.

**Comment by fongfai** [comment]
> Yup! It seemed related to that and as you pointed out in your codebox, using `unstable_batchedUpdates`, will do the trick.
> 
> But I still have one question though.
> 
> What would be the downsides of moving the subscription from the useEffect to directly in the hook call? (Ex.: [index.tsx](https://github.com/ratoi-crysty/zustand/blob/2f390721b7a3eda5f5edfaf852c7918b4e2f4d92/src/index.ts#L103)) This way, the listeners will be added in the same order as the component tree render order, therefore, avoiding having the child listener called before the parent. In this case, it should dramatically reduce, if not eliminate, the problem with the zombie child, as the parent will be rendered before the child.

your link address "index.tsx" has been 404,

**Comment by voidtask** [comment]
Hey everyone! Been reading [docs that link to this issue](https://zustand.docs.pmnd.rs/guides/event-handler-in-pre-react-18), is it still required to wrap actions outside of React with `unstable_batchedUpdates` if we're talking about React 19.2?

**Comment by dai-shi** [comment]
You don't need it with React 18 and above.
It's for pre React 18.
We can probably drop that doc entirely.

**Comment by voidtask** [comment]
> You don't need it with React 18 and above. It's for pre React 18. We can probably drop that doc entirely.

I see, thanks! Dropping the doc entirely is probably not the best, some of us might still be running legacy versions, just maybe add the clarification that it's not needed anymore :)
