### ISSUE TITLE
Separating / merging state using immer middleware + TS

### ISSUE THREAD

**Issue by ivancuric** [pmndrs/zustand#304]
I'd ideally want to use zustand with immer and TS and to be able to extract the actions from the values.
How would one combine these two patterns?
https://github.com/pmndrs/zustand/issues/211#issuecomment-710782706:
```ts
import create from 'zustand'

const createActions = (set) => ({
  setTitle: (title) => set({ title }),
  toggle: () => set(prev => ({ done: !prev.done })),
})

const useStore = create((set) => ({
  title: 'foo',
  done: false,
  ...createActions(set),
}))
```
https://github.com/pmndrs/zustand/pull/169#issuecomment-687770407:
```ts
const immer = <T extends State>(
  config: StateCreator<T, (fn: (state: T) => void) => void>
): StateCreator<T> => (set, get, api) =>
  config((fn) => set(produce(fn) as (state: T) => T), get, api);

const useStore = create<{
  bees: boolean;
  setBees: (b: boolean) => void;
}>(
  immer((set) => ({
    bees: false,
    setBees: (input) =>
      set((state) => {
        state.bees = input;
      })
  }))
);
```

**Comment by dai-shi** [comment]
What's your _minimal_ final goal look like? You want to infer all types, or type annotation is okay?

**Comment by ivancuric** [comment]
Ideally the more inferring the better. I was thinking of something along these lines:
```ts
interface IStore extends State {
  bees: boolean;
  setBees: (b: boolean) => void;
}

const createActions = (set) => ({
  setBees: (input) =>
    set((state) => {
      state.bees = input;
    })
});

const useStore = create<IStore>(
  immer((set) => ({
    bees: false,
    ...createActions(set)
  }))
);
```

Perhaps even extracting `{bees: false}`. It just feels messy managing a huge store in a single object 3 nesting levels deep.

**Comment by dai-shi** [comment]
> const createActions = (set) => ({

This part can never be type inferred.

> It just feels messy managing a huge store in a single object 3 nesting levels deep.

Yeah, we have some related discussions in various issues. Reopened #178.

**Comment by ivancuric** [comment]
A follow-up:

https://codesandbox.io/s/zustand-array-tdtph?file=/src/App.tsx

Casting in the producer works, but I kinda feel I'm breaking stuff here:
```ts
 ...createActions(set as SetState<Store>)
```
The immer middleware is typed as:
```ts
(fn: (draft: WritableDraft<Store>) => void) => void;
```

**Comment by dai-shi** [comment]
Closing this. For namespacing, track the issue in #178.
