### ISSUE TITLE
weak type safety in setState due to usage of Partial

### ISSUE THREAD

**Issue by TkDodo** [pmndrs/zustand#317]
reproduction: https://codesandbox.io/s/romantic-moon-xxkzd?file=/src/App.tsx

in this example, our `dec` function sets `count` to `undefined`, even though this is not allowed (it has to be a number). If we try to set it to a string, this will correctly type-error.

`setState` takes a `Partial<State>`, as defined here: https://github.com/pmndrs/zustand/blob/58c286e6cb9d6fc6dfe0142113b12aada0894ec8/src/vanilla.ts#L17-L20

but `Partial` not only lets you omit keys, it also adds lets you explicitly set every key to `undefined`, which is quite dangerous since those partial objects are then usually spread over the existing state, thus setting the value to `undefined` at runtime.

[Here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAysCGxoF4oG8oGMD2BXAdkgE4BcU+uAtgEYREC+AUIzvgM7BQeIRkAK8IsACW8ADYAeODwB8UVBhwFiZAgBMIAM2H4IaqPSA) is a minimal typescript playground repro, so TS is fine with these two lines:

```
type State = { counter: number}
const state: Partial<State> = { counter: undefined }
```

`this.setState` in class-based React components does not have this problem, because they are not using `Partial`, but rather picking the keys manually:

```
setState<K extends keyof S>(
            state: ((prevState: Readonly<S>, props: Readonly<P>) => (Pick<S, K> | S | null)) | (Pick<S, K> | S | null),
```

not sure if we could tweak the types here to do something similar?

**Comment by dai-shi** [comment]
Good point. not sure either.
Anyone interested trying out? A little concern is that we don't have many typing tests, so not sure if it will be a breaking change or not. (But, basically proper types are just good.)

**Comment by TkDodo** [comment]
do you consider changes to the typings to be breaking? I think it would mean better type-safety, and if people get new errors in their code because of it, they were likely doing it wrong before :)

I can maybe take a stab at this on the weekend. do you have a preference on how to test types?

**Comment by dai-shi** [comment]
> do you consider changes to the typings to be breaking?

No, but I'd like to write something in the release note if the change is significant.

> I can maybe take a stab at this on the weekend.

Great!

> do you have a preference on how to test types?

Not much. What I meant was if the current tests are in TS (without `any`), we could have noticed how big the impact would be.
If you have suggestions, they are welcome.

**Comment by TkDodo** [comment]
closed with https://github.com/pmndrs/zustand/pull/320
