### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by TrueWill** [pmndrs/zustand#323]
I see you're [targeting esnext](https://github.com/pmndrs/zustand/blob/master/tsconfig.json#L3); have you documented supported browsers anywhere and/or given thought to targeting es5 instead for IE11 support? Thanks!

**Comment by dai-shi** [comment]
Hi,

https://github.com/pmndrs/zustand/blob/78192e41d48984f3345cdce5074759510f056da3/rollup.config.js#L60-L61

If I understand it correctly, it transpiles with babel after typescript, targeting IE11. Did you see any issues with IE11?

**Comment by TrueWill** [comment]
@dai-shi My apologies; I missed that. I haven't tested it yet; my company was evaluating different options. Thank you!
