### ISSUE TITLE
mutate store state without triggering a re-render

### ISSUE THREAD

**Issue by yehonadav** [pmndrs/zustand#329]
so i have a table
and im saving the table data in a persistent store.

and i found myself in a use-case where i need to update just 1 row, 

i don't want to trigger a re-render for the whole table, 
yet i need to update the table data in case the user navigate outside and back to the table, 
or simply refresh the page.

is there a way to set the state without triggering a re-render ? if not, a feature like that would be nice

**Comment by dai-shi** [comment]
I suppose what you are looking for is what we call [transient updates](https://github.com/pmndrs/zustand#transient-updates-for-often-occuring-state-changes).

**Comment by yehonadav** [comment]
i think i didn't specify all of my scenarios correctly,
there are also legitimate use cases where i do want to re-render the entire table,

let's say a row is added/removed, a transient update wouldn't work ?

**Comment by dai-shi** [comment]
So, you basically want to introduce inconsistencies between the state and what users see. Again, transient updates is a way to accomplish it and you could trigger re-render with other methods.
We could actually store a ref object and mutate it, but it's not really designed for it.

This is the first time to think about your use case. What I would recommend off the top of my head is to separate the data to show users and pending data (maybe patches).
To illustrate something simple, let's copy the data (not patches).

```js
const useStore = create((set, get) => ({
  items: [],
  pendingItems: [],
  setItem: (item, index) => {
    get().commitPendingItems()
    const prev = get().items
    const next = [...prev.slice(0, index), item, ...prev.slice(index + 1)] 
    set({ items: next, pendingItems: next })
  }),
  setPendingItem:  (item, index) => set((prev) => ({ pendingItems: [...prev.pendingItems.slice(0, index), item, ...prev.pendingItems.slice(index + 1)] })),
  commitPendingItems: () => set((prev) => ({ items: prev.pendingItems })),
}))

**Comment by dai-shi** [comment]
Closing as stale.
