### ISSUE TITLE
Single dispatch for multiple stores with redux-middleware

### ISSUE THREAD

**Issue by simon-milleto** [pmndrs/zustand#330]
I have an app that currently use a Flux architecture with a single dispatcher and multiple stores that reacts to an action. I want to rewrite it with zustand but I'm not sure how to re-create this pattern.
So basically I want multiple stores with reducer that react to an action, and one action is dispatched to every reducer in stores.

I created a simple exemple of my attempt [here](https://codesandbox.io/s/gifted-jennings-h3np6?file=/src/index.js)

The main thing here is
```
const dispatch = (...args) => {
  apiA.dispatch(...args);
  apiB.dispatch(...args);
}
```
I have a single dispatch function that will dispatch to every stores. This works great but is there a better way to handle it with zustand ? Or is zustand not made for this kind of architecture ?

Maybe my answer is the `combine` function, but I'm not sure how to implement it.

**Comment by dai-shi** [comment]
My understanding of flux architecture is limited, but dispatching actions to multiple stores seems to work. I think it's probably a good pattern if you don't see any issues so far.

There's no special features in zustand provided to coordinate multiple stores. Multiple stores just work as totally isolated. We have some discussions about namespacing a single store: #178

**Comment by simon-milleto** [comment]
Thanks for your answer, I don't see issues and it works great.
There is one feature from the flux architecture that I'm not able to reproduce for now, it's the `waitFor` utility function. Basically it allows a store to wait for change from another store, in my current flux architecture it look like that
```js
/* StoreA */
...
case types.increase:
    return { count: state.count + 1 };
...
/* StoreB */
...
case types.increase:
    waitFor([storeA]);
    // Here I'm sure that the storeA is updated and I can work with its state
    return { count: storeA.getState().count + 1 };
...
```

Do you think this kind of pattern can be reproduced with zustand ?

**Comment by dai-shi** [comment]
We could make one store to subscribe another, but generally it's not very straightforward to coordinate multiple stores.

```js
const dispatch = (...args) => {
  apiA.dispatch(...args);
  apiB.dispatch(...args);
}
```
Because setState is synchronous, if you change the order of dispatches, you can technically control the timing.

For example:
```js
const dispatch = (action) => {
  if (action.type === 'increase') {
    apiA.dispatch(action)
    apiB.dispatch(action)
  } else {
    apiB.dispatch(action)
    apiA.dispatch(action)
  }
}
```

**Comment by simon-milleto** [comment]
I tried this solution and it works as expected, for a simple case like this one it's fine but I'm not sure that for a real world app it would be a great solution. There is no way to know, with the redux middleware, if a store has finished dispatching ?

**Comment by simon-milleto** [comment]
Is there a way to make the reducer to work asynchronously ? In my case I found a solution where I can do something like this:
```jsx
/* CounterB Class*/
async reducer(state, { type }) {
    const storeA = this.getStoreA();

    switch (type) {
    case types.increase:
      await storeA.onFinishDispatching();
      // Here I'm sure that the storeA is updated and I can work with its state
      return { count: storeA.getState().count + 1 };
    }
}
```
But unfortunately it doesn't work since the reducer is async

**Comment by dai-shi** [comment]
So, it's like locking store updates. A naive way would be like this?
```js
const useStore = create((set, get) => ({
  promise: null,
  data: {},
  setData: async (data) => {
    await get().promise
    set({ data })
  }
}))

const updateState = (fn) => {
  useStore.setState({
    promise: new Promise((resolve) => {
      fn()
      useStore.setState({ promise: null })
      resolve()
    })
  })
}
```

Not very confident if this works without pitfalls, though, depending on usage.

**Comment by simon-milleto** [comment]
So, I found a way to achieve what I wanted, I've kept my reducer synchronous as described in the doc. And for the action where I need to run asynchronous, I do not use the returned value from reducer but I use the `setState()` function.
I'm closing this issue, thanks for the help @dai-shi
