### ISSUE TITLE
Importing in a `type=module` project fails

### ISSUE THREAD

**Issue by wolframkriesing** [pmndrs/zustand#334]
First: thanks for the simplified version of state management. So glad I found it, so sad it took me so long ;).

I created a small project, where the `package.json` sets it to be a ESM project, by `type=module`.
See https://codeberg.org/wolframkriesing/bug-exploration-zustand-and-esm/src/branch/main/package.json#L4

I ran into two issues, that are somehow related to #201 but I am not sure exactly what's the root cause.

## The Problem(s)
I wanted to get zustand to be testable with mocha in an ESM setup. But I ran into:
1) When using `type=module` and importing `zustand/vanilla` mocha says
   there is no such file. No idea what that might be.
   This is the JS file and the error it throws:
   https://codeberg.org/wolframkriesing/bug-exploration-zustand-and-esm/src/branch/main/src/vanilla.test.js
2) When importing `zustand/vanilla.js` the default export is somehow broken. A change of 
   `exports.default = create;`  
   to   
   `module.exports = create;`  
   in `zustand/vanilla.js` would fix it.
   This sounds like a packager problem in zustand?
   https://codeberg.org/wolframkriesing/bug-exploration-zustand-and-esm/src/branch/main/src/vanilla-js.test.js
   
Is the ESM setup just not there yet, and not recommended? I had hoped to go there gradually.
How do others solve this issue?

**Comment by wolframkriesing** [comment]
One idea I just had to possibly solve it, is to create a pure esm build of zustand, maybe so it can be imported via `import created from "zustand/esm"`. Which would "just" need a stripping away the TS from the original sources, I guess.
Will give it a try and hope to provide a PR.

**Comment by dai-shi** [comment]
As you have already noticed, the issue is `zustand/vanilla` is CJS.
Would you just import `zustand` and see if it works? Or, have you already tried?

**Comment by wolframkriesing** [comment]
Importing `zustand` works, since it is ESM, right. I understood that this is the react-style `create`, right? I want to import the `zustand/vanilla` to be able to write tests that dont need react.
Currently I am doing it like so: 
```
import zustand from 'zustand/vanilla.js';
const create = typeof zustand === 'function' ? zustand : zustand.default;
```

this works, but I guess its not meant this way.
`typeof zustand === 'function'` is `true` when the code was transpiled.

`zustand.default` is needed when running it in a `type=module` package using just nodejs without any transpilation.

**Comment by dai-shi** [comment]
> I understood that this is the react-style `create`, right?

Yes, but it's just adding something on top of vanilla, so only the reason someone want to use `zustand/vanilla` instead of `zustand` is to remove react dependency (and react related code).

**Comment by worstpractice** [comment]
@wolframkriesing For what it's worth, I don't think it's a Zustand issue. I have multiple typescript projects where everything is running as modules and Zustand works as expected.

No doubt, getting modules to work can take some work in the current ecosystem (still totally work it tbh, [modules are awesome](https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/)), but that mostly has to do with the bundler config/node version/typescript config, I find.

In my own personal experience, Zustand has had nothing to do with any configuration woes, and has caused me no issues in my module projects.

All that just to say, it can be done.

**Comment by dai-shi** [comment]
As far as I can tell, webpack esm and nodejs mjs is not 100% equal.

@wolframkriesing We releaseed v3.4.1 lately and it ended up with something like what you suggested in #336 originally. Would you see how it works or not in your use case?

**Comment by rschristian** [comment]
@worstpractice It was a Zustand issue, at least before v3.4.1. While the main `zustand` export had ESM, if you needed to use `zustand/x` then you were out of luck. It didn't offer module exports for the subpackages. 

> In my own personal experience, Zustand has had nothing to do with any configuration woes

It was an issue/shortcoming with Zustand itself due to the lack of expected exports. Sure, users could set up babel to transpile everything down to CJS or a tool to transpile up to ESM, but that shouldn't really be expected. "It can be done", sure, but with that logic library authors could just bundle ES3 and leave it up to users to figure out usage. Ideally we'd look for a more optimal solution.

@dai-shi Not OP here, but may I ask why `module` is being used in `exports`? [That's not a condition Node implements](https://nodejs.org/api/packages.html#packages_conditional_exports). Node will end up using the `default` key there which is CJS.

It'll need to be `import`, and furthermore, it'll need to be `.mjs`, else Node will use the CJS loader.

**Comment by dai-shi** [comment]
> may I ask why module is being used in exports?

https://webpack.js.org/guides/package-exports/#conditions
It's used by webpack v5.

> It'll need to be import, and furthermore, it'll need to be .mjs

That was my original trial in [jotai](https://github.com/pmndrs/jotai) and it was troublesome.
We can try again in zustand, because there's no dependencies.
Do you know with what condition we can claim mjs?

**Comment by rschristian** [comment]
Fair enough, though the obvious follow up would be why only support Webpack v5? Quite limited ecosystem for that.

What some libs do is offer `browser` -> esm, `.js` and `import` -> esm, `.mjs`. Should work in most (all?) popular bundlers.

**Comment by wolframkriesing** [comment]
@dai-shi I updated to use zustand 3.4.1 in my testing project, see https://codeberg.org/wolframkriesing/bug-exploration-zustand-and-esm

In this test (project) I have:
* a pure ESM setup, see package.json `type=module`
* zustand is the only dependency, just to prevent side-effects
* and still the `import create from 'zustand/vanilla'` does NOT import the expected function

What has changed, from my point of view, compare to pre-3.4.1 version, is that I dont need to import `import create from 'zustand/vanilla.js'` anymore.  
What am I doing wrong that it works for "everyone" else?

**Comment by rschristian** [comment]
> What am I doing wrong that it works for "everyone" else?
> 
> It is very strange, that the `zustand/esm/vanilla.js` does not get used, even though my project is pure ESM.

As mentioned in the above comments, the current setup only supports webpack v5. The key used in `exports` (`module`) is not implemented by anything else.

**Comment by dai-shi** [comment]
@rschristian 
I forgot to mention that specifying `import` incurs dual package hazard.
https://nodejs.org/api/packages.html#packages_dual_package_hazard

This is a real issue with [valtio](https://github.com/pmndrs/valtio). For zustand, it might not be important because right now we don't have such exports. (but we plan to add a new feature which impacts on it.)
We also want to keep the configs consistent as much as possible among zustand/jotai/valtio for maintainability.

**Comment by wolframkriesing** [comment]
> current setup only supports Webpack v5

didnt get that yet, thanks @rschristian

**Comment by dai-shi** [comment]
@wolframkriesing 
Yeah, like @rschristian mentioned, the current v3.4.1 config only uses cjs even if you have `type=module`. This is regretful, but intentional for some reasons mentioned above.

We would like to have better ideas in the future.

My question for now is if the original issue with `type-module` is solved (as workaround) with v3.4.1 with CJS, that was not solved in v3.3.3.

**Comment by wolframkriesing** [comment]
As documented in the project I linked, I don't see the type=module issue solved, but there seems to be a common understanding how zustand works in that regards, maybe its good enough to document that.

**Comment by rschristian** [comment]
The "workaround" requires using the `default` key on the exported object, i.e., `import create from 'zustand/vanilla';` returns `create: { default: <create function> }`, so `create.default()` is needed.

**Comment by dai-shi** [comment]
Ah, I see. I was hoping `import create from 'zustand/esm/vanilla.js';` to work, which doesn't in node14 because it understands `"exports"`.

Let's keep this issue open and wait for suggestions / ideas.
Some criteria:
- we want to have easily-maintainable configs across zustand/jotai/valtio.
- we want to avoid dual package hazard strictly.
- we still want to provide a build for old browsers by default. (this may change sooner or later)

**Comment by dai-shi** [comment]
```js
// The last test fails, due to `zustand/vanilla.js` exporting `create`
// like this `exports.default = create;`
// if it was `module.exports = create;` it would work :(
```

I wonder if there's a babel config to fix this (= specify both).

**Comment by dai-shi** [comment]
> so it'd be easier to figure this out going forward on a v4

that's true, but i still don't see how to solve dual package hazard. we can't drop cjs even in v4...

**Comment by rschristian** [comment]
Supporting older browsers probably isn't too likely of an issue. ES2017 sees something like 95% global market share, so ESM itself is a couple points higher. Bigger issue would be Node.

Did you actually see issues arising with the dual package hazard? It's a potential issue, sure, but loading both formats simultaneously is more likely to be an issue with the user than it is an issue for the authors here.

Most common causee would be deps loading whatever version the user isn't directly using, though do any other packages depend on zustand/valtio/jotai? I have very little history with any of these, so I have no idea if that ecosystem is there or not at the moment.

You don't need to drop CJS, just need to make sure their build tools aren't pulling in that CJS while they're using the ESM (or the reverse); most built tools are quite good at this. Node could be a tad awkward of course, but you can try to isolate state to alleviate that potential issue, as suggested [here](https://nodejs.org/api/packages.html#packages_approach_2_isolate_state)

Another way around this can be to use both extensions, i.e., `.cjs` and `.mjs`. I believe [twind](https://github.com/tw-in-js/twind) makes use of this. Obviously that will be breaking if anyone uses the full file path.

I'll take a look this evening, see if I can try to get at least a demo together that'll pass the major bundlers/node @ latest. Then I guess we can go from there to look at what needs support beyond that, if it's not covered. Great part about the arbitrary keys of `exports` means you can pretty much always maul something into working if need be.

**Comment by dai-shi** [comment]
> do any other packages depend on zustand/valtio/jotai?

Yeah, there are some 3rd party zustand packages and a few jotai packages (the library use is a big selling point in jotai.)

> Another way around this can be to use both extensions, i.e., .cjs and .mjs. 

I originally thought that too and tried, but it breaks old bundlers which don't understand `exports` or something like that. We should keep .js and do things in `exports`.

**Comment by rschristian** [comment]
Twind ends up forming their `exports` at build time, so it's hard to reference, but they output the following:

```
".": {
      "module": "./twind.js",
      "script": "./twind.umd.js",
      "types": "./twind.d.ts",
      "require": "./twind.cjs",
      "node": "./twind.mjs",
      "default": "./twind.js"
    },
    "./colors": {
      "module": "./colors/colors.js",
      "script": "./colors/colors.umd.js",
      "types": "./colors/colors.d.ts",
      "require": "./colors/colors.cjs",
      "node": "./colors/colors.mjs",
      "default": "./colors/colors.js"
    },
    ...
```

You can offer the full set of extensions with the right ordering of keys.

**Comment by dai-shi** [comment]
Ah, "node" for .mjs is a good idea! Hm, can it simply point to esm/index.js in our case?

**Comment by rschristian** [comment]
At `esm/index.js`, no, but if you made a copy as `esm/index.mjs`, then yes, that'd work for Node. Of course, the `require` key would be needed.

**Comment by dai-shi** [comment]
#357 adds "node" only. So, without "require" node with require() breaks. Hmmm.

Why doesn't it work with pointing at `esm/index.js`?

**Comment by dai-shi** [comment]
So, what we want is "node-import" condition...

**Comment by rschristian** [comment]
Yeah, sorry, didn't get my ninja-edit in quick enough. 

So the "node-import" will be `node`. `require` before it, as in the example, should handle all `node-require` usage.

**Comment by dai-shi** [comment]
By "node-import", I mean we don't have the preceding "require".

Then the question is whether the combination of "require" and "module" does or dose not suffer from dual package hazard in webpack and other bundlers.

**Comment by rschristian** [comment]
I don't know of a pattern that would allow you to get rid of the preceding require. Node's the limiting factor there in the keys it has implemented.

As for the dual hazard, I suppose the only way to tell is to test. I'll try a few things out, see if I can get something to break.

**Comment by wolframkriesing** [comment]
Sounds like a tricky one, not fun.
What about a (challenging) suggestion: Why not ship ESM only? One file, only import/export, pure ESM.
Why?
1) this is where JS is going
2) let the user transpiler if they need it (anyways)
3) much simpler to maintain

Sounds more like a major version thing, and it might prevent more compat work?

**Comment by duarten** [comment]
This is still an issue for me with `3.5.10` when using jest configured for esm modules (`--experimental-vm-modules` is set). As a workaround, I'm doing:

```ts
import workaround, { State, StateCreator, StoreApi, UseStore } from "zustand"

type CreateFunc = <TState extends State>(createState: StateCreator<TState> | StoreApi<TState>) => UseStore<TState>
const create = ((workaround as unknown) as { default: CreateFunc }).default
```

**Comment by dai-shi** [comment]
@duarten Thanks for the feedback. Would you create a new issue please? (I'm not sure if the issue with jest is the same as what we discussed here or not, but anyway it should be filed as a new one to get more attention.)

**Comment by duarten** [comment]
@dai-shi I opened #559 :)
