### ISSUE TITLE
Is possible call useContext into useStore ?

### ISSUE THREAD

**Issue by caltamiranob** [pmndrs/zustand#335]
Hi everybody, i hope you can help me with the following question:

Recently I am using zustand in a project that handles states with "Context", my stores with zustand I'm saving it in separated file, for example  I have a file "useDocuments.js" that contains:
`
const useDocuments = create((set, get) => ({
    loading: false,
    documents: [],
    filters: {}
}));
export default useDocuments;
`
Now, I want initialize the 'filters' field with values like (userId, companyId) , but this values are stored in a "context", how could call useContext for fetch this values.

Thank you for your support.

**Comment by dai-shi** [comment]
Zustand store resides outside React. Whenever you need React world to interact with outside world, `useEffect`.

Something like this:

```js
import { useDocument } from './store'

const Component = () => {
  const { userId } = useContext(Foo) // or props or state
  const documents = useDocuments()
  useEffect(() => {
    useDocuments.setState({ userId })
    // or if you need to do something
    useDocuments.getState().setUserId(userId)
  }, [userId])
  // ...
}
```

**Comment by caltamiranob** [comment]
Thanks @dai-shi, i get it.
Now, I have another doubt about lifecycle of stores, I'm creating different stores for funcionality, for example i have one store to handle users (useUserStore.js) and another store to handle documents (useDocuments.js), i have two forms (user and documents), i put an "useEffect" in every form for show one field from store, I've noticed that:
1. When I enter to "user" form, have the field "companyId" undefined and I set the "companyId" in the userStore.
2. Next, I enter to "documents" form.
3. Next, return to "user" form and **i've noticed that my store has the "companyId" field fill realized in the step 1.**, it means the when the store is created never is destroyed.

I would like to know the store life cycle or how could handle that this store live just when one component is showing and next was destroyed. Thanks for your support.



 if first enter to user form, my store useDocuments load mi fields, and next,  to one fie

**Comment by dai-shi** [comment]
The primary use case of zustand is so-called module state, which is created at first and not destroyed.
In this use case, the recommendation is to clear property in the store (keeping the store itself live always.)
So, I hope creating a single store for both user and documents would help.

One could use zustand for component state, but I'd say it's rather for experts who are fully familiar with it.

**Comment by caltamiranob** [comment]
@dai-shi Thanks for your support and time. It may not be the right place to ask you this question, but I need to be clear about this; If I have an application that has many modules, is it recommendable to use zustand only for global states and continue using useState or useContext for local states? or if I store all the states of my entire application with zustand, could I have any performance issues? What is the most recommendable practice?.

**Comment by dai-shi** [comment]
You want to use global states with zustand and local states with useState.
Local states would be passed to child components with props.
I wouldn't recommend using useContext for global states in this case.

Closing this issue as resolved, but you can continue asking related questions here.
Alternatively, you may open [a new discussion](https://github.com/pmndrs/zustand/discussions/new) for other questions.
