### ISSUE TITLE
How to persist state 

### ISSUE THREAD

**Issue by Madses** [pmndrs/zustand#345]
Hi I have my store setup like this :

```
import create from 'zustand';

export const useStore = create((set) => ({
    filters: {searchQuery: 'hello', evaluationMonth : null},
    setFilters: (e) => set((state) => ({filters : {evaluationMonth : 'New Month'}}),true),
}))

```

When i call setFilters it updates evaluationMonth as expected, but it wipes out everything else (searchQuery). How do i persist the old state? I tried adding the second argument 'true', but this didnt work.

**Comment by dai-shi** [comment]
Here you go:

```js
export const useStore = create((set) => ({
    filters: {searchQuery: 'hello', evaluationMonth : null},
    setFilters: (e) => set((state) => ({ filters : { ...state.filters, evaluationMonth : 'New Month' } })),
}))
```

**Comment by Madses** [comment]
> Here you go:
> 
> ```js
> export const useStore = create((set) => ({
>     filters: {searchQuery: 'hello', evaluationMonth : null},
>     setFilters: (e) => set((state) => ({ filters : { ...state.filters, evaluationMonth : 'New Month' } })),
> }))
> ```

Thank you so much !
