### ISSUE TITLE
regeneratorRuntime is not defined (after installing 3.4)

### ISSUE THREAD

**Issue by garth** [pmndrs/zustand#351]
```
ReferenceError: regeneratorRuntime is not defined
    at create ([...]/node_modules/zustand/index.js:156:31)
```

Reverting back to 3.3.3 fixes the issue.

**Comment by aulneau** [comment]
@dai-shi might be that `regenerator-runtime` needs to be a peer dep.

@garth can you try to install [`regenerator-runtime`](https://www.npmjs.com/package/regenerator-runtime) and see if that fixes it?

**Comment by SimeonGriggs** [comment]
Oh boy it's not just me! What a relief 😅

Confirmed going back to 3.3.3 fixes.

**Comment by garth** [comment]
Adding regenerator-runtime as a dependency doesn't seem to make any difference.

I did check the release notes, but it's not clear to me what the implications are.

**Comment by worstpractice** [comment]
Related: https://github.com/pmndrs/zustand/pull/336#discussion_r603708944

**Comment by dai-shi** [comment]
Sorry, guys. I'll investigate it later. Meanwhile, please keep using v3.3.3.
This is just unexpected for me, thus not noted in the release note.

**Comment by gersomvg** [comment]
Ai this broke our builds as well. Didn't realise that if you do a fresh install with `"zustand": "^3.1.3"` it will install the latest minor version (not the latest patch). Removing the `^` for now..

**Comment by dai-shi** [comment]
@gersomvg would you please test if #352 fixes it?
This breaking is not intended. My apologies.
Note `^` does update minor, `~` does for patch.

**Comment by prarabdhb** [comment]
I tested #352 and the build succeeded. It was failing with `3.4.0` but its working now.

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/zustand/v/3.4.1

Thanks everyone for reporting and testing.

**Comment by gersomvg** [comment]
@dai-shi No worries, thanks for fixing it so quick! 🙏🏻  This helped me get a better grasp of how NPM install/update works with respect to semver, so for me it served a purpose 😬
