### ISSUE TITLE
Syntax error on IE11 when v3.4.1 is bundled by webpack

### ISSUE THREAD

**Issue by tt4g** [pmndrs/zustand#354]
I have just updated from version 3.3 to 3.4 and noticed that `index.cjs.js` is missing.
`index.cjs.js` worked on IE11, but syntax error occurs version 3.4 `index.js`

Our project has to continue to support IE11..
After version 3.4, is the only way to support it to transpile `index.js` by itself?

**Comment by AnatoleLucet** [comment]
Have you tried with `3.4.1`? (see #351 & https://github.com/pmndrs/zustand/releases/tag/v3.4.1)

**Comment by tt4g** [comment]
Thank you for quick response.

Yes, our project is using v3.4.1 but get "SCRIPT1002 syntax error. vendor.696739b3b87e417414ff.js (92943,40)".
And the syntax error is occurring in the arrow function (`=>`).

NOTE I should have mentioned this at the beginning, but the project uses webpack.

I found out that the source code bundled by webpack is `zustand/esm/index.js`.
Probably webpack bundles `zustand/esm/index.js` in priority according to `"module": "esm/index.js"` in `package.json`.

**Comment by tt4g** [comment]
After adding the following settings to `webpack.config.js`, zustand worked in IE11.

```javascript
resolve: {
    extensions: [".ts", ".tsx", ".js", ".jsx"],
    modules: ["node_modules"],
    alias: {
    zustand: path.resolve(__dirname, "node_modules/zustand/index.js"),
    },
},
```

Should I force webpack to bundle `zustand/index.js`?

BTW Transpiling `zustand/esm/index.js` with babel worked with IE11.

**Comment by AnatoleLucet** [comment]
I don't think it's a good idea to hard code this path in your webpack config. You might better look into [`resolve.mainFields`](https://webpack.js.org/configuration/resolve/#resolvemainfields).
But still, you probably shouldn't have to.

Since the `.cjs` has been removed from the filename, we may need to add a `"type": "commonjs"` in the `package.json` (https://nodejs.org/api/packages.html#packages_determining_module_system)? @dai-shi

**Comment by dai-shi** [comment]
So, the old zustand/index.js didn't have `=>` ? That's something I wasn't aware of...

What we have in 3.4.1 is: `zustand/index.js` is cjs for old browsers and `zustand/esm/index.js` is esm for modern browsers.

I guess `mainFields` or direct path is a way to go for IE11 with webpack.

> `"type": "commonjs"`

I don't think it helps, as it's default.

**Comment by tt4g** [comment]
Does not set `resolve.mainFields` but `target: "browserslist"` was specified.
According to the [`target: "browserslist"`](https://webpack.js.org/configuration/target/), it activates the ES feature.

`.browserslistrc`

```
defaults
> 5%
last 2 version
IE 11
not dead
```

```bash
$ $ npx browserslist
and_chr 89
and_ff 86
and_qq 10.4
and_uc 12.12
android 89
baidu 7.12
chrome 89
chrome 88
chrome 87
edge 89
edge 88
firefox 86
firefox 85
firefox 78
ie 11
ios_saf 14.0-14.5
ios_saf 13.4-13.7
kaios 2.5
op_mini all
op_mob 62
opera 73
opera 72
safari 14
safari 13.1
samsung 13.0
samsung 12.0
```

**Comment by tt4g** [comment]
> What we have in 3.4.1 is: zustand/index.js is cjs for old browsers and zustand/esm/index.js is esm for modern browsers.

v3.3 used the following webpack aliases.

```javascript
resolve: {
    extensions: [".ts", ".tsx", ".js", ".jsx"],
    modules: ["node_modules"],
    alias: {
        zustand: path.resolve(__dirname, "node_modules/zustand/index.cjs.js"),
    },
},
```

> I guess mainFields or direct path is a way to go for IE11 with webpack.

As of now, the following two settings worked with IE11.

<details>
<summary>Use webpack resolve alias:</summary>

```javascript
resolve: {
    extensions: [".ts", ".tsx", ".js", ".jsx"],
    modules: ["node_modules"],
    alias: {
        zustand: path.resolve(__dirname, "node_modules/zustand/index.js"),
    },
},
```
</details>

<details>
<summary>Use babel (transpile):</summary>

```javascript
module: {
      rules: [
        {
          test: /\.jsx?$/,
          include: [
            path.resolve(__dirname, "src"), // project source root.
            path.resolve("node_modules/zustand/"), // transpile for IE11 support.
          ],
          use: [{
            loader: "babel-loader"
          }],
        },
}
```
</details>

IMO: webpack resolve alias may be the best workaround. This way, even if webpack prioritizes ES modules, the same files will always be bundled.
Transpiling with babel changes the post-transpiling state depending on the module resolved by webpack.

**Comment by dai-shi** [comment]
Okay, I checked that v3.3.3 `zustand/index.js` has arrow functions.

So, basically, you fall into the breaking change in v3.4.

I would say either of your two following workarounds is the right one.

> After adding the following settings to webpack.config.js, zustand worked in IE11.

> BTW Transpiling zustand/esm/index.js with babel worked with IE11.

---
I'm not sure if there's a better way. Suggestions are welcome, but totally uncertain if they can be accepted.

**Comment by tt4g** [comment]
I think this is a minor issue as IE11 will be out of support for many products by August 2021.

I'm going to close it because there are workarounds.
