### ISSUE TITLE
Using devtools for multiple stores

### ISSUE THREAD

**Issue by israelalagbe** [pmndrs/zustand#355]
At the moment, I tried using the devtool for multiple stores, it seems it can only work for a single store at a time.

**Comment by dai-shi** [comment]
Does putting "prefix" solve it?
https://github.com/pmndrs/zustand#redux-devtools

**Comment by israelalagbe** [comment]
@dai-shi 
No it didn't, I tried that too.

**Comment by dai-shi** [comment]
Hmm, I'm not sure then. Can anyone help?

**Comment by dai-shi** [comment]
> in fact each zustand store will have its own redux devtools page

Hmm, I thought it's by design. If you want a single store like redux, why won't you create a single zustand store?

**Comment by olavoparno** [comment]
@dai-shi precisely. I don't know if it would be better if it was explained in the docs this difference from redux store when using devtools so that it wouldn't be misunderstood.

**Comment by dai-shi** [comment]
> each zustand store will have its own redux devtools page

So, explain this in the readme? Mind opening a PR?

**Comment by olavoparno** [comment]
I might do it later this week

**Comment by olavoparno** [comment]
> > each zustand store will have its own redux devtools page
> 
> So, explain this in the readme? Mind opening a PR?

here it is, https://github.com/pmndrs/zustand/pull/369

**Comment by dai-shi** [comment]
closed by #369
