### ISSUE TITLE
Deserialize option of PersistOptions has an incorrect type

### ISSUE THREAD

**Issue by Birbone** [pmndrs/zustand#358]
Option `deserialize` has the following definition in PersistOptions type:
`deserialize?: (str: string) => StorageValue<S> | Promise<S>;`
Because of that asynchronous version demands to return Store value itself and not the object that incapsulates state and version of the state. While code that uses this option always expects `StorageValue<S>` to be returned out of deserialize method, for both sync and async versions.
I think the type should be defined like this:
`deserialize?: (str: string) => StorageValue<S> | Promise<StorageValue<S>>;`

**Comment by AnatoleLucet** [comment]
Oops, it's an oversight 😄
Thanks, I'll fix it!
