### ISSUE TITLE
[jest] Still throwing "not wrapped in act(...)" errors

### ISSUE THREAD

**Issue by ivancuric** [pmndrs/zustand#363]
Follow up on https://github.com/pmndrs/zustand/issues/272#issuecomment-809660791.

After updating my test runner to `jest-circus` and wrapping each `resetFn` in `act(...)` I thought I got rid of this error, but it came up again after another state update that is done inside a `useEffect` on mount. This one reads a json file from the filesystem and stores it in a zustand store:

```ts
    refreshGallery: async () => {
      const galleryData = await api.readGallery();
      set((draft) => {
        draft.gallery = galleryData;
      });
    },
```
Which basically does the following (Electron app):
```ts
  ipcHandle('readGallery', async () => {
    const dbPath = path.join(app.getPath('userData'), 'media', 'database.json');
    const db = await fs.readFile(dbPath, 'utf-8');
    const data = JSON.parse(db);
    return data;
  });
```

The (newly) failing test is 
```tsx
test('sidebar exists', () => {
  render(<App />);
  expect(screen.getByTitle('nav.camera')).toBeInTheDocument();
});
```

I've managed to fix the `wrapped in act(...)` error by basically wrapping the entire test in `async`:
```tsx
test('sidebar exists', async () => {
  await act(async () => {
    render(<App />);
  });
  expect(screen.getByTitle('nav.camera')).toBeInTheDocument();
});
```

Could this be a `zustand` issue, or is it something `jest`-related?

**Comment by squarism** [comment]
I'm having a similar issue.  I have a create-react-app with zustand (refactor branch moving away from redux).  Commenting out useEffect in my component gets rid of the act() warnings.  For a time, it seemed like these warnings weren't happening.

Maybe I shouldn't be setting up state using props?
```
  useEffect(() => {
    setWidgets(props.widgets)
  }, [])
```
This probably isn't related to zustand by itself.  I don't see how this isn't allowed.  If I had an API call I needed to do, I would do this.  Do the API call in useEffect, set zustand state.  Right?  If this is true, maybe we should open an issue on react-testing-library.

**Comment by squarism** [comment]
@ivancuric I watched the videos here btw: https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning
There are lots of tips and examples there.  And lots of explanation.

Adding
```
    const promise = Promise.resolve()
    await act(() => promise)
```
To the end of my test fixed this for me.

**Comment by italodeandra** [comment]
I had the same problem with `valtio`. I also had the same process as you, I thought `jest-circus` had fixed (https://github.com/pmndrs/zustand/issues/272#issuecomment-839943504), but if you have a effect that updates the store, then the problem will happen again.

The explanation is that the test ends before valtio/zustand end doing their thing to the proxy/store, so React triggers this warning, and I couldn't find any way to make it wait for the change.

**Comment by dai-shi** [comment]
Would anyone summarize the state of this issue please? Can close or not?

**Comment by tsuz** [comment]
Using react-testing-library, a workaround for me was to add `cleanup()` at the end of each test. I couldn't find what was causing this, either zustand or react-query.

```
import { cleanup, render, } from '@testing-library/react';

it('' => {
  ...
  cleanup()
})
```

**Comment by ivancuric** [comment]
> Would anyone summarize the state of this issue please? Can close or not?

You can close it I think, as it seems that it's a universal issue not really related to Zustand, but any state changes that are running as a side-effect, which need to be somehow mitigated by the user.

> Using react-testing-library, a workaround for me was to add `cleanup()` at the end of each test. I couldn't find what was causing this, either zustand or react-query.
> 
> ```
> import { cleanup, render, } from '@testing-library/react';
> 
> it('' => {
>   ...
>   cleanup()
> })
> ```

https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-cleanup

> For a long time now cleanup happens automatically (supported for most major testing frameworks) and you no longer need to worry about it.
>
> Advice: don't use cleanup

**Comment by dai-shi** [comment]
Thanks for the updates. Let me close this now.
