### ISSUE TITLE
Object/Array pick triggers rerenders with r3f

### ISSUE THREAD

**Issue by andreivips** [pmndrs/zustand#364]
Batch state picking triggers rerendering when using zustand with r3f (!):

`const { nuts, honey } = useStore(state => ({ nuts: state.nuts, honey: state.honey }))`
`const [nuts, honey] = useStore(state => [state.nuts, state.honey])`

Simple picking, works fine:

`const nuts = useStore(s => s.nuts)`
`const honey = useStore(s => s.honey )`

log appear as batch output in console:

![shot](https://user-images.githubusercontent.com/56654837/114763295-efc5b700-9d62-11eb-99f8-c8205771fed1.png)

tracked with [https://github.com/welldone-software/why-did-you-render](url)

possibly object/array state selectors ref are not handled stable and forceUpdate displays its incrementing value as shown
[https://github.com/pmndrs/zustand/blob/2adf4ee47768e90e556355b8e1168fe3281c3408/src/index.ts#L43](url)

**Comment by drcmda** [comment]
you need to use shallow equality for these to work: https://github.com/pmndrs/zustand#selecting-multiple-state-slices otherwise you're giving it a new object every render and strict equality (a === b) will flag that as a change always.

**Comment by andreivips** [comment]
Yes, it works only that way and looks like an instant advice for this case.
Also regarding to shallow-function, it compares objects by keys.length:
[https://github.com/pmndrs/zustand/blob/2adf4ee47768e90e556355b8e1168fe3281c3408/src/shallow.ts#L19](url)

> const keysA = Object.keys(objA as object)
  if (keysA.length !== Object.keys(objB as object).length) {
    return false
  }

wouldn't this led to state miss when only property change but not the length of keys as a result,
next line makes more in depth comparison:
[https://github.com/pmndrs/zustand/blob/2adf4ee47768e90e556355b8e1168fe3281c3408/src/shallow.ts#L22](url)

> for (let i = 0; i < keysA.length; i++) {
    if ( !Object.prototype.hasOwnProperty.call(objB, keysA[i]) || !Object.is((objA as Obj)[keysA[i]], (objB as Obj)[keysA[i]]) ) {
      return false
    }
  } 

or its just a performance trick ?

**Comment by Honga1** [comment]
It returns only the mismatched case early. After that check it does the rest as you point out. So I'd say yes it's a performance 'trick'.

**Comment by dai-shi** [comment]
Closing this as resolved.
