### ISSUE TITLE
persist middleware: Rehydrate on demand

### ISSUE THREAD

**Issue by Daiz** [pmndrs/zustand#374]
Looking at the code of the persist middleware, it seems that loading from storage / rehydration only happens on initialization. It would be nice if it was possible to also rehydrate on demand, eg. if you are using localStorage and you want to react to changes made to storage in another tab (like authentication, or anything really) via [`window.addEventListener("storage")`.](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event)

Looking at the code, I think the best way to implement this would be as part of PersistOptions, something like `update?: (rehydrate: () => Promise<void>) => void` where `rehydrate` is naturally the [rehydration function](https://github.com/pmndrs/zustand/blob/master/src/middleware.ts#L261-L290) and the user can configure how they call it inside the listener function (by eg. adding a window event listener for the storage event).

**Comment by AnatoleLucet** [comment]
That's a good idea. Though I think it'd be more flexible if the `rehydrate` function was exposed through the [persist api](https://github.com/pmndrs/zustand/issues/267) instead of an option.

**Comment by Daiz** [comment]
Oh yeah, an API definitely sounds like a more fitting place of it. I missed the fact that it had one on my quick look over it.

**Comment by AnatoleLucet** [comment]
Great, I'll close this issue and reference it in #267 then.
