### ISSUE TITLE
Persist middleware storing or returning wrong value

### ISSUE THREAD

**Issue by Logaqm** [pmndrs/zustand#378]
I have an object in my store im initializing with a mock dataset, using persist seems to cause some issues (probably somewhere in the serialization/deserialization process) and mutates the object. Not using persist solves the issue, and I get the correct value 
returned. 

This is the proper data and what it should be returning 
![good](https://user-images.githubusercontent.com/16585353/117385954-0966a400-aeb4-11eb-9cbb-c0466c844d7b.png)

And this what im getting when using persist 
![bad](https://user-images.githubusercontent.com/16585353/117386003-1be0dd80-aeb4-11eb-9c0d-45c052d57038.png)

Note the `rootId` has changed type, and the `items` object is now empty

**Comment by AnatoleLucet** [comment]
Hi @Logaqm, can you please share some code so I can reproduce on my end? 🙏

**Comment by Logaqm** [comment]
Ive tried to recreate the issue in a codesandbox, but no luck. Heres the code in my project, Theres not a lot here, since i just started integrating zustand yesterday.  

This is my store 


![97e21062542973ff43706b89d75a4459](https://user-images.githubusercontent.com/16585353/117460207-45cceb00-af1a-11eb-8400-18bd68e5a4a1.png)

**Comment by Logaqm** [comment]
Ive tried recreating with a codesandbox, but no luck. This is the code in question in my project. I just started integrating zustand yesterday, so not a ton here. 

This is my store 
![97e21062542973ff43706b89d75a4459](https://user-images.githubusercontent.com/16585353/117460485-8fb5d100-af1a-11eb-87c0-f2a77d16d965.png)

And this is the code that is printing out the incorrect data. 
![e9ee793ecd2df3a3256b7f919a6f69e2](https://user-images.githubusercontent.com/16585353/117460491-92182b00-af1a-11eb-9467-9bcb709a29ac.png)
Its working perfectly when im storing the selected item, so i dont think its a problem with my use of zustand?

**Comment by AnatoleLucet** [comment]
You need to pass an option object as the second argument of `persist`.
```js
DocumentDataStore = persist(DocumentDataStore, { name: "document-data" })
```
You at least need to give a name to `persist`, the other settings are optional.
I'm not sure if the issue comes from here. But you should give it a try.

**Comment by Logaqm** [comment]
That did the trick- my bad. Thanks.
