### ISSUE TITLE
listener update performance issue?

### ISSUE THREAD

**Issue by windmaomao** [pmndrs/zustand#390]
I have a question when reading the following line,
```
listeners.forEach(listener => listener())
```

Since each listen is literally a `set` from a instance of `useState`, how could this line not wrapped in a `unstable_batchedUpdates`. If the topology of the network is 

A* -> B -> C*
    \
     > D*

How could you make sure C or D is not rendered twice?  * indicates where the `useStore` is written. I'm just curious. Thank, this is an awesome library, pretty much eye opener for me.

**Comment by dai-shi** [comment]
There were some discussions on this before, and it might be controversial. A short answer is it's the responsibility of the library users.

A bit long answer is, most likely if this is called from react callback, it's already in a batch. Only users know when it's not and a batch is really necessary. In the future React version, it's said that this will be improved and basically we would never need to use batchedUpdates, I _guess_. And, that's probably the reason it's `unstable_`. We shouldn't depend on `unstable_` as much as possible. Furthermore, batchedUpdates is not in `react`, but it's in renderer like `react-dom`. zustand only depends on `react`. Adding non-deterministic peer dependencies is too much hustle to work well with recent bundlers.

Closing this, but feel free to continue discussions on the closed issue.

**Comment by windmaomao** [comment]
Thanks dai-shi for the quick answer. It totally makes sense. I guess most of time the react event callback is good enough. Thank you. 

If you have time,  please let me know what you think on node B in above chart, if B has no prop ? When C triggers the `merge`, what is happening.

**Comment by dai-shi** [comment]
You are welcome.

I'm not sure if I get the topology. Can elaborate? If it's not batched, it will render twice, but the store would be just as expected. I mean there's no magic behind it.
