### ISSUE TITLE
Add more docs

### ISSUE THREAD

**Issue by samarmohan** [pmndrs/zustand#391]
Amazing library! The only thing I can think of is adding more docs. (CONTRIBUTING.md, middleware guides, more examples.)

**Comment by pvinis** [comment]
More examples are definitely needed. Right now all examples are like `count: 1` or whatever, and that's not really a real life example.

**Comment by dcsan** [comment]
there are some good tutorials around, maybe those folks could contribute as examples?
https://blog.bitsrc.io/zustands-guide-to-simple-state-management-12c654c69990

**Comment by robrechtme** [comment]
Maybe also add an API reference? Not _every_ option/parameter is mentioned in the docs, so it would be nice if you could browse through them. 🙂

**Comment by dai-shi** [comment]
Maybe someone want to make a wiki page liking to some good articles?

**Comment by devcui** [comment]
It is true that the demo on the official website is too monotonous, but this is the best state management component I have ever used.

**Comment by dai-shi** [comment]
We started adding some docs in `./docs` and #1008. So, closing this old issue.
Eventually, we hope to have more docs. We welcome more contributors.
