### ISSUE TITLE
Zustand persist for React Native AsyncStorage 

### ISSUE THREAD

**Issue by ghacosta** [pmndrs/zustand#394]
Does Zustand built-in persist functionality works with AsyncStorage to persist state on React Native?

if not, it is on scope? I'd like to know if any member could give me some ideas about how to deliver this functionality and see if I can come up with a PR for it.

Note: I've already checked this project https://github.com/roadmanfong/zustand-persist but it is having issues to deliver what it's aimed for.

**Comment by charkour** [comment]
Hi, thanks for the great question!

I haven't tried this, but have you tried using the existing persist middleware zustand provides passing in the AsyncStorage as an option?

```tsx
import AsyncStorage from '@react-native-async-storage/async-storage';
import create from "zustand"
import { persist } from "zustand/middleware"

export const useStore = create(persist(
  (set, get) => ({
    fishes: 0,
    addAFish: () => set({ fishes: get().fishes + 1 })
  }),
  {
    name: "food-storage", // unique name
    getStorage: () => AsyncStorage, // Add this here!
  }
))
```

**Comment by AnatoleLucet** [comment]
👋 the built-in `persist` middleware supports async storages. So @charkour's snippet should work.
Let me know if there's any issue.

**Comment by jasoncslaughter** [comment]
Just a note for whoever is searching for async storage for use in the browser as opposed to React Native (I found this post looking for that), the persist middleware also seems to work perfectly with the localForage library (https://github.com/localForage/localForage):

```
import create from "zustand";
import { persist } from "zustand/middleware";
import localForage from "localforage";

type BearState = {
  bears: number;
  increase: (by: number) => void;
};

export const useBearStore = create<BearState>(
  persist(
    (set) => ({
      bears: 0,
      increase: (by) => set((state) => ({ bears: state.bears + by })),
    }),
    {
      name: "bear-storage",
      getStorage: () => localForage as never,
    }
  )
);
```

**Comment by hungdev** [comment]
@charkour @AnatoleLucet it doesnt work.

> Hi, thanks for the great question! I'm not a maintainer but I use zustand a lot.
> 
> I haven't tried this, but have you tried using the existing persist middleware zustand provides passing in the AsyncStorage as an option?
> 
> ```tsx
> import AsyncStorage from '@react-native-async-storage/async-storage';
> import create from "zustand"
> import { persist } from "zustand/middleware"
> 
> export const useStore = create(persist(
>   (set, get) => ({
>     fishes: 0,
>     addAFish: () => set({ fishes: get().fishes + 1 })
>   }),
>   {
>     name: "food-storage", // unique name
>     getStorage: () => AsyncStorage, // Add this here!
>   }
> ))
> ```
> 
> Since AsyncStorage has the same `getItem`, `setItem` API as something like localStorage, then my gut says it should work.

I got the error:
![image](https://user-images.githubusercontent.com/12009276/150302806-c46112c5-a9e3-49d0-bbac-a60e73ceacc6.png)

**Comment by AnatoleLucet** [comment]
@hungdev according to the error, you might be forgetting the `name` property on persist's options (which is **required**).

Or else could you send a code snippet?

**Comment by hungdev** [comment]
@AnatoleLucet i already have a name
here is my code:
```
import AsyncStorage from '@react-native-async-storage/async-storage';
import create from "zustand";
import { persist } from "zustand/middleware";

export const useStore = create(persist(
  (set, get) => ({
    fishes: 0,
    addAFish: () => set({ fishes: get().fishes + 1 })
  }),
  {
    name: "food-storage", // unique name
    getStorage: () => AsyncStorage, // Add this here!
  }
));
```
![image](https://user-images.githubusercontent.com/12009276/150304317-a0d3fbba-06f0-4777-96f0-638bd93a9821.png)

**Comment by hungdev** [comment]
@AnatoleLucet sorry, it's my mistake. I missed the name in another file. and now it works

**Comment by hungdev** [comment]
@AnatoleLucet I have a question. I have useStore, it combined authSlice, createBearSlice, createHoneySlice, , createFishSlice. 
So Case 1: I don't want to persist authSlice, remaining still persist.
 Case 2: I just want to persist only authSlice, remaining do not persist
how do I do that?

**Comment by AnatoleLucet** [comment]
You can use [partialize](https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data#partialize) to omit/keep specific slices fields.

**Comment by hungdev** [comment]
@AnatoleLucet thank you so much <3

**Comment by kecoliva** [comment]
I just discovered something. Not sure if this is correct but for some reason it works.

So if ever you want to use Expo's **expo-secure-store**:

```
import { deleteItemAsync, getItemAsync, setItemAsync } from 'expo-secure-store';
import create from 'zustand';
import { combine, persist } from 'zustand/middleware';

export const useSession = create(
  persist(
    combine({ accessToken: null as null | string }, (set) => ({
      setAccessToken: (accessToken: null | string) => set({ accessToken }),
    })),
    {
      name: 'accessToken',
      getStorage: () => ({
        setItem: setItemAsync,
        getItem: getItemAsync,
        removeItem: deleteItemAsync,
      }),
    }
  )
);

```

**Comment by WenLonG12345** [comment]
> Hi, thanks for the great question! I'm not a maintainer but I use zustand a lot.
> 
> I haven't tried this, but have you tried using the existing persist middleware zustand provides passing in the AsyncStorage as an option?
> 
> ```tsx
> import AsyncStorage from '@react-native-async-storage/async-storage';
> import create from "zustand"
> import { persist } from "zustand/middleware"
> 
> export const useStore = create(persist(
>   (set, get) => ({
>     fishes: 0,
>     addAFish: () => set({ fishes: get().fishes + 1 })
>   }),
>   {
>     name: "food-storage", // unique name
>     getStorage: () => AsyncStorage, // Add this here!
>   }
> ))
> ```
> 
> Since AsyncStorage has the same `getItem`, `setItem` API as something like localStorage, then my gut says it should work.

How about typescript? I tried to do so but TS throw errors

**Comment by nihilates** [comment]
> How about typescript? I tried to do so but TS throw errors
@WenLonG12345 

I was able to get my typescript to compile without error and see the working persisted storage by implementing typescript in this way:

```typescript
import AsyncStorage from '@react-native-async-storage/async-storage'
import create from 'zustand'
import { persist } from 'zustand/middleware'

interface FoodStoreState {
  fishes: number
  addAFish(): void
}

export const useScansStore = create(persist<FoodStoreState>(
  (set, get) => ({
    fishes: 0,
    addAFish: () => set({ fishes: get().fishes + 1 })
  }),
  {
    name: "food-storage",
    getStorage: () => AsyncStorage
  }
))
```

So, passing a declared interface in to the `persist<...>` properly lined up my types.

**Comment by ElectricCoffee** [comment]
> > How about typescript? I tried to do so but TS throw errors
> > @WenLonG12345
> 
> I was able to get my typescript to compile without error and see the working persisted storage by implementing typescript in this way:
> 
> ```ts
> import AsyncStorage from '@react-native-async-storage/async-storage'
> import create from 'zustand'
> import { persist } from 'zustand/middleware'
> 
> interface FoodStoreState {
>   fishes: number
>   addAFish(): void
> }
> 
> export const useScansStore = create(persist<FoodStoreState>(
>   (set, get) => ({
>     fishes: 0,
>     addAFish: () => set({ fishes: get().fishes + 1 })
>   }),
>   {
>     name: "food-storage",
>     getStorage: () => AsyncStorage
>   }
> ))
> ```
> 
> So, passing a declared interface in to the `persist<...>` properly lined up my types.

The Zustand docs say to just do this: `create<FoodStoreState>()(persist(...));` i.e. use the curried form

**Comment by AmirDiafi** [comment]
@relaxxpls thanks bro👍

**Comment by IgorMing** [comment]
not sure if someone keeps seeing ESLint problems for adding persist with `AsyncStorage`, but I had to add a more specific type for the `create` function.

```diff
- export const useAuthStore = create<AuthState>(
+ export const useAuthStore = create<AuthState, [['zustand/persist', AuthState]]>(
  persist(
    (set) => ({
      isLoggedIn: false,
      toggleAuth: () => set((state) => ({ isLoggedIn: !state.isLoggedIn })),
    }),
    { name: 'auth-storage', storage: createJSONStorage(() => AsyncStorage) },
  ),
);
```

Hope it helps someone!

**Comment by dai-shi** [comment]
You want to try this instead:
```diff
- export const useAuthStore = create<AuthState>(
+ export const useAuthStore = create<AuthState>()(
  persist(
    (set) => ({
      isLoggedIn: false,
      toggleAuth: () => set((state) => ({ isLoggedIn: !state.isLoggedIn })),
    }),
    { name: 'auth-storage', storage: createJSONStorage(() => AsyncStorage) },
  ),
);
```

**Comment by dangnguyen1004** [comment]
I resolved an issue when using persist with custom async storage that made the state unhydrated, so I want to share it with someone who needs it. The problem with the method getItem is that it must be returned as string, but my custom storage return an object so I have to JSON.stringify the result of the getItem so that it can be used along with createJSONStorage 
```
import { create } from 'zustand';
import { StateStorage, createJSONStorage, persist } from 'zustand/middleware';

interface IFirstOrderStore {
    orderNo: string;
    saveFirstOrder: (orderNo: string) => void;
}

export const myAsyncStorage: StateStorage = {
    getItem: async (key: string) => JSON.stringify(await MyStorage.getItem(key)),
    setItem: async (key: string, value: string) => MyStorage.setItem(key, value),
    removeItem: async (key: string) => MyStorage.removeItem(key),
};

export const useFirstOrder = create<IFirstOrderStore, [['zustand/persist', IFirstOrderStore]]>(
    persist(
        set => ({
            orderNo: '',
            saveFirstOrder: (orderNo: string) => set({ orderNo }),
        }),
        {
            name: 'first-order-storage',
            storage: createJSONStorage(() => myAsyncStorage),
        }
    )
);
```

**Comment by bogdanaks** [comment]
Code for those using `expo-secure-store` and getting a warning:

> [DEPRECATED] `getStorage`, `serialize` and `deserialize` options are deprecated. Use `storage` option instead.

```
import { deleteItemAsync, getItemAsync, setItemAsync } from "expo-secure-store"
import { create } from "zustand"
import { StorageValue, persist } from "zustand/middleware"

interface AuthState {
  isAuth: boolean
  setIsAuth: (toggle: boolean) => void
}

export const useAuthStore = create<AuthState>()(
  persist(
    (set) => ({
      isAuth: false,
      setIsAuth: (toggle: boolean) => set({ isAuth: toggle }),
    }),
    {
      name: "auth-storage",
      storage: {
        setItem: async (key, value) => await setItemAsync(key, value as unknown as string),
        getItem: async (key) => await getItemAsync(key) as Promise<StorageValue<AuthState>> | null,
        removeItem: async (key) => await deleteItemAsync(key),
      },
    }
  )
)

```

**Comment by quememo** [comment]
> Code for those using `expo-secure-store` and getting a warning:
> 
> > [DEPRECATED] `getStorage`, `serialize` and `deserialize` options are deprecated. Use `storage` option instead.
> 
> ### Based on `createJSONStorage` create `storage`
> ```
> export const expoSecureStorage = {
>   setItem: async (key: string, value: string) => await setItemAsync(key, value),
>   getItem: async (key: string) => (await getItemAsync(key)) as Promise<string> | null,
>   removeItem: async (key: string) => await deleteItemAsync(key),
> }
> ```
> 
> ### How to use:
> ```
> import { create } from "zustand"
> import { createJSONStorage, persist } from "zustand/middleware"
> 
> import { expoSecureStorage } from "shared/libs/storage"
> 
> interface AuthState {
>   isAuth: boolean
>   setIsAuth: (toggle: boolean) => void
> }
> 
> export const useAuthStore = create<AuthState>()(
>   persist(
>     (set) => ({
>       isAuth: false,
>       setIsAuth: (toggle: boolean) => set({ isAuth: toggle }),
>     }),
>     {
>       name: "auth-storage",
>       storage: createJSONStorage(() => expoSecureStorage),
>     }
>   )
> )
> ```

Gigachad! This should be in the Docs considering the popularity of Expo, or maybe a more direct integration

**Comment by bryanltobing** [comment]
> setIsAuth: (toggle: boolean) => set({ isAuth: toggle }),

in this case. when using `setIsAuth` should we use `await` ? since it (expo-securie-store setter) is  async internally?

**Comment by romain-spielmann** [comment]
> I just discovered something. Not sure if this is correct but for some reason it works.
> 
> So if ever you want to use Expo's **expo-secure-store**:
> 
> ```
> import { deleteItemAsync, getItemAsync, setItemAsync } from 'expo-secure-store';
> import create from 'zustand';
> import { combine, persist } from 'zustand/middleware';
> 
> export const useSession = create(
>   persist(
>     combine({ accessToken: null as null | string }, (set) => ({
>       setAccessToken: (accessToken: null | string) => set({ accessToken }),
>     })),
>     {
>       name: 'accessToken',
>       getStorage: () => ({
>         setItem: setItemAsync,
>         getItem: getItemAsync,
>         removeItem: deleteItemAsync,
>       }),
>     }
>   )
> );
> ```

It might be useful to note that `expo-secure-store` is not a direct replacement for `react-native-async-storage`. It utilizes [Keychain](https://developer.apple.com/documentation/security/keychain_services) on iOS and [Keystore](https://developer.android.com/privacy-and-security/keystore?hl=fr) on Android and encrypt your data. Also on iOS, the data persists even after the app is deleted and will be restored upon reinstallation. While it will mostly work, in some cases it may result in random behaviors.

Here is the alternative using `react-native-async-storage`

```ts
const asyncStoragePersistConfig = {
  setItem: async (key: string, value: string) =>
    await AsyncStorage.setItem(key, value),
  getItem: async (key: string) => await AsyncStorage.getItem(key),
  removeItem: async (key: string) => await AsyncStorage.removeItem(key),
};
```

```ts
storage: createJSONStorage(() => asyncStoragePersistConfig),
```
