### ISSUE TITLE
[Feature request] What about auto-generating selectors for a store?

### ISSUE THREAD

**Issue by Albert-Gao** [pmndrs/zustand#400]
Keep writing these selectors, 

```typescript
export interface IAuthStore {
  isAuth: boolean
  logout: () => Promise<void>
}

export const useAuthStore = createStore<IAuthStore>(
  set => ({
    isAuth: false,
    logout: async () => {},
  }),
)

useAuthStore.selectors =  {
  isAuth: (state: IAuthStore) => state.isAuth,
  logout: (state: IAuthStore) => state.logout,
}
```

I am wondering can we have this feature built-in?

which means, after `export const useAuthStore = createStore<IAuthStore>(......)`

We can just use it like:

```typescript
// isAuth will have a correct type
const isAuth = useAuthStore(useAuthStore.selectors.isAuth)
```

`useAuthStore.selectors` here is generated by `create` function from `zustand`

Should be a great feature :)

**Comment by dai-shi** [comment]
zustand is trying to be minimal (especially in bundle size, we actually try to reduce it), so it won't be including a new feature in core.

If someone is adding this kind of feature, they could do so in a 3rd party library. And, we are starting to maintain the listing of such libraries: https://github.com/pmndrs/zustand/wiki/3rd-Party-Libraries

Having said that, I have a question or a suggestion regarding this feature. I would like to have auto generated custom hooks instead of selectors. What do you think?

```js
const useStore = createStore(set => ({
  isAuth: false,
  logout: async () => {},
}))

export const store = {
  useStore
}

Object.keys(useStore.getState()).forEach((key) => {
  const selector = state => state[key]
  store[`use${capitalize(key)}`] = useStore(selector)
})
```

The idea is pretty close to my another lib: https://github.com/dai-shi/react-hooks-global-state

**Comment by Albert-Gao** [comment]
There is no doubt you are a React state guru, thanks! That works well, the hook does not work well, since when doing ` store[`use${capitalize(key)}`] = useStore(selector)` outside of a component, we are essentially invoking hook outside of a component, then some overhead against that, but this logic can be applied to selectors and works quite well, auto-generate with proper typing, thanks!

**Comment by dai-shi** [comment]
Oops, that was simply a bug.

```js
const useStore = createStore(set => ({
  isAuth: false,
  logout: async () => {},
}))

export const store = {
  useStore
}

const capitalize = (s) => s.charAt(0).toUpperCase() + s.slice(1)

Object.keys(useStore.getState()).forEach((key) => {
  const selector = state => state[key]
  store[`use${capitalize(key)}`] = () => useStore(selector)
})
```

Usage:
```jsx
import { store } from './store'

const Component () => {
  const isAuth = store.useIsAuth()
  // ...
}
```

(I haven't run it, so there can still be a bug.)

**Comment by Albert-Gao** [comment]
yup. wrap it as a function works, and just a few more lines will make it work with Typescript quite well, thanks!

`use[key]` is hard to type in TS, the best we can do is `use${key}` with the new template literal syntax, or make keys all uppercase, but not the 1st letter, so I wrapped them under a `.use` object

```typescript
interface Selectors<StoreType> {
  use: {
    [key in keyof StoreType]: () => StoreType[key]
  }
}

function autoGenerateSelectorHooksForStore<StoreType extends State>(
  store: UseStore<StoreType>,
) {
  // @ts-ignore
  store.use = {}
  Object.keys(store.getState()).forEach(key => {
    const selector = (state: StoreType) => state[key as keyof StoreType]
    // @ts-ignore
    store.use[key] = () => store(selector)
  })
}

export function createStore<StoreType extends object>(
  createState: StateCreator<StoreType> | StoreApi<StoreType>,
) {
  const store = pipe(log, immer, create)(createState)

  autoGenerateSelectorHooksForStore(store)

  return store as UseStore<StoreType> & Selectors<StoreType>
}
```

then in the component
```typescript
const isAuth = useAuthStore.use.isAuth()
```

**Comment by dai-shi** [comment]
Maybe, we could type capitalize: https://github.com/type-challenges/type-challenges/blob/master/questions/110-medium-capitalize/README.md

`useFoo` is a little better, because eslint rule understand it as a hook, I expect.

**Comment by Albert-Gao** [comment]
Thanks for the light! we are getting close!

```typescript
interface Selectors<StoreType extends object, Key extends string & keyof StoreType, CapitalizedKey extends Capitalize<Key>> {
  [`use${CapitalizedKey}`]:  () => StoreType[Key]
}
```

![image](https://user-images.githubusercontent.com/18282328/119768769-52d36d80-bf0d-11eb-981a-944d282114be.png)

Just need to solve this one last piece 🤣

**Comment by Albert-Gao** [comment]
Solved, the type is

```tyepscript
type Transformed<BaseType> = {
  [Key in keyof BaseType as `use${Capitalize<string & Key>}`]: () => BaseType[Key]
}
```

**Comment by ivancuric** [comment]
Hey! Do you have a complete example somewhere of this use case?

**Comment by Albert-Gao** [comment]
@ivancuric   Yes, it is from the above example, tells you how to have that helper and how to use, I end up with the `useStore.use.blahblah()` since I like the consolidation of all selectors under `.use`

But if you prefer, `useStore.useBlah()`, already solved, check the latest example


> yup. wrap it as a function works, and just a few more lines will make it work with Typescript quite well, thanks!
> 
> `use[key]` is hard to type in TS, the best we can do is `use${key}` with the new template literal syntax, or make keys all uppercase, but not the 1st letter, so I wrapped them under a `.use` object
> 
> ```ts
> interface Selectors<StoreType> {
>   use: {
>     [key in keyof StoreType]: () => StoreType[key]
>   }
> }
> 
> function autoGenerateSelectorHooksForStore<StoreType extends State>(
>   store: UseStore<StoreType>,
> ) {
>   const newStore: Record<string, any> = store
> 
>   newStore.use = {}
>   Object.keys(store.getState()).forEach(key => {
>     const selector = (state: StoreType) => state[key as keyof StoreType]
>     newStore.use[key] = () => store(selector)
>   })
> 
>   return newStore as UseStore<StoreType> & Selectors<StoreType>
> }
> 
> export function createStore<StoreType extends object>(
>   createState: StateCreator<StoreType> | StoreApi<StoreType>,
> ) {
>   const store = pipe(log, immer, create)(createState)
> 
>   return autoGenerateSelectorHooksForStore<StoreType>(store)
> }
> ```
> 
> then in the component
> 
> ```ts
> const isAuth = useAuthStore.use.isAuth()
> ```
> 
> the intellisense works quite well here
> ![image](https://user-images.githubusercontent.com/18282328/119765971-4e588600-bf08-11eb-9242-e14c5a37d73b.png)

**Comment by ivancuric** [comment]
This is great. I'm honestly tired of writing `const something = useSomethingStore(x => x.something)`.

I wonder if I can combine it with https://github.com/pmndrs/zustand/issues/304#issuecomment-853715431

**Comment by ivancuric** [comment]
@Albert-Gao how did you type your immer middleware? Gotta say I'm a bit over my head with function compositions and types.

Using this:
```ts
import produce, { Draft } from 'immer';
import type { State, StateCreator } from 'zustand';

// typed immer middleware
// https://github.com/pmndrs/zustand/commit/a03550043f72aca8883402171d47572eea40f342
export const immer =
  <T extends State>(
    config: StateCreator<T, (fn: (draft: Draft<T>) => void) => void>,
  ): StateCreator<T> =>
  (set, get, api) =>
    config((fn) => set(produce<T>(fn)), get, api);
```

I get this error with `createState`:
### ```
Argument of type 'StateCreator<StoreType, SetState<StoreType>> | StoreApi<StoreType>' is not assignable to parameter of type 'StateCreator<StoreType, (fn: (draft: Draft<StoreType>) => void) => void>'.
  Type 'StateCreator<StoreType, SetState<StoreType>>' is not assignable to type 'StateCreator<StoreType, (fn: (draft: Draft<StoreType>) => void) => void>'.
    Types of parameters 'set' and 'set' are incompatible.
      Types of parameters 'fn' and 'partial' are incompatible.
        Type 'PartialState<StoreType, K1, K2, K3, K4>' is not assignable to type '(draft: Draft<StoreType>) => void'.ts(2345)
```

**Comment by Albert-Gao** [comment]
interesting, i was using an `any` approach

```typescript
const immer = (config: any) => (set: any, get: any, api: any) =>
  config((fn: any) => set(produce(fn)), get, api)
```

Then I copied your code, still no error,

Here are the versions:
    "immer": "9.0.2",
    "zustand": "3.5.1"
    "typescript": "4.3.2"

**Comment by Albert-Gao** [comment]
I remembered, did you use `combine()`, that causes trouble, I stopped using it, and everything is fine now.

just write a type first, I was thinking this is duplicate typing, then realize the benefit is I can reuse the type without some nasty infer

![image](https://user-images.githubusercontent.com/18282328/121094669-1aa02900-c843-11eb-9aaf-646ab2e959bb.png)

![image](https://user-images.githubusercontent.com/18282328/121094723-2b509f00-c843-11eb-986c-a0f0f6d7888c.png)

**Comment by dai-shi** [comment]
@Albert-Gao Would you be interested in organizing your whole idea and creating a wiki page?
https://github.com/pmndrs/zustand/wiki/Auto-Generating-Selectors
(or https://github.com/pmndrs/zustand/wiki/Auto-Generating-Hooks or as you like)

**Comment by Albert-Gao** [comment]
sure, love to, you love it to be written in js or ts, or both? :) @dai-shi

**Comment by dai-shi** [comment]
ts would be super nice. 🚀

**Comment by Albert-Gao** [comment]
Done, when writing that, i feel the TS version is actually quite hard, so published a lib for wrapping up the wiki page, updated the 3rd party page as well.

- Wiki: https://github.com/pmndrs/zustand/wiki/Auto-Generating-Selectors
- 3rd party libs page: https://github.com/pmndrs/zustand/wiki/3rd-Party-Libraries

**Comment by ivancuric** [comment]
> I remembered, did you use `combine()`, that causes trouble, I stopped using it, and everything is fine now.
Nope, didn't even get to passing a store or calling a function.

**Comment by lautin0** [comment]
@Albert-Gao Thanks for your contribution! This is a really great idea! 

I suggest adding `useFoo` pattern into wiki page also =D

**Comment by Albert-Gao** [comment]
@ivancuric    is your ramda type version update to date?  "@types/ramda": "0.27.40" This should be what controls the input type and output type

@lautin0 my pleasure, this is indeed a very good pattern, thanks @dai-shi

**Comment by zbeyens** [comment]
I have been inspired by this thread to build [zustood](https://github.com/udecode/zustood), a modular store factory auto generating hooks, getters and setters for each field of the store, plus support for extending actions and selectors. Thanks again!

**Comment by wuarmin** [comment]
@dai-shi 
I refer to your example from the 2nd and 4th answer and I have a question: Why you are using `createStore` and not just `create`?

Thanks
