### ISSUE TITLE
Subscribe & hooks not reacting when the slice is an array

### ISSUE THREAD

**Issue by ivancuric** [pmndrs/zustand#406]
I have a state which is basically:

```ts
type State = {
  items: {
    a: string,
    b: number
  }[]
}
```

Pushing another item to the `items` array, or mutating the `a` or `b` props of an item won't trigger an update if subscribed to only the `items` slice, like:
```ts
useStore.subscribe(console.log  x => x.items);
```
or
```ts
const items= useStore(x => x.items);

useEffect(() => {
  console.log(items);
}, [items]);
```

Subscribing to the entire store (eg `const state = useStore()` )works fine, but I'd like to only monitor this slice of state.

I'm using Immer middleware to update state, and an example action that adds an item is:
```ts
addItem: (item) => set((draft) => void draft.items.unshift(item);
```

**Comment by charkour** [comment]
Would it work if you return a new array rather than modifying the current array?

Something like this maybe (may have to fix slight syntax errors):

```tsx
addItem: (item) => set((draft) => {
  draft.items.unshift(item)
  return {items: [...draft.items]}
};
```

**Comment by ivancuric** [comment]
That's an antipattern in Immer. You can't both mutate the state and return a new one.
What I can do is use `draft.items = [...draft.items]` after every update which is kinda missing the point.

I'm not sure why Zustand detects the entire store update.

**Comment by charkour** [comment]
Oh yes, you're right. I forgot that's how Immer works. Sorry about that. 

Yeah, I am not sure why either. Hopefully, someone else will have a better answer.

**Comment by ivancuric** [comment]
I found another issue: seems that the previous and current values aren't properly handled:
```ts
useStore.subscribe((prev, next) =>
  console.log(prev.items[0].a, next.items[0].a)
);
```
These two are always the same when updating `a` on the first item in the array.

**Comment by dai-shi** [comment]
Do you see any issue if you don't use immer and update values immutably instead?

Would you be able to create a minimal repro in codesandbox?

**Comment by ivancuric** [comment]
I am an idiot who forgot to put in immer in the actual producer. 🤦‍♂️
