### ISSUE TITLE
TypeScript being able to setState by key

### ISSUE THREAD

**Issue by Marcsimm** [pmndrs/zustand#411]
I have this state below with a bunch of properties. I want `setValue`  function to set a value based on a provided key there won't be a need for a bunch setState methods.

But I am getting the error below 

`
Argument of type '{ [x: string]: ValueOf<PersonStore>; }' is not assignable to parameter of type 'PartialState<SeriesFormStoreTypes, "setValue" | keyof State | "setInitialState">'.
` 

```
type ValueOf<T> = T[keyof T]

type PersonStore = {
    firstName: string
    lastName: string
    age: number
    height: number
    setValue: (key: keyof State, value: ValueOf<PersonStore>) => void
}

export const PersonFormStore = create<PersonStore>(
  (set: SetState<PersonStore>) => ({
    firstName: "",
    lastName: "",
    age 0,
    height: 0,
    setValue: (key, value) => set({ [key]: value }),
  })
```

Any idea of how I can add a function like described above and fix the type error?

> `PersonStore` needs to extend `State` and your `keyof State` should be `keyof PersonStore`:
> 
> ```ts
> type PersonStore = {
>   firstName: string;
>   lastName: string;
>   age: number;
>   height: number;
>   setValue: <K extends keyof Omit<PersonStore, "setValue">>(key: K, value: PersonStore[K]) => void;
> } & State;
> ```
> 
> In the above snippet, I've also omitted `setValue` from the `key` argument since you probably don't want it to be replaced.

I am sorry but the same problem still happens

**Comment by AnatoleLucet** [comment]
`PersonStore` needs to extend `State`:
```ts
type PersonStore = {
  firstName: string;
  lastName: string;
  age: number;
  height: number;
  setValue: <K extends keyof Omit<PersonStore, "setValue">>(key: K, value: PersonStore[K]) => void;
} & State;
```

**Comment by AnatoleLucet** [comment]
> I am sorry but the same problem still happens

My bad, I was on 3.3.1. It would seem like this is a regression (at least with my snippet) introduced in 3.5.0.

**Comment by dai-shi** [comment]
@AnatoleLucet Let me and @TkDodo know if you have trouble fixing your snippet. A typescript playground might help.

**Comment by dai-shi** [comment]
Closing as stale. Let us know if we should re-open.
