### ISSUE TITLE
[v3.5.2] Type error when using devtools and persist in TypeScript

### ISSUE THREAD

**Issue by onlyling** [pmndrs/zustand#434]
## Test code

```tsx
import create from 'zustand';
import { devtools, persist } from 'zustand/middleware';

interface TestState {
  t1: string;
  t2: number;
  setT1: (t: string) => void;
  [key: string]: any;
}

const useTest = create<TestState>(
  devtools(
    persist(
      (set) => ({
        t1: null,
        t2: null,
        setT1: (n) => {
          set({
            t1: n,
          });
        },
      }),
      {
        name: 'zustand-state-test',
        getStorage: () => localStorage,
      },
    ),
  ),
);

export default useTest;
```

## What happens?

`zustand: 3.4.2` no type error

`zustand: 3.5.2` show some type error

persist use SetState, but devtools use NamedSet.

## Screenshot

<img width="977" alt="zustand-type-error" src="https://user-images.githubusercontent.com/9999765/121844220-38bfca80-cd16-11eb-81e1-851258a30add.png">

## CodeSandbox

https://codesandbox.io/s/elegant-flower-s0e9c?file=/src/App.tsx

**Comment by dai-shi** [comment]
Can #421 fix this??

**Comment by onlyling** [comment]
> Can #421 fix this??

Not able to.

Maybe there is a problem with the way I use it, I want to use devtools and persist in the same store.

**Comment by dai-shi** [comment]
Maybe #428 is related?

@TkDodo can help?

**Comment by TkDodo** [comment]
I put the example code in a codesandbox: https://codesandbox.io/s/elegant-flower-s0e9c?file=/src/App.tsx

If you put it in the issue description, any linked PR will automatically deploy it, thanks.

I also tested it on #428 but the error remains the same. Need to look closer into it but might take some time.

**Comment by punit-shah-cko** [comment]
I am getting a similar error when trying to use the same `createState` function for `create()` and `create(devtools())` calls

```ts
const createState = (set: SetState<Store>) => ({
  // ...
});

const useStore = isProduction
  ? create<Store>(createState)
  : create<Store>(devtools(createState));
```

It seems `NamedSet` is not compatible with `SetState`?

codesandbox: https://codesandbox.io/s/hopeful-wind-04jph?file=/src/store.ts

**Comment by FranciscoMendes10866** [comment]
> I am getting a similar error when trying to use the same `createState` function for separate `create()` and `create(devtools())` calls
> 
> ```ts
> const createState = (set: SetState<Store>) => ({
>   // ...
> });
> 
> const useStore = isProduction
>   ? create<Store>(createState)
>   : create<Store>(devtools(createState));
> ```
> 
> It seems `NamedSet` and `SetState` are not compatible with each other?
> 
> codesandbox: https://codesandbox.io/s/hopeful-wind-04jph?file=/src/store.ts

I have exactly the same problem that you have in your example, which is the following:

```
Types of parameters 'set' and 'set' are incompatible.
```

Do you have a solution for this?

**Comment by TkDodo** [comment]
@FranciscoMendes10866 I tested your example with #441 and it works there.

also, the initial sandbox from @onlyling seems to work with #441 , so it looks really promising 👍
