### ISSUE TITLE
User initial state is null  / avoid user?.name

### ISSUE THREAD

**Issue by diegoarcega** [pmndrs/zustand#435]
Hey guys, 

I have this store that contains an user.

![image](https://user-images.githubusercontent.com/1951007/122053194-e84f7800-cdbc-11eb-9662-acf2d4346017.png)

I find it annoying having to check if there is an user before trying to access it  with `user?.name`.

![image](https://user-images.githubusercontent.com/1951007/122053153-df5ea680-cdbc-11eb-8f97-be2de17f65ef.png)

I have this private route that should also check if the user is in the store, but react is not smart enough to calculate what is after the private route.
![image](https://user-images.githubusercontent.com/1951007/122053950-9c510300-cdbd-11eb-8006-58f351a66302.png)

Do you guys architect your components in a different way to avoid that? or do you have any other ideas? 

Thanks

**Comment by zgid123** [comment]
this issue is not related with react. This is about the typescript. Because your `user` in interface `UserState` is `User | null`, it means user may be null, that's why you will have optional chaining `user?.roles`.

To avoid using it, you can do like this

```
const useUserStore = create<UserState>((set) => ({
  user: {},
  // user: {} as User (if your interface User has some required keys
  // user: { [requiredKeyName]: <default value> }
});
```

**Comment by dai-shi** [comment]
Closing this as answered.

**Comment by diegoarcega** [comment]
> ```ts
> {
> ```

nice, good idea, it can be an empty object, thanks bro!
