### ISSUE TITLE
useState is effecting Zustand Store

### ISSUE THREAD

**Issue by maguirekrist** [pmndrs/zustand#439]
I don't know how to identify this issue I'm experiencing, and after reaching out to other react developers with only inauspicious outcomes, I am left with the Zustand GitHub repo as my only potential solace. Essentially, it seems that my Zustand store is "reacting" and "updating" to the changes in a useState hook within a React component. I put "updates" in quotes as, well, it is not officially updating the Zustand store, i.e., when the state is placed within a useEffect it is not triggered despite the Zustand state being changed. Here is my code example: 

![Code_wVSpWFn8eU](https://user-images.githubusercontent.com/6757360/122591309-c9f1b280-d030-11eb-8e83-f5322b827454.png)

Code in the react component:
![Code_u7X2FupAEl](https://user-images.githubusercontent.com/6757360/122591260-b7777900-d030-11eb-8c91-ded827d3a077.png)

Used images as the code section was acting weird with my .env variables. Anyway, look closely at the last image and the commented section of code. When that is undone, that code is effecting my Zustand state! I know this as the console.log(get().vendors) returns the value of the storedVendors useState and never triggers an update in a useEffect hook with const state = useManageEvent(); as a dependency.

To wrap things up, I am open to anyone straight up telling me that this is "bad practice" or I should be using Zustand in a different way. I am new and open to doing it the right way, I just am self taught so it's hard for me to get access the best practices from mentors or work. However, if this reveals some key issue with Zustand, I'm happy to provide more information upon request! Thank you!

**Comment by dai-shi** [comment]
May not be related, but I would try to invoke `set()` just once.
```js
  setEvent: ({ event }) => {
    if (event) {
      set({ event, vendors: event.vendors })
    } else {
      set({ event })
    }
  }
```

**Comment by dai-shi** [comment]
Did you solve the issue already? If not, would you provide a *minimal* reproduction with codesandbox?

**Comment by dai-shi** [comment]
Closing as stale. Let us know if we should re-open.
