### ISSUE TITLE
zustand/context: drop initialStore and add createStore

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/zustand#445]
https://github.com/pmndrs/zustand/issues/402#issuecomment-861880370

I think initialStore can easily be misused, and requires memoization on caller.

**Comment by dai-shi** [comment]
@Munawwar Are you around?

**Comment by Munawwar** [comment]
@dai-shi I was away for a while. I have to recollect the next.js issues again. I will try this new solution on the next.js example

**Comment by Munawwar** [comment]
Ok I managed to get next.js working with new interface. https://codesandbox.io/s/nextjs-with-zustand-354-forked-bryjr?file=/lib/store.js

Though once again I thought `createStore` would create store every time. So it is more like `createStoreOnce` or `createInitialStore`.

**Comment by dai-shi** [comment]
Thanks for confirming.

About naming, I thought about adding `Initial`, but thought maybe obvious. Let's wait and see if others report confusion.
