### ISSUE TITLE
Get store by id

### ISSUE THREAD

**Issue by karthikeyan676** [pmndrs/zustand#448]
I have one doubt can we get the zustand store by id?

Like we access the store using any id. 

Explanation:

I want to create a store per component

Let's say I used a store inside the `<Button />` component I'm using the button component many times and the store should create many times also should not share one store for all components. 
I want to use the first `<Button />` store in the second and vice versa using the Id. 

I can use context but the problem is I cannot access the store outside the `<Button />` component.

**Comment by dai-shi** [comment]
You can store stores in a map? `Map<string, Store>`

btw, multiple store pattern is expert use case. I would only recommend when stores are totally isolated.

**Comment by wolframkriesing** [comment]
@dai-shi why do you call multi-stores "expert use case"? I made good experience with it, and I feel it very well makes me see boundaries and data dependencies. And eventually it results in multiple stores to merge, but that is a decision I can delay.

**Comment by dai-shi** [comment]
There's no technical drawbacks. It's not flux-like, so usage drawbacks? Often people complain there's no way to dispatch an action to multiple stores. It's true because zustand is not designed so. So, the single store use case is primary. "expert" might be misleading for this one, maybe call it secondary use case.

**Comment by wolframkriesing** [comment]
Dispatching an action to multiple stores might be a hint that the things belong in one store, but that is just the question that code sometimes makes one ask. I am connecting stores without them knowing, e.g. by passing in an "afterUpdate()" callback, that will be executed after an update and that might interact with other stores, but I try to use that rarely.

**Comment by dai-shi** [comment]
Using a single store is the primary use case as `set` is designed so, but the library is unopinionated and using multiple stores is fine too.

**Comment by karthikeyan676** [comment]
Can you show me any boilerplate code to implement a store like this?

**Comment by dai-shi** [comment]
1. Map<string, Store>
2. single global store
3. component store

which one would you like? can you provide a small code snippet to play with?

**Comment by dai-shi** [comment]
> @dai-shi I was looking for something similar, I want to create same store object per component. I have ended up creating something like this: https://codesandbox.io/s/zustand-store-per-component-b4tx3n
> 
> Could you please take a look at it and provide suggestions if any?

It just looks like a normal usage. Nothing is wrong except that you shouldn't mutate existing state.
A fix: https://codesandbox.io/s/zustand-store-per-component-forked-2j89tm

**Comment by bharatpatil** [comment]
@dai-shi just for the sake of example, added a separate initialize method, which could be called inside the component to initialize the first state.

https://codesandbox.io/s/zustand-store-per-component-b4tx3n?file=/src/App.tsx

**Comment by bharatpatil** [comment]
@dai-shi - sorry for bothering you again, would you be able to take a look again? I have added an async counter example as well. Thank you.

https://codesandbox.io/s/zustand-store-per-component-b4tx3n?file=/src/App.tsx

**Comment by dai-shi** [comment]
I think you want to open a new discussion with a clear context so that people can help you.
