### ISSUE TITLE
.push when using immer as middleware does not cause a re-render

### ISSUE THREAD

**Issue by phaistonian** [pmndrs/zustand#449]
Hello,

Using `immer` as a middleware for zustand works great, however when using `.push` to add an item to an array a re-render does not take place.

Example:

```js
setState(state => {
  state.items.push(item);
});
```

The above does not work.

This does (i.e. triggers a re-render).

```js
setState(state => {
  state.items = [...state.items, item];
});
```

Any ideas?

Ps: `.push` is [immer's the recommended way of adding](https://immerjs.github.io/immer/update-patterns/#array-mutations) to an array .

**Comment by phaistonian** [comment]
Here's [a codesandbox](https://codesandbox.io/s/push-dvhyy?file=/src/App.js) to illustrate the issue.

**Comment by dai-shi** [comment]
It's how `immer` middleware works (patching `set` internally).

You would need something like this:
```js
const addFromSetState = () =>
  useStore.setState(produce((state) => {
    state.items.push(Date.now());
  }));
```

**Comment by phaistonian** [comment]
@dai-shi Alright. But, as seen in the sandbox, cloning and extending the array works — so does .push when used directly. 

I am wondering why those cases work fine and this does not.

Thank you.

**Comment by dai-shi** [comment]
If you clone an array, you get a new reference, so it detects as changed.
I'm not sure if I fully understand the question. Without the immer middleware, everything works as you expect?

**Comment by phaistonian** [comment]
This is what feels weird to me; When pushing _directly_ a re-render does take place.

![CleanShot 2021-07-05 at 07 05 04@2x](https://user-images.githubusercontent.com/796530/124416323-67eaba00-dd5f-11eb-8e51-cfbeacdab249.png)

**Comment by dai-shi** [comment]
I think if you patch `setState` too, it could probably be done. (not recommending, as it's confusing, maybe?)

```js
const immer = (config) => (set, get, api) => {
  api.setState = (fn) => set(produce(fn))
  return config((fn) => set(produce(fn)), get, api)
}
```

(tbh, middleware is confusing...)

**Comment by phaistonian** [comment]
It did work - thank you.

I thought `api.setState` was _just_ a reference_ to `set`, btw, that's why I did not try this approach.

And yes, middleware is a bit confusing indeed.

**Comment by phaistonian** [comment]
Ps: Can you explain why [this works?](https://codesandbox.io/s/no-immer-9gjce?file=/src/App.js) :)

**Comment by dai-shi** [comment]
Good point. It somewhat accidentally works.
```js
set((state) => {
  state.items = [...state.items, Date.now()];
  return undefined;
})
```
It's returning `undefined`, so `state = Object.assign({}, state, undefined)` will create a new state object which triggers re-render.
It's not recommended as it's mutating old state, which might cause issues with concurrent rendering in the future.

**Comment by dai-shi** [comment]
Closing as resolved.
