### ISSUE TITLE
onRehydrateStorage argument

### ISSUE THREAD

**Issue by MillerGregor** [pmndrs/zustand#451]
in v3.5.1 the persist middleware's `onRehydrateStorage` option provided the entire state as the argument.  

in 3.5.4 only the persisted data is returned in the argument.

I was relying on having the whole state, to use these options (as an example):

```javascript
const persistOptions = {
    name: my-storage',
    whitelist: ['persisted'],
    onRehydrateStorage: () => {
        return (state: FullState) => {
            state.setRehydrated(true);
        };
    },
};
```

Is this a deliberate change?  If so, I'll find another way to keep track of rehydration status.

thanks

**Comment by meinto** [comment]
We have this problem too. We keep track of our rehydration state through a middleware:

```ts
import {State, StateCreator} from 'zustand';

export interface RehydratedState extends State {
  rehydrated?: boolean;
  setRehydrated?: () => void;
}
export const rehydrated =
  <T extends RehydratedState>(config: StateCreator<T>): StateCreator<T> =>
  (set, get, api) => {
    const result = config(set, get, api);
    return {
      ...result,
      rehydrated: false,
      setRehydrated: () =>
        set(state => {
          state.rehydrated = true;
        }),
    };
  };
```

In our `createPersisted` helper we set the `rehydrated` flag of our persisted store in the `onRehydrateStorage` callback.

```ts
export const createPersisted = <T extends State>(
  config: StateCreator<T>,
  persistConfig: any,
) => {
  return create(persist(rehydrated(config), {
      ...persistConfig,
      onRehydrateStorage: () => (state: RehydratedState) => {
        if (!state.rehydrated) {
          state.setRehydrated!();
        }
      },
    }),
  );
};
```

**Comment by meinto** [comment]
If this is the new intended behavior it would be a breaking change and should be sheduled for the next major release according to semantic versioning.
