### ISSUE TITLE
zustand persist - actions inside nested object are undefined on rehydration

### ISSUE THREAD

**Issue by ColinKrist** [pmndrs/zustand#457]
Hi all - I use the pattern of wrapping all my actions in an 'actions' object. I wanted to use persistence for an easter egg state, but I noticed that when I would toggle the easter egg, refresh the page and try again I would get errors with the toggle being undefined.

Is this desired behavior? Moving the actions to a flat object and not in my 'actions' object solved the issue, I only did the actions object because I believe I saw it elsewhere. Are there other shortcomings of using that pattern?

```ts
interface EasterEggState {
    active: boolean;
    actions: {
        set: (value: boolean) => void;
        toggle: () => void;
    };
}

export const useEasterEgg = create<EasterEggState>(
    persist(
        (set, get) => ({
            active: false,
            actions: {
                set: (value) => set({ active: value }),
                toggle: () => set({ active: !get().active }),
            },
        }),
        {
            name: 'app.easteregg',
            version: 1,
        },
    ),
);
```

![image](https://user-images.githubusercontent.com/27971797/123206123-c15e0980-d480-11eb-96e7-377b72fdb3be.png)

**Comment by AnatoleLucet** [comment]
I believe [the spread](https://github.com/pmndrs/zustand/blob/master/src/middleware.ts#L381) overrides the state's `actions`.
We might need to refactor this to use a recursive merge.

For now, you can try to blacklist the `actions` property from being stored in the storage:
```ts
{
  name: 'app.easteregg',
  version: 1,
  blacklist: ['actions'],
},
```

**Comment by AnatoleLucet** [comment]
I'll close this for now.
In the next version, you'll be able to give you own merge function to, for e.g., deep merge the stored state with the current one (see #466).
Meanwhile, the `blacklist` is still a viable option. FYI, nested paths (which could definitely be useful in this kind of case) are currently worked on in #463.

**Comment by amiellion** [comment]
@namansamra you may try this, i think it worked for me:

i used lodash's merge function
```javascript
   import { merge } from "lodash"; 
```
``` javascript
 // inyour zustand persistsettings
 {
      name: "useAuthStore",
      merge: (persistedState, currentState) => { // add this part
          return merge({}, currentState, persistedState);
        } 
    }
```
