### ISSUE TITLE
zustand persist with indexedDB bug

### ISSUE THREAD

**Issue by nothing628** [pmndrs/zustand#458]
Before explain the problem, here is library that I used to reproduce the bug.
- react@17.0.2
- react-dom@17.0.2
- idb-keyval@5.0.6
- zustand@3.5.4

And this code for creating the state
```javascript
import create from "zustand";
import { persist } from "zustand/middleware";
import { get, set } from "idb-keyval";

export const IDBStorage = {
  getItem: async (name) => {
    // Exit early on server
    if (typeof indexedDB === "undefined") {
      return null;
    }

    const value = await get(name);

    console.log("load indexeddb called");
    return value || null;
  },
  setItem: async (name, value) => {
    // Exit early on server
    if (typeof indexedDB === "undefined") {
      return;
    }
    set(name, value);
  },
};

export default create(
  persist(
    (set, get) => ({
      products: [],
      clear: () => {
        console.log("clear called !");
        set({
          products: [],
        });
      },
      loadProducts: async () => {
        console.log("load called 1");
        const response = await fetch(
          "https://hub.dummyapis.com/products?noofRecords=10&idStarts=1001&currency=usd"
        );
        const products = await response.json();
        const current_products = get().products;

        console.log("load called 2", products);

        // In actual scenario, there is pagination mechanism
        // but, since I call `clear` method first, the `current_products` should be empty
        set({
          products: [...current_products, ...products],
        });
      },
    }),
    {
      name: "app_products",
      getStorage: () => IDBStorage,
    }
  )
);
```
and this the react component code
```jsx
import "./App.css";
import useAppStore from "./store";
import { useEffect } from "react";
import shallow from "zustand/shallow";

function App() {
  const [products, clear, loadProducts] = useAppStore(
    (state) => [state.products, state.clear, state.loadProducts],
    shallow
  );

  useEffect(() => {
    clear();
    loadProducts();
  }, [clear, loadProducts]);

  return (
    <div className="App">
      <header className="App-header">
        {products.map((product) => (
          <li key={product.id}>{product.name}</li>
        ))}
      </header>
    </div>
  );
}

export default App;
```
You can clone the project at [nothing628/react-zustand-test](https://github.com/nothing628/react-zustand-test)
First, this code just doing clear product list and then load new product list from API. So at first time running the application, zustand don't have any data to `rehydrate` and application running correctly.

But, at second time user reload the webpage, this is happen
![686090ae-1d69-43e1-bdbd-136e3832f771](https://user-images.githubusercontent.com/15797914/123218574-18ea8c80-d4f6-11eb-95b3-5a17a9bc8dc9.png)
![Screenshot from 2021-06-24 14-12-12](https://user-images.githubusercontent.com/15797914/123219170-cbbaea80-d4f6-11eb-9658-0ef45ceb1a5f.png)

I think rehydrate procedure should be called first before any method in the store called. Please help me to check if this is bug or not.

Note : Sorry if there are spelling mistakes in my writing. I hope you understand what I mean

**Comment by AnatoleLucet** [comment]
I'm not sure to understand what's the issue here. Is it the fact that `current_products` is not empty after calling `clear()`?

**Comment by nothing628** [comment]
yes, actually `current_products` is empty after calling `clear()`, but after waiting response from API, the middleware `persists` overwrite the state and makes `current_products` not empty

**Comment by AnatoleLucet** [comment]
This is caused by the async storage.
Once #455 is released, you'll be able to call `clear()` from within the `onRehydrateStorage` option using the `state` argument.

Though I don't really understand why you'd want to clear the stored data on each page load. Why use the persist middleware at all?

**Comment by AnatoleLucet** [comment]
You can also call `loadProducts()` from within `onRehydrateStorage`. Which is not ideal, but again, this use case seems pretty odd to me.

**Comment by nothing628** [comment]
Let's say I change `loadProducts` become like this. and just call `loadProducts`
```javascript
loadProducts: async () => {
        const current_products = get().products;

        if (current_products.length == 0) {
          const response = await fetch(
            "https://hub.dummyapis.com/products?noofRecords=10&idStarts=1001&currency=usd"
          );
          const products = await response.json();

          set({ products: products }));
        }
      },
```

The result is the application detect that product is empty and make unnecessary request to the server because async storage not finish moved the state. I think there is race condition between async storage and my action 🤔

**Comment by nothing628** [comment]
I think I will close this issue, because this problem caused by race condition between API call and Rehydrate session. By delaying API call, it will solve my problem. Thanks 👌

**Comment by Ashish50514561** [comment]
Hi I am using idbkeyval for persisting data to indexeddb but everytime i refresh the hydration is not done on the persisted data instead iam getting initial states ,please guys help me out , this is my store and i am not calling any setter function on initial render.




import { Mutate, State, StoreApi, create } from "zustand";
import { persist, createJSONStorage, StateStorage } from "zustand/middleware";
import saveToLocalStorage from "./components/localStorage";
// import { db } from "./db";
import { get, set, del } from "idb-keyval";
type StoreWithPersist = Mutate<StoreApi<State>, [["zustand/persist", unknown]]>;

export const withStorageDOMEvents = (store: StoreWithPersist) => {
  const storageEventCallback = (e: StorageEvent) => {
    if (e.key === store.persist.getOptions().name && e.newValue) {
      store.persist.rehydrate();
    }
  };

  // window.addEventListener("storage", storageEventCallback);

  // return () => {
  //   window.removeEventListener("storage", storageEventCallback);
  // };
};

const storage: StateStorage = {
  getItem: async (name: string): Promise<string | null> => {
    console.log(name, "has been retrieved");
    console.log("here is data from storage", await get(name));
    const store = await get(name);
    // set(name, store);
    // console.log("parsed", JSON.parse(store));
    const x = JSON.stringify(store);
    console.log({ x });

    return x || null;
  },
  setItem: async (name: string, value: string): Promise<void> => {
    console.log(name, "with value", value, "has been saved", value);
    const x = (await get(name)) || null;
    console.log({ x, value });
    // if (x) {
    //   await set(name, { ...x, ...JSON.parse(value).state });
    // } else {
    await set(name, { ...JSON.parse(value).state });
    // }
  },
  removeItem: async (name: string): Promise<void> => {
    console.log(name, "has been deleted");
    await del(name);
  },
};

const useStore = create(
  persist(
    (set, get) => ({
      cat: "meow",
      bears: "hawwww",
      dataBase: false,
      check: null,
      _hasHydrated: false,

      setDataBase: (database: any) =>
        set((state: any) => {
          return { dataBase: database };
        }),

      increasePopulation: () =>
        set((state: any) => {
          // console.log(
          //   "deers",
          //   state.dataBase &&
          //     saveToLocalStorage(state.dataBase, { deers: "Josephine", age: 21 })
          // );
          return { cat: "i can also talk" };
        }),
      checkPopulation: () =>
        set((state: any) => {
          // console.warn(
          //   "bears",
          //   state.dataBase &&
          //     saveToLocalStorage(state.dataBase, { bears: "check", age: 21 })
          // );
          return { check: "i can talk" };
        }),

      inPopulation: () =>
        set((state: any) => {
          // console.warn(
          //   "name",
          //   state.dataBase &&
          //     saveToLocalStorage(state.dataBase, { name: "in", age: 21 })
          // );
          return { bears: "ialk" };
        }),
      removeAllBears: () => set({ bears: 0 }),
    }),
    {
      name: "food-storage", // unique name
      storage: createJSONStorage(() => storage),
      version: 1, // a migration will be triggered if the version in the storage mismatches this one

      skipHydration: true,
      onRehydrateStorage: (state) => {
        console.log("hydration starts");

        console.log({ state });
        // optional
        return (state, error) => {
          if (error) {
            console.log("an error happened during hydration", error);
          } else {
            console.log({ state }, "after hydration");

            console.log("hydration finished");
          }
        };
      },
    }
  )
);

module.exports = useStore;
