### ISSUE TITLE
Calling own store methods inside the store? 

### ISSUE THREAD

**Issue by Joshua-Chu** [pmndrs/zustand#460]
is there a way to call a method that you created inside a store, so that other methods can use it within the store? 

so basically I created a method to getUser inside the localStorage, an object will be returned containing the information about the user. 

and I want to create a new method inside the store that would get the fullname of the user stored in the localstorage. What I originally thought was I will call my getUser method, inside my new getFullname method. But, it seems that I can't find a way around it. Would this be considered a good practice? 

P.S. pls be gentle I'm a potato lol.

**Comment by dai-shi** [comment]
Is it something like this?

```jsx
import create from 'zustand'

export const useStore = create((set, get) => ({
  firstName: 'react',
  lastName: 'hooks',
  getFirstName: () => get().firstName,
  getLastName: () => get().lastName,
  getFullName: () => get().getFirstName() + ' ' + get().getLastName(),
}))
```

**Comment by Joshua-Chu** [comment]
Yes it does look something like that! Oh thank you so much this has been very insightful. I did not know that a get argument can be given, this is cool! Thank you for being responsive!
