### ISSUE TITLE
IE 11 not working with > v3.5.2

### ISSUE THREAD

**Issue by adrhumphreys** [pmndrs/zustand#461]
Hey team,

Looks like the generator jazz that was removed in https://github.com/pmndrs/zustand/releases/tag/v3.5.3 and then added back in https://github.com/pmndrs/zustand/releases/tag/v3.5.4 has stopped IE11 working

I've currently got it set in my webpack config like so:
```javascript
// Zustand in IE land, need to specify that we're using the cjs and not esm
// https://github.com/pmndrs/zustand/issues/354#issuecomment-816534766
{
  resolve: {
    alias: {
      zustand: path.resolve(__dirname, "node_modules/zustand/index.js"),
    },
  },
};
````

And this works in 3.5.2 but not for any of the later versions.

Worth mentioning that I could be missing some key detail in how I'm meant to use this library with IE11 support

Thanks ❤️

**Comment by dai-shi** [comment]
Hi, thanks for chiming in, and sorry for the inconvenience.

Well, the incompatibility in v3.5.3 was just my bad, and v3.5.4 is more or less a hot fix.
Let me see what we can do, taking some more time.

Notes to anyone who would like to tackle this issue.
What we want is to create a cjs bundle without babel-runtime, that works for ie11.
(I feel like I would hand transpile the generator code, which is just a backward compatibility for v2 api.)

Now, @adrhumphreys is here, we can do some experiments and find a solution. (I don't have access to ie11 and can't try it alone.)

**Comment by adrhumphreys** [comment]
@dai-shi if you don't mind spending some time to sort it out, it looks like you can get a free membership to Browser stack since your project is open source over here: https://www.browserstack.com/open-source
