### ISSUE TITLE
Await store function from function in same store

### ISSUE THREAD

**Issue by icecapp** [pmndrs/zustand#467]
I would like to compose a store function using another (async) function

```js
const useContactsStore = create((set, get) => ({
  contacts: [],
  fetchContacts: async () => {
    const contacts = await Contacts.getAll();
    set({ contacts });
  },
  setupContacts: async () => {
    (...)
    const { fetchContacts, contacts } = get();
    await fetchContacts();
    console.log('contacts from other function: ', contacts);
    console.log('contacts inline: ', await Contacts.getAll());
```

In this example, the first log returns an empty array while the second succeeds and returns the request result. 

I understand `fetchContacts` doesn't seem to return a Promise.

How would you go about this?

**Comment by dai-shi** [comment]
Please try this.
```diff
-     const { fetchContacts, contacts } = get();
-     await fetchContacts();
-     console.log('contacts from other function: ', contacts);
+     await get().fetchContacts();
+     console.log('contacts from other function: ', get().contacts);
```

**Comment by icecapp** [comment]
I tried that and it works, thank you!

However this seems like a caveat. Could you please explain why the first version doesn't work? 

Without trying to understand the internals of zustand, it seems to me that both versions, from a js standpoint are equivalent?

**Comment by dai-shi** [comment]
From a js standpoint, it's different.

You can try this too:
```js
    const { fetchContacts } = get();
    await fetchContacts();
    const { contacts } = get();
    console.log('contacts from other function: ', contacts);
```

Notice the state is immutable object.
```js
let state = { contacts: [] }
const get = () => state
const set = (partial) => { state = Object.assign({}, state, partial) }
```

**Comment by dai-shi** [comment]
Closing as answered.
