### ISSUE TITLE
Using zustand/middleware warns about enabling devtools in tests

### ISSUE THREAD

**Issue by timkindberg** [pmndrs/zustand#47]
I'm getting superfluous warnings during tests:
```
  ● Console

    console.warn node_modules/zustand/middleware.cjs.js:50
      Please install/enable Redux devtools extension
    console.warn node_modules/zustand/middleware.cjs.js:50
      Please install/enable Redux devtools extension
    console.warn node_modules/zustand/middleware.cjs.js:50
      Please install/enable Redux devtools extension
    console.warn node_modules/zustand/middleware.cjs.js:50
      Please install/enable Redux devtools extension
    console.warn node_modules/zustand/middleware.cjs.js:50
      Please install/enable Redux devtools extension
```
Because obviously it's not finding devtools. Maybe we can either disable this warning completely (I'd be fine with that), or put it behind a `if (NODE_ENV === 'development')` check or something.

**Comment by JeremyRH** [comment]
I've tested this and it should be fixed with 2.0.0.

**Comment by mjcarnaje** [comment]
![image](https://user-images.githubusercontent.com/65398905/120604118-486e2200-c47f-11eb-98a3-6d2a83fc956e.png)

**Comment by aquibbaig** [comment]
this is not fixed even in v3.6

**Comment by coltanium13** [comment]
Its not even fixed in v3.7. is it fixed in v4? i have enabled: process.env.NODE_ENV === 'development', but it still throws this warning when running tests, even though the process.env.NODE_ENV is 'test'

 [zustand devtools middleware] Please install/enable Redux devtools extension

**Comment by coltanium13** [comment]
> Its not even fixed in v3.7. is it fixed in v4? i have enabled: process.env.NODE_ENV === 'development', but it still throws this warning when running tests, even though the process.env.NODE_ENV is 'test'
> 
> [zustand devtools middleware] Please install/enable Redux devtools extension

**Comment by JeremyRH** [comment]
I'll reopen the issue.

**Comment by JeremyRH** [comment]
The README states:

> If you wish to disable devtools (on production for instance). You can customize this setting by providing the enabled parameter:
`devtools(..., { enabled: false, ... })`

So I'm guessing this will solve the issue:
```js
devtools(..., { enabled: process.env.NODE_ENV === 'development', ... })
```

**Comment by coltanium13** [comment]
No, in v3 it does not resolve the issue. During tests it still tries to
load the dev tools, even though the environment is 'test'. However if you
upgrade to v4, it seems to work as expected. It must be some issue with the
v3 dev tools enabled logic.

-Colton

**Comment by clayrisser** [comment]
I get this warning everywhere.

I get the warning in storybook.

I get the warning in nextjs server side.

I get the warning in nextjs web.

I get the warning in Expo on web, android, and ios.

I get this warning in my tests.

I get this warning even when I'm using redux devtools in my browser.

Can you please provide an option to disable this warning. It is very annoying.

**Comment by dai-shi** [comment]
Please specify the `enabled` option. `true` or `false`, not `undefined`.

https://github.com/pmndrs/zustand/blob/dfa779b14d515730d8f91a1020ada6e75386c059/src/middleware/devtools.ts#L127

**Comment by coltanium13** [comment]
Also, the enabled does not seem to work right before v4. I upgraded to v4
and it seems to work now. So make sure you are upgraded to v4.

-Colton

**Comment by clayrisser** [comment]
I want it enabled, but I want to disable the warning.

**Comment by dai-shi** [comment]
If you see the warning, it's no-op. So, it behaves the same as `enabled: false`.

https://github.com/pmndrs/zustand/blob/dfa779b14d515730d8f91a1020ada6e75386c059/src/middleware/devtools.ts#L229

Maybe you can specify `enabled: Boolean(window.__REDUX_DEVTOOLS_EXTENSION__)`.

**Comment by clayrisser** [comment]
Thansk @dai-shi that's what I ended up doing.

**Comment by dai-shi** [comment]
If anyone needs further help, please open [a new discussion](https://github.com/pmndrs/zustand/discussions/new/choose).
