### ISSUE TITLE
How do Toggle using Zustand

### ISSUE THREAD

**Issue by thecodeclimber** [pmndrs/zustand#472]
I have created the following store using Zustand:  

```
import create from "zustand"

const useStore = create((set) => ({
  show: false,
  toggleShow: () => set((state) => ({ show: !state.show })),
}))
```

I assumed that this would be the correct way to toggle the value of `show`.  However, typescript is not happy -- it has a red squiggly line underneath the `show` in `!state.show` with the following error message:

```
Property 'show' does not exist on type 'object'.ts(2339)
any
```

Any idea why I am getting that error message and how I can properly set up a toggle function using Zustand?

Thanks.

**Comment by lodisy** [comment]
You may need to declare the state type:

```
type State = {
    show: boolean
    toggleShow: () => void
}

const useStore = create((set) => ({
  show: false,
  toggleShow: () => set((state:State) => ({ show: !state.show })),
}))


```

**Comment by thecodeclimber** [comment]
This is the solution that I came up with which seems to work (that is, all of the typescript errors went away, I haven't had a chance to test it yet):

```
import create from "zustand"

interface NavbarState {
  show: boolean
  toggleShow: () => void
  showOn: () => void
  showOff: () => void
}

const useStore = create<NavbarState>((set) => ({
  show: false,
  toggleShow: () => set((state) => ({ show: !state.show })),
  showOn: () => set((state) => ({ show: true })),
  showOff: () => set((state) => ({ show: false })),
}))

export default useStore
```
