### ISSUE TITLE
feature request: option for useStore.subscribe fire once on initialisation

### ISSUE THREAD

**Issue by funwithtriangles** [pmndrs/zustand#475]
Currently `useStore.subscribe` only fires when the subscribed part of the store changes. It would be useful if there was an option to force the function to fire once upon initialisation. Maybe I'm missing something, here's an example:

```javascript
useEffect(() => {
    // I don't want to have to repeat myself up here just for initialisation
    const { position, rotation } = getSceneObject(props.id)(useStore.getState())
    target.current.position.set(position[0], position[1] - 3, position[2])
    plane.current.position.set(...position)
    plane.current.rotation.set(rotation[0], Math.PI, 0)

    return useStore.subscribe(
      ({ position, rotation }: SceneObject) => {
        target.current.position.set(position[0], position[1] - 3, position[2])
        plane.current.position.set(...position)
        plane.current.rotation.set(rotation[0], Math.PI, 0)
      },
      (state) => getSceneObject(props.id)(state)
    )
  }, [props.id])
````

**Comment by dai-shi** [comment]
I'm not sure if this is what you want, but it's often the pattern/technique to run callback once after subscription in useEffect.
```js
useEffect(() => {
  const callback = ...
  const unsubscribe = subscribe(callback)
  callback()
  return unsubscribe
}, [])
```
This is not a unique technique for zustand, but say react-redux does the same.

**Comment by funwithtriangles** [comment]
That's neater for sure, thanks. However I'm still having to manually get state for the initial callback:

```javascript
useEffect(() => {
    const callback =  ({ position, rotation }: SceneObject) => {
      target.current.position.set(position[0], position[1] - 3, position[2])
      plane.current.position.set(...position)
      plane.current.rotation.set(rotation[0], Math.PI, 0)
    }

    const initialState = getSceneObject(props.id)(useStore.getState()
    callback(initialState)

    return useStore.subscribe(
      callback,
      (state) => getSceneObject(props.id)(state)
    )
  }, [props.id])
```

**Comment by dai-shi** [comment]
Oh, I see, because it's a scoped subscription (= slice listener). It makes sense.
Maybe we could add a forth option for the scoped subscription.

At the same time, I feel like it would be nice if we could make subscribeWithSelector more pluggable. It's a bit confusing to add more options for the normal subscribe (no selector) which react hook uses.

**Comment by funwithtriangles** [comment]
Well I had no idea bout 'subscribeWithSelector`, it's not in the docs! Can you give an example use case?

**Comment by drcmda** [comment]
maybe we should make it flush once outright? you subscribe and it's guaranteed to call back. i also think that would make so many things easier though i am not certain about the breaking change since the callback definitively can have side effects (though even if, i wonder what kind of back end or listener wouldn't be interested in initial state).

**Comment by dai-shi** [comment]
sorry, `subscribeWithSelector` is internal function name in code. It's `subscribe` with selector/equalityFn.

> i'm not sure why this wasn't considered for subscribe as well.

because the hook use `subscribe` on mount, and it's tricky to handle the initial render. initial callback blindly would not be desired. (but, the real reason would be to be consistent with redux.)

**Comment by drcmda** [comment]
ah right i forgot about the internals but now it comes back. could we maybe introduce some kind of a flush that just calls listeners? now that you mention redux, before zustand i did face this exact problem in a big redux app.

```jsx
const useStore = create(...)

useStore.subscribe(console.log, sel)
useStore.flush() // calling all listeners no matter what
```

?

**Comment by dai-shi** [comment]
`useStore.flush()` is an interesting idea.
"no matter what" doesn't hold in this case, thought. selector/equalifyFn prevents invoking listeners, without changing the behavior.
if we were ok to change the behavior, i would just like to fire once for `subscribeWithSelector`.

**Comment by funwithtriangles** [comment]
I think changing the behaviour doesn't seem like a huge issue and I was half expecting it to behave this way when I first tried it. For instance, when you "subscribe" to dependencies with a `useEffect` hook, the hook still fires initially, it doesn't wait for those dependencies to change. Ultimately, we want to respond to every version of that piece of state, *including* the first one.

**Comment by dai-shi** [comment]
@funwithtriangles note that when i mean to change the behavior, it's only for `subscribeWithSelector`. So, the behavior will be different from subscribe without selector.

**Comment by funwithtriangles** [comment]
If I understand correctly, my example is using a selector so the behaviour would change, so I'd no longer need to initially call the callback function.

**Comment by dai-shi** [comment]
yes, that's correct.

**Comment by dai-shi** [comment]
I revisited this and changed my mind. I don't think we should change the library for this. It would add extra complexity or inconsistency.

So, I would suggest solving this on user end. One idea would be a middleware.

```js
const fireOnce = (config) => (set, get, api) => {
  const savedSubscribe = api.subscribe
  api.subscribe = (listener, selector, equalityFn) => {
    const unsubscribe = savedSubscribe(listener, selector, equalityFn)
    if (selector) {
      listener(selector(get())) // fire once
    }
    return unsubscribe
  }
  return config(set, get, api)
}
```

Usage:
```js
const useStore = create(fireOnce((set) => ({
  bears: 0,
  increasePopulation: () => set(state => ({ bears: state.bears + 1 })),
  removeAllBears: () => set({ bears: 0 })
})))
```

I can help if it doesn't work as expected.

Closing this but feel free to add comments.

**Comment by timothyallan** [comment]
Just dropping in my 2c here to think about for potential future dev: I use this feature all the time in MobX. They have optional params you can pass into the subscribe function, one is called `fireImmidiately`, which does exactly what it sounds like.

**Comment by ycmjason** [comment]
In case anyone need an idea for firing a subscribe immediately. Here's another idea:

```ts
const fireImmediately = <T,>(fn: (t: T) => void, initialData: T): ((t: T) => void) => {
  fn(initialData);
  return fn;
};

bearStore.subscribe(
  fireImmediately(
    bearState => {
      ...
    },
    bearStore.getState(),
  ),
);
```
