### ISSUE TITLE
createContext's useStore type are not complete?

### ISSUE THREAD

**Issue by wadamek65** [pmndrs/zustand#481]
Seems like types of `useStore` are not really consistent with the usual `useStore` hook created by `create` function. Due to the fact there is only one call signature it doesn't infer the store's types correctly. Example below:

```ts
const {Provider, useStore} = createContext<SlideshowStore>();
const store = useStore(); // store is of `unknown` type
```

I have worked around it like this:

```ts
const {Provider, useStore, useStoreApi: getStoreApi} = createContext<SlideshowStore>();
const useSlideShow: UseStore<SlideshowStore> = Object.assign(useStore, getStoreApi());
```

Is this an oversight or was this done on purpose? If this is something that could be improved I am willing to work on this and submit a PR.

**Comment by dai-shi** [comment]
Oh, no. This is unexpected for me.

https://github.com/pmndrs/zustand/blob/726584ccb0fc1dd98f8d073b226aa34cf39aa0a9/tests/context.test.tsx#L23
I added `{count * 1}` in the test to detect this, but `count` is `any` not `unknown`...

Maybe, #447 broke the typing?

Yes, please go ahead and work on it. Thanks.

**Comment by wadamek65** [comment]
@dai-shi I've created a very simple reproduction and it also seems to be of type `unknown` [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAYygUwIY2QYQgOwwD3gDMoIQ4ByALwFcBnGVHAEwHoFcCYKAoHmAJ5hkcALICAyjGgiAvHADePOHFQAuOAGYeAXx4ccDRXHrIpMuDrjykaDNjzJCAHnHmUAPgAUASj4GjBgt5U3dkXx4gA).

I will try and submit a PR in the upcoming days. 😄
