### ISSUE TITLE
What's the difference between zustand and valtio?

### ISSUE THREAD

**Issue by meglio** [pmndrs/zustand#483]
It's not obvious by just looking at examples what are the main differences? Both can updates objects and subscribe to those updates.

**Comment by dai-shi** [comment]
## The major difference is: zustand is immutable state model, whereas valtio is mutable state model.

```js
import create from 'zustand'

// intentionally show non-hook deep usage
const store = create(() => ({ obj: { count: 0 } }))
store.setState((prev) => ({ obj: { count: prev.obj.count + 1 } })
```
```js
import { proxy } from 'valtio'

import state = proxy({ obj: { count: 0 } })
state.obj.count += 1
```

## Another difference is render optimization.

```js
import create from 'zustand'

const useStore = create(() => ({
  count1: 0,
  count2: 1,
}))

const Component = () => {
  const count1 = useStore((state) => state.count1) // manual render optimization with selector
  // ...
}
```
```js
import { proxy, useSnapshot } from 'valtio'

const state = proxy({
  count1: 0,
  count2: 0,
})

const Component = () => {
  const { count1 } = useSnapshot(state) // automatic render optimization with property access
  // ...
}
```

**Comment by meglio** [comment]
Great, thank you!

Now that it's easier to see the difference, do you mind also explaining which to prefer over another in which cases, based on your experience? Would make for a great entry in FAQ, or even as a separate article.

**Comment by dai-shi** [comment]
If someone comes from redux or likes react's natural immutable updates, zustand would fit well.
If someone is from vue/svelte/mobx, or new to JS and/or react,  valtio's mutable model would fit well.

zustand is a very thin library and never behaves unexpectedly. valtio comes with proxy magic.

One thing I suggest most of the time: if someone use zustand + immer, my recommendation is to try valtio instead.

**Comment by dai-shi** [comment]
Created a wiki page: https://github.com/pmndrs/zustand/wiki/Difference-between-zustand-and-valtio
I will add a link in readme.md

**Comment by chrisdrackett** [comment]
@dai-shi can you expand on why you suggest valitio over zustand + immer?

**Comment by dai-shi** [comment]
I suggest considering valtio if they haven't, for people who consider zustand with immer middleware. If people prefer the mutable state model, it's a built-in feature in valtio, whereas zustand is basically on the mutable state model. But, if people like the immutable model as base, and use immer mutable model with mental model **switch** (btw, I think immer does it very well with the notion of "draft"), they can stay with zustand+immer for sure.

**Comment by drcmda** [comment]
@chrisdrackett someone on twitter mentioned ramdas mergeDeepRight https://ramdajs.com/docs/#mergeDeepRight which imo is a formidable non magic way to deal with nested props without having to turn everything into a proxy. i prefer that as well over immer in zustand. like @dai-shi said, zustand is mostly for people like that plain js no magic with safe assumptions. immer arguably already blows that ideal. though it's perfectly fine to use it with zustand.

**Comment by chrisdrackett** [comment]
I think `mergeDeepRight` looks very promising and I want to look into it more. The one area I've had issues wrapping my head around with Zustand+Immer is what to do when I get a full object via a subscription to my server. I feel like in theory  `mergeDeepRight` solves this easily while I have no idea what to do with it with Immer itself.

**Comment by dai-shi** [comment]
mergeDeepRight works well. It's still a bit verbose, but acceptable.
I tried to use it for replacing an array item, which doesn't look very comfortable.
Are there any other functions in ramda for manipulating an array?
https://codesandbox.io/s/zustand-normal-immer-optics-updating-ynn3o?file=/src/App.tsx

**Comment by chrisdrackett** [comment]
is it possible to use these things together? like using Immer for setting an item in an array and `mergeDeepRight` for doing a complex update?

**Comment by dai-shi** [comment]
It's up to you. I just want to learn if there's any option.

**Comment by chrisdrackett** [comment]
me too!

**Comment by dai-shi** [comment]
I made something I'm comfortable with, with rambda.
https://twitter.com/dai_shi/status/1456564194338291745

**Comment by chrisdrackett** [comment]
this looks better for sure, but does it work with typescript?

**Comment by dai-shi** [comment]
yes! everything in the example is typed.

btw, I made docs (a wiki page): https://github.com/pmndrs/zustand/wiki/Updating-nested-state-object-values

**Comment by dsacramone** [comment]
Immer usage looks so much more succinct. Why would you use rambda, over immer?

**Comment by dai-shi** [comment]
It's about mental model.
Immer is mutation style. If I were to use mutation style, I'd use valtio.
So, that means, in zustand, I prefer immutable style, like rambda.
Bundle size may probably be different too, if that matters.

**Comment by aestheticsdata** [comment]
> It's about mental model. Immer is mutation style. If I were to use mutation style, I'd use valtio. So, that means, in zustand, I prefer immutable style, like rambda. Bundle size may probably be different too, if that matters.

I use immer with zustand (I used immer with Redux too), so zustand immutable VS valtio mutable, I get it, just a matter of personal preference, but recently the focus was on immutability. So in the end, what is better immutability or mutability ?? Is this just a matter of personal preference ?

**Comment by dai-shi** [comment]
re: immutable vs. mutable

At the language level, JS is on mutable model. Ensuring immutability in JS is not easy, and what we do is to educate the patterns like don't do `Array.splice` but do `Array.slice`. (Or, do `Object.freeze` on all objects.) React is more or less based on immutable model. Immutable model is efficient for change detection. Using proxies allows change detection too. Which is more efficient would depend on how it's used.

**Comment by aestheticsdata** [comment]
> Immutable model is efficient for change detection. Using proxies allows change detection too. Which is more efficient would depend on how it's used.

@dai-shi it's really hard to know which lib to use between zustand and valtio. "Which is more efficient would depend on how it's used" ? But your answer seems to mean that whatever you use between zustand and valtio is in the end the same. What do you mean exactly by "on how it's used" ? If we can achieve the same result with an immutable approach or mutable approach, why bother emphasize about immutability ? Disclaimer: I've used a lot immutability in Javascript for years.

**Comment by dai-shi** [comment]
If you are familiar with immutable style, why would you choose mutable style? zustand sounds like a perfect fit.

> in the end the same.

Overall, I think so.

> on how it's used

Let's see the simplest example.

```js
const immutableState1 = { count: 0 }
const immutableState2 = { count: immutableState1.count + 1 }
const immutableState3 = { count: immutableState2.count + 1 }
// then use immutableState3 to render in React
// the intermediate immutableState2 isn't used and GC'd

const mutableState = { count: 0 }
++mutableState.count
++mutableState.count
// then render in React
// no intermediate object to GC
// But this style requires proxies to detect changes for React
```
So, in this case, the overhead is GC vs Proxy. But, doesn't it sound just trivial? Or premature optimization scenario?

> why such an emphasis on immutability ?

I'm not sure what you mean by this. React is based on immutability, right?

**Comment by aestheticsdata** [comment]
@dai-shi ok I'll stick with zustand. Thanx.

**Comment by dsacramone** [comment]
A little old, but curious - does Valtio solve the issue with deriving state whereas Zustand has issue? Does Valtio do derive out of the box, so to speak? Lastly, does one have better performance?

**Comment by dai-shi** [comment]
> does Valtio solve the issue with deriving state whereas Zustand has issue?

Yes, theoretically.

> Does Valtio do derive out of the box, so to speak?

Yes, theoretically, but it requires decent JS knowledge.

> Lastly, does one have better performance?

Yes, theoretically, but performance is hard to discuss without measuring specific cases.

See more: https://github.com/pmndrs/valtio/blob/baba86789712f5a0857b2b7580248ffc0f8934e0/docs/guides/computed-properties.mdx

**Comment by cademis** [comment]
I'm very much a junior javascript developer using react/nextjs. I've been using Jotai for the last 6 months but a recent project has required some more complex logic over the state / setState style of Jotai. I struggle with the immutable syntax style of zustand but i wrote this in my store.ts file and this all makes sense to me. Is this a suitable pattern for using valtio?

```
import { proxy } from "valtio";

// Define the State type
type State = {
  selectedProjectId: string | null;
  selectedProjectLayoutPlanId: string | null;
  selectedZoneId: string | null;
  pointLoad: string | null;
};

// Define the Actions type
type Actions = {
  setSelectedProjectId: (id: string | null) => void;
  setSelectedProjectLayoutPlanId: (id: string | null) => void;
};

export const state = proxy<State>({
  selectedProjectId: null,
  selectedProjectLayoutPlanId: null,
});


export const actions: Actions = {
  setSelectedProjectId: (id: string | null) => {
    state.selectedProjectId = id;
    state.selectedProjectLayoutPlanId = null;   
  },
  setSelectedProjectId: (id: string | null) => {
    state.selectedProjectLayoutPlanId = id;   
  },
};
```

```
const ProjectsTable = () => {
  const { setSelectedProjectId } = actions;
...
}

const ProjectLayoutPlanTable = () => {
  const { setSelectedProjectLayoutPlanId } = actions;
...
}
```
