### ISSUE TITLE
Multiple components, one store with a list of items - how to let the initiator component switch the currently selected item to a newly created one?

### ISSUE THREAD

**Issue by meglio** [pmndrs/zustand#487]
Is there an easy way to achieve the following:

Setup:
* one store, with an array `L` and an action `addToL()`
* two components, `A` and `B`, each displaying list L in a dropdown
* both components have a Plus button (+), which calls `addToL()`

Scenario:
Now, imagine I click on the Plus button in component `A`. The `addToL()` action does some ajax and then eventually adds to the list `L`.

Goal:

I need the dropdown box in `A` to switch to the newly created item in array `L` as soon as it is created.

I don't want dropdown box in `B` be affected in any way.

====

A simple analogy would be a split editor, each showing a list of files available in a dropdown list. When I create a new file, and editor A is active, I expect the new file to become selected and in edit mode in A, but not in B.

B might be showing another file, and I don't want both A and B to switch to the newly created file.

Does my explanation make sense?

**Comment by dai-shi** [comment]
It sounds to me that the local wip list is only for a component, so I'd make it a component state. It's like an optimistic update.

```js
const ComponentA = () => {
  const { list, addToList } = useStore()
  const [wipList, setWipList] = useState()
  const add = async (something) => {
    setWipList([...list, something])
    await addToList(something)
    setWipList(undefined)
  }
  return (wipList || list).map(item => <Item item={item} />)
}
```

**Comment by meglio** [comment]
Hm, I might have failed in explaining the case.

What I need is a list in a store accessed by multiple components. Each component shows the list in a dropdown box AND can add a new item to the list (by calling a store's callback). Once an item is added, only the component who added it should automatically select it in its dropdown box. Other components will only update the items in their dropdown lists, but not change which item is selected.

**Comment by dai-shi** [comment]
OK, but then isn't the idea similar? Use useState for the selection, not useStore? If it's not the selection, it can be the UUID, or any identifier. You might need to create a toy in codesandbox so that we can play with. Or, maybe someone have some ideas.

**Comment by meglio** [comment]
Correct, I do use a store to only hold the list, and useState to hold current selection per component.

The issue is that the component does not know when a new item in the list gets created, what is the item, and who initiated that creation process.

**Comment by meglio** [comment]
My ugly solution that works is below. However, I'm still seeking for a more elegant / simpler way to address this problem.

-----

First, I need unique IDs for the component instances `A` and `B` from the examples above. So, I create a hook in file `useUniqueComponentId.js`:

```js
import {useRef} from "react";

let nextUniqueComponentId = 1;

export default function useUniqueComponentId() {
    const ref = useRef(null);
    if (ref.current === null) {
        ref.current = nextUniqueComponentId;
        nextUniqueComponentId++;
    }
    return ref.current;
}
```

Next, I add this to the component:

```js
const componentId = useUniqueComponentId();
```

In my store, I now have to record when a new element gets created successfully and who was the caller (= component id):

<img width="386" alt="image" src="https://user-images.githubusercontent.com/282177/125030361-2db84a00-e0ca-11eb-9146-5ae35e246961.png">

Finally, I can subscribe to the updates and change the selection in the dropdown box:

```js
// Subscribe to the event of when a new Ranking Configs item gets created. If this is us who created it, select it in the dropdown box.
    useEffect(() => {
        const unsub = useRankingConfigsStore.subscribe(
            ([lastNewRankingConfigUuidCreated, lastNewRankingConfigCallerId]) => {
                if (lastNewRankingConfigCallerId === componentId && lastNewRankingConfigUuidCreated !== selectedRankingConfigUuid) {
                    set_selectedRankingConfigUuid(lastNewRankingConfigUuidCreated);
                }
            },
            state => [state.lastNewRankingConfigUuidCreated, state.lastNewRankingConfigCallerId],
            shallow
        );
        return unsub;
    }, [componentId]);
```

Please note that it seems way too verbose for such a simple task. I hope we can come up with a better idea. Can we? :)

**Comment by dai-shi** [comment]
Hm, I don't think `useUniqueComponentId` is too ugly.
You can useStore with selector with the id, and you don't need `useEffect` and `subscribe`.
It would be less verbose.

I don't think this is a simple task and hope someone has some ideas too.

**Comment by meglio** [comment]
> You can useStore with selector with the id, and you don't need useEffect and subscribe.

Oh, could you please elaborate? I'd like to understand this approach.

**Comment by dai-shi** [comment]
Without understanding your code fully, I can convert it and it will look like this:
```js
    const selectedRankingConfigUuid = useRankingConfigsStore(useCallback(state => (
      state.lastNewRankingConfigCallerId === componentId &&
      state.lastNewRankingConfigUuidCreated || undefined /* or null? */
    ), [componentId]))
```

**Comment by meglio** [comment]
I think I now understand what you mean. This won't work because after creating this new item, the user can now select another one in the dropdown box, so there is a separate state (local to the component) for `selectedRankingConfigUuid`.

**Comment by dai-shi** [comment]
> if we had a way to supply a callback that the store would call once an action is complete.

```js
const useStore = create((set) => ({
  data: null,
  fetchData: async (url, cb) => {
    const response = await fetch(url);
    const data = await response.json();
    set({ data })
    cb('what is some data that is only known after it is completed?')
  }
}))
```

**Comment by meglio** [comment]
> what is some data that is only known after it is completed?

:) This contains fields of the newly created item; the fields are populated server-side based on the complex logic and some default values for columns in a database table.

Now, when the `cb()` is called, it will happen before the component is re-rendered, so the component won't see the updated store:

```js
fetchData: async (url, cb) => {

// ...

set({ data });
// the component cannot see these updated to the store until the `fetchData` function completes

cb(someData);
// cb() is called within the fetchData() function - the component that supplied this `cb` callback
// will not see the updated store 

}
// Now that the `fetchData` function has completed, react will start re-rendering components,
// and our component will see the updated state.
// But it's too late - we attempted to use `someData` while running the `cb()` callback,
// and the store did not have the new item at that time.
```

**Comment by dai-shi** [comment]
Oh, so it's a timing issue.

What I come up with is this. Not sure if it's an ideal solution.

```js
    const [selectedRankingConfigUuid, setSelectedRankingConfigUuid] = useState()
    const lastNewRankingConfigUuidCreated = useRankingConfigsStore(useCallback(state => (
    const selectedRankingConfigUuid = useRankingConfigsStore(useCallback(state => (
      state.lastNewRankingConfigCallerId === componentId && state.lastNewRankingConfigUuidCreated
    ), [componentId]))
    useEffect(() => {
      if (lastNewRankingConfigUuidCreated) {
        setSelectedRankingConfigUuid(lastNewRankingConfigUuidCreated)
      }
    }, [lastNewRankingConfigUuidCreated])
```
So, it becomes verbose. subscribe() might be better if it works.

You could also put selectedRankingConfigUuid in the global store with componentId, which may simplifies it. I would prefer keeping local state local though.

**Comment by meglio** [comment]
> subscribe() might be better if it works.

Has been working so far. But I don't like it -- too much code to solve a very little problem. I feel like a proper API would be very useful here. But I haven't come with a crystallized idea about the API signature and behavior yet.

My current workaround is the one I shared above - i.e. when I save the "last caller ID and last UUID of the item that got created".

You can probably too see and feel like this is a basic need and should be an API, and the verbose workaround is not in line with the quick and easy way of doing other things with this library. I really hope we can improve in this area.

**Comment by dai-shi** [comment]
Closing this as stale. If someone has ideas for better practices. Would love to continue exploring.

**Comment by meglio** [comment]
Hey @dai-shi , even if someone has ideas, they likely won't find this issue because it is now closed.

**Comment by dai-shi** [comment]
I saw many people found closed issues and commented, so not worried too much.
But, if it concerns you, we can move this to discussions. Would you like me to convert this, or you prefer creating a new discussion?

**Comment by meglio** [comment]
Let's leave it like it is here then... I don't know. From my experience, it will be equally lost in discussions and will be considered more like a phylosophycal design question rather than a practical question that need attention and action from the core library engineers. So if you ask me, I prefer to leave it as an issue.

**Comment by dai-shi** [comment]
On the other hand, while you are here, if we would dig this issue further, I would suggest you to create a minimal possible codesandbox to show the problem, and optionally how it could be solved without a library with just useState.

I'm not very confident if it's zustand specific issue or general React use case issue.

**Comment by meglio** [comment]
> I'm not very confident if it's zustand specific issue or general React use case issue.

It is so general that Facebook is working on a library to manage state shared by multiple independent components. Still not general enough?

With `useState` (and without context), I'd have to make the outermost page component store the shared state, and pass down every and each state element and callbacks for events and state manipulation down to all interested components. It's a super old problem that all state management libraries try to solve in one way or another. React native way of solving the problem (partially) is to use Context.

I'm not sure I understand what exactly is that makes it confusing to you? Could you elaborate please.

**Comment by meglio** [comment]
Example.

Imagine I have lawyers and postcodes. Each postcode can have multiple lawyers assigned to each postcode.

I have 3 components:

1. The map, showing all postcodes and mouse-hover popups listing lawyers at that postcode.
2. The lawyers table.
3. The overall statistics (how many lawyers, how many postcodes).

All 3 components use the same store.

However, for each user in the system I want to show different lawyers and postcodes. Therefore, I cannot share the state among all users. Each page load would start a fresh Zustand instance for that page.

In the same time, I want the state be shared between multiple isolated components on the same page.

Please note that it can be done through Context, of course. But then I have to solve other problems that Zustand solves out of the box. For example, what if I have 4th component that allows me to add new lawyer? It would add the lawyer to the store after a successful API call. I now want all the other 3 components to get notified of this addition.

As it can be seen, Zustand is a perfect solution for this use-case. The thing is, the API does not facilitate "starting from scratch" for every new page load, be it Next.js, create-react-app, or whatever (the framework does not matter).

**Comment by dai-shi** [comment]
> > I'm not very confident if it's zustand specific issue or general React use case issue.
> 
> It is so general that Facebook is working on a library to manage state shared by multiple independent components. Still not general enough?

I mean, if it's not a question specific to zustand, there would be a better place to ask.

> I'm not sure I understand what exactly is that makes it confusing to you? Could you elaborate please.

So, is this a problem that we want shared state for subtree but not using context? That's my confusion.

---
Thanks for the example.

> Please note that it can be done through Context, of course.

okay. good to know.

> For example, what if I have 4th component that allows me to add new lawyer?

Now, does this add the new one for all pages? Or, just the page that's open?

> But then I have to solve other problems that Zustand solves out of the box.

Maybe, I can ask differently, what's the problem zustand solves but not Context? I think extra re-renders, but is it only the problem we are referring?

Thanks for your patience. I'd like to understand the problem space, which I might have misunderstood.

**Comment by dai-shi** [comment]
To add a note, although it may have seemed that my attitude was a bit negative, it's not so.
If my current assumption were correct, the problem could be something close to what I felt.
I developed [jotai](http://github.com/pmndrs/jotai), because there's a conceptual limitation in zustand.
Later, we added `zustand/context` to cover it to some extent. It may feel like a workaround, but I think it's the best effort with zustand.
Hope that explains some background.

**Comment by meglio** [comment]
> Maybe, I can ask differently, what's the problem zustand solves but not Context? I think extra re-renders, but is it only the problem we are referring?

1) That, plus 2) subscriptions to updates, plus 3) subscriptions to partial data only.

> So, is this a problem that we want shared state for subtree but not using context? That's my confusion.

This only defines part of the problem. The other part is the state should not be shared between different users - in the case I described above, non-trivial workarounds were needed to artificially "reset" the state (which I believe could be part of API) - this happens  because Next.js API is within the stateful way of processing HTTP requests.

Please note that not all javascript applications are single-page applications with shared state on the server side. Same as not all JavaScript applications use JavaScript for backend. The case I describe arises when thinking "stateless" or non-javascript-backend.

Same as with web frameworks built with statically typed languages, like Java and Scala: some frameworks, like Play, promote the stateless applications, just like e.g. in most PHP applications nowadays, so I'd be getting a new instance of a store per HTTP request and that is not shared between users. By this I'm trying to say that, because JavaScript supports both stateful and stateless approaches (server-side state), the Zustand APIs should be able to accomodate both with ease. Does it make sense to you, or still bad description?

>> Please note that it can be done through Context, of course. But then I have to solve other problems that Zustand solves out of the box. For example, what if I have 4th component that allows me to add new lawyer? It would add the lawyer to the store after a successful API call. I now want all the other 3 components to get notified of this addition.

> Now, does this add the new one for all pages? Or, just the page that's open?

Just the page that's open. When the page is refreshed, the data is fetched and pre-populated from scratch - _for that specific user_. Just as I described the stateless applications concept above. The state is not persistent on the server-side. And even if we want to persist it, we would need to make sure it's isolated per user, which is much more work than just having a fresh new state per page render. Which is most people do in PHP, Ruby, etc (while still using JavaScript for frontend, optionally with React, optionally with Zustand).

**Comment by dai-shi** [comment]
> > Maybe, I can ask differently, what's the problem zustand solves but not Context? I think extra re-renders, but is it only the problem we are referring?
> 
>     1. That, plus 2) subscriptions to updates, plus 3) subscriptions to partial data only.

This sounds what `zustand/context` was developed for.
But, I'd admit we don't have enough examples to show the usage.

> Just the page that's open. When the page is refreshed, the data is fetched and pre-populated from scratch - _for that specific user_. Just as I described the stateless applications concept above. The state is not persistent on the server-side. And even if we want to persist it, we would need to make sure it's isolated per user, which is much more work than just having a fresh new state per page render. Which is most people do in PHP, Ruby, etc (while still using JavaScript for frontend, optionally with React, optionally with Zustand).

Are these about the issue with the combination with server-side? Or, is there still an issue with client-only?
I would like to solve the client-only issue in this issue discussion.

> Please note that it can be done through Context, of course. But then I have to solve other problems that Zustand solves out of the box.

Would it be possible for you to create a minimal working example (client-only) with Context? I would like to learn from it and have a better understanding of the pain.
