### ISSUE TITLE
Trying to migrate from React Context Api -> Stuck on "Rendered fewer hooks than expected..."

### ISSUE THREAD

**Issue by ke3pup** [pmndrs/zustand#490]
Hi guys,

I've been trying to migrate my app that was using React context api as a simple state management to zustand which i find pretty cool.

I created a sample repo to demonstrate my issue [here](https://github.com/ke3pup/with-zustand-demo) which is based on the nextjs with-zustand example. 

I haven't been able to get past the `Rendered fewer hooks than expected. This may be caused by an accidental early return statement.` issue coming from `layout.js` even though the useEffects aren't conditional and same thing in react's Context API world works?

I know I'm doing something horrendously wrong so would appreciate any hints on what i can look into.

**Comment by ke3pup** [comment]
Even with a simplified `layout.js` like below i still get the same issue:

```javascriot

// layout.js
export default function Layout({ children }) {
  // redirect to login in useEffect
  useEffect(() => {
    Router.replace({
      pathname: '/login',
    });
  }, []);

  return (
    <div className="flex flex-col items-center h-full">
      <div id="mainSection" className="flex-1 px-8 max-w-7xl">
        <React.Fragment>{children}</React.Fragment>
      </div>
    </div>
  );
}

```

Error:

```
react_devtools_backend.js:2560 The above error occurred in the <Provider> component:

    at Provider (webpack-internal:///./node_modules/zustand/esm/context.js:9:5)
    at MyApp (webpack-internal:///./pages/_app.js:23:24)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:86:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:160:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:648:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:784:25)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by drcmda** [comment]
the link is a 404, could you post it again please?

**Comment by ke3pup** [comment]
> the link is a 404, could you post it again please?

sorry about that. I accidentally created it as private repo. Fixed now.

**Comment by ke3pup** [comment]
I think the issue is with this line: 

https://github.com/ke3pup/with-zustand-demo/blob/f3a9221328001f01b2877308c233c80205406be9/pages/_app.js#L6

<img width="596" alt="Screenshot 2021-07-12 at 14 47 24@2x" src="https://user-images.githubusercontent.com/87265126/125232514-24281f80-e320-11eb-9610-7302183c3785.png">


Switching it back to `const store = useHydrate(pageProps.initialZustandState);` and changing Provider to `<Provider initialStore={store}>` removes the hook errors i was getting. Since `initialStore={store}` is deprecated, what's the proper way to use `createStore` in a provider?

**Comment by younanjo** [comment]
sorry about this. I need this are mostly my own introduced issues.

**Comment by ke3pup** [comment]
Closing this since i think these are my issues. Sorry about this.

**Comment by dai-shi** [comment]
> what's the proper way to use createStore in a provider?

Please try `createStore={() => store}`.
