### ISSUE TITLE
Accessing store from another store

### ISSUE THREAD

**Issue by icecapp** [pmndrs/zustand#494]
Is it possible to access a store from another store? 

Or is this an anti-pattern? 

Is store composition the way to go?

Or do you just access the raw state like such:

> // Getting non-reactive fresh state
```js 
const paws = useBearStore.getState().paws
```

**Comment by dai-shi** [comment]
The primary use case is a single store. Multiple stores make sense if they are totally isolated.
It sounds like for your use case, a single store would be a good pattern.

**Comment by icecapp** [comment]
What is an idiomatic pattern for splitting up a store then? e.g. say you have state related to your network client, your user, products, orders, etc

**Comment by dai-shi** [comment]
I had been wondering it too, but just recently got the idea to relate with flux/redux.

We should model the store like this:
```js
const useStore = create((set) => ({
  storeSliceA: ...,
  storeSliceB: ...,
  storeSliceC: ...,
  dispatchX: () => set(...),
  dispatchY: () => set(...),
}))
```

> say you have state related to your network client, your user, products, orders, etc

those are store slices.

This is an idiomatic way in zustand, but zustand itself is unopinionated and using multiple stores is totally fine.

**Comment by EB1811** [comment]
Any major disadvantages of getting the raw state?

**Comment by dai-shi** [comment]
> Any major disadvantages of getting the raw state?

Nothing from the library point of view.

**Comment by dai-shi** [comment]
https://github.com/pmndrs/zustand/issues/494#issuecomment-878669052
Based on this, I created a wiki page: https://github.com/pmndrs/zustand/wiki/Flux-inspired-practice 

Closing this issue as answered.

**Comment by zbeyens** [comment]
[zustood](https://github.com/udecode/zustood) is providing a pattern to split all the stores and combine them in a global store with type inference support
