### ISSUE TITLE
Split store into multiple files 

### ISSUE THREAD

**Issue by getzelus** [pmndrs/zustand#497]
Hello, thanks for Zustand, magnificient library simple and efficient for React state management.

I would like to be able to use a single store with create but split it into multiple files like combineReducers in Redux. 
Because in a big project, i may have a lot of data and functions for different components that will interact with each other in the same store. The js file will be very big and difficult to maintain.

It would be cool to be able to import data and functions (with get and set state) inside the main store from different js files.
Regards,
Getzel

**Comment by dai-shi** [comment]
How about this?
```js
const createSliceA = (set) => ({
  countA: 0,
  incA: () => set((prev) => ({ countA: prev.countA + 1 })),
}))

const createSliceB = (set) => ({
  countB: 0,
  incB: () => set((prev) => ({ countB: prev.countB + 1 })),
}))

const useStore = create((set) => ({
  ...createSliceA(set),
  ...createSliceB(set),
}))
```

Related: #13

**Comment by getzelus** [comment]
Thanks, it seems to work perfectly so I proposed a new example in the documentation.

**Comment by dai-shi** [comment]
In terms of conceptual documentation, I would like to somehow show this pattern.
```js
const useStore = create((set) => ({
  storeSliceA: ...,
  storeSliceB: ...,
  storeSliceC: ...,
  dispatchX: () => set(...),
  dispatchY: () => set(...),
}))
```

**Comment by zbeyens** [comment]
[zustood](https://github.com/udecode/zustood) is proposing a pattern to have a global store combining all the stores
