### ISSUE TITLE
Add dependency on selector in useIsomorphicLayoutEffect call in index.ts?

### ISSUE THREAD

**Issue by Delannor** [pmndrs/zustand#499]
Hi,

I am currently working on a function that creates multiple instances of a zustand store.

So far I have come up with this piece of typescript (using zustand@3.5.7):

```typescript
type Stores<T extends State> = { [storeIndex: string]: UseStore<T> }
const multiStores = new WeakMap<StoreApi<any> | StateCreator<any, SetState<any>>, Stores<any>>()

const getOrCreateStoreHook = <T extends State>(
  storeIndex: string,
  createState: StoreApi<T> | StateCreator<T, SetState<T>>
): UseStore<T> => {
  if (!multiStores.has(createState)) multiStores.set(createState, {} as Stores<T>)
  const ms = multiStores.get(createState) as Stores<T>
  if (!ms[storeIndex]) return (ms[storeIndex] = createHook(createState))
  return ms[storeIndex]
}

export const createMultiStore = <T extends State>(createState: StoreApi<T> | StateCreator<T, SetState<T>>) => {
  function useMultiStore<U>(
    storeIndex: string,
    selector: StateSelector<{ state: string }, U>,
    equalityFn?: EqualityChecker<U> | undefined
  ): U
  function useMultiStore(storeIndex: string): T
  function useMultiStore<U>(
    storeIndex: string,
    selector?: StateSelector<{ state: string }, U>,
    equalityFn?: EqualityChecker<U> | undefined
  ) {
    const useStore = getOrCreateStoreHook(storeIndex, createState)
    return useStore(selector || (useStore.getState as any), equalityFn) as U | T
  }
  return Object.assign(useMultiStore, {
    getApi: (storeIndex: string) => (multiStores.get(createState) as Stores<T>)[storeIndex] as UseStore<T>,
  })
}
```

and I use it like this (in a contrived example):
```typescript
type CounterState = { state: { count: number }; inc(): void; dec(): void; reset(): void }

const useCounterStore = createMultiStore<CounterState>((set, get, api) => ({
  state: { count: 0 },
  inc: () => set((store) => ({ state: { count: store.state.count + 1 } })),
  dec: () => set((store) => ({ state: { count: store.state.count - 1 } })),
  reset: () => set({ state: { count: 0 } }),
}))

const MultiStore = ({ storeName }: { storeName: string }) => {
  const { state: state1, inc, dec, reset } = useCounterStore(storeName)
  return (
    <div>
      <h1>{storeName}</h1>
      <h2>Hook State: {state1.count}</h2>
      <h3>Manual getState(): {useCounterStore.getApi(storeName)?.getState().state.count}</h3>
      <button onClick={dec}>DECREASE</button>
      <button onClick={inc}>INCREASE</button>
      <button onClick={reset}>RESET</button>
    </div>
  )
}
const Tests = () => {
  const [storeName, setStoreName] = useState('store1')
  const handleStoreSwitch = () => {
    storeName === 'store1' ? setStoreName('store2') : setStoreName('store1')
  }
  return (
    <div style={{ textAlign: 'center' }}>
      <h2>Test Zustand Multi-Store</h2>
      <button onClick={handleStoreSwitch}>SWITCH STORE</button>
      <MultiStore storeName={storeName} />
    </div>
  )
}
```
Regretfully this doesn't work. When I switch between stores only the first store gets updated. 
The only way I see how to make this work is by making a small change to zustand. 

If I change the empty dependency list of the useIsomorphicLayoutEffect called in the create function inside index.ts 

```typescript
    const stateBeforeSubscriptionRef = useRef(state)
    useIsomorphicLayoutEffect(() => {

    /*...*/

    }, [])
```

to include selector

```typescript
    }, [selector])
```

then everything works for me.
So my question is, if this is a change you would consider? I don't know if this dependency screws up something else. But it does work wonders for my code. :)

**Comment by dai-shi** [comment]
Creating a hook on demand is not recommended and easy to violate rules of hooks.
You are basically doing this.
```js
const Component = ({ mode }) => {
  const [state, setState] = mode ? useState('case1') : useState('case2')
  //...
}
```

Unfortunately, the zustand api does not work for this use case.

(btw, valtio works for this, because it has an exported hook api.)

**Comment by Delannor** [comment]
Thank you for the quick response. I guess zustand might have been an entirely wrong choice for this usecase. I do want to see if I can make it work with some magic overrides though, before looking at other state management options.

**Comment by dai-shi** [comment]
fwiw, we knew this limitation and considered `import { createStore, useStore } from 'zustand'` approach which covers this use case, but chose the current api for simplicity in one aspect. (and in valtio, we took a different approach.)

closing this as the original suggestion can be applied, but please feel free to continue discussions here. I'm actually interested in what is possible with the current api for such use cases. (It's not going to be a recommended pattern, but for experienced developers, good to know any possible hacks.)
