### ISSUE TITLE
[Question] How to get useEffect to only update on store changes when the change is from another component/own component

### ISSUE THREAD

**Issue by RuiXiong2211** [pmndrs/zustand#501]
Hi, I am trying to update a component in real time with data that is to be displayed into a table without refreshing the page when there are changes in the state of the store after retrieving the data once in the component. 

However, the page is constantly re-rendered instead of re-rendering when there are changes to the store

Here is my store ,

```javascript
  const baseUrl = "http://localhost:4000/app/reservation";

  export const useStore = create((set) => ({
  reservations: [],
  getReservations: async () => {
    const response = await axios.get(baseUrl);
    set({ reservations: await response.data });
  },
  addReservation: (reservation) => {
    set((state) => ({ reservations: [...state.reservations, reservation] }));
  },
  removeReservation: (id) => {
    set((state) => ({
      reservations: state.reservations.filter(
        (reservation) => id !== reservation._id
      ),
    }));
  },
}));
```

Here is the component where I use the store,
```javascript
  const getAllReservation = useStore((state) => state.getReservations);
  const reservations = useStore((state) => state.reservations);
  const reservationsRef = useRef(useStore.getState().reservations);

  useEffect(() => {
    getAllReservation();
    useStore.subscribe(
      (reservations) => (reservationsRef.current = reservations),
      (state) => state.reservations
    );
  }, [reservations, getAllReservation]);
```

I have another component, different from the one above which calls `addReservation` from the store.

I have tried the code below but it does not re-render the page on changes but constantly re-renders the page
``` javascript
useEffect(() => {
    getAllReservation();
  }, [reservations, getAllReservation]);
```

I have tried the code below but it requires me to refresh the page in order to show the updated changes. when i call `addReservation`
```
  useEffect(() => {
    getAllReservation();
  }, []);
```

Thank you for your help.

**Comment by dai-shi** [comment]
Not 100% sure what you are trying, but a possible fix would be this:
```js
  const getAllReservation = useStore((state) => state.getReservations);
  const reservationsRef = useRef(useStore.getState().reservations);

  useEffect(() => {
    getAllReservation();
    return useStore.subscribe(
      (reservations) => (reservationsRef.current = reservations),
      (state) => state.reservations
    );
  }, [getAllReservation]);
```

**Comment by RuiXiong2211** [comment]
Hi, thank you for your response. The code does not work as I intended.

I have two components A and B, component A is an input form which uses the `addReservation`  function of the to update value of `reservations` at the zustand store. Component B is a table displaying all the data from the `reservations` in the store that is retrieved from the mongodb database.

I am trying to get component B, the table displaying `reservations` to update whenever I add a reservation through component A, the input form by getting component B to re-render whenever the `reservations` store is updated. Currently, for the code above, component B does not re-render on changes to `reservations`, the webpage has to be manually refreshed in order to view the changes.

Thank you.

**Comment by dai-shi** [comment]
So, you don't want to do this in component B for some reason?
```js
  const reservations = useStore((state) => state.reservations);
```

Still not sure if I get the intention correctly. You might want to create a codesandbox repro without fetch nor mongo. Or, let's wait and see if somebody else can help on it.

**Comment by RuiXiong2211** [comment]
Component B has a 

```
const reservations = useStore((state) => state.reservations);
```

**Comment by samuelcolburn** [comment]
It's hard to give a good answer to this without a sandbox, it could be many things. 

- Check renders in your parent components. There maybe something triggering a re-render further up the tree
- Memoize your reservation selector(s) and/or store them in an object:
````javascript

// refactor your state to store your data as an object with an array of ids instead optimal selectors
  export const useStore = create((set) => ({
  ids: [],
  reservations: {}, 
  getReservations: async () => {
    const response = await axios.get(baseUrl);
    const data = await response.data;

    set({
      ids: data.map(value => value.id),
      reservations: data.reduce((acc, curr) =>({...acc, [curr.id]: curr }), {}),
    });
  },
// ...
}));

// now that you have your state as an object, you can use memoized selectors per table cell.
// something like:
const Row = ({ id }) => {
  const data = useStore(useCallback(state => state.reservations?.[id], [id]));

  return (<tr>{JSON.stringify(data)}</tr>)
};

const Table = () => {
 const ids = useStore(state => state.ids);

 return (
   <table>
     {ids?.map(id => <Row key={id} />}
    </table>
  )
};

````
- You could also try using immer in your store. Again, hard to give a definitive answer without a pen.

**Comment by dai-shi** [comment]
Closing this as stale. Please open [a new discussion](https://github.com/pmndrs/zustand/discussions/new) with a reproduction.
