### ISSUE TITLE
Inital state set proposal

### ISSUE THREAD

**Issue by GrefriT** [pmndrs/zustand#511]
Hi. I really like zustand, but using it with next js is a big problem. Due to the fact that there is no way to set the initial state from the component itself, in 90% of cases you have to use useState.  I will give an example of how I would like what the api would look like.
```
const useCounter = create(set => ({
    incrementCounter: () => set(state => ({ count: state.count + 1 }))
}));
```
```
//nextjs page
export default Page({ data }) {
    const count = useCounter(state => state.count, { count: data.count }); //second argument provides initial state
    return <div><span>{count}</span><IncrementButton /></div>;
}

  function IncrementButton() {
    const incrementCounter = useCount(state => state.incrementCounter);
    return <button onClick={incrementCounter}>Increment</button>;
  }

  export function getServerSideProps() {
    return {
      props: {
        data: {
          count: // fetch("https://externalapi.com")...
        }
      }
    }
  }
```
In my opinion, the internal implementation of the hook should look like this(pseudocode)
```
function useCounter(selector, initialState) {
    ...
    for(const key in initialState){
       if(!(key in actualState) {
        setState({...actualState, [key]: initialState[key]);
       }
    }
  ...
  }
```
That is, if several hooks have an initialState, then it will be applied only from the hook that will be called first. If such a field is already in the state, then we will not change anything. Of course, you can use useEffect to achieve what you want, but I would like it to work with SSR as useState. I hope I clearly explained my idea.
P.S. I saw an example in the nextjs repository and in my opinion it cannot be used normally and I would like to have another way.

**Comment by dai-shi** [comment]
> That is, if several hooks have an initialState, then it will be applied only from the hook that will be called first. If such a field is already in the state, then we will not change anything.

If you are sure what you are doing (sounds like you are), you can `setState` in render.

```js
const useCounterBase = create(set => ({
  incrementCounter: () => set(state => ({ count: state.count + 1 }))
}));

const useCounter = (selector, initialState) => {
  for (const key in initialState) {
    if (!(key in useCounterBase.getState()) {
      useCounterBase.setState({ [key]: initialState[key] })
    }
  }
  return useCounterBase(selector)
}
```

(Actually, it should be improved and call `setState` just once.)

If this works for your use case, why won't you please create a wiki page to describe this practice. (If it looks good, we can link from https://github.com/pmndrs/zustand#best-practices)

**Comment by GrefriT** [comment]
Sorry for the late reply. Thank you very much, this is exactly what I needed. As time will be, I will try to describe it in the wiki
