### ISSUE TITLE
[Question] Flux pattern with high number of dispatch functions

### ISSUE THREAD

**Issue by sproott** [pmndrs/zustand#512]
The [Flux inspired practice](https://github.com/pmndrs/zustand/wiki/Flux-inspired-practice) page suggests to flatten the stores into a single large store.

How does this scale with increasing numbers of dispatch functions? Is it advised to split it up into a tree-like structure, or keep it flat? Because one could get lost if all the dispatch functions in the whole applications are in a single store.

**Comment by dai-shi** [comment]
It shows a practice, but generally speaking it's unopinonated.
You can make objects and structure dispatch functions in a tree.
Just be reminded, when you update a state, it's shallow merged by default.
If you need deep merge, you need to do it on your end.

As for performance, it may slow down if it's extremely huge.
But, in such a case, there would be various room of improvement, and the preliminary investigation/measurement would be important.

**Comment by sproott** [comment]
Does immer do deep merges automatically?

**Comment by sproott** [comment]
>But, in such a case, there would be various room of improvement, and the preliminary investigation/measurement would be important.

Could you elaborate?

**Comment by dai-shi** [comment]
Yeah, immer would work for deep merge.

I mean, if you have say thousands dispatch functions in flat, it may impact on performance,
but it would cause other performance issues and shallow merge wouldn't be a bottleneck.
TBH, I don't know the performance characteristic of shallow merge, and it's just subjective.
Or, I could say the "one could get lost" problem would come first before the performance problem.
Sorry for the confusion.

**Comment by chidev** [comment]
A hello world or TODO list example would be great, right now it's unclear what dispatchX/Y is doing (is that setting properties on one of the other store slices?)

**Comment by dai-shi** [comment]
Sorry if I misunderstand the question, but the hello world example is the counter.
https://codesandbox.io/s/dazzling-moon-itop4
`sliceA` is `count`, and `dispatchX` is `inc`.
(There must be TODO example somewhere..)

dispatchX/Y is updating one or more slices. What I wanted to note there is slice-dispatch is not 1:1 relationship. (Now, I'm getting realized that it was too easy code snippet to show the idea. 😓 )

**Comment by dai-shi** [comment]
Let me close this as answered. #391 is related. It's not very active though.
