### ISSUE TITLE
Set Persist API storage `name` with variable

### ISSUE THREAD

**Issue by felixhaeberle** [pmndrs/zustand#513]
Hey folks, thanks for providing this great module. 🤙

I was wondering on how to set the name of the persistent storage dynamically through a variable.

Something like:

```js
export const useActiveComposition = create<ActiveCompositionState>(persist(
  (set) => ({
    activeCompositionId: null,
    setActiveCompositionId: (composition: Composition) => set({ activeCompositionId: composition ? composition.id : null })
  }),
  {
    name: `melo-active-composition-${useProject.getState().project?.id}`,
    getStorage: () => localStorage,
  }
));
```

But unfortunately, this returns undefined because the hook gets initialized at a time where the value isn't ready. 

How would I approach this problem, and access another stores data or a variable in general to provide it here in a persistent store as a name? Can I pass a variable when calling the hook?

Thanks in advance! 🙏

**Comment by AnatoleLucet** [comment]
There's probably a hacky way to do this, but I can't figure out how.
We've planned to add a way to edit the `persist` config (including the `name`) in #267. But we're kind of stuck with the types.

I'll leave this open in the hope that someone has a way to do this with the current api :crossed_fingers:

**Comment by Sixzero** [comment]
I am also interested in such a solution.
Maybe we could run `create` in a function body where the necessary variables are available? Until that the store is just an empty skeleton with null store?

**Comment by jonataswalker** [comment]
A solution would be fantastic, for not being able to set an unique key (think a user cart) we have to maintain a collection and loop to find the user staff.

**Comment by AnatoleLucet** [comment]
It's now possible to set a dynamic name:
```js
const useStore = create(persist(...))

useStore.persist.setOptions({
  name: "dynamic-name"
})
// to rehydrate the zustand store using the new name
useStore.persist.rehydrate()
```
It'll be released in the next version.

**Comment by estoldy** [comment]
> 

Can you provide an example on how to use inside a store?

**Comment by estoldy** [comment]
> It's now possible to set a dynamic name:
> 
> ```js
> const useStore = create(persist(...))
> 
> useStore.persist.setOptions({
>   name: "dynamic-name"
> })
> // to rehydrate the zustand store using the new name
> useStore.persist.rehydrate()
> ```
> 
> It'll be released in the next version.

Could you provide an example on how to use inside a store?

**Comment by mieradi** [comment]
@ekiwi111 This still feels a little hacky but here's how I am doing it. 

Context: 
- Using Next
- Project Id is a query param 
- I want a new store per projectId on mount

```js
// store.ts

    ...your store setup
    {
      name: 'placeholder-project-id',
    }
```

```js
// your-component.tsx

  useEffect(() => {
    // rename the store
    createTripBuilderStoreMethod?.persist.setOptions({
      name: query?.organizationId as string,
    });
    // rehydrate the store
    createTripBuilderStoreMethod?.persist.rehydrate();
    // remove the default index
    localStorage.removeItem('initial-name');
  }, [query.projectId]);
  ```

I seem to still need a default name, and even though I can set dynamic one, the initial name will be stored regardless. So, I am explicitly removing it from local storage.

Would love to see other patterns that nay be cleaner, but this works for me at the moment.

**Comment by rockreyad** [comment]
```tsx
const [isHydrated, setIsHydrated] = useState(false)

  useEffect(() => {
    if (isLoggedIn && !userData?.id) {
      // dynamic storage name
      usePromoStore.persist.setOptions({
        name: `promo-${userData?.id}`,
      })
      usePromoStore.persist.rehydrate()
      localStorage.removeItem('promo-store')

      setIsHydrated(usePromoStore.persist.hasHydrated())
    }
  }, [isLoggedIn, userData?.id])
```

other logic will run after the `hydration is complete`.i have setup like this and it's working as well .

**Comment by zicjin** [comment]
> It's now possible to set a dynamic name:现在可以设置动态名称了：
> 
> const useStore = create(persist(...))
> 
> useStore.persist.setOptions({
>   name: "dynamic-name"
> })
> // to rehydrate the zustand store using the new name
> useStore.persist.rehydrate()
> It'll be released in the next version.

https://zustand.docs.pmnd.rs/integrations/persisting-store-data#how-can-i-use-a-custom-storage-engine

hi, StateStorage methods require a persist name parameter.
@AnatoleLucet
