### ISSUE TITLE
[Question] Name actions differently in devtools with setState api returned from create

### ISSUE THREAD

**Issue by raviteja83** [pmndrs/zustand#517]
Instead of creating individual fn's to update slices of store, I want to do it with a single function, but I want to have custom action names for each call to `setState`. Something like below.

```
store.setState(callback, false, 'Action1');
store.setState(callback, false, 'Action2');
```
Is there a way I can do this currently? What I notice is `create()` returns `setState(fn: any, replace?: boolean)` only.

I am using vanilla store.

**Comment by dai-shi** [comment]
Yeah, devtools doesn't patch `api`.
It would be easy to change `api.setState` technically, but typing would be difficult. (related #212)
Not 100% sure if it doesn't conflict with other middleware currently and in the future.
If anyone is interested, please feel free to tackle it.

**Comment by dai-shi** [comment]
A workaround for now:
```js
const store = create(devtools((set) => ({
  //...
  set
})))

store.getState().set(callback, false, 'Action1')
```

**Comment by dai-shi** [comment]
Another related issue: #216
