### ISSUE TITLE
[Question] Any example about used in combination with @react-spring

### ISSUE THREAD

**Issue by OhBonsai** [pmndrs/zustand#518]
As title

**Comment by dai-shi** [comment]
Maybe search codesandbox?
https://codesandbox.io/search?refinementList%5Bnpm_dependencies.dependency%5D%5B0%5D=zustand&refinementList%5Bnpm_dependencies.dependency%5D%5B1%5D=react-spring&page=1&configure%5BhitsPerPage%5D=12

**Comment by dai-shi** [comment]
Closing this. If you like to continue discussions, please open [a new discussion](https://github.com/pmndrs/zustand/discussions/new) maybe with some requirements.
