### ISSUE TITLE
server side rendering?

### ISSUE THREAD

**Issue by isc30** [pmndrs/zustand#519]
Hi, is it possible to get SSR working easily?

**Comment by dai-shi** [comment]
We hope `zustand/context` makes it a little easier, but docs and best practices would be still missing.

**Comment by dai-shi** [comment]
Hope this helps: https://github.com/vercel/next.js/tree/master/examples/with-zustand
It may worth for non-nextjs SSR.

Closing this. Open [a new discussion](https://github.com/pmndrs/zustand/discussions/new) for further questions.

**Comment by inceenes10** [comment]
is there examples with zustand 4

**Comment by dai-shi** [comment]
Someone was trying to update the nextjs example, but I don't think it's done yet.

You can check out #1180 the migration guide.

**Comment by eduardo-amaro-maciel** [comment]
Well, the example given above doesn't use the `/app` directory, but I'm also waiting to know if it's possible to use zustand with `/app` without using the "use client"
