### ISSUE TITLE
[Question] Access to store state inside SSR Next.js

### ISSUE THREAD

**Issue by ProxyJoshua** [pmndrs/zustand#521]
It is possible to access to the store inside the getServerSideProps function? Is there any option? I want to avoid some api request if the data it is already loaded in the store

**Comment by dai-shi** [comment]
Store state can be accessed with `useStore.getState()`. Note that it's shared in SSR #182.

**Comment by dai-shi** [comment]
Closing as partly answered. If you want to continue discussions, please open [a new discussion](https://github.com/pmndrs/zustand/discussions/new) maybe with some code snippet.
