### ISSUE TITLE
Philosophy question

### ISSUE THREAD

**Issue by jackmoore** [pmndrs/zustand#522]
What's the advantage in putting non-reactive data in the store? Take the following example:

```
const useStore = create(set => ({
  bears: 0,
  increasePopulation: () => set(state => ({ bears: state.bears + 1 })),
}))
```

Wouldn't it be better to pull the non-reactive data out so that selectors / memoization isn't required:
```
const useStore = create(set => ({
  bears: 0,
}))

function increasePopulation() {
  useStore.setState(state => ({ bears: state.bears + 1 })
}
```

My apologies for creating a ticket for a question. Thanks for zustand!

**Comment by dai-shi** [comment]
Some people prefer the former style as it's more flux like. The latter style is perfectly fine (and technically efficient).
The library itself is unopinionated. readme just shows the former style as a primary usage.
(fwiw, [valtio](http://github.com/pmndrs/valtio) shows the latter style as a primary usage.)

**Comment by jackmoore** [comment]
Thanks, just making sure I wasn't overlooking something 👍

**Comment by zbeyens** [comment]
[zustood](https://github.com/udecode/zustood) is being more opinionated by generating the actions outside the store state

**Comment by pietrofxq** [comment]
@dai-shi I am converting a medium-sized codebase to zustand and I am wondering if this would have any negative effects:

```js
create(set => ({
  setState: set,
  counter: 0
}))
```
to be used in components like:
```js
const App = () => {
 const [setState] = useStore(state => state.setState)

  return <button onClick={() => setState({counter: 1})>Set Counter</button>
})
```

I believe it is fine since the reference of `set` is kept, but I wondered why there was no such examples of this in the docs. I believe it is a very common use case that people want to place their setState functions only in the components that would use them, not set every possible state change function in the store definition

**Comment by dai-shi** [comment]
It is totally fine. No negative effects.

I would do the following, which can be a little more efficient.
```js
const useStore = create(() => ({
  counter: 0
}))

const App = () => {
  const setState = useStore.setState

  return <button onClick={() => setState({counter: 1})>Set Counter</button>
})
```

**Comment by dai-shi** [comment]
I made a wiki page: https://github.com/pmndrs/zustand/wiki/Practice-with-no-store-actions
