### ISSUE TITLE
zustand forms - steps needed to Garbage Collect zustand store

### ISSUE THREAD

**Issue by TriStarGod** [pmndrs/zustand#535]
I'm using zustands with a passive form generator. A summarized version looks like

```
const createFormStore = () => createStore(....);

function Form(initialState, onFieldAsync, onFormAsync) {
 const formStoreRef = useRef(createFormStore());
 ...
 useEffect(() => {
  formStoreRef.current.setForm(initialData);
  return () => {
   // destroy form
  };
 }, [intialData]);
 return (
  <form ...>
   <FormContext.Provider value={formStoreRef.current.formStore)>
   ...
   </FormContext>
  </form>
 )
}
```

It works. However, I'm not sure if the older forms were Garbage Collected. Do I have to take any steps to get it Garbage Collected (ie destroy zustand store)?

**Comment by dai-shi** [comment]
If all subscriptions are unsubscribed, which is guaranteed if using only the hook, it should be garbage collected.

**Comment by TriStarGod** [comment]
@dai-shi  By hook, you mean `useStore`? All the form components use `useStore` hooks.

**Comment by dai-shi** [comment]
> By hook, do you mean `useStore`?

Yes.

BTW, passing hooks in context values has a risk of violating the rule of hooks. We provided `zustand/context` to prevent the risk. I don't think it covers your use case though.

wait, if you are _replacing_ the hook `useStore`, there might be memory leak, the store might not be garbage collected, like you concerned. So, I'd recommend using `zustand/context` or using the same technique to make sure useStore unsubscribes.

**Comment by TriStarGod** [comment]
Ah, didn't realize a `zustand/context` option was available. So something like this?

```
const { Provider, useStore as useFormStore } = createContext();
const createFormStore = () => createStore(....);

function FormWrapper({ initialState, onFieldAsync, onFormAsync }) {
 return (<Provider createStore={createFormStore}><Form initialState={initialState} ... /></Provider>);
}

const store2form = ({ setForm, ... }) => ({ setForm, ... });
function Form({ initialState, onFieldAsync, onFormAsync }) {
 const { setForm, ... } = useFormStore(store2form, shallow);
 ...
 useEffect(() => {
  setForm(initialData);
  return () => {
   // destroy form
  };
 }, [intialData, setForm]);
 return (
  <form ...>
   ...
  </form>
 )
}

function FormComponentString(...) {
 const value = useFormStore(useCallback(....));
}
```

**Comment by dai-shi** [comment]
yeah, something like that.

**Comment by TriStarGod** [comment]
@dai-shi  Thanks! Zustand is amazing!
