### ISSUE TITLE
Persist middleware and localstorage

### ISSUE THREAD

**Issue by halchester** [pmndrs/zustand#536]
I use zustand middleware persist with my store. and here's the code for the store.

```
type UserStore = {
  userData: User | null;
  setUserData: (user: User) => void;
  removeUserData: () => void;
};

export const useUserData = create<UserStore>(
  persist(
    (set) => ({
      userData: null,

      setUserData: (user: User) => {
        set(() => ({
          userData: user,
        }));
      },

      removeUserData: () => {
        set(() => ({
          userData: null,
        }));
      },
    }),
    {
      name: "userStore",
    }
  )
);
```

The problem is after I've logged out the current user, if i check the localStorage, the user is still persisted at the localStorage (browser). The only thing i can get rid of the current user is by `localStorage.setItem("userStore", JSON.stringyfy(null))`

Is there a workaround with this or am i just doing it wrong? Thanks.

**Comment by AnatoleLucet** [comment]
Hi. Is the `userData` in the storage still a `User`, or is it `null`?
If it's still a `User`, can you send a repro (e.g. codesandbox)?

**Comment by halchester** [comment]
Hello, sorry. The problem is that if i console log in bash it says null, but in browser localStorage it has persisted data. I'll close this issue for now, I'll investigate whether it's from my end or the library. Thanks!
