### ISSUE TITLE
Differences between shallow and default equality function

### ISSUE THREAD

**Issue by frontendhz** [pmndrs/zustand#538]
Hi, I am wondering what are the differences between shallow and the default equality function? The default equality function (if I understand the code correctly) is Object.is, and shallow also uses Object.is in its definition, so I feel like most of the time their return values would be the same?

**Comment by dai-shi** [comment]
Assuming your question is about the difference between `Object.js` and `shallow` in general:
```js
// if values are primitives, they behave the same.
Object.is(1, 1) // is true
shallow(1, 1) // is true

// but if values are objects, they are different.
Object.is({ count: 1 }, { count: 1 }) // is false
shallow({ count: 1 }, { count: 1 }) // is true
```

**Comment by dai-shi** [comment]
Closing as answered.
