### ISSUE TITLE
Reduce type definition when using Typescript 

### ISSUE THREAD

**Issue by frontendhz** [pmndrs/zustand#539]
Is there anyway we can avoid defining the type of create function's return value (especially functions) when using typescript to reduce the number of codes we need to write? Can zustand infer the types automatically?

<img width="619" alt="截屏2021-08-17 下午2 58 15" src="https://user-images.githubusercontent.com/89065116/129678986-8eab8836-a4fa-4364-8858-670d59b8098c.png">

**Comment by dai-shi** [comment]
https://codesandbox.io/s/loving-knuth-dbrzr?file=/src/App.tsx
I don't think TypeScript can't infer types as you desire.

https://github.com/pmndrs/zustand#typing-your-store-and-combine-middleware
`combine` might help for some use cases.

**Comment by dai-shi** [comment]
Closing this. Feel free to open [a new discussion](https://github.com/pmndrs/zustand/discussions/new) for more discussions.
