### ISSUE TITLE
how to use to share state across components!

### ISSUE THREAD

**Issue by dcsan** [pmndrs/zustand#547]
Obvious question, but I haven't got this from the docs.

State manager is to share state across components. 

in the [example code](https://github.com/pmndrs/zustand/blob/main/examples/src/App.js) and docs, `useStore` is just a global variable, and all components are in the same file.

when I put the store into a separate file and import into a couple of places

it still seems to call the update fns a little boilerplate is needed, like this. I have to first define constants for those anon funcs?

```
  const setWallet = useStore(state => state.setWallet);
  const setBalance = useStore(state => state.setBalance);
  useEffect(() => {
     // doesnt' work
    /// useStore((state) => { state.setWallet(localWallet) })

    setWallet(localWallet)
    setBalance(balance)
  }, [address, balance]);
```

the first method gives an error like:

```
./src/App.jsx
  Line 240:5:  React Hook "useStore" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function  react-hooks/rules-of-hooks
```

is there a quicker pattern or more concise way?
For ref I have the store defined as this

```
// Store.js
import create from 'zustand'

// state and store
const useStore = create(set => ({
    letters: [],
    wallet: null,
    balance: 0,
    name: '',
    setWallet: (wallet) => set({ wallet }),
    setBalance: (balance) => set({ balance }),
    setName: (name) => set({ name }),
}))

export default useStore
```

**Comment by dai-shi** [comment]
I'm not sure if I understand the confusion around separate files, but your example looks fine.

```jsx
import useStore from './Store';

const Component = () => {
  const setWallet = useStore(state => state.setWallet);
  const setBalance = useStore(state => state.setBalance);
  useEffect(() => {
    setWallet(localWallet)
    setBalance(balance)
  }, [setWallet, setBalance, localWallet, balance]);
  // ...
};
```

If you think this is boilerplatey, you can use `getState()` in the store api.

```jsx
import useStore from './Store';

const Component = () => {
  useEffect(() => {
    useStore.getState().setWallet(localWallet)
    useStore.getState().setBalance(balance)
  }, [localWallet, balance]);
  // ...
};
```

**Comment by dcsan** [comment]
ok thanks. so `getState()` is not reactive - but for calling methods thats fine I guess? anything else depending on that output will be reactively invoked?

**Comment by dai-shi** [comment]
yes, `getState()` is not reactive. `useStore()` is reactive. Does this answer your question?

**Comment by dcsan** [comment]
yes I think so! thanks a lot, loving this library!
