### ISSUE TITLE
recommend way to deep merge state inside set function

### ISSUE THREAD

**Issue by lili21** [pmndrs/zustand#551]
```js
import create from 'zustand';

const useStore = create(set => ({
  test: { name: 'lili', age: 10 },
  update: () => set({ test: { age: 11 }})
})
```

the expected result state is  ` test: { name: 'lili', age: 11} `。

**Comment by dai-shi** [comment]
quick answer:
1. merge it on your own: `set(state => ({ test: { ...state.test, age: 11 } }))`
2. use immer `produce` or [middleware](https://github.com/pmndrs/zustand#middleware)
3. (prefer [valtio](https://github.com/pmndrs/valtio) 🤫 )
