### ISSUE TITLE
Got an issue with nextjs

### ISSUE THREAD

**Issue by MatteoGauthier** [pmndrs/zustand#561]
```
Unhandled Runtime Error
Error: Seems like you have not used zustand provider as an ancestor.
```

**Comment by dai-shi** [comment]
Seems like you have not used zustand provider as an ancestor?

You might want to provide a small reproduction, so that someone can help.

**Comment by dai-shi** [comment]
Closing this as stale.
Please open [a new discussion](https://github.com/pmndrs/zustand/discussions/new) for usage questions.
