### ISSUE TITLE
Next.js SSR  - initialZustandState removes actions from client-side state

### ISSUE THREAD

**Issue by imthenapo** [pmndrs/zustand#564]
Actions are deleted from client side ?
I followed your example but using TS and State Slices...

Any direction on why this could happen?

`
import { useLayoutEffect } from 'react'

import create, { SetState, GetState, UseStore } from 'zustand'
import createContext from 'zustand/context'

import { devtools, redux } from 'zustand/middleware'

import createSidebarSlice, { SidebarState } from './SidebarSlice';
import createLocationSlice, { LocationState } from './LocationSlice';
import createNewsFiltersSlice, { NewsFiltersState } from './NewsFiltersSlice';

const zustandContext = createContext()
export const Provider = zustandContext.Provider
// An example of how to get types

/** @type {import('zustand/index').UseStore<typeof initialState>} */

export type Store =
    SidebarState &
    LocationState &
    NewsFiltersState

let store: UseStore<Store>;

export const useStore: UseStore<Store | any> = zustandContext.useStore

export const initializeStore = (preloadedState: any = {}) => {
    const store = (set: SetState<Store>, get: GetState<Store>) => ({
        ...createSidebarSlice(set, get),
        ...createLocationSlice(set, get),
        ...createNewsFiltersSlice(set, get, preloadedState.newsfilters),
    });
    return create<Store>(
        process.env.NODE_ENV === 'development' ? devtools(store) : store
    )
}

export function useCreateStore(initialState: any) {
    // For SSR & SSG, always use a new store.
    if (typeof window === 'undefined') {
      return () => initializeStore(initialState)
    }
  
    // For CSR, always re-use same store.
    store = store ?? initializeStore(initialState)
    // And if initialState changes, then merge states in the next render cycle.
    //
    // eslint complaining "React Hooks must be called in the exact same order in every component render"
    // is ignorable as this code runs in same order in a given environment
    // eslint-disable-next-line react-hooks/rules-of-hooks
    useLayoutEffect(() => {
      if (initialState && store) {
          console.info("Store")
        store.setState({
          ...store.getState(),
          ...initialState,
        })
      }
    }, [initialState])
  
    return () => store
  }

// const useStore = create<Store>(
//     process.env.NODE_ENV === 'development' ? devtools(store) : store
// )

export default useStore

`

**Comment by dai-shi** [comment]
Not sure what's happening. You might want to drill down the issue.

**Comment by imthenapo** [comment]
For anybody stuck with this issue,
Please look at this CODEPEN for the solution:

https://codesandbox.io/s/nextjs-with-zustand-forked-ntden?file=/lib/store.js:1249-1466
