### ISSUE TITLE
[Questions] [Help Wanted] Zustand + React

### ISSUE THREAD

**Issue by YeonV** [pmndrs/zustand#570]
Hi bros!
First of all thanks for this amazing project!!!
I created a new test-project using zustand, and it exploded into a full big project:
https://github.com/YeonV/LedFx-Frontend-v2/blob/main/src/utils/apiStore.jsx

It works super well!

Questions:

1. Do you have any recommendations for me to my code? (optimizations, best-practices,...)

> my next steps would be slicing and maybe add types?

2. is it possible to make the functions CTRL-clickable to "jump to definition"? (without bloating the code) so one can jump from the component direcly to the set-function-definition for example.
3. Shared state between Zustand and Electron is possible? (is there an example anywhere?)

Thank you very much
Gratefully

Blade

**Comment by zbeyens** [comment]
1. Take a look at [zustood](https://github.com/udecode/zustood)
