### ISSUE TITLE
Error: Package subpath './shallow' is not defined by "exports"

### ISSUE THREAD

**Issue by jedashford** [pmndrs/zustand#576]
I get the below error on a new nextjs project. The component is a copy and paste from the example in the readme. My package.json shares the same three.js dependencies. Any ideas?

``` 1 of 1 unhandled error
Server Error
Error: Package subpath './shallow' is not defined by "exports" in .../node_modules/zustand/package.json

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
applyExports
internal/modules/cjs/loader.js (491:9)
resolveExports
internal/modules/cjs/loader.js (507:23)
Function.Module._findPath
internal/modules/cjs/loader.js (635:31)
Function.Module._resolveFilename
internal/modules/cjs/loader.js (1007:27)
Function.mod._resolveFilename
.../node_modules/next/dist/build/webpack/require-hook.js (96:28)
Function.Module._load
internal/modules/cjs/loader.js (890:27)
Module.require
internal/modules/cjs/loader.js (1080:19)
require
internal/modules/cjs/helpers.js (72:18)
Object.<anonymous>
.../node_modules/@react-three/fiber/dist/react-three-fiber.cjs.dev.js (8:15)
Module._compile
internal/modules/cjs/loader.js (1176:30)

**Comment by dai-shi** [comment]
Hi @jacobrask, welcome here.
We believe we fixed the "exports" issue in zustand. There can still be an issue, especially with another library like r3f.
Can you confirm which zustand version is used?
@barelyhuman Can you help on this?

**Comment by barelyhuman** [comment]
hey @jedashford ,
can you tell me what platform are you running this on? Codesandbox? Local? 
and if local , what version of Node are you using?

**Comment by jedashford** [comment]
Local, Node v14.2.0

**Comment by superposelabs** [comment]
same issue. Local, Node v14.8.0 with a NextJs app

**Comment by barelyhuman** [comment]
@dai-shi 
Webpack does have the needed code in their `enhanced-resolve` package to handle wildcard exports , I'm guessing our builds and pkg.json might need changes, I'll get back on this. 

https://github.com/webpack/enhanced-resolve/blob/d1a3cb65cdf90754871a263172006e2902a2f86e/lib/util/entrypoints.js#L551


@jedashford @superposelabs , you'll have to wait for a bit more , thanks

**Comment by barelyhuman** [comment]
found it.
@jedashford @superposelabs , could one of you upgrade to v14.13.0 and confirm that it works after doing that?

**Comment by dai-shi** [comment]
Also, would you guys try #577 build and see if it yells about unsupported version?
https://ci.codesandbox.io/status/pmndrs/zustand/pr/577 👉 "Local Install Instructions"
```bash
yarn add https://pkg.csb.dev/pmndrs/zustand/commit/6f0dc9cf/zustand
npm i https://pkg.csb.dev/pmndrs/zustand/commit/6f0dc9cf/zustand
```

**Comment by dai-shi** [comment]
#577 is void. #578 is a fix.

**Comment by jedashford** [comment]
Upgraded to v14.18.0 and it works perfectly. I'll try with the zustand
packages later in the day.
