### ISSUE TITLE
calling set within middleware

### ISSUE THREAD

**Issue by chrisdrackett** [pmndrs/zustand#579]
I'm trying to hook zustand up to our persistent database at the moment. I'm trying to create a middleware that sets up a listener to changes in our database and then makes the changes in zustand. The issue I'm running into is that these changes don't seem to actually make it into my store. Here is my middleware:

```
export const myMiddleware = (config) => (set, get, api) => {
    databaseDocument.$.subscribe((rawData) => {
      set(initialDocument)

      console.log('get within subscription', get())
    })

    return config(
      set,
      get,
      api,
    )
  }
```

I find that if I log `get()` (see above) within my subscription I see the correct thing, but if I try and access my store I don't find my data. Is this expected? What am I missing :)

**Comment by dai-shi** [comment]
It looks okay at a glance. You might want to create a small reproduction so that someone can help.
Also, you might want to try the same thing without middleware and see if it works.

**Comment by chrisdrackett** [comment]
I think I have an idea what is going on, I think when I actually create the store I'm overwriting the values added by the middleware:

https://codesandbox.io/s/zustand-initial-value-efs90

**Comment by dai-shi** [comment]
Not sure if I 100% follow, but you can do something after invoking inner createState.
```js
export const myMiddleware = (config) => (set, get, api) => {
  store = config(set, get, api)
  // do something
  return store
}
```

**Comment by chrisdrackett** [comment]
@dai-shi I'm getting the same behavior with your suggestion:

https://codesandbox.io/s/zustand-initial-value-forked-9den1?file=/src/index.ts

the only state that I'm seeing after calling create is the state put on the store within the `create` function and not the state set via the middleware

**Comment by dai-shi** [comment]
Oops, my bad. `config()` return an initial state.
So, something like this: https://codesandbox.io/s/zustand-initial-value-forked-nstlq

But, it doesn't seem like what you want.
Your original example is about the subscribe usage, and it would work fine if the callback invocation is delayed.

**Comment by dai-shi** [comment]
I'm not sure if this is resolved. Assuming it's not a bug, please open [a new discussion](https://github.com/pmndrs/zustand/discussions/new), if any help is still needed.
