### ISSUE TITLE
[Question] How to persist store partially ?

### ISSUE THREAD

**Issue by hug0b** [pmndrs/zustand#581]
Is it possible to apply the `persist()` middleware on a store so it only applies to some values ?

**Comment by AnatoleLucet** [comment]
Sure, you can blacklist / whitelist specific fields

```ts
persist(
  (set) => ({
    foo: null,
    bar: null, // <-- won't be persisted
  }),
  {
    name: "my-store",
    whitelist: ["foo"]
  }
)
```

https://github.com/pmndrs/zustand/blob/main/src/middleware.ts#L219-L226

**Comment by hug0b** [comment]
Thanks, looking at the README I was not under the impression that there were other options. 
I guess a limitation of this API is that it's not possible to whitelist / blacklist nested properties though, like  `whitelist: ["foo.bar.baz"]`.

**Comment by AnatoleLucet** [comment]
I started working on nested properties in #463, but I need to clean it up a bit
