### ISSUE TITLE
how to use React ref with zustand ? (forwardRef in zustand)

### ISSUE THREAD

**Issue by metinozkan** [pmndrs/zustand#584]
I have a ref variable in my parent component. I want to use this ref variable in my child components. How can i do this ? 
There is "forwardRef" option in redux. Is there any same option ?

```connect(mapStateToProps, null, null, { forwardRef: true })(wrapper)```

my parent comp
```
  const clientReferences= clients.reduce((acc, value) => {
    acc[value.key] = React.createRef();
    return acc;
  }, {})
```

in any child comp

```
   <group ref={clientsReferences[key]}>
                   . 
                   . 
                   .
```

**Comment by RodrigoSosa95** [comment]
This does not sound like a zustand related question, but here's a code sandbox that explains briefly how `refs` work and how to use `React.forwardRef` to bind a ref created from a parent component to a child component.

[React.forwardRed](https://codesandbox.io/s/wizardly-fast-0nx7y?file=/src/App.js)

**Comment by dai-shi** [comment]
I'm not sure if it's solved. If not, please open [a new discussion](https://github.com/pmndrs/zustand/discussions/new) for usage questions.
