### ISSUE TITLE
Check if component is wrapped with Zustand Provider

### ISSUE THREAD

**Issue by moklick** [pmndrs/zustand#586]
Hey!

Thanks for this awesome library :) 

I need to find out if a component is already wrapped with a Zustand Provider in order to decide if I need to wrap it or not. Is this somehow possible?  I am using the Zustand `createContext` api.

**Comment by vlad-zhukov** [comment]
It's possible in v3, something along the lines

```js
function WrapOnDemand({ children }) {
  let isWrapped = true;
  try {
    ZustandContext.useStoreApi();
  } catch {
    isWrapped = false;
  }

  if (isWrapped) {
    return children;
  }
  
  return (
    <ZustandContext.Provider ...>
      {children}
    </ZustandContext.Provider>
  );
}
```

**Comment by moklick** [comment]
Hey @vlad-zhukov 

this works fine :) Thanks!
