### ISSUE TITLE
set function typescript type to have third parameter

### ISSUE THREAD

**Issue by electronic33** [pmndrs/zustand#611]
If I'm not mistaken, the `set` function accepts a third parameter that reflects in the devtools panel when the given `set` function is called. Now in the typescript type it only has two parameters: `partial` and `replace`.

![image](https://user-images.githubusercontent.com/37542420/138645286-7fc1cc10-0cb7-4e62-bb0b-fa0356131f21.png)

**Comment by dai-shi** [comment]
types are changed/improved in v3.6.2. please refer `tests/middlewareTypes.test.tsx` for hints.
If you think it's a bug, please open a new issue with a minimal reproduction.
For usage questions, please open [a new discussion](https://github.com/pmndrs/zustand/discussions/new).
