### ISSUE TITLE
Using thunk when dispatching action

### ISSUE THREAD

**Issue by ralexhassle** [pmndrs/zustand#615]
First thank you for this amazing library, I am in love with the API syntax as I find it simple and lightweight. I am currently migrating from a context + reducer + memo approach to Zustand in my company. My codebase use a redux/flux style with the classic: reducers, selectors, action creators. I read the doc and created some slice stores with their corresponding dispatch as recommended.

I am wondering if I am doing it right though as my action creators are returning either an action (object with a type & payload) or a thunk (a function with dispatch as an argument). In order to handle the thunk I did the following:

```typescript
type Thunk = (dispatch: Dispatch) => void;
export const createSlice = (set: SetState<State>, get: GetState<State>) => ({
  isBooting: true,
  appDispatch: (action: Action | Thunk) => {
    if (typeof action === "function") {
      const dispatch = get().appDispatch;
      return action(dispatch);
    }
    return set((state: State) => reducer(state, action));
  }
});
``` 

An action creator:

```typescript
export const boot = () => (dispatch: Dispatch) => {
  dispatch({ type: BOOT_START });

  const cookie = Storage.restore<boolean>(COOKIE_KEY, false);
  const uuid = Storage.restore<string | null>(UUID_KEY, uuidv4());
  Storage.persist(UUID_KEY, uuid);
  client.Session.setDevice(uuid);

  dispatch({ type: BOOT_SUCCESS, payload: cookie });
};
```

Is it a problem to get `appDispatch` this way in order to handle a thunk ? Is it possible to use a middleware instead ?
I am not using the redux middleware by the way as I had trouble typing the store. I've seen people passing the `dispatch` directly to the action creator and I did it in the past but I want to be consistent with my actual codebase.

**Comment by dai-shi** [comment]
Closing as answered. Please open [a new discussion](https://github.com/pmndrs/zustand/discussions/new) if you still have some questions.
