### ISSUE TITLE
subscribeWithSelector break types with Typescript

### ISSUE THREAD

**Issue by fryck** [pmndrs/zustand#616]
Hello,

I have issue with the new middleware `subscribeWithSelector`

![Screenshot 2021-10-28 at 16 27 38](https://user-images.githubusercontent.com/1364225/139276590-5bc340e6-a626-4f1b-8c94-8b898c20901f.png)

I dont't understand why...

Previously I used ramda `pipe` function to combine my differents middlware in a more clean way, but the same error...

More generaly, Zustand lack of typescript examples / documentation, I'm often struggled with Type error using zustand

Could you help me ? Thanks !

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/zustand/v/3.6.2

Thanks for your help!
