### ISSUE TITLE
Listen change in zustand slice

### ISSUE THREAD

**Issue by cuongdo926** [pmndrs/zustand#623]
In Mobx, there is a feature that runs side effects when there are some changes on data.
```
reaction(
      () => this.token,
      async (token) => {
        token ? await authStorage.setToken(token) : await authStorage.removeToken();
      }
    );
```

I have a zustand slice like below. Is there any way to listen to a change of token then update the storage?
```
type State = {
  token: AuthToken | null;
  setToken: (token?: AuthToken) => void;
  restoreToken: (token?: AuthToken) => void;
  logout: () => void;
};

const updateStorage = async (token?: AuthToken) => {
  token ? await authStorage.setToken(token) : await authStorage.removeToken();
};

const createAuthSlice = (set: SetState<State>, get: GetState<State>) => ({
  setToken: (token?: AuthToken) => {
    if (!token) return;
    set((s) => void (s.token = token));
  },
  restoreToken: async () => {
    const token = await authStorage.getToken();
    if (!token) return;
    get().setToken(token);
  },
  logout: () => set((s) => void (s.token = null)),
});

export default createAuthSlice;
```

**Comment by dai-shi** [comment]
While you could use `subscribe`, I guess this is fine and predictable:
```js
const createAuthSlice = (set: SetState<State>, get: GetState<State>) => ({
  setToken: (token?: AuthToken) => {
    if (!token) {
      authStorage.removeToken()
      return;
    }
    set((s) => void (s.token = token));
    authStorage.setToken(token);
  },
  restoreToken: async () => {
    const token = await authStorage.getToken();
    if (!token) return;
    set((s) => void (s.token = token));
  },
  logout: () => set((s) => void (s.token = null)),
});
```

**Comment by cuongdo926** [comment]
May I ask how to use subscribe if I would like to implement the subscribe in this slice file?

**Comment by dai-shi** [comment]
If you want to subscribe with selector, here's what looks like:

```js
import create from 'zustand'
import { subscribeWithSelector } from 'zustand/middleware'

const useStore = create(subscribeWithSelector((set, get) => ({
  token: null
  setToken: (token) => {
    if (!token) return
    set((s) => void (s.token = token))
  },
  restoreToken: async () => {
    const token = await authStorage.getToken()
    if (!token) return
    get().setToken(token)
  },
  logout: () => set((s) => void (s.token = null)),
})))

useStore.subscribe(
  (state) => state.token,
  async (token) => {
    token ? await authStorage.setToken(token) : await authStorage.removeToken()
  }
)
```

So, it needs some tweaks to define it in a slice file maybe?

**Comment by cuongdo926** [comment]
Thanks for your answer.
How can I get state from other slices?

**Comment by dai-shi** [comment]
`get()` or `useStore.getState()` will return the entire state object.

**Comment by cuongdo926** [comment]
Let me clarify more. I have some slices: AuthSlice (AuthState), HubSlice (HubState). In HubSlice I need to access the token from AuthSlice. How can I access other slice states with ```get: GetState<HubState>```?
Or I should design a State type as a full state object type?

**Comment by dai-shi** [comment]
> I should design a State type as a full state object type?

Yes. Once you created a store, `get()` will return the entire state object. It's not restricted to a slice. (and, namespacing is often requested and discussed, but it's how the library is designed and implemented.)

**Comment by dai-shi** [comment]
Closing as answered. Feel free to have some related comments, or open a [new discussion](https://github.com/pmndrs/zustand/discussions/new) for usage questions.

**Comment by paurock** [comment]
I've got another problem with this case but exactly in TypeScripting. I was not able to TS this kind of resolution.
Here my question - https://stackoverflow.com/questions/77190365/typescript-zustand-subscribewithselector-errors
