### ISSUE TITLE
[Question] [Typescript] StoreApiWithPersist with union type trying to update to 3.6.3

### ISSUE THREAD

**Issue by jafin** [pmndrs/zustand#631]
I'm attempting to update some code to 3.6.3 (from 3.6).

Some state properties I have are union types:  `number | null`.
Using the test case as an example, I cannot get this to validate, any advice on how to get this compiling?

```ts
type CounterState = {
    count: number | null;
};

const useStore = create<
   CounterState, 
   SetState<CounterState>, 
   GetState<CounterState>, 
   StoreApiWithPersist<CounterState>>(
    persist(
        (set, get) => ({
            count: 1,
        }),
        { name: 'prefix' },
    ),
);
```

The error received on persist:

Argument of type '(set: SetState<CounterState>, get: GetState<CounterState>, api: StoreApiWithPersist<{ count: number; inc: () => void; }>) => { ...; }' is not assignable to parameter of type 'StoreApiWithPersist<CounterState> | StateCreator<CounterState, SetState<CounterState>, GetState<CounterState>, StoreApiWithPersist<...>>'.
  Type '(set: SetState<CounterState>, get: GetState<CounterState>, api: StoreApiWithPersist<{ count: number; inc: () => void; }>) => { ...; }' is not assignable to type 'StateCreator<CounterState, SetState<CounterState>, GetState<CounterState>, StoreApiWithPersist<CounterState>>'.
    Types of parameters 'api' and 'api' are incompatible.
      Type 'StoreApiWithPersist<CounterState>' is not assignable to type 'StoreApiWithPersist<{ count: number; inc: () => void; }>'.
        Type 'StoreApiWithPersist<CounterState>' is not assignable to type 'StoreApi<{ count: number; inc: () => void; }>'.
          Types of property 'setState' are incompatible.
            Type 'SetState<CounterState>' is not assignable to type 'SetState<{ count: number; inc: () => void; }>'.
              Type 'number | null' is not assignable to type 'number'.
                Type 'null' is not assignable to type 'number'.ts(2345)

Changing  `StoreApiWithPersist<CounterState>`  to `StoreApiWithPersist<any>` bypasses the warning

**Comment by dai-shi** [comment]
We have a discussion recently in #619.
This is very unfortunate, and a workaround I found so far is `count: 1 as number | null`.

I wonder if there is any TS expert out there who has other suggestions.

**Comment by jafin** [comment]
Thank you, that's fixed it, if I cast the whole state object it also corrects it (or so it appears)

```ts
const useStore = create<
   CounterState, 
   SetState<CounterState>, 
   GetState<CounterState>, 
   StoreApiWithPersist<CounterState>>(
    persist(
        (set, get) => ({
            count: 1,
        } as CounterState),  // change
        { name: 'prefix' },
    ),
);
```
