### ISSUE TITLE
[TypeScript] v3.6.3 multiple middlewares breaks type check on stores with objects

### ISSUE THREAD

**Issue by istvanp** [pmndrs/zustand#632]
As per the test example here: https://github.com/pmndrs/zustand/blob/9f47fdc9276c96db99b70ee763e3990b2ec533a7/tests/middlewareTypes.test.tsx#L440-L476

If one of the items stored is an object, type checking reports an error. (Sorry this must be the 5th question/issue about TS being a pain!)

**Minimal example:**

```typescript
type ObjectState = {
  count: 0,
  obj: {
    prop: string;
  };
  inc: () => void;
};

const useStore = create<
  ObjectState,
  SetState<ObjectState>,
  GetState<ObjectState>,
  StoreApiWithSubscribeWithSelector<ObjectState> & StoreApiWithPersist<ObjectState>
>(
  subscribeWithSelector(
    persist(
      (set, get) => ({
        count: 0,
        inc: () => set({ count: get().count + 1 }, false),
      }),
      { name: "count" }
    )
  ),
  { name: "prefix" }
);
```

**Comment by dai-shi** [comment]
Seems like there are some obvious errors in the example.
I added something based on it in #633, so would you suggest changes that may fail?

**Comment by istvanp** [comment]
Upon closer inspection, this is the same issue as #631. The values within cannot be a subset of the declared store type. The partial values must be cast back to the original declaration's type. This is not an issue for `number` for some reason so I suggest trying another data type in there such as a boolean for your test.

**Comment by dai-shi** [comment]
Do you mean something like this?
```ts
type ObjectState = {
  count: 0;
  foo: boolean;
  inc: () => void;
};
```

**Comment by istvanp** [comment]
Indeed. But the count stuff isn't necessary for this example. Here's a shorter one:

```typescript
type BoolState = {
  foo: boolean;
};

const useObjectStore = create<
  BoolState,
  SetState<BoolState>,
  GetState<BoolState>,
  StoreApiWithSubscribeWithSelector<BoolState> & StoreApiWithPersist<BoolState>
>(
  subscribeWithSelector(
    persist(
      (set, get) => ({
        foo: true as boolean, // remove /as boolean/ to trigger TS error
      }),
      { name: "bool" }
    )
  )
);
```

**Comment by istvanp** [comment]
TS basically assumes the type given and reduces it to smallest set, in this case as evaluating as always `true` unless you tell it that it is actually potentially false too (aka boolean) and then it matches the declared type. Type inference based on the given data doesn't really work without casting. Not that terrible but something to document if there are no workarounds.

**Comment by dai-shi** [comment]
#633 updated, please let us know if there are any examples to add.

**Comment by dai-shi** [comment]
Another option is to add type annotation on `persist`.
```ts
    const useStore = create(                                                   
      subscribeWithSelector(                                                   
        persist<                                                               
          MyState,                                                             
          SetState<MyState>,  
          GetState<MyState>,  
          StoreApiWithSubscribeWithSelector<MyState> &  
            StoreApiWithPersist<MyState>  
        >(                  
          () => ({                                                             
            foo: true,    
          }),               
          { name: 'name' }              
        )                                                                       
      )                                                                         
    )  
```

**Comment by istvanp** [comment]
Ah, that is better! Type casting is always iffy so I think this is probably the way to go!

**Comment by dai-shi** [comment]
Okay, updated #633.

It's originally suggested in https://github.com/pmndrs/zustand/discussions/619#discussioncomment-1563333 by @dumbmatter.

**Comment by istvanp** [comment]
LGTM

**Comment by dai-shi** [comment]
Thanks. I added #631 example in #633 too.
But, should we remove `as ...` workaround and only show the last example?

**Comment by istvanp** [comment]
The one with just the inner annotation is clearly superior (less code and DRY) but doesn't make the other one inherently _wrong_ so I would leave it in but maybe only point to the persist<...> in official docs / wiki / what have you.

**Comment by dai-shi** [comment]
I added a link to the test file in readme. Let me change the order in the test file for now.
