### ISSUE TITLE
Persist Middleware Typescript Error

### ISSUE THREAD

**Issue by andreechristian** [pmndrs/zustand#638]
Hello,

I am getting this error bellow when setting my typescript tsconfig strict mode to `true`.

`Argument of type '(set: SetState<{ session: SessionData; user: UserData | null; }>, get: GetState<{ session: SessionData; user: UserData | null; }>, api: StoreApi<...> & { ...; }) => { ...; }' is not assignable to parameter of type 'StoreApi<{ session: SessionData; user: UserData | null; }> | StateCreator<{ session: SessionData; user: UserData | null; }, SetState<{ session: SessionData; user: UserData | null; }>, GetState<...>, StoreApi<...>>'.
  Type '(set: SetState<{ session: SessionData; user: UserData | null; }>, get: GetState<{ session: SessionData; user: UserData | null; }>, api: StoreApi<...> & { ...; }) => { ...; }' is not assignable to type 'StateCreator<{ session: SessionData; user: UserData | null; }, SetState<{ session: SessionData; user: UserData | null; }>, GetState<{ session: SessionData; user: UserData | null; }>, StoreApi<...>>'.
    Types of parameters 'api' and 'api' are incompatible.
      Type 'StoreApi<{ session: SessionData; user: UserData | null; }>' is not assignable to type 'StoreApi<{ session: {}; user: null; }> & { persist: { setOptions: (options: Partial<PersistOptions<{ session: {}; user: null; }, Partial<{ session: {}; user: null; }>>>) => void; clearStorage: () => void; rehydrate: () => Promise<...>; hasHydrated: () => boolean; onHydrate: (fn: (state: { ...; }) => void) => void; }...'.
        Type 'StoreApi<{ session: SessionData; user: UserData | null; }>' is not assignable to type 'StoreApi<{ session: {}; user: null; }>'.
          Types of property 'setState' are incompatible.
            Type 'SetState<{ session: SessionData; user: UserData | null; }>' is not assignable to type 'SetState<{ session: {}; user: null; }>'.
              Type '{ session: SessionData; user: UserData | null; }' is not assignable to type '{ session: {}; user: null; }'.ts(2345)`

I have created a minimum repo [here](https://codesandbox.io/s/typescript-forked-xijc8?file=/src/index.ts).

Thank you in advance.

**Comment by andreechristian** [comment]
Submitted fix for this https://github.com/pmndrs/zustand/pull/639

**Comment by dai-shi** [comment]
We had a similar discussion in #632.
I know this is unfortunate, but the best workaround for now is this:
https://codesandbox.io/s/typescript-forked-dd0i8

Hm, but, your use case is very unfortunate, because it doesn't even care about the persist api.
Let's see how it can be workaround in a different way.
Thanks very much for the feedback.

**Comment by andreechristian** [comment]
Yep, I just follow the guideline stated on the docs page XD. This is very unfortunate indeed. Will gladly use the workaround but definitely will wait for the fix.

Thank you @dai-shi
