### ISSUE TITLE
`createContext` doesn't work with `@react-three/fiber`

### ISSUE THREAD

**Issue by imed-instadeep** [pmndrs/zustand#640]
I wanted to expose the `Canvas` state, so I used `createContext` and wrapped `Canvas` in the returned Provider, like so:

```tsx
// store.tsx

import create from "zustand";
import createContext from "zustand/context";

const { Provider, useStore } = createContext();

export function StoreProvider({ children, initialState }) {
  return (
    <Provider createStore={() => create(() => ({ ...initialState }))}>
      {children}
    </Provider>
  );
}

export { useStore };
```

```tsx
// App.tsx

function App() {
  const someState = useStore(state => state.someState)

  return (
    <Canvas>
      <Content />
    </Canvas>
  );
}

function Wrapper() {
  return (
    <StoreProvider initialState={{}}>
      <App />
    </StoreProvider>
  );
}

export default Wrapper;
```

```tsx
// Content.tsx

export function Content() {
  const someOtherState = useStore(state => state.someOtherState)

  return <mesh />;
}

```

This throws an error similar to:

```
Uncaught Error: Seems like you have not used zustand provider as an ancestor.
    at useStore (context.js:25)
    at Content (Content.tsx? [sm]:22)
```

My understanding is that Zustand works out of the box with multiple renderers. Am I missing something?

Thank you!

**Comment by dai-shi** [comment]
> Zustand works out of the box with multiple renderers.

It works out of the box, because it doesn't use context.
Now, if you use `zustand/context`, it's no longer true.

See also: https://github.com/pmndrs/zustand/pull/635#issuecomment-960232869

Closing this, but feel free to comment in this issue.

**Comment by imed-instadeep** [comment]
Oh, I see. Is there a way to expose internal functions without context then? Or, how do I use `useContextBridge` with Zustand?

**Comment by dai-shi** [comment]
Why do you need context? Is it SSR?
I'm not sure what you mean by exposing internal functions. Can you elaborate?

**Comment by imed-instadeep** [comment]
I want to allow the users of my (r3f) component to change its state. For example, they should be able to highlight a particular mesh. The way I wanted to do this is by adding a `highlightMesh` function to Zustand, and allowing users to use it from outside the component. Then, I'd listen to state changes from inside the r3f component and update what's needed.

**Comment by dai-shi** [comment]
Sounds like you don't need context. You should just define `useStore` at the module level.

**Comment by imed-instadeep** [comment]
And pass it as a prop?

**Comment by dai-shi** [comment]
where are the values you want to initialize come from?

**Comment by imed-instadeep** [comment]
From the user of the component. When they import it, they have to pass some initial values that are fetched from the server (or from a JSON file when testing, etc). I guess in this case I should pass `useStore` down as a prop?

**Comment by dai-shi** [comment]
I guess this is the case you can't avoid useEffect.
I wouldn't usually recommend it (it causes dual renders), but can't think of any other good workarounds.

**Comment by imed-instadeep** [comment]
Could you explain how useEffect would be used here?

Thank you for your help!

**Comment by dai-shi** [comment]
```js
import create from 'zustand'

const useStore = create(...)

const Component = ({ foo }) => {
  useEffect(() => {
    useStore.setState({ foo })
  }, [foo])
  ...
}
```
