### ISSUE TITLE
[Bug] New subscribe documentation doesn't work

### ISSUE THREAD

**Issue by iamkimchico** [pmndrs/zustand#642]
Hi Zustand

Thanks for an awesome library!

I'm running into an issue with the new subscribeWithSelector in the new zustand version

**Zustand Version**
3.6.4

**Problem**
According to your documentation i should be able to use subscribe with the new subscribeWithSelector, but I keep getting the error that I should use the middleware.

My Store:
`export type TControlsStore = {
  publicBargainingAgreement: string;
};`

`const store = (set: NamedSet<TControlsStore>, get: GetState<TControlsStore>) => ({
  publicBargainingAgreement: '',
});`

`const useControlsStore = create<TControlsStore>(devtools(subscribeWithSelector(store)));`

My subscription:
`useControlsStore.subscribe(state => state, console.log("my log"))`

**Steps to reproduce**
Install Zustand 3.6.4 and add subscribe according to the documentation and see that you get the error.

![image](https://user-images.githubusercontent.com/59334469/140504515-4690d8ef-f437-4f14-b165-0d067b8989e1.png)
![image](https://user-images.githubusercontent.com/59334469/140504545-fade1c32-f93d-4d04-a709-f1c040810087.png)

-----

Am I missing something from the documentation? To me it looks exactly the same and I can seem to find where the error is?

**Comment by dai-shi** [comment]
Sorry for the inconvenience.
The warning is TypeScript only right? It works fine if you run it, I suppose.

Would you please try this?
```ts
const useControlsStore = create<
  TControlsStore,
  SetState<TControlsStore>,
  GetState<TControlsStore>,
  StoreApiWithSubscribeWithSelector<TControlsStore>
>(devtools(subscribeWithSelector(store)));
```
This is only written in `types/middlewareTypes.test.tsx`.
Let me think about adding something in readme.
Maybe, it's time to write readme in TypeScript first.

**Comment by iamkimchico** [comment]
Hi @dai-shi 

Ah.. Of course.. My bad! Your solution works! Thank you very much! 🥇 

It would be awesome if the documentation were in Typescript ;)
