### ISSUE TITLE
Persisting one of my stores is inconstant on android

### ISSUE THREAD

**Issue by haibert** [pmndrs/zustand#644]
Hi Guys,

I have fully migrated my app over from redux to zustand and the experience has been wonderful, so much less code.. Thank you for all the hard work. 

I am persisting one of my stores responsible for retaining pictures that failed to upload. I keep the base64 of the picture taken from the camera in an array and present it to the user in a FailedUploads cue screen where they can decide to upload or discard  the photos. This works great in iOS but on android I am seeing inconsistency when reloading the app. Meaning some times it loads the persisted data, sometimes it loads some of it, and sometimes it removes all the persisted data.

I was able to stop the inconsistency by removing the base64 of the photo temporarily and just persisting the photoID and date stamp, so I can say that loading the large base64 could be the issue, or possibly the fact that there is no waiting for store rehydration in my app.js? In Redux for example there is a persist gate that keeps the splash screen showing until the store is rehydrated. But I am not able to find any instructions on that in your documentation for this, if you have such functionality even? Any guidance would be greatly appreciated.

**Comment by AnatoleLucet** [comment]
Hi, you can check if hydration is done using `useStore.persist.hasHydrated()`if that can help (not a reactive value, it's just a regular getter).

Is this related to #562?

**Comment by haibert** [comment]
Thank you for this tip. I was able to resolve the issue by not storing the base64 of the images, as long as its just text being saved it seems to work fine and that is good enough for now. 

can you tell me if useStore.persist.hasHydrated() returns anything ? is it a async function that gives a true or false when the hydration is finished ? If so I can use it to keep the splash screen open until hydration is complete and that would be great

**Comment by AnatoleLucet** [comment]
`useStore.persist.hasHydrated()` returns true if hydration is done, and false if it isn't.

You could reactively check for hydration with the following:
```ts
const [isHydrated, setIsHydrated] = useState(false);

useEffect(() => {
  if (useStore.persist.hasHydrated()) {
    setIsHydrated(true)
  } else {
    useStore.persist.onHydrate(() => {
      setIsHydrated(true)
    })
  }
}, [])
```
`useStore.persist.onHydrate` will be called after hydration. Though this makes me realize `onHydrate` is probably not the most accurate name :thinking:

**Comment by haibert** [comment]
@AnatoleLucet Interesting. Greatly appreciate the response and code. Yea the naming is kind of confusing, I guess .hasHydrated() is a status checker and .onHydrate() is a manual way of calling for hydration to begin would you say? I'm just trying to figure out the difference between them..

**Comment by AnatoleLucet** [comment]
> .hasHydrated() is a status checker

Yes

> .onHydrate() is a manual way of calling for hydration to begin would you say

`.onHydrate()` is just a way to call a function / do something once the store has been hydrated with the storage's data.

**Comment by haibert** [comment]
Thank you so much. Cant wait until the documentation is updated to show all this awesomeness.
