### ISSUE TITLE
[middleware/devtools] api.setState doesn't support the third argument

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/zustand#674]
https://twitter.com/dai_shi/status/1462689869411454979
`useStore.setState` isn't `namedSet`. The type lies (because I didn't know it's not implemented. 😓 )

https://codesandbox.io/s/suspicious-sky-7t3jc?file=/src/App.tsx

<img width="502" alt="image" src="https://user-images.githubusercontent.com/490574/142823594-1258918c-5e03-4698-94a4-d90933b774fd.png">

Having both `action` and `setState` is weird too. So, it's not really implemented correctly.

**Comment by dai-shi** [comment]
@devanshj Are you working on `devtools`? Or, should I just draft a small PR to only fix this issue?

**Comment by dai-shi** [comment]
https://github.com/pmndrs/zustand/blob/833f57ed131e94f3ed48627d4cfbf09cb9c7df03/src/middleware/devtools.ts#L89
I don't know why I did this. This causes double actions.

**Comment by devanshj** [comment]
I'm working on `devtools`, this will get fixed afaict, I'll open a PR in sometime. If it's urgent feel free to open a PR and fix it.
