### ISSUE TITLE
Compatibility with Electron Redux Dev Tools

### ISSUE THREAD

**Issue by euirim** [pmndrs/zustand#680]
Hello, I'm using Zustand v3.6.5 with electron v13.1.9 as well as the popular electron-forge v6.0.0 and it works well. Electron also supports redux dev tools via [electron-devtools-installer](https://github.com/MarshallOfSound/electron-devtools-installer) v3.2.0, which works well with vanilla redux. However, when I try to get my Zustand store to work with redux dev tools via the `devtools` middleware, I get the following error:

`SyntaxError: Unexpected token (32:10)` in `/node_modules/zustand/esm/middleware.js`.

Here is how I use the middleware:

```typescript
export const useGameStore = create<GameState>(devtools(store));
```

The third line in this try-catch block includes the supposed syntax error the console complains about:

```javascript
try {
    extension = window.__REDUX_DEVTOOLS_EXTENSION__ || window.top.__REDUX_DEVTOOLS_EXTENSION__;
} catch {
}
```

I checked in the electron developer tools console and `window.__REDUX_DEVTOOLS_EXTENSION__` is indeed defined.

Does anyone have any ideas why this might occur and how I can resolve this error? It's been puzzling me for a while.

**Comment by dai-shi** [comment]
you don't have any issue without devtools, do you?

**Comment by euirim** [comment]
No issue when not using the zustand devtools middleware.

**Comment by dai-shi** [comment]
Not exactly sure about the syntax error, but using cjs build might help.
something like:
```js
const { devtools } = require('zustand/middleware.js')
```
Alternatively, you can transpile esm code on your end. Sorry for the inconvenience. Hope someone jumps in with some other ideas.

**Comment by euirim** [comment]
Thanks for the reply. I just had the chance to test your suggestion. Unfortunately, using `require('zustand/middleware.js')` does not work as zustand doesn't export the cjs build in its package.json.

**Comment by dai-shi** [comment]
ah, it's because nodejs follows the "exports" config. I guess your workaround is good. I don't know if there's a better workaround.

**Comment by dai-shi** [comment]
Closing as resolved.
