### ISSUE TITLE
How do I persist a subset of slices?

### ISSUE THREAD

**Issue by lkdm** [pmndrs/zustand#683]
**Code**

```
export const useStore = create<StoreState>(persist(
    // Define the slices that we want to persist across page loads.
    (set, get) => ({
        ...createAuthSlice(set, get), // <-- to be stored in session
        ...createUserSlice(set, get),
        ...createPreferenceSlice(set, get),
    }),
    {
        // Configure persist middleware
        name: "store", // Name of persistent storage
        getStorage: () => sessionStorage, // Use the browser's session storage
        partialize: (state) => ({ auth: state.user }),
    }
))
```

I am trying to persist only the user attribute in the auth slice in session, but I keep getting the following error.

`Type '(state: { user: IUser; getAccessToken: any; forgotPassword: any; forgotPasswordSubmit: any; signUp: any; signIn: any; logOut: any; verifyUser: any; }) => { auth: IUser; }' is not assignable to type '(state: { user: IUser; getAccessToken: any; forgotPassword: any; forgotPasswordSubmit: any; signUp: any; signIn: any; logOut: any; verifyUser: any; }) => DeepPartial<{ user: IUser; getAccessToken: any; ... 5 more ...; verifyUser: any; }>'.
  Type '{ auth: IUser; }' has no properties in common with type 'DeepPartial<{ user: IUser; getAccessToken: any; forgotPassword: any; forgotPasswordSubmit: any; signUp: any; signIn: any; logOut: any; verifyUser: any; }>'.ts(2322)
middleware.d.ts(135, 5): The expected type comes from property 'partialize' which is declared here on type 'PersistOptions<{ user: IUser; getAccessToken: any; forgotPassword: any; forgotPasswordSubmit: any; signUp: any; signIn: any; logOut: any; verifyUser: any; }, Partial<{ user: IUser; getAccessToken: any; ... 5 more ...; verifyUser: any; }>>'
(property) partialize?: ((state: AuthSlice) => DeepPartial<AuthSlice>) | undefined`

I would appreciate any help anyone can give me.

**Comment by lkdm** [comment]
The rest of store.ts (appended by above useStore code)

`
// Import Slices - which are responsible for different types of state
import { AuthSlice, createAuthSlice } from './persistent/authSlice'
import { UserSlice, createUserSlice } from './persistent/userSlice'
import { PreferenceSlice, createPreferenceSlice } from './persistent/preferenceSlice'

// Create a StoreState generic type; and a unified interface for accessing its sub-types
export type StoreState = AuthSlice & UserSlice & PreferenceSlice
export type StoreSlice<T> = (
    set: SetState<StoreState>,
    get: GetState<StoreState>
) => T
`

authSlice.ts

`

import { IUser } from '../../types/Auth';

export interface AuthSlice {
  // Properties
  user: IUser,
  // Behaviour
  getAccessToken: any,
  forgotPassword: any,
  forgotPasswordSubmit: any,
  signUp: any,
  signIn: any,
  logOut: any,
  verifyUser: any
}

//=============================================================================
// Zustand Store
//=============================================================================
export const createAuthSlice: StoreSlice<AuthSlice> = (set, get) => ({
  // Initial state
  user: undefined,
  // .... Behaviour
  
})

**Comment by lkdm** [comment]
I have created a workaround by using multiple stores. However, my understanding of the documentation is that using a single store is better. Does anybody have any input on this? Thank you.

**Comment by AnatoleLucet** [comment]
I'm pretty sure this is because you're renaming the field `user` to `auth` in partialize.
Partialize is not intended for renaming fields. Only for "partializing" the state object while keeping the same structure.

Could you try the following?
```
partialize: (state) => ({ user: state.user }),
```

**Comment by AnatoleLucet** [comment]
Closing. Feel free to reopen if your issue isn't solved.

**Comment by pavi2410** [comment]
I don't think partialize is the right solution to this, as we couldn't set a different storage for different slices. The approach presented in #800 could be a good solution.
