### ISSUE TITLE
Is it possible to set the default comparison function to shallow? 

### ISSUE THREAD

**Issue by looeee** [pmndrs/zustand#685]
I recently updated to Zustand 3.6.5. The changed order of `.subscribe` and the need to use `subscribeWithSelector` came as a bit of a surprise but once I worked everything out it's worth it for the improved types. 

However, I now have to `import shallow from 'zustand/shallow'` all over my app. So far there's nowhere that I _don't_ want to use shallow comparison. Is there any way to set the default comparison function on the store itself? Or if not, could this feature be added?

**Comment by dai-shi** [comment]
Would creating another wrapping hook help?

```js
const useStoreBase = create(...)
export const useStore = (selector) => useStoreBase(selector, shallow)
```

**Comment by kasugaicrow** [comment]
Tried to play around a bit and came out with an implementation which consists in passing a default option object as a parameter to the `create` function. The type of that object would be
```ts
type DefaultCreateOptions<D> = {
  equalityFn: EqualityChecker<D>
}
```
and the `create` function
```ts
function create<
  TState extends State,
  CustomSetState,
  CustomGetState,
  CustomStoreApi extends StoreApi<TState>
>(
  createState:
    | StateCreator<TState, CustomSetState, CustomGetState, CustomStoreApi>
    | CustomStoreApi,
  defaultCreateOptions?: DefaultCreateOptions<unknown>
): UseBoundStore<TState, CustomStoreApi> {
   ...
}
```
this way is scalable if we want to add another default parameter.
Then, instead of passing to the `useStore` the `Object.is` function, we can pass `equalityFnDef` that is:
```ts 
const equalityFnDef = defaultCreateOptions?.equalityFn ?? Object.is
```

Working on avoiding the `unknown` on `DefaultCreateOptions`.

Like @looeee said, it could be helpful to have a set of defaults so if you are interested let me know and I'll work on it a little more!

**Comment by dai-shi** [comment]
Please make it a middleware or a wrapper instead of modifying the core.
You want to work on it after #662 lands, or v4 lands. Things are changing.
At this point, I'm not sure if that'd fit in official middleware / docs, or third-party library, but I understand the use case.

**Comment by looeee** [comment]
@kasugaicrow Yeah, this is exactly what I had in mind. 

``` ts
const useStore = create<CounterState>(
  (set) => ({
    count: 0,
    inc: () => set((state) => ({ count: state.count + 1 })),
  }),
  { equalityFn: shallow }
)
```

@dai-shi what is the issue with adding options as the second parameter for `create`?

> Would creating another wrapping hook help?

``` ts
const useStoreBase = create(...)
export const useStore = (selector) => useStoreBase(selector, shallow)
```

If this works it's a nice solution too. However, it's non-obvious - it's not something most people would ever think of doing (at least I wouldn't 😅).

**Comment by dai-shi** [comment]
> If this works it's a nice solution too. However, it's non-obvious - it's not something most people would ever think of doing

Oh... I thought it's very obvious. We could add docs about wrapping with custom hooks. This should be very powerful, not only for this use case.

> what is the issue with adding options as the second parameter for create?

It increases bundle size. For enhancing features like this, middleware is the way already provided, or a wrapper like that.

**Comment by looeee** [comment]
> It increases bundle size. 

Yeah that makes sense.  But a counterargument is that too much middleware makes for some ugly nesting 

``` s
const usStore = create<
	State,
	SetState<State>,
	GetState<State>,
	StoreApiWithSubscribeWithSelector<State>
>(
	subscribeWithSelector(persist(useShallow(combine(immer((set, get) => {}))), {});
``` 
 > Oh... I thought it's very obvious. 
 
Probably because you are an expert in React state management and I am but a struggling beginner 😅

**Comment by looeee** [comment]
I've tried implementing this: 

``` ts
const useStoreBase = create(...)
export const useStore = (selector) => useStoreBase(selector, shallow)
```

Using a real (simplified) store from my app: 

``` ts
import create from 'zustand';

interface ControlState {
	sidebarOpen: boolean;
}

export const useControlStore = create<ControlState>(() => ({
	sidebarOpen: false,
}));
```

I'm using it to set a toggle to open or closed:

``` jsx
const sidebarOpen = useControlStore((state) => state.sidebarOpen);

return <Toggle
    toggled={sidebarOpen}
/>
```

I converted it to look like this:

``` ts
import create from 'zustand';
import shallow from 'zustand/shallow';

interface ControlState {
	sidebarOpen: boolean;
}

export const useControlStoreBase = create<ControlState>(() => ({
	sidebarOpen: false,
}));

export const useControlStore = (selector) => useControlStoreBase(selector, shallow);
```

However this results `Type 'unknown' is not assignable to type 'boolean'` error within the `Toggle` component. Seems like the type of useControl store us now returned as `unknown`, I can't call `useControlStore.getState`, `useControlStore .setState` or access any properties from it. 

I spent a while trying to get types to work, for example:

``` ts
export const useControlStore = (selector):ControlState => useControlStoreBase(selector, shallow);
```

Or 

``` ts
const sidebarOpen = useControlStore((state:ControlState) => state.sidebarOpen);
	
<Toggle
    toggled={sidebarOpen as boolean }
/>
```

But unfortunately this is beyond my typescript ability and I haven't been able to find a solution.

**Comment by kasugaicrow** [comment]
> You want to work on it after #662 lands, or v4 lands. Things are changing.

@dai-shi cool, I'll came back to work on a middleware on the next relase. Thanks!

@looeee I think you have to type the `selector` as `StateSelector` of the `ControlState` and a generic, that is a field of your `ControlState`
```ts
export const useControlStore = <K>(
  selector: StateSelector<ControlState, K>
) => useControlStoreBase(selector, shallow)
```

This way on the component's side it works
```ts
const sidebarOpen = useControlStore((state) => state.sidebarOpen)
return <Toggle toggled={sidebarOpen} />
```

**Comment by dai-shi** [comment]
> oh, I just noticed in the docs that I can use ramda pipe with middleware. That would make this nicer. Is it possible to pipe middleware like persist that has an options object?

pipe works in JS. typing can be tricky. The options object has to be contained. Some discussions in #224.

> I can't call useControlStore.getState, useControlStore .setState or access any properties from it.

To this, it would require:
```js
const useStoreBase = create(...)
export const useStore = (selector) => useStoreBase(selector, shallow)
Object.assign(useStore, useStoreBase)
```
(I haven't tried, and I agree this is not obvious.)

> But unfortunately this is beyond my typescript ability and I haven't been able to find a solution.

Yeah, typing is hard. It's the hardest part in zustand.

If we are fine to lie a little bit, this should be easy:
```ts
const useStoreBase = create(...)
export const useStore = ((selector) => useStoreBase(selector, shallow)) as typeof useStoreBase
Object.assign(useStore, useStoreBase)
```

`StateSelector` @kasugaicrow suggested might also work.

**Comment by looeee** [comment]
> ``` ts
> export const useControlStore = <K>(
>  selector: StateSelector<ControlState, K>
> ) => useControlStoreBase(selector, shallow)
> This way on the component's side it works

> ``` ts
> const sidebarOpen = useControlStore((state) => state.sidebarOpen)
> return <Toggle toggled={sidebarOpen} />
> ```

This does work for the `sideBarOpen` property. However other stuff is still broken, for example I cannot access `getState`

> Property 'getState' does not exist on type '<K>(selector: StateSelector<UIState, K>) => K'.

However, if I refactor out uses of get/setState this seems to work.

**Comment by looeee** [comment]
> If we are fine to lie a little bit, this should be easy:

``` ts
> const useStoreBase = create(...)
>  export const useStore = ((selector) => useStoreBase(selector, shallow)) as typeof useStoreBase
> Object.assign(useStore, useStoreBase)
```

This does seem to work immediately. And I'm fine with a little lie :)

**Comment by dai-shi** [comment]
Oh, so you are using subscribeWithSelector middleware.
You want to grab it and customize on your end.
```js
const subscribeWithSelector = (fn) => (set, get, api) => {
  const origSubscribe = api.subscribe
  api.subscribe = (selector, listener, equalityFn) => {
    if (selector || equalityFn) {
      const origListener = listener
      selector = selector || s => s
      equalityFn = equalityFn || shallow
      let currentSlice = selector(api.getState())
      listener = (state) => {
        const nextSlice = selector(state)
        if (!equalityFn(currentSlice, nextSlice)) {
          const previousSlice = currentSlice
          origListener((currentSlice = nextSlice), previousSlice)
        }
      }
    }
    return origSubscribe(listener)
  }
  const initialState = fn(set, get, api)
  return initialState
}

const useStoreBase = create(subscribeWithSelector(...))
export const useStore = (selector, equalityFn = shallow) => useStoreBase(selector, equalityFn)
Object.assign(useStore, useStoreBase)
```
☝️ This works in JS.

---

Hm, but wait, you don't need to replace it fully.

```ts
import create from 'zustand'
import { subscribeWithSelector } from 'zustand/middleware'
import shallow from 'zustand/shallow'

const useStoreBase = create<...>(subscribeWithSelector(...))
export const useStore = ((selector, equalityFn = shallow) => useStoreBase(selector, equalityFn)) as typeof useStoreBase
Object.assign(useStore, useStoreBase, {
  subscribe: (selector, listener, equalityFn = shallow) => useStoreBase.subscribe(selector, listener, equalityFn)
})
```
☝️ This should work with types.
And, actually, it doesn't lie with types.

**Comment by looeee** [comment]
> Oh, so you are using subscribeWithSelector middleware.

Yeah, I do think a solution to this should work with any of the middleware. 

I tried your latest suggestion and it works with a minor change:

``` ts
const useStoreBase = create<...>(subscribeWithSelector(...))
export const useStore = ((selector, equalityFn = shallow) => useStoreBase(selector, equalityFn)) as typeof useStoreBase
Object.assign(useStore, useStoreBase, {
  subscribe: (selector, listener) => useStoreBase.subscribe(selector, listener, { equalityFn: shallow })
})
```

Overall though I still don't think this is a very clear or obvious solution. Maybe it would be best to wait for the V4 release and then revisit this?

**Comment by dai-shi** [comment]
Ah, I forgot that the third argument is an option object.

I agree it's not obvious, but we don't plan to add anything in core. So, it will be docs or middleware/wrapper issue. v4 will hopefully help typing things, but the architecture will be the same. (there's a chance that middleware coordinates each other. we do it for `redux` and `devtools`.) Yeah, let's revisit it later.

**Comment by dai-shi** [comment]
So, here's untested middleware `customEqualityFn`.

```ts
// customEqualityFn.ts
import {
  EqualityChecker,
  SetState,
  State,
  StateCreator,
  StoreMutatorIdentifier,
} from 'zustand'

type Options<T extends State> = {
  equalityFn: EqualityChecker<T>
}

type CustomEqualityFn = <
  T extends State,
  Mps extends [StoreMutatorIdentifier, unknown][] = [],
  Mcs extends [StoreMutatorIdentifier, unknown][] = []
>(
  initializer: StateCreator<T, Mps, Mcs>,
  options: Options<T>
) => StateCreator<T, Mps, Mcs>

type PopArgument<T extends (...a: never[]) => unknown> = T extends (
  ...a: [...infer A, infer _]
) => infer R
  ? (...a: A) => R
  : never

type CustomEqualityFnImpl = <T extends State>(
  storeInitializer: PopArgument<StateCreator<T, [], []>>,
  options: Options<T>
) => PopArgument<StateCreator<T, [], []>>

const customEqualityFnImpl: CustomEqualityFnImpl =
  (fn, options) => (set, get, api) => {
    type S = ReturnType<typeof fn>
    const origSetState = api.setState as SetState<S>
    api.setState = (partial, replace) => {
      const state = api.getState()
      const partialState =
        typeof partial === 'function'
          ? (partial as (state: S) => S)(state)
          : partial
      const nextState = replace
        ? (partialState as S)
        : Object.assign({}, state, partialState)
      if (!options.equalityFn(state, nextState)) {
        origSetState(partial, replace)
      }
    }
    const initialState = fn(set, get, api)
    return initialState
  }

export const customEqualityFn =
  customEqualityFnImpl as unknown as CustomEqualityFn
```

This replaces the default `setState` behavior with `equalityFn`.
Unfortunately this is sub optimal.
- It doesn't replace `useStore`'s equalityFn.
- It doesn't replace `subscribeWithSelector`'s equalityFn.

Adding full feature would be fairly complicated and will not be widely used (as our recommendation is the default behavior), so I'd claim this is an open field for third-party libraries, and close this issue.

**Comment by ehynds** [comment]
For anyone looking to use the wrapper approach and are wondering what to replace the deprecated `StateSelector` with, this works:

```tsx
const useBearStore = create<State>()( ... );

const useShallowBearStore = <U>(selector: (state: State) => U) => {
  return useDraftEntryStore(selector, shallow);
};
```

**Comment by Carnageous** [comment]
> @kasugaicrow Yeah, this is exactly what I had in mind.
> 
> ```ts
> const useStore = create<CounterState>(
>   (set) => ({
>     count: 0,
>     inc: () => set((state) => ({ count: state.count + 1 })),
>   }),
>   { equalityFn: shallow }
> )
> ```
> 
> @dai-shi what is the issue with adding options as the second parameter for `create`?
> 
> > Would creating another wrapping hook help?
> 
> ```ts
> const useStoreBase = create(...)
> export const useStore = (selector) => useStoreBase(selector, shallow)
> ```
> 
> If this works it's a nice solution too. However, it's non-obvious - it's not something most people would ever think of doing (at least I wouldn't 😅).

I'm sorry to bump this issue, but was there any middleware or API added to Zustand that allows to set the default comparison function to shallow?
We just migrated a v3 codebase to v4 and were pretty suprised by this rather big change. We now have to add "shallow" to hundreds of store selects, and a middleware would be a lot cleaner.

**Comment by dai-shi** [comment]
You can specify custom equality function to the store hook. From the latest v3 to v4, there are no changes in JS except for deprecation (is it what you see?). There are big changes in TS, though.

> We now have to add "shallow" to hundreds of store selects

It sounds like some mistakes.

**Comment by Carnageous** [comment]
> You can specify custom equality function to the store hook. From the latest v3 to v4, there are no changes in JS except for deprecation (is it what you see?). There are big changes in TS, though.
> 
> > We now have to add "shallow" to hundreds of store selects
> 
> It sounds like some mistakes.

Thank you @dai-shi for the very fast reply. And you were right. it was a mistake on our side. I was sure that selecing store slices with `const [count, setCount] = useCountStore(s => [s.count, s.setCount]` would only re-render the component when either `count` or `setCount` changes, but it does that on every store change. In the README for v4 you clearly say that, so I should have read that.

Anyways, would you be so kind to point me to the docs on how to specify the equality function when creating a store, not while consuming it? I would like `shallow` to be used by default for all stores, if that's possible. Cannot find it on the "recipes" docs page.

**Comment by dai-shi** [comment]
@Carnageous It should do on every store change in v3 too. You need to do `const [count, setCount] = useCountStore(s => [s.count, s.setCount], shallow)` both in v3 and v4. (btw, my preference is is to use two hooks in two lines, mostly stylistic.)

**Comment by christian-gama** [comment]
I needed a wrapper for immer and set shallow as default. This is my result:

```
import _create, { type StateCreator } from 'zustand'
import { immer } from 'zustand/middleware/immer'
import shallow from 'zustand/shallow'

export const create = <T>(initializer: StateCreator<T, [['zustand/immer', never]]>) => {
	const useBaseStore = _create(immer(initializer))

	return <U>(selector?: (state: T) => U, equalityFn?: (left: U, right: U) => boolean) => {
		return useBaseStore(selector ?? ((state) => state as unknown as U), equalityFn ?? shallow)
	}
}
```

**Comment by Carnageous** [comment]
> I needed a wrapper for immer and set shallow as default. This is my result:

Thank you very much, this is what I wanted but I struggled with some of the typing.

And I did notice, that with this implementation I cannot use `.getState()` on the stores anymore. This is probably because we're wrapping/calling the baseStore hook and returning the result. This means all properties defined on the the return object of `_create` (the useBaseStore object) are not exposed, right?

**Comment by micah-redwood** [comment]
> Anyways, would you be so kind to point me to the docs on how to specify the equality function when creating a store, not while consuming it? I would like shallow to be used by default for all stores, and if possible not create a hook that wraps useStore with shallow

@Carnageous , I'm curious, were you able to find a suitable solution to avoid adding `shallow` to tons of hooks in your codebase?

> @Carnageous It should do on every store change in v3 too. You need to do const [count, setCount] = useCountStore(s => [s.count, s.setCount], shallow) both in v3 and v4. (btw, my preference is is to use two hooks in two lines, mostly stylistic.)

@dai-shi , I can see how using two lines instead of creating, comparing & destructuring an array makes sense when you're only using two state properties, but how do you handle more than two? Do you create a new line for each one, e.g.

```ts
const user = useUserStore(s => s.user);
const signOut = useUserStore(s => s.signOut);
const signIn = useUserStore(s => s.signIn);
const lastSignInDate = useUserStore(s => s.lastSignInDate);
```

In the years I've used Zustand, I very often find myself using 2 or more properties from a store in each of my components, and it's easy to forget `shallow`. The current recommended solution appears to work (without middleware anyway), but it feels a bit icky to have to do this for every store...

```ts
const useUserStore = create<UserState>((set) => ({
  ...
}));

// Enforce shallow comparison
export const useShallowUserStore = (<U>(selector: (state: UserState) => U) => {
  return useUserStore(selector, shallow);
}) as typeof useUserStore;

// Add other properties (e.g. getState(), setState())
Object.assign(useShallowUserStore, useUserStore);
```

Is there something obvious I'm missing? Thanks!

**Comment by dai-shi** [comment]
@micah-redwood 
I think you are on the right track, and what you do is just correct.
You could create your own `create` function if you feel repetitive.

I personally think `shallow` is very optional. I just don't use it. [I'm not alone.](https://tkdodo.eu/blog/working-with-zustand)
If the performance is a real concern, we could/should consider memoizing selector functions.
And, I can also suggest extracting actions from state without using the hook,
```js
const { signIn, signOut } = useUserStore.getState();
```
or this: https://github.com/pmndrs/zustand/blob/main/docs/guides/practice-with-no-store-actions.md

**Comment by Carnageous** [comment]
> @Carnageous , I'm curious, were you able to find a suitable solution to avoid adding `shallow` to tons of hooks in your codebase?

I was not entirely, but the answer @christian-gama posted was very close to what I needed. Combining this with `Object.assign()` or `Object.create()` + `Object.getPrototypeOf` would have probably worked. I ended up only using `shallow` at places where it was really needed, but realized that often when I needed it, my stores were just not atomic enough (see TkDodo's blog post).

**Comment by dustinlacewell** [comment]
Stumbling upon this thread years later, the take away seems to suggest that Jotai is what people, including the author of Zustand, is actually looking for.
