### ISSUE TITLE
ReferenceError when using devtools middleware

### ISSUE THREAD

**Issue by ruvkr** [pmndrs/zustand#694]
Hi, I'm getting `ReferenceError: Cannot access 'useStore' before initialization` when using zustand(3.6.6) with devtools middleware in a Nextjs project created using create-next-app.

Steps to reproduce:
1. `npx create-next-app zustand-test`
2. `cd zustand-test`
3. `npm i zustand`
4. Replace `/pages/index.js` with [index.js] and add `store.js` with [store.js]
5. `npm run dev` or `npm run build`

[index.js]
```js
import { useStore } from '../store';

const Home = () => {
  const value = useStore(s => s.value);
  return <div>{value}</div>;
};

export default Home;
```
[store.js]
```js
import create from 'zustand';
import { devtools } from 'zustand/middleware';

const createStore = () => ({
  value: 10,
});

export const useStore = create(devtools(createStore));
```
![ReferenceError](https://user-images.githubusercontent.com/34903858/144757541-dbbb47a8-eac1-4972-a00a-059ef3d55939.png)

**Comment by ruvkr** [comment]
Also getting `ReferenceError: window is not defined` after merging `store.js` and `index.js`

[index.js]
```js
import create from 'zustand';
import { devtools } from 'zustand/middleware';

const createStore = () => ({
  value: 10,
});

const useStore = create(devtools(createStore));

const Home = () => {
  const value = useStore(s => s.value);
  return <div>{value}</div>;
};

export default Home;
```
![Window](https://user-images.githubusercontent.com/34903858/144757750-a5701f54-2d1a-43bd-8726-22cfb03ff541.png)

**Comment by dai-shi** [comment]
Thanks for reporting. #693 will resolve undefined window issue.

Can you try the codesandbox build?
https://ci.codesandbox.io/status/pmndrs/zustand/pr/693
☝️ See "Local Install Instructions"

**Comment by ruvkr** [comment]
@dai-shi both the issues are fixed in the codesandbox build.
https://codesandbox.io/s/next-js-forked-su90m?file=/pages/index.js
https://codesandbox.io/s/next-js-forked-6ypbm?file=/pages/index.js
Thank you for fixing this

**Comment by dai-shi** [comment]
https://github.com/pmndrs/zustand/releases/tag/v3.6.7

**Comment by Ic3b3rg** [comment]
I have a similar error. Trying to call the `useStore `in the Next.js index page gives me the same error.
How can I solve?
Am I doing something wrong or is it a problem with the library?

```
"dependencies": {
    "next": "^12.0.9",
    "next-seo": "^4.29.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "styled-jsx-plugin-postcss": "^4.0.1",
    "web3": "^1.7.0",
    "zustand": "^3.6.9"
  },
```


<img width="575" alt="Immagine 2022-02-22 123115" src="https://user-images.githubusercontent.com/61518840/155123772-28868e79-8531-4109-bea9-a1df7ad7e209.png">

**Comment by dai-shi** [comment]
Can you try downgrading nextjs and see if the problem persists?

**Comment by Ic3b3rg** [comment]
@dai-shi  which version should I bring it to?

**Comment by Ic3b3rg** [comment]
@dai-shi i tried to bring Next to version @ 11.1.4 and it breaks the whole application with many other errors. :(

**Comment by dai-shi** [comment]
> @dai-shi which version should I bring it to?

how about `next@12.0.1`?

**Comment by Ic3b3rg** [comment]
@dai-shi Now it disappeared by itself without changing version however it is a blocking error it would be nice if you fix it.

**Comment by Ic3b3rg** [comment]
@dai-shi when the error came out it was version `12.0.9` then I moved to `11.1.4` where I had many other errors then I went back to `12.0.9` and the problem solved itself.  I don't understand what the problem is due to honestly.

**Comment by dai-shi** [comment]
oh, okay. then, there's nothing actionable. please open a new issue if you can reproduce the error.
