### ISSUE TITLE
add storage event listener for persist

### ISSUE THREAD

**Issue by souporserious** [pmndrs/zustand#714]
Hello, I'm working on a project that uses local storage and wondering if it makes sense for the `persist` middleware to subscribe to the window `storage` event if local storage is being used? This would make sure any other open browser windows will get the update. Right now I'm subscribing and parsing through `useEffect` which is fine, but would be cool if it was baked in. I'm happy to work on a PR for this if it sounds good 😄 

```js
React.useEffect(() => {
  function handleStorage(event) {
    if (event.key === 'playground') {
      const { state } = JSON.parse(event.newValue)
      setPosition(state.position)
    }
  }
  window.addEventListener('storage', handleStorage)
  return () => {
    window.removeEventListener('storage', handleStorage)
  }
}, [])
```

**Comment by dai-shi** [comment]
(Linking to another issue in jotai for my reference: https://github.com/pmndrs/jotai/issues/882 )

**Comment by garganurag89** [comment]
Hi, Can we have this feature please jotai has already added this.

**Comment by dai-shi** [comment]
Would you like to work on it??

**Comment by tbor00** [comment]
Hi, i open [PR](https://github.com/pmndrs/zustand/pull/1075) for this
