### ISSUE TITLE
Question: Why do hooks useRef instead of useState

### ISSUE THREAD

**Issue by mfbx9da4** [pmndrs/zustand#719]
I've noticed for a [few](https://github.com/ctrlplusb/easy-peasy/blob/5c4c0e8e0a708e0c218f82d0a89aa679d1f44dcb/src/hooks.js#L79) state libraries, [including zustand](https://github.com/pmndrs/zustand/blob/c319075d8c152b59054de78ca6051e3d22b7c62f/src/react.ts#L138), use `useRef`, diff the previous value and then forceRender(), instead of leaving this to `useState` which does all this for free. Why is that?

My guess it's something to do with isomorphic layouts?

**Comment by dai-shi** [comment]
basically, it's to support inline (non-memoized) selectors (and to avoid re-subscribing when selectors change).

with #550, we no longer have explicit useRef.

**Comment by mfbx9da4** [comment]
But can't you support non-memoized selectors like so

```
function useStore(selector) {
  const ref = useRef({ selector }).current;
  ref.selector = selector;
  const [state, setState] = useState(selector(value));
  useEffect(() => subscribe((x) => setState(ref.selector(x))), []);
  return useMemo(() => [state, set], [state]);
}
```

**Comment by dai-shi** [comment]
no, you want to support changing the selector. `useStore(state => state[props.key])`

**Comment by mfbx9da4** [comment]
Ah gotcha! The resulting state will be stale until the underlying state itself changes.
