### ISSUE TITLE
[Devtools middleware] undefined is not an object

### ISSUE THREAD

**Issue by fristyr** [pmndrs/zustand#723]
After update zustand - "zustand": "^3.6.7"
I get red error 

<img width="926" alt="Screenshot 2021-12-23 at 13 54 47" src="https://user-images.githubusercontent.com/33237937/147243384-00434d5a-e70b-4f3d-b5fc-e6d74fb24dc4.png">

**Comment by dai-shi** [comment]
@fristyr Ah, so it's RN. Thanks for reporting.

@devanshj I feel like we should revert to try-catch in any case. It's safer. I'll create a PR.

**Comment by dai-shi** [comment]
https://ci.codesandbox.io/status/pmndrs/zustand/pr/724
@fristyr can you try this? find "Local Install Instructions" ☝️

**Comment by fristyr** [comment]
Yep!

**Comment by fristyr** [comment]
@dai-shi Yes I can confirm the red box is gone. Sorry didn’t specify from start that I am using in in React Native
