### ISSUE TITLE
On Suspense

### ISSUE THREAD

**Issue by phaistonian** [pmndrs/zustand#733]
Hello,

Since 18 is already here, I am wondering if there's any suggested － or "planned" － way for Zustand to work, the proper way, with `Suspense`.

Merry Christmas to you all! 🎉

**Comment by dai-shi** [comment]
Good question. Suspense for Data Fetching will still not be finalized in 18.0.0, so not sure if we can do anything officially. Besides, zustand library doesn't deal anything with async stuff at the moment. It will be something totally new concept. What would people expect with Suspense?

Merry Christmas!

**Comment by dai-shi** [comment]
In case somebody doesn't know, other two libs [jotai](https://github.com/pmndrs/jotai) and [valtio](https://github.com/pmndrs/valtio) support Suspense. So, there's something we can learn.

**Comment by phaistonian** [comment]
@dai-shi perhaps [useSyncExternalStore](https://github.com/reactwg/react-18/discussions/86) is the _proper_ way to go.

> Our goal is for all subscription-based libraries to migrate their implementations to useSyncExternalStore.

**Comment by dai-shi** [comment]
Ah, you just mean to support React 18 in general.
#550 has been there for 4 months. We will release v4 when everything is ready.
(https://github.com/reactwg/react-18/discussions/86 is open Aug 28 and #550 is created Aug 31 right after that even before uSES is actually implemented!)
Stay tuned!
