### ISSUE TITLE
How to get ReturnType from store?

### ISSUE THREAD

**Issue by benjick** [pmndrs/zustand#736]
With the following code:

```ts
import create from "zustand";
import { combine } from "zustand/middleware";

const useStore = create(
  combine({ bears: 0 }, (set) => ({
    increase: (by: number) => set((state) => ({ bears: state.bears + by }))
  }))
);

type Type = ReturnType<typeof useStore>;
```

`Type` will be typed as  `unknown`. Is this fixable somehow?

**Comment by dai-shi** [comment]
https://codesandbox.io/s/charming-currying-erfwc?file=/src/App.tsx
Hm, maybe it's not possible. It's overloaded and unless you specify a selector, we don't have a concrete return type.

**Comment by benjick** [comment]
I understand, thanks for the quick reply!

**Comment by devanshj** [comment]
Here's how you do it... https://tsplay.dev/WG6r9m I hope this is what you were looking for

```ts
import create, { UseBoundStore } from "zustand";
import { combine } from "zustand/middleware";

const useStore = create(
  combine({ bears: 0 }, (set) => ({
    increase: (by: number) => set((state) => ({ bears: state.bears + by }))
  }))
);

type Type = typeof useStore extends UseBoundStore<infer T> ? T : never
```

**Comment by dai-shi** [comment]
Found another solution: https://tsplay.dev/WzA8rm
```ts
class Wrapper {
  f() {
    return useStore();
  }
}
type Type = ReturnType<Wrapper["f"]>;
```

**Comment by benjick** [comment]
Hey, thank you! I appreciate the help!

**Comment by vorant94** [comment]
@devanshj doesn't seem to work in my case

here is the code. the only thing i changed is `create` isn't a default export anymore

```ts
import {create, UseBoundStore } from "zustand";
import { combine } from "zustand/middleware";

const useStore = create(
  combine({ bears: 0 }, (set) => ({
    increase: (by: number) => set((state) => ({ bears: state.bears + by }))
  }))
);

type Type = typeof useStore extends UseBoundStore<infer T> ? T : never
//     ^?


declare var state: Type;

state.
```

here is TS autocomplete not giving back type of the store meaning something like that `{bears: number, increase: (by: number) => ...}`

<img width="698" alt="Screenshot 2024-12-31 at 17 11 27" src="https://github.com/user-attachments/assets/59c3e0e1-3b90-4dd8-99a2-71f51b6a6d36" />

**Comment by dai-shi** [comment]
@vorant94 Would you like to open a new discussion with the typescript playground link?

**Comment by vorant94** [comment]
yeah, this is the one
