### ISSUE TITLE
Add Icon to enrich your brand

### ISSUE THREAD

**Issue by YeonV** [pmndrs/zustand#739]
Broos, first of all: AMAZING project!

I know it sounds stupid and marketing-like, 
but i suggest to add a brand icon.

Besides all advantages like growing your degree of awareness,
we could use your icon for several things. 
like your website or in readme files like:

![lcon](https://img.shields.io/badge/React-StateManagement-blue.svg?logo=React&logoColor=white&label=Zustand)

Of course this is totally unimportant, but would spice it up a bit :)

**Comment by dai-shi** [comment]
Thanks for the suggestion. I'm not exactly sure what to do. btw, our bear mascot is already popular.
Leaving this open for a while for others to share some thoughts.

**Comment by DanielPower** [comment]
For the time being in something like a Github badge, people could use the 🐻  emoji. 

A Zustand icon that looks good at various sizes would be neat. Perhaps something similar to 🐻  but stylized to look more like the mascot?

**Comment by dai-shi** [comment]
btw, i use [this](https://github.com/pmndrs/zustand/blob/8aefb6b1c7195992c0868cb614ce1f66e7774649/bear.png) for the repository's social preview.

closing this. feel free to add comments here or open a new discussion.

**Comment by YeonV** [comment]
@dai-shi 


![zustand_small](https://user-images.githubusercontent.com/28861537/149433422-0c228ac6-3239-4a29-a507-03700e1c5cc3.png)
