### ISSUE TITLE
does returning get() to chain commands come with a performance impact?

### ISSUE THREAD

**Issue by agcty** [pmndrs/zustand#741]
I'm trying to build a store that lets me chain calls together

Something like:

```jsx
const useMyStore((state) => state.showOrHide)
showOrHide().removeMultiple(["id1", "id2"]).add("id3")
```

technically, in the store every function would just return get()

```jsx
showOrHide: (element) => {
  // if the element is already open, close it
  if (get().isOpen(element)) {
    get().remove(element)
    // else just show it
  } else {
    get().add(element as Draft<T>)
  }
  return get()
}
```

However, not sure if that is incredibly imperformant

**Comment by dai-shi** [comment]
There's no magic behind `get()`.

https://github.com/pmndrs/zustand/blob/1dce3d2f140374630c4a64a897858e9308379c37/src/vanilla.ts#L105

No, it shouldn't impact the performance.

**Comment by agcty** [comment]
@dai-shi your response time is absolutely amazing, thanks!
