### ISSUE TITLE
Inconsistent typing between zustand and zustand/vanilla

### ISSUE THREAD

**Issue by Bartozzz** [pmndrs/zustand#748]
If we pass the `StoreApi` created with `zustand/vanilla` as an argument to the `create` method from `zustand`, the typing is incorrectly inferred.

### `zustand`

```tsx
import create from "zustand";

const useStore = create(
  combine(
    {
      bears: 0,
    },
    (set) => ({
      increase: (by: number) => set((state) => ({ bears: state.bears + by })),
    })
  )
);

useStore((state) => state.bears); // ✅ number
```

### `zustand/vanilla` + `zustand`

```tsx
import create from "zustand";
import createVanilla from "zustand/vanilla";

const vanillaStore = createVanilla(
  combine(
    {
      bears: 0,
    },
    (set) => ({
      increase: (by: number) => set((state) => ({ bears: state.bears + by })),
    })
  )
);

const useVanillaStore = create(vanillaStore);

useVanillaStore((state) => state.bears); // ❎ Property 'bears' does not exist on type 'object'
```

The expected type is `number`.

---

Tested on `v3.6.9`. It was working properly on `v3.4.1`.

**Comment by dai-shi** [comment]
Thanks for reporting!

> Tested on `v3.6.9`. It was working properly on `v3.4.1`.

I assume it worked pre v3.6.0? The last one would be v3.5.14.

@devanshj Do you think v4 will cover this?

**Comment by devanshj** [comment]
Afk but probably yes, will confirm when I get to the keyboard.

**Comment by dai-shi** [comment]
Does v3.7.0 help? Unlikely.

**Comment by dai-shi** [comment]
@Bartozzz Would you like to confirm if it's fixed in the latest version?

**Comment by Bartozzz** [comment]
It works fine on my end too! Thanks 👍🏻
