### ISSUE TITLE
Can't use devtools with Typed store

### ISSUE THREAD

**Issue by saif399** [pmndrs/zustand#755]
hey guys and thanks for all the effort you are putting on this amazing project,

my issue is simple, i want to use typescript & devtools on stores
![Screenshot 2022-01-14 215913](https://user-images.githubusercontent.com/92998703/149577392-9a01ed74-4b5f-4ce3-9080-0eecf7862adc.png)

currently i'm using the commented line, but i'd like to have the first line working. any help please?

**Comment by dai-shi** [comment]
Please see some typing examples in `tests/middlewareTypes.test.tsx`.
Typing with middleware is tricky currently. We are working to fix them in v4.

**Comment by saif399** [comment]
@dai-shi  Thanks for helping,
i did this and now it showing more errors :( 
![image](https://user-images.githubusercontent.com/92998703/149620499-1132f46e-1f9f-4704-97c2-386e3fcecebf.png)

**Comment by dai-shi** [comment]
Assuming you already have userStore typed, does `create(devtools(userStore))` work?

**Comment by saif399** [comment]
@dai-shi  it was my first try, but no it didn't work

**Comment by saif399** [comment]
@dai-shi  without a type yeah it did work

**Comment by Hirbod** [comment]
I was also unable to type with `zustandFlipper`, a wrapper around Flipper

```tsx
export const useStore = create<IStore>(
  zustandFlipper(
    //@ts-ignore
    persist(
      (set, get, api) => ({
        ...createLoginSlice(
          set as unknown as SetState<ILoginSlice>,
          get as unknown as GetState<ILoginSlice>,
          api as unknown as StoreApi<ILoginSlice>,
        ),
        ...createThemeSlice(
          set as unknown as SetState<IThemeSlice>,
          get as unknown as GetState<IThemeSlice>,
          api as unknown as StoreApi<IThemeSlice>,
        ),
        ...createSettingsSlice(
          set as unknown as SetState<ISettingsSlice>,
          get as unknown as GetState<ISettingsSlice>,
          api as unknown as StoreApi<ISettingsSlice>,
        ),
      }),
      {
        name: 'app-storage',
        getStorage: () => mmkvStorage,
      },
    )
  )
);
```

**Comment by dai-shi** [comment]
v3.7.0 changed some typing. Please see `tests/middlewareTypes.test.tsx` and if someone has a question, open [a new discussion](https://github.com/pmndrs/zustand/discussions/new). Closing this.

**Comment by anastely** [comment]
Hey @hirbod Sorry maybe it's not related
But how did you integrate [mmkv](https://github.com/mrousavy/react-native-mmkv) here?

can you please share the value of `mmkvStorage`?

**Comment by hirbod** [comment]
Even though the message was removed (I do have the email though :D).
Here is how I did implement it with mmkv:

```tsx
// storageInstance.ts
import { MMKV } from 'react-native-mmkv'
export const storage = new MMKV();


// mmkvStorage.ts
import { storage } from './storageInstance';

export interface ZustandStorage {
    getItem: (name: string) => string | null | Promise<string | null>
    setItem: (name: string, value: string) => void | Promise<void>
    removeItem: (name: string) => void | Promise<void>
}

export const mmkvStorage: ZustandStorage = {
    setItem: (key, value) => storage.set(key, value),
    getItem: (key) => storage.getString(key) || null,
    removeItem: (key) => storage.delete(key)
}
```

**Comment by anastely** [comment]
Hey @hirbod, I'm trying to use your `mmkvStorage` in the last version of zustand 

but I got this error
```
Error: Value is undefined, expected an Object
    at MMKV.set (native)
```
if you use the last v of zustand can you tell me how you solve this issue?

```

import {create} from 'zustand';
import {createJSONStorage, persist} from 'zustand/middleware';
import {zustandStorage} from '../util/Storage';

export const useEmployeeInfoStore = create(
  persist(
    set => ({
      employeeInfo: null,
      setEmployeeInfo: employeeInfo => set({employeeInfo}),
    }),
    {
      name: 'employeeInfo-local',
      storage: createJSONStorage(() => zustandStorage),
    },
  ),
);
```
