### ISSUE TITLE
[TypeScript] subscribe shows as deprecated even when using middleware...

### ISSUE THREAD

**Issue by schoening** [pmndrs/zustand#760]
I am using `zustand/vanilla` and with the 3.6.0 changes my subscribe function is showing depricated even after importing the middleware:

```
export const trackStore = create<TrackState>(
  subscribeWithSelector((set, get) => ({
    tracks: [],
    actions: {
      setVisibleTracks: (trackIds: number[]) => {
        console.log('trackIds:', trackIds)
        set(
          produce((draft: TrackState) => {
            draft.tracks = trackIds
          }),
        )
      },
    },
  })),
)
```

Is Zustand moving into only supporting React or is this a temporary problem?

**Comment by dai-shi** [comment]
Vanilla version and React version should be the same in this case.
Is this TypeScript only issue? If so, please see `middlewareTypes.test.tsx` and find how to type it. This is an unfortunate workaround for v3.6 and we are looking for a fix in v4.

**Comment by schoening** [comment]
Ok thanks for the quick reply. I'm gonna lock my package to the previous version until v4.

**Comment by dai-shi** [comment]
Note that v4 will come with some breaking changes and for the migration, the recommendation will be to upgrade to the latest v3.x before v4. But, you can do that later.
