### ISSUE TITLE
How to overwrite localStorage when initial value has been changed?

### ISSUE THREAD

**Issue by SeongwoonHong** [pmndrs/zustand#763]
for instance, this is how my local storage looks like
```
{ name: 'John' }
```

but when I pass a prop to state object I want my component to be reactive so it uses the new value that was passed via prop. But since zustand uses values from local storage, it ignores the prop value.
Is there a way or is this a bad practice?

Thanks in advance!

**Comment by AnatoleLucet** [comment]
Hi. I'm not sure to understand. Could you give a reproducible example? 🙏

**Comment by SeongwoonHong** [comment]
this is being addressed in another issue ticket. Hence I'll close this one :) 
https://github.com/pmndrs/zustand/issues/766
