### ISSUE TITLE
Proper arguments are not printed when using log middleware + Persist middleware not persisting functions

### ISSUE THREAD

**Issue by SeongwoonHong** [pmndrs/zustand#766]
I have set up log/immer middleware like the documentation. However, when I trigger a function from the store, the arguments on the log are not properly printed. I get something like "ƒ (n){var r=this;void 0===n&&(n=u);for(var t=arguments.length,e=Array(t>1?t-1:0),o=1;o<t;o++)e[o-1]=arguments[o];return a.produce(n,(function(n){var t;return(t=i).call.apply(t,[r,n].concat(e))}))}" 
get() part looks good on my end though.

Please let me know if I missed anything!
Thanks in advance!

```
import produce from 'immer';
import create, { SetState } from 'zustand';
import createContext from 'zustand/context';

const log = config => (set, get, api) =>
  config(
    (args) => {
      console.log(
        'payload: ',
        args,
      );
      console.log(
        'New State: ',
        get(),
      );
      set(args);
    },
    get,
    api,
  );

const immer = config => (set, get, api) =>
  config(
    (partial, replace) => {
      const nextState = typeof partial === 'function' ? produce(partial) : partial;
      return set(nextState, replace);
    },
    get,
    api,
  );
  
  const { Provider, useStore } = createContext();
  
  const createStore = () =>
    create(
      log(
        immer((set)=> {
          return {
            store: ...,
            props: ...,
            actions: {
              fetchRequest: () => {
                set(state => {
                  state.store.network.status = LOADING;
                });
              },
              },
            },
          };
        }),
      ),
    );
    
    <Provider createStore={createStore}>{children}</Provider>
```

**Comment by dai-shi** [comment]
What's your expected result to be logged?
Would you be able to create a minimal reproduction please? (Is createContext required to reproduce the issue?)

**Comment by SeongwoonHong** [comment]
@dai-shi I'd like to expect the result to be what is about to be changed if that's possible. and yes i use createContext to trigger the function from the store

in another component that is in another file, which belongs to Provider 
```
import { useStore } from ' ...'
...
const { actions } = useStore();
const { fetchRequest } = actions;
useEffect(() => {
  fetchRequest()
}, [])
```

**Comment by dai-shi** [comment]
Can you create a codesandbox example to represent your issue? Please make it as minimal as possible. If you remove createContext and immer, does it still reproduce?

**Comment by SeongwoonHong** [comment]
> Can you create a codesandbox example to represent your issue? Please make it as minimal as possible. If you remove createContext and immer, does it still reproduce?

I'm able to put it together in CodeSandbox. https://codesandbox.io/s/beautiful-borg-z4lyo?file=/src/Builder/BuilderProvider.js

As I mentioned there, There are 2 issues.

 **First**,
 the log middleware isn't working properly. Nothing is being printed in this CodeSandbox example, However In my actual app, `Builder New State` part is printed correctly whereas  `Builder Payload` part is printing function body in the console. such as
  ```Builder Payload: ƒ (n){var r=this;void 0===n&&(n=u);for(var t=arguments.length,e=Array(t>1?t-1:0),o=1;o<t;o++)e[o-1]=arguments[o];return a.produce(n,(function(n){var t;return(t=i).call.apply(t,[r,n].concat(e))}))}```
  The expected behaviour I want is to see what's being passed to `set` function
  
![Screen Shot 2022-02-09 at 10 55 28 PM](https://user-images.githubusercontent.com/19713918/153334984-e22cc1a8-582f-4168-9e59-983af81c34a5.png)

  

   **The second issue** is (this is not reproducible in CodeSandbox as localStorage isn't available in codesandbox)
   If I un-comment the persist middleware,
   it doesn't persist **actions** object since it has functions.
   therefore in the localStorage, **actions** object is **ALWAYS** empty
  
  However, If I add a primitive value such as
  ```
  actions: {
     something: 55,       <-- 
     setText: () => {},
   }
   ```
  I'm able to see this value on localStorage but still no functions are available in localstorage.

**Comment by dai-shi** [comment]
> The expected behaviour I want is to see what's being passed to set function

I guess you would need to log inside immer middleware.
https://codesandbox.io/s/hungry-fast-66p5p?file=/src/Builder/BuilderProvider.js

See also: https://github.com/pmndrs/zustand/discussions/788#discussioncomment-2132755


> it doesn't persist **actions** object since it has functions.
> therefore in the localStorage, **actions** object is **ALWAYS** empty

This sounds correct. What do you expect to happen?

> I'm able to see this value on localStorage but still no functions are available in localstorage.

If you want to exclude the `actions` entirely in this case, the `partialize` option is for you. https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data#partialize

**Comment by SeongwoonHong** [comment]
> > The expected behaviour I want is to see what's being passed to set function
> 
> I guess you would need to log inside immer middleware. https://codesandbox.io/s/hungry-fast-66p5p?file=/src/Builder/BuilderProvider.js
> 
> See also: [#788 (comment)](https://github.com/pmndrs/zustand/discussions/788#discussioncomment-2132755)
> 
> > it doesn't persist **actions** object since it has functions.
> > therefore in the localStorage, **actions** object is **ALWAYS** empty
> 
> This sounds correct. What do you expect to happen?
> 
> > I'm able to see this value on localStorage but still no functions are available in localstorage.
> 
> If you want to exclude the `actions` entirely in this case, the `partialize` option is for you. https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data#partialize

Thank you for your response! really appreciate it. 
I have follow up questions.

1. Even after I put the log inside immer middleware, I'm unable to see payload. Is there a way to log what is being passed to `set` function ?

2. I'd like to persist `actions` object even though it has functions. I don't want to exclude that object. I want it to be persist just like the other objects being persist

Thank you so much!

**Comment by dai-shi** [comment]
1: Isn't "Hello World!" the payload?
<img width="334" alt="image" src="https://user-images.githubusercontent.com/490574/153535790-0c65a054-5e61-4b81-8431-b81f68d558d6.png">

2: It's impossible to serialize functions. You can provide `serialize` and `deserialize` options to have more control. See: https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data#serialize

**Comment by SeongwoonHong** [comment]
> https://codesandbox.io/s/hungry-fast-66p5p?file=/src/Builder/BuilderProvider.js

1. No that is printed by me manually console logging, not done by log middleware..
```
          actions: {
              setText: (payload, aa, bb) => {
                console.log("setText:", payload);
                set((store) => {
                  store.state.text = payload;
                });
              },
              setData: (payload) => {
                console.log("setDate:", payload);
                set((store) => {
                  store.state.data = payload;
                });
              }
```

2. I see. But since the functions are not serialized in localStorage, when my app is loaded, it doesn't work since it seems Zustand is trying to call the functions from localStorage first but my `actions` object is empty, not containing any functions. i'm getting such as `actions.setText is not a function`
In this case do you think I should provide `serialize` option? If so, I wonder how that works with very simple demo that has functions in a store and want to persist

**Comment by dai-shi** [comment]
> not done by log middleware

but, log middleware doesn't know the payload.

> localStorage stores the values like this,

yeah, but you can't store functions in localStorage unless you somehow serialize them.
I suggest to give up serializing it, but use `merge` option not to override your actions object. https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data#merge

**Comment by SeongwoonHong** [comment]
> > not done by log middleware
> 
> but, log middleware doesn't know the payload.
> 
> > localStorage stores the values like this,
> 
> yeah, but you can't store functions in localStorage unless you somehow serialize them. I suggest to give up serializing it, but use `merge` option not to override your actions object. https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data#merge

I see, Yes  I could maybe utilize the `merge` option! Thank you :)

About the log middleware not knowing the payload, So there's no way what function/action is triggered to change some value?
What's possible is to print old states and new states, is my understanding correct?
If my app is huge thus huge store and there are multiple setters changing different values on page load, I think it'd be great if we could know what action/setters are triggered at least without the payload, then we can closely look at the setter to see the value differences.
