### ISSUE TITLE
'devtools' is deprecated.

### ISSUE THREAD

**Issue by Ic3b3rg** [pmndrs/zustand#780]
Following the library README I saw how to use devtools to debug my application. I have implemented the devtools just like the guide says but from VSC it tells me that the devtools method is deprecated, is there a new way to use the devtools? Can I have some information about it? Thank you.
Below you will find my code.

```import create from "zustand";
import { devtools } from "zustand/middleware";
export const useStore = create(
  devtools((set: any) => ({
    address: "Connect Wallet", // case: Install wallet, Connect Wallet, Address
    setAddress: (newAddress) => set((state) => ({ address: newAddress })),
    removeAddress: () => set({ address: null }),
    chain: null,
    setChain: (chain) => set((state) => ({ chain })),
    removeChain: () => set({ chain: null }),
  }))
);

package.json :
"dependencies ": {
    "next": "12.0.8",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "zustand": "^ 3.6.9"
  } 

```
<img width="544" alt="Immagine 2022-02-04 172922" src="https://user-images.githubusercontent.com/61518840/152565927-3cc5c7d3-ea54-485c-a95a-b82c346f6911.png">

**Comment by dai-shi** [comment]
@devanshj can we avoid showing the deprecated message if `options` is undefined?

@Ic3b3rg meanwhile, if you pass `{}` to the second argument of `devtools()`, the warning will go away.

**Comment by Ic3b3rg** [comment]
> @devanshj can we avoid showing the deprecated message if `options` is undefined?
> 
> @Ic3b3rg meanwhile, if you pass `{}` to the second argument of `devtools()`, the warning will go away.

ok, i will try it and let you know.  Thank you so much

**Comment by devanshj** [comment]
> @devanshj can we avoid showing the deprecated message if options is undefined?

Yeah, I think adding another overload at the top which only takes one argument would fix the issue.

I'm afk for a while do you mind opening a PR?

**Comment by dai-shi** [comment]
You can work on it when you are available.

**Comment by dai-shi** [comment]
@Ic3b3rg Can you try #781 and see if it fixes your case?
https://ci.codesandbox.io/status/pmndrs/zustand/pr/781
Please find "Local Install Instructions" there ☝️ .

**Comment by Ic3b3rg** [comment]
> @Ic3b3rg Puoi provare #781 e vedere se risolve il tuo caso? https://ci.codesandbox.io/status/pmndrs/zustand/pr/781 Trova le "Istruzioni per l'installazione locale" lì☝️.

Amazing! The problem disappeared as soon as the library was installed. It was my first open issue of my life. You were very fast in answering and resolving, and I was also afraid of having made a mistake in exposing the problem. Thanks again zustand team you are great.

**Comment by dai-shi** [comment]
Great to hear that.
I plan to release it with the next version, but no ETA at the moment.
Meanwhile, you can either keep using the codesandbox build or pass `{}`.
Thanks for reporting!
