### ISSUE TITLE
Multiple persist slices under one store

### ISSUE THREAD

**Issue by gperl27** [pmndrs/zustand#800]
Is there anyway to have multiple slices use different `persist` storage types? In my use case, I'm trying to have one subset use `localStorage` and another one `sessionStorage`.

Ideal usage:

```
const useStore = create((set, get) => {
  firstSlice: ...persist(firstSlice, { getStorage: () => localStorage }),
  secondSlice: ...persist(secondSlice, { getStorage: () => sessionStorage }),
})
```

What I've tried so far:
- Did something like example above
  - Resulted in reading/writing to both storages. Seems this is due to `hydrate` being bound to the `create` function
- Created two middlewares that run `useStore.persist.setOptions({ getStorage })` before every `get`/`set` with persist being at the top-level and using `partialize` on notable keys
  - Resulted in runtime errors and main state corruption

Would love to know if there's a way to do this. My interim approach will be to just have completely different stores for these two storage types.

**Comment by DennisSmolek** [comment]
What is the usecase to justify it? Cross tabs? Are they identical?

IMO thats a lot of tightly coupled logic, something fails in the session and local fails, etc
Whats the latency of using local storage if across tabs? I've not tried that pattern..

Maybe a [`Combine()`](https://github.com/pmndrs/zustand#typing-your-store-and-combine-middleware) after the two calls complete?

**Comment by pavi2410** [comment]
@gperl27 Did you explicitly not provide a `name` to persist?

**Comment by gperl27** [comment]
> @gperl27 Did you explicitly not provide a `name` to persist?

That's correct. The code snippet was to supplement the question in a pseudocode sense.

**Comment by ryanhyslop** [comment]
We've come up against a similar use case with what we're doing. To greatly simplify it we essentially have a piece of state for our user (name, email etc) and we have an access token (JWT) and a refresh token.

This is a react native app and we are storing the access token in [Secure Store](https://docs.expo.dev/versions/latest/sdk/securestore/). This has a limit of ~2000 bytes so we can't really use it to also store lots of user profile data.

Presently we've created a separate AuthStore to keep the token and persist it with SecureStore. However from a domain point of view its quite tightly coupled to the user which is now in our other main store which is persisted with [AsyncStorage](https://github.com/react-native-async-storage/async-storage). So we have to reach across stores for things like logging in and logging out. 

Be interested to know how others are solving this, ultimately just wanted to add another voice to the utility of persisting different parts of our state to different storage methods as per the original issue.

**Comment by laclance** [comment]
> Your suggestion @gperl27 is great. I have a similar use case, where I wish to slice up a bigger zustand store, and persist one of the slices in localstorage. So +1 for your suggestion!

I have the same requirement, very large single page app where multiple stores need to interact with each other easily but 1 or 2 need not be persisted.

**Comment by TiagoCavalcante** [comment]
I need this for a different purpose: only persist part of the store.

**Comment by mfkrause** [comment]
> I need this for a different purpose: only persist part of the store.

You can already do that using `partialize`. [See here.](https://github.com/pmndrs/zustand/blob/main/docs/integrations/persisting-store-data.md#partialize)

+1 to the original suggestion, though.

**Comment by TiagoCavalcante** [comment]
> > I need this for a different purpose: only persist part of the store.
>
> You can already do that using partialize. [See here.](https://github.com/pmndrs/zustand/blob/main/docs/integrations/persisting-store-data.md#partialize)

I'm using that now, the problem is that about half of my store should be saved, and half shouldn't, and so I have to list half of the store twice.

**Comment by teddybee** [comment]
I am in similar situation. Can I persist part of my store in two(or more) different storage? 
For example one part of my store don`t need to be saved, but a part needs in localStorage, and another part needs a sessionStorage.

**Comment by enchorb** [comment]
`@udecode/zustood` works perfectly for this use case. Can combine multiple stores with different or no persist (among other options) into a root store

**Comment by Podmaskov** [comment]
Hello.
I combine three types of slices into one store. My problem is that the sessionStorageSlices doesn't work with localeStorageSlices. Can anyone tell me what I'm doing wrong?

`import { create, StoreApi } from "zustand";
import { createJSONStorage, devtools, persist } from "zustand/middleware";
import { ProjectModalSlice, projectModalSlice } from "./codex/slices/projectModalSlice";
import { FirmPaneSlice, firmPaneSlice } from "./firms/slices/firmPaneSlice";
import {
  SuggestedCandidatesFiltersSlice,
  suggestedCandidatesFiltersSlice,
} from "./projects/suggestedCandidatesFiltersSlice";
import { SidebarSlice, sidebarSlice } from "./layout/slices/sidebarSlice";
import { AppThemeSlice, appThemeSlice } from "./layout/slices/appThemeSlice";
import {
  DeleteConfirmationSlice,
  deleteConfirmationSlice,
} from "./layout/slices/deleteConfirmationSlice";

type GeneralSlices = ProjectModalSlice & FirmPaneSlice;

type LocaleStorageSlices = SuggestedCandidatesFiltersSlice & SidebarSlice & AppThemeSlice;

type SessionStorageSlices = DeleteConfirmationSlice;

type Set = StoreApi<GeneralSlices>["setState"];
type Get = StoreApi<GeneralSlices>["getState"];
type Api = StoreApi<ProjectModalSlice & FirmPaneSlice>;

export type RootStore = GeneralSlices & LocaleStorageSlices & SessionStorageSlices;

const generalSlices = (...a: [Set, Get, Api]): GeneralSlices => ({
  ...projectModalSlice(...a),
  ...firmPaneSlice(...a),
});

const localeStorageSlices = persist<LocaleStorageSlices>(
  (...a) => ({
    ...suggestedCandidatesFiltersSlice(...a),
    ...sidebarSlice(...a),
    ...appThemeSlice(...a),
  }),
  {
    name: "RootStoreLocalPersist",
    storage: createJSONStorage(() => localStorage),
    partialize: (state): any => ({
      suggestedCandidatesFilters: state.suggestedCandidatesFilters,
      isSidebarCollapse: state.isSidebarCollapse,
      appTheme: state.appTheme,
    }),
  },
);

const sessionStorageSlices = persist<SessionStorageSlices>(
  (...a) => ({ ...deleteConfirmationSlice(...a) }),
  {
    name: "RootStoreSessionPersist",
    storage: createJSONStorage(() => sessionStorage),
    partialize: (state): any => ({ isDeleteConfirmationActive: state.isDeleteConfirmationActive }),
  },
);

export const useRootStore = create<RootStore>()(
  devtools(
    (...a) => ({
      ...generalSlices(...a),
      ...localeStorageSlices(...a),
      ...sessionStorageSlices(...a),
    }),
    { name: "RootStore" },
  ),
);
`

**Comment by Podmaskov** [comment]
In my case, I have one store for the entire application, but part of it must be stored in local storage, another part in session storage, and the rest in the store. How can I do this without creating different stores?

**Comment by dbritto-dev** [comment]
@Podmaskov well, the only way to achieve that would be creating a custom storage

**Comment by mooalot** [comment]
You can nest persists indefinitely. You just have to be careful with your keys and give each one a unique name.

```typescript
type State = {
  local: number;
  session: number;
};

const useStore = create<State>()(
  persist(
    persist(
      (set) => ({
        local: 0,
        session: 0,
      }),
      {
        name: 'local',
        storage: createJSONStorage(() => localStorage),
        partialize: (state) => ({ local: state.local }),
      },
    ),
    {
      name: 'session',
      storage: createJSONStorage(() => sessionStorage),
      partialize: (state) => ({ session: state.session }),
    },
  ),
);
```

**Comment by VariabileAleatoria** [comment]
> We've come up against a similar use case with what we're doing. To greatly simplify it we essentially have a piece of state for our user (name, email etc) and we have an access token (JWT) and a refresh token.
> 
> This is a react native app and we are storing the access token in [Secure Store](https://docs.expo.dev/versions/latest/sdk/securestore/). This has a limit of ~2000 bytes so we can't really use it to also store lots of user profile data.
> 
> Presently we've created a separate AuthStore to keep the token and persist it with SecureStore. However from a domain point of view its quite tightly coupled to the user which is now in our other main store which is persisted with [AsyncStorage](https://github.com/react-native-async-storage/async-storage). So we have to reach across stores for things like logging in and logging out.
> 
> Be interested to know how others are solving this, ultimately just wanted to add another voice to the utility of persisting different parts of our state to different storage methods as per the original issue.

came here with the same problem, I'm storing access token and refresh token and exceeding the Expo Secure Store size limit.  
Any working solution?

**Comment by dbritto-dev** [comment]
@VariabileAleatoria have you ever tried `zustand-slices`?

**Comment by VariabileAleatoria** [comment]
> [@VariabileAleatoria](https://github.com/VariabileAleatoria) have you ever tried `zustand-slices`?

are slices stored as separate entries in the secure store? Otherwise I'm not sure on how that would help
