### ISSUE TITLE
useCallback selector loses type inference in version 3.7.0

### ISSUE THREAD

**Issue by GuskiS** [pmndrs/zustand#812]
Just updated from 3.6.9 to 3.7.0 and I'm facing typescript errors in my project because useCallback loses type inference.
Here is an example: https://codesandbox.io/s/tender-scott-9902ek?file=/src/App.tsx
hover `valid` and `invalid` variables.

You can change zustand version to 3.6.9 sandbox to see it working.

**Comment by dai-shi** [comment]
@GuskiS Thanks for reporting.

@devanshj Do you know how this is happening? Is this fixable?

**Comment by devanshj** [comment]
I simplified `FooContext.useStore` to not have overloads but due to typescript limitations it doesn't work nicely with things like `useCallback`.

```ts
// https://tsplay.dev/wR5DEW

declare const useCallback:
  <T extends (...args: any[]) => any>(callback: T, deps: ReadonlyArray<any>) => T

type Foo = { foo: string }
declare const useFoov37:
  <U = Foo>
    ( selector?: (state: Foo) => U
    , equalityFn?: (a: U, b: U) => boolean
    ) => U;

declare const useFoov36:
  { (): Foo
  , <U>
      ( selector: (state: Foo) => U
      , equalityFn?: (a: U, b: U) => boolean
      ): U;
  }
  
let test1 = useFoov36(useCallback(x => x.foo, []))
//   ^? string

let test2 = useFoov37(useCallback(x => x.foo, []))
//   ^? any
```

It's unlikely that we can make `useCallback`'s type such that the inference works, so let's revert the change.

**Comment by dai-shi** [comment]
Thanks. I wasn't aware there's such a drawback.

**Comment by GuskiS** [comment]
@devanshj Problem there is that selector is optional.
To fix that, either make it required or do something like this:
```ts
declare const useFoov37:
  <S extends (state: U) => U, U = Foo>
    ( selector?: S
    , equalityFn?: (a: U, b: U) => boolean
    ) => U;
```

**Comment by dai-shi** [comment]
@GuskiS Can you confirm if #817 fixes it?
https://ci.codesandbox.io/status/pmndrs/zustand/pr/817
☝️ Find "Local Install Instructions"

**Comment by GuskiS** [comment]
It works, thanks 👌

**Comment by devanshj** [comment]
> ```ts
> declare const useFoov37:
>   <S extends (state: U) => U, U = Foo>
>     ( selector?: S
>     , equalityFn?: (a: U, b: U) => boolean
>     ) => U;
> ```

Perhaps you meant `(state: Foo) => U` instead but either way `test2` is `Foo` (as you can also see if your screenshot) and it should be `string` instead. And the selector is truly optional as even `useStore()` is valid.

**Comment by Andarist** [comment]
@devanshj perhaps worth reporting this case to the TS team? I feel like there is a huge potential for the contextual type being provided here to the inner callback. The parameter type here isn't even generic, it's just `Foo` so it should be possible for this to "flow" to the inner function.

**Comment by devanshj** [comment]
> @devanshj perhaps worth reporting this case to the TS team? I feel like there is a huge potential for the contextual type being provided here to the inner callback. The parameter type here isn't even generic, it's just Foo so it should be possible for this to "flow" to the inner function.

I guess there already must be an issue already filed for this (I don't know what could be the search terms though) but nonetheless if you want to file one go ahead, at worst it'll be marked as duplicate. Here's a minimal version...

```ts
declare const identity: <T extends (...args: never[]) => unknown>(f: T) => T
declare const foo1: (f: (a: { foo: string }) => void) => void
declare const foo2: <A = { foo: string }>(f: (a: A) => void) => void

foo1(identity(x => x)) // compiles
foo2(identity(x => x)) // doesn't compile, should
```
