### ISSUE TITLE
Jest v27 - jest-circus/runner does not allow global afterEach

### ISSUE THREAD

**Issue by terwort** [pmndrs/zustand#813]
With jest v27 they implemented some new defaults. One of them is switching from jasmine2 as the test runner to their version called jest-circus/runner. The problem here is that it doesn't allow for global beforeEach/afterEach. This is a problem because the example given by this repo for testing is to mock zustand with a global afterEach as seen here: https://github.com/pmndrs/zustand/wiki/Testing

It looks like for future versions of jest zustand is going to need a fix to this.

To fix this for now I have manually set my testRunner back to jasmine2. But I would love to use jest-circus/runner as it is most up to date and supported by the jest team.

**Comment by dai-shi** [comment]
Closing as stale. The wiki page isn't super correct now. Needs updating.
Related: #271, #968.
