### ISSUE TITLE
Example in persist is broken

### ISSUE THREAD

**Issue by lichenglu** [pmndrs/zustand#830]
### What is the issue

The line `useStore.setState({ _hasHydrated: true })` does not actually update the state: https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data#how-can-i-check-if-my-store-has-been-hydrated

```javascript
const useStore = create(
  persist(
    (set, get) => ({
      // ...
      _hasHydrated: false
    }),
    {
      // ...
      onRehydrateStorage: () => () => {
        useStore.setState({ _hasHydrated: true }) // THIS DOES NOT CHANGE THE STATE
      }
    }
  )
);

export default function App() {
  const hasHydrated = useStore(state => state._hasHydrated);

  if (!hasHydrated) {
    return <p>Loading...</p>
  }

  return (
    // ...
  );
}
```

However, if we update the state through a setter, then it works
```javascript
const useStore = create(
  persist(
    (set, get) => ({
      // ...
      setHydrate: (val) =>
        set((state) => {
          state._hasHydrated = val;
      }),
      _hasHydrated: false
    }),
    {
      // ...
      onRehydrateStorage: () => (state) => {
        state.setHydrate(true) // THIS WORKS
      }
    }
  )
);
```

### Reproducible Example
https://codesandbox.io/s/dry-breeze-rpfk4p?file=/src/App.js:420-513

Is this an expected behavior? Or I can probably take a look and fix it.

**Comment by AnatoleLucet** [comment]
Ah! You're right, this would only work with an async storage.
I'll update the doc, thanks

**Comment by lichenglu** [comment]
> Ah! You're right, this would only work with an async storage. I'll update the doc, thanks

Thank you for your prompt response! However, it is not very clear to me why it would only work for async storage. Could you explain it or do you have any documented resources that you can point me to? Thanks a lot!

**Comment by AnatoleLucet** [comment]
Sure.
Basically, when using a synchronous storage, `useStore` would be undefined (more precisely *not defined*) from within `onRehydrateStorage` because `create`/`persist` has not finished executing yet.
It's like doing: 
```ts
const fn = (cb) => {
  cb();
  
  return {
    foo: "bar"
  }
}

const obj = fn(() => {
  console.log(obj.foo) // ReferenceError: obj is not defined
})
```
But if `cb` was called asynchronously (like when using an async storage with `persist`):
```ts
const fn = (cb) => {
  // Promise.resolve could compare to resolving the storage's data
  Promise.resolve().then(() => {
      // this is called later on, in a microtask. So the script has ended and `obj` is now defined
      cb();
  });
  
  return {
    foo: "bar"
  }
}

const obj = fn(() => {
  console.log(obj.foo) // "bar"
})
```

**Comment by lichenglu** [comment]
Ah! Of course! I was thinking in the wrong direction. Thank you so much for the detailed explanation!

**Comment by kevinxh** [comment]
if it's impossible to set state in `onRehydrateStorage`, what's the proper way to mutate the state after hydration is done?

**Comment by AnatoleLucet** [comment]
@kevinxh while it is possible to mutate the state directly (`state.foo = "bar"`), i would suggest using a setter function defined in your state.

**Comment by eightyfive** [comment]
@AnatoleLucet It is not possible to use a setter function if hydration returns `state === undefined`.

This does not work:

```ts
onRehydrateStorage: () => (state) => {
  state?.init(state?.token);
},
```

`state?.init` setter function is also `undefined` in that case.

In my case I use React Native (async storage...) on an Android device, and it happens on the first app launch, if nothing has been persisted yet/before.

My work around is using the "wrong example" this issue is about lol:

```ts
onRehydrateStorage: () => (state) => {
  useSession.setState({ token: state?.token || "", isLoading: false });
},
```

It's not ideal, I would prefer the possibility to use a store setter function so I can have an `onInit` option on my generic `Session` store:

```ts

export function createSession(
  name: string,
  { onInit, onStart, onStop }: SessionOptions,
) {
  const useSession = create<Session>()(
    persist(
      (set) => ({
        // State
        isLoading: true,
        token: "",

        // Actions
        init(token: string) {
          if (onInit) {
            onInit(token);
          }

          set({ isLoading: false, token });
        },
        
        // ...
```
