### ISSUE TITLE
Use store inside a custom hook

### ISSUE THREAD

**Issue by ha3** [pmndrs/zustand#834]
Hello,

Frequently, I bump into the need of using zustand stores lazily, after some configs are fetched and ready to use. And also I need them instance based. So I thought, I can extract the creation of the store into a custom hook.

But typing seems to be problematic. I can't just give `UseBoundStore<Store>` as hook's type and move on. Typescript complains about signature's incompatibility with `useStore()` usage. I couldn't find how to overcome it.

```ts
type Store = {};

const stores = new Map<string, UseBoundStore<Store>>();

const getCollectionStore = (collectionId: string) => {
  const store = stores.get(collectionId);
  
  if (store) { return store; }
  
  const newStore = create<Store>({ ... });
  
  stores.set(collectionId, newStore);
  
  return newStore;
}


const useCollectionStore: UseBoundStore<Store> = (selector, equalityFn) => {
  const route = useRoute();
  const collectionId = route.params.collectionId;
  
  const storeRef = React.useRef(getCollectionCreationStore(collectionId));
  Object.assign(useCollectionCreationStore, storeRef.current);
  
  React.useLayoutEffect(() => {
    storeRef.current = getCollectionCreationStore(collectionId);
    Object.assign(useCollectionCreationStore, storeRef.current);
  }, [collectionId]);
  
  return storeRef.current(selector, equalityFn);
}
```

```bash
Type '<U>(selector: StateSelector<Store, U>, equalityFn: EqualityChecker<U> | undefined) => any' is not assignable to type '{ (): Store; <U>(selector: StateSelector<Store, U>, equalityFn?: EqualityChecker<U> | undefined): U; }'.
```

Returning slice as any doesn't work either: `storeRef.current(selector, equalityFn) as any`. I think it is because of the `(): T` signature; this one works:

```ts
type UseBoundStoreAlt<T> = <U>(
  selector: StateSelector<T, U>,
  equalityFn?: EqualityChecker<U>
) => U & StoreApi<T>;


const useCollectionStore: UseBoundStoreAlt<Store> = (selector, equalityFn) => {
  ...

  return storeRef.current(selector, equalityFn) as any;
}
```

Any thoughts on this?

Thanks.

**Comment by dai-shi** [comment]
Is this type only issue? Does the way `zustand/context` does help?

**Comment by ha3** [comment]
Yes, it is type only. I inspected `zustand/context` but api and hooks seem to be separated there. If possible, I don't prefer it because that way, I'm going to need to duplicate the retrieval logic of the store in two different places and use the same store with two different variables.

**Comment by dai-shi** [comment]
I see. Maybe it's not possible to infer overloaded types. Type assertion would only be a solution.

**Comment by dai-shi** [comment]
Closing this for now. You might want to try/investigate again once v4 lands.
