### ISSUE TITLE
Expose zustand/context for use in Class components

### ISSUE THREAD

**Issue by httpete** [pmndrs/zustand#837]
Zustand/context is a great for what I need. I need to use the Context in a Class component as well as functional. Can you just export the value from React.CreateContext() ?

https://github.com/pmndrs/zustand/blob/main/src/context.ts

**Comment by dai-shi** [comment]
Mostly answered in https://github.com/pmndrs/zustand/issues/815#issuecomment-1044480148.
In short, we want to drop `zustand/context`.
If you want it now, I'd suggest to do something similar to `zustand/context` on your end. Simply pass down `useStore` hook via context value, and be careful not to violate rules of hooks. (btw, I'm curious how you could use it in a class component.)

**Comment by httpete** [comment]
I get why you wouldn't want to be in the business of wrapping zustand/context. I can't say I understand everything that is going on in there, but it's a good enough starting point. Ill internalize it. 
In order to use the Zustand store in a class component, I decided just to pass values needed as props. We try not to use Classes , but we do extensive yFiles work and those are better suited for Classes. We just slice out the few values we need as props from a Higher functional component.

**Comment by httpete** [comment]
Will the other exports from Zustand be around ? These are pure types.

```import type {
  EqualityChecker,
  State,
  StateSelector,
  UseBoundStore,
} from 'zustand';

**Comment by httpete** [comment]
If anyone else needs, here is a stripped down and cleaned up version of zustand/context.

```
/*
 * Copyright: (c) 2022 Broadcom. The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This software and all information contained therein is confidential and
 * proprietary and shall not be duplicated, used, disclosed or disseminated in any
 * way except as authorized by the applicable license agreement, without the
 * express written permission of CA. All authorized reproductions must be marked
 * with this language.
 *
 * EXCEPT AS SET FORTH IN THE APPLICABLE LICENSE AGREEMENT, TO THE
 * EXTENT PERMITTED BY APPLICABLE LAW, CA PROVIDES THIS SOFTWARE
 * WITHOUT WARRANTY OF ANY KIND, INCLUDING WITHOUT LIMITATION, ANY
 * IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR
 * PURPOSE. IN NO EVENT WILL CA BE LIABLE TO THE END USER OR ANY
 * THIRD PARTY FOR ANY LOSS OR DAMAGE, DIRECT OR INDIRECT, FROM THE
 * USE OF THIS SOFTWARE, INCLUDING WITHOUT LIMITATION, LOST PROFITS
 * BUSINESS INTERRUPTION, GOODWILL, OR LOST DATA, EVEN IF CA IS
 * EXPRESSLY ADVISED OF SUCH LOSS OR DAMAGE.
 */

import {
  createContext as reactCreateContext,
  createElement,
  useContext,
  useRef,
  type ReactNode,
} from 'react';
import type {
  EqualityChecker,
  State,
  StateSelector,
  UseBoundStore,
} from 'zustand';

type UseContextStore<T extends State> = {
  (): T;
  <U>(selector: StateSelector<T, U>, equalityFn?: EqualityChecker<U>): U;
};

function createContext<
  TState extends State,
  TUseBoundStore extends UseBoundStore<TState> = UseBoundStore<TState>
>() {
  const ZustandContext = reactCreateContext<TUseBoundStore | undefined>(
    undefined
  );

  const Provider = ({
    createStore,
    children,
  }: {
    createStore: () => TUseBoundStore;
    children: ReactNode;
  }) => {
    const storeRef = useRef<TUseBoundStore>();

    if (!storeRef.current) {
      storeRef.current = createStore();
    }

    return createElement(
      ZustandContext.Provider,
      { value: storeRef.current },
      children
    );
  };

  const useStore: UseContextStore<TState> = <StateSlice>(
    selector?: StateSelector<TState, StateSlice>,
    equalityFn = Object.is
  ) => {
    // ZustandContext value is guaranteed to be stable.
    const useProviderStore = useContext(ZustandContext);
    if (!useProviderStore) {
      throw new Error(
        'Seems like you have not used zustand provider as an ancestor.'
      );
    }

    return useProviderStore(
      selector as StateSelector<TState, StateSlice>,
      equalityFn
    );
  };

  return {
    Provider,
    useStore,
  };
}

export default createContext;

**Comment by dai-shi** [comment]
> I decided just to pass values needed as props.

Yeah, that sounds better to me.

**Comment by dai-shi** [comment]
> Will the other exports from Zustand be around ? These are pure types. It's better to use a type only import in modern TS.
> 
> ```
> import type {
>   EqualityChecker,
>   State,
>   StateSelector,
>   UseBoundStore,
> } from 'zustand';
> ```

In fact, we would have wanted to drop some types in v4. But, at the same time, we want to keep the backward compatibility from v3 as much as possible. So, if harmless we keep them in v4 (and maybe drop in v5?). Some types will be removed in v4, and they are deprecated in the latest version of v3.

Or, you just mean to prefer `import type`? Yeah, why not.

**Comment by dai-shi** [comment]
> prefer `import type`?

Hm, zustand repo doesn't use downlevel-dts, so let's leave it as is.

Closing as the original issue seems resolved.
