### ISSUE TITLE
unable to unsubscribe from `subscribeWithSelector` on `fireImmediately`

### ISSUE THREAD

**Issue by cortopy** [pmndrs/zustand#848]
I have a case where I need to subscribe to the store and wait until a condition is met. Following the example in the docs, it would be something like this:

```js
const useStore = create(
  subscribeWithSelector(() => ({ paw: true, snout: true, fur: true }))
);

const unsub = useStore.subscribe(
  state => state.paw,
  hasPaw => {
      if (hasPaw) {
        unsub() // unsub is undefined on first call
      } else {
        // ... do something else
      }
  },
  { fireImmediately: true }
);
```

The problem is that the first call triggered by `fireImmediately` happens before the subscription is set up, and so `unsub` is `undefined`

Looking at the code, when the first call happens [the subscription is indeed not set up yet](https://github.com/pmndrs/zustand/blob/main/src/middleware/subscribeWithSelector.ts#L88)

Is this expected behaviour? If it is, then I can add a PR to warn of this in the docs. If not, I don't mind working on this but I only started using zustand this week so I may need guidance on what would be the prefered approach

**Comment by dai-shi** [comment]
I think it's expected behavior, because `immediately` should mean sync.
I don't think the pattern to unsubscribe on callback is recommended in general. It feels like there should be a better way. Like `waitUntil`?
We don't want to change vanilla.js, but middleware is relatively open for suggestions, and third-party middlewares are welcome.

Anyway, what can be done with the current implementation:
```js
const hasPaw = useStore.getState().paw;
if (!hasPaw) {
  const unsub = useStore.subscribe(
    state => state.paw,
    hasPaw => {
      if (hasPaw) {
        unsub()
      } else {
        // ... do something else
      }
  }
)
```
or
```js
let destroyed = false
const unsub = useStore.subscribe(
  state => state.paw,
  hasPaw => {
      if (hasPaw) {
        unsub?.()
        destroyed = true
      } else {
        // ... do something else
      }
  },
  { fireImmediately: true }
)
if (destroyed) {
  unsub()
}
```

**Comment by cortopy** [comment]
> I don't think the pattern to unsubscribe on callback is recommended in general. It feels like there should be a better way. Like waitUntil?

This is exactly what I wanted to get at. I have worked with RxJS for a long time, and this pattern is actually very common. What I was trying to flesh out is the recommended way of doing this with zustand. I've just done a quick search on RxJS patterns, and indeed the first article I found also uses this pattern. See the [section Unsubscribing Within a Subscription Callback on this article](https://bytethisstore.com/articles/pg/rxjs-unsubscribe)

I don't have any issues with this pattern not been recommended for Zustand, but anybody with a background on observables may see the `subscribe` method and follow certain expectations.

Would this work as a section on the docs/wiki?

```markdown
It's generally not recommended to unsubscribe within the subscription callback like this:

const useStore = create(
  subscribeWithSelector(() => ({ paw: true, snout: true, fur: true }))
);

const unsub = useStore.subscribe(
  state => state.paw,
  hasPaw => {
      if (hasPaw) {
        unsub() // unsub is undefined on first call
      } else {
        // ... do something else
      }
  },
  { fireImmediately: true }
);

It's recommended to rather do:

const hasPaw = useStore.getState().paw;
if (!hasPaw) {
  const unsub = useStore.subscribe(
    state => state.paw,
    hasPaw => {
      if (hasPaw) {
        unsub()
      } else {
        // ... do something else
      }
  }
)

or

let destroyed = false
const unsub = useStore.subscribe(
  state => state.paw,
  hasPaw => {
      if (hasPaw) {
        unsub?.()
        destroyed = true
      } else {
        // ... do something else
      }
  },
  { fireImmediately: true }
)
if (destroyed) {
  unsub()
}

```

**Comment by dai-shi** [comment]
Yes, feel free to create a wiki page. For "It's recommended to rather do:", I wouldn't call it a recommended pattern. It's a workaround. Hope someone to have less-ugly solutions..

**Comment by nbmgl** [comment]
This seems like a critical pattern error to me. @dai-shi  - I'm not clear how we're supposed to unsubscribe if we're not able to do it within the callback. In my opinion, this **is** best practice.

Of course, you have the obvious React `useEffect` way to unsubscribe, but we're talking about vanilla best-practice patterns

**Comment by nbmgl** [comment]
Is there any recommended approach here, that you or @cortopy have come to?

**Comment by dai-shi** [comment]
How about using setTimeout? Does your case require `fireImmediately`?
