### ISSUE TITLE
RN Expo [zustand devtools middleware] Please install/enable Redux devtools extension

### ISSUE THREAD

**Issue by fristyr** [pmndrs/zustand#852]
I use the latest version of zustand 3.7.1
<img width="1179" alt="Screenshot 2022-03-05 at 11 31 43" src="https://user-images.githubusercontent.com/33237937/156879504-41b498f6-8be8-4245-ab9e-0914c3cce316.png">

**Comment by dai-shi** [comment]
Missing a link for reproduction?
Also, is this warning only issue, and no behavioral issues?

Anyway, the warning is show in
https://github.com/pmndrs/zustand/blob/a46f1fd87188fccacac7d2ee84702a62c631ad47/src/middleware/devtools.ts#L207-L211

so, `window` is not `undefined` in expo.
I don't think it's very easy to fix it for any environments, and rather think removing the warning entirely.
We have the same discussion in valtio: https://github.com/pmndrs/valtio/pull/378#issuecomment-1048287837
Would anyone know if there's such a warning in Redux? If they don't, it would be fine for us to remove it.

**Comment by fristyr** [comment]
@dai-shi 
You can use this for reproduction 
https://snack.expo.dev/@fristyrd/zustand-jotai-test
But unfortunately you need to download it from expo snack and run it locally to see this error.

And now this is just a warning and no behavioural issues

**Comment by dai-shi** [comment]
thanks. so, does it mean `typeof window` in snack is `undefined`, but it's not locally???

**Comment by fristyr** [comment]
@dai-shi Just started my project and I see **__DEV__** is **true**
and in expo snack **__DEV__** is not defined

About **typeof window**  
expo snack:  typeof window -> object
local project: typeof window -> object

So it's weird :)

**Comment by dai-shi** [comment]
well, the logic is correct. the warning is shown when `__DEV__` is truthy **and** `window` is defined (not `undefined`).

**Comment by fristyr** [comment]
But the issue is still open unfortunately.
I don't have control over window object and can't set __DEV__ variable to something else because of expo

**Comment by dai-shi** [comment]
> But the issue is still open unfortunately.

Yeah, I know. At least we know how this is happening.

https://github.com/pmndrs/zustand/issues/852#issuecomment-1059783350
> I don't think it's very easy to fix it for any environments, and rather think removing the warning entirely.

**Comment by vinaciotm** [comment]
I am so happy that i SOLVE the problem. 

adding this in package.json:

`
"zustand": "*",
    "@types/react": "*",
    "immer": "^9.0.6",
    "use-sync-external-store": "^1.2.0",
    "web-vitals": "*"
`


It's working perfectly, and works with persist too!


you can test here: [](https://snack.expo.dev/@vinaciotm/zustand-expo)

code:
`import React from 'react';
import { SafeAreaView, View, Text, Button } from 'react-native';

import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import AsynStorage from '@react-native-async-storage/async-storage';

// simple store
const useStore = create((set) => ({
  counter: 0,
  increase: () => set((state) => ({ counter: state.counter + 1 })),
  reset: () => set({ counter: 0 }),
}));

// persist store
const useStorePersisted = create(
  persist(
    (set) => ({
      counter: 0,
      increase: () => set((state) => ({ counter: state.counter + 1 })),
      reset: () => set({ counter: 0 }),
    }),

    {
      name: 'my-app-storage', // unique name for storage key
      storage: createJSONStorage(() => AsynStorage), // Using WmaStorage as the storage engine
    }
  )
);

const Counter = () => {
  const { counter, increase, reset } = useStore();

  return (
    <View style={{ backgroundColor: 'lightgreen' }}>
      <Text>{counter}</Text>
      <Button title="increase" onPress={increase} />
      <Button title="reset" onPress={reset} />
    </View>
  );
};

const CounterPersisted = () => {
  const { counter, increase, reset } = useStorePersisted();

  return (
    <View style={{ backgroundColor: 'lightblue' }}>
      <Text>{counter}</Text>
      <Button title="increase" onPress={increase} />
      <Button title="reset" onPress={reset} />
    </View>
  );
};

export default function App() {
  return (
    <SafeAreaView>
      <Counter />
      <CounterPersisted />
    </SafeAreaView>
  );
}
`



full package:
`{
  "dependencies": {
    "immer": "^9.0.6",
    "zustand": "*",
    "@expo/vector-icons": "^14.0.2",
    "react-native-paper": "4.9.2",
    "expo-zustand-persist": "*",
    "use-sync-external-store": "^1.2.0",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@types/react": "*",
    "web-vitals": "*",
    "zustand/middleware": "*"
  }
}`
