### ISSUE TITLE
Unable to receive up-to-date props from outside when using createContext 

### ISSUE THREAD

**Issue by SeongwoonHong** [pmndrs/zustand#865]
Here's a mini repo https://codesandbox.io/s/magical-gauss-12zyn5?file=/src/Builder/BuilderProvider.js

So my use case in this repo is if I click "Increase count" this increased **count** variable by 1 and it is being passed to **Builder** component that passed all the props to **BuilderProvider**. If you look at line 36 in BuilderProvider, when **setText** function is called, I want to get most up to date **count** value that is passed from **index.js**
So the expected outcome is if I click "Increase count" three times and make the **count** value to 3 and click "call setText function" button, I want to see 3 (the value of **count**) being printed like **state.count = 3** in the screen

**Comment by ankitchouhan1020** [comment]
Hi @SeongwoonHong, count is not getting updated due to stale closure. You can keep a ref to hold the count value. https://codesandbox.io/s/serene-montalcini-vkhnm7

**Comment by SeongwoonHong** [comment]
> Hi @SeongwoonHong, count is not getting updated due to stale closure. You can keep a ref to hold the count value. https://codesandbox.io/s/serene-montalcini-vkhnm7

Working like a charm. Thank you so much :D 
Closing this
