### ISSUE TITLE
Zustand DevTools log in production code

### ISSUE THREAD

**Issue by reintroducing** [pmndrs/zustand#874]
My understanding is that the devtools only load in development and when `NODE_ENV === 'production'` they are not included. That being said, I'm looking at my output JS and I'm seeing the `console.warn` still showing in there even though its around a `__DEV__` condition, which I assume is looking at `NODE_ENV === 'development'` from what I can gather looking through the source. Why would this log still be showing (`[zustand devtools middleware] Please install/enable Redux devtools extension`)? Here is a snipped of my production code where you can see the log(s) are still present:

```js
u=void 0===t?{name:void 0,anonymousActionType:void 0}:"string"==typeof t?{name:t}:t;let s;try{s=window.__REDUX_DEVTOOLS_EXTENSION__||window.top.__REDUX_DEVTOOLS_EXTENSION__}catch{}if(!s)return"undefined"!=typeof window&&console.warn("[zustand devtools middleware] Please install/enable Redux devtools extension"),e(n,r,i);let c=Object.create(s.connect(u)),l=!1;Object.defineProperty(i,"devtools",{get:()=>(l||(console.warn("[zustand devtools middleware] `devtools` property on the store is deprecated it will be removed in the next major.\nYou shouldn't interact with the extension directly. But in case you still want to you can patch `window.__REDUX_DEVTOOLS_EXTENSION__` directly"),l=!0),c),set:e=>{l||(console.warn("[zustand devtools middleware] `api.devtools` is deprecated, it will be removed in the next major.\nYou shouldn't interact with the extension directly. But in case you still want to you can patch `window.__REDUX_DEVTOOLS_EXTENSION__` directly"),l=!0),c=e}});
```

This is my hook:
```js
export const useUserStore = create(
    devtools(set => ({
        ...storeStuff
    }))
);
```

**Comment by dai-shi** [comment]
Sounds like it fails to detect production mode?

Lately, I'm thinking about removing the warning altogether, as it seems to cause troubles more than helps.
Related: #852, https://github.com/pmndrs/valtio/pull/378

**Comment by reintroducing** [comment]
@dai-shi yes thats what it sounds like, but I’m not as concerned about the warning (although that is also unnecessary for people who don’t have the devtools installed) as I am with the fact that the devtools is actually getting included in the production bundle. I’m not sure how large the devtools are but anything that shouldn’t be in a production bundle and thus making it larger than it needs to be is what my main concern is. 

Is it just the warning or is the whole thing being included in the prod bundle?

**Comment by dai-shi** [comment]
It's not big, but I would remove it in the production bundle.
The library doesn't remove code automatically. Please see #842.

**Comment by reintroducing** [comment]
@dai-shi Interesting, thank you for that link. I was under the impression this was built into zustand's devtools already. React Query has devtools as well that automatically get removed in production builds, and most other tools I thought also do this. Not a huge deal as the code is pretty simple, but may be something to think about for a future version to automatically add this in? 

Regardless, this will solve my issue so I'll go ahead and close this. Appreciate your help.

**Comment by dai-shi** [comment]
Yeah, but my little concerns that if we remove it in the libary are:
- we can't remove it completely anyway.
- `__DEV__` detection might not be 100% accurate.
- someone may want to use it in production.

It may still be worth trying, though.
