### ISSUE TITLE
Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.

### ISSUE THREAD

**Issue by talentlessguy** [pmndrs/zustand#886]
With React 18, this error occurs when using a useStore hook:

```ts
// useDarkMode.ts
import create from 'zustand'
import { persist } from 'zustand/middleware'

type darkModeState = {
  /**
   * State of user settings
   */
  isDarkMode: boolean
  toggleDarkMode: () => void
}

export const useDarkMode = create<darkModeState>(
  persist(
    (set) => ({
      isDarkMode: false,
      toggleDarkMode: () =>
        set(({ isDarkMode }) => ({
          isDarkMode: !isDarkMode
        }))
    }),
    { name: 'useDarkMode' }
  )
)
```

```tsx
// app.tsx

import { useMemo } from 'react'
import { cssStringFromTheme } from '../css/cssStringFromTheme'
import { useDarkMode } from '../hooks/useDarkMode'
import { darkTheme } from '../themes/darkTheme'
import { lightTheme } from '../themes/lightTheme'
import { Box } from './Box'

export const ThemeSwitch = () => {
  const isDarkMode = useDarkMode((s) => s.isDarkMode)
  const toggleDarkMode = useDarkMode((s) => s.toggleDarkMode)

  const themeObject = useMemo(() => {
    if (isDarkMode) return darkTheme
    else return lightTheme
  }, [isDarkMode])

  return (
    <style global jsx>
      {`
        :root {
          ${cssStringFromTheme(themeObject)}
        }

        @media (prefers-color-scheme: dark) {
          :root {
            ${cssStringFromTheme(isDarkMode ? darkTheme : themeObject)}
          }
        }
      `}
    </style>
  )
}
```

this error occurs:

![image](https://user-images.githubusercontent.com/35937217/160880323-02b33c95-eb0e-4adb-a7e7-7e2d3bb8c8f4.png)

This is using zustand@4.0.0-beta.2, react@18 and next@12.1

**Comment by dai-shi** [comment]
Ohhh, I wasn't aware that.. I was expecting it will revert to client rendering silently.
Thanks for reporting.
Is this warning only problem? Hmm, I think we should follow how react-redux does. 🤔

**Comment by dai-shi** [comment]
Can you try this?
https://ci.codesandbox.io/status/pmndrs/zustand/pr/550/builds/233894
Find "Local Install Instructions" ☝️

**Comment by talentlessguy** [comment]
yeah it seems to work

https://codesandbox.io/s/react-typescript-forked-7fyb80?file=/src/App.tsx

looking forward to have this in `4.0.0-beta.3`

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/zustand/v/4.0.0-beta.3

**Comment by nickytonline** [comment]
I seem to be experiencing this issue in https://github.com/open-sauced/app/pull/1734 with Zustand 4.3.2 with Next.js 13.4.7. Still digging into why the fix here doesn't kick in. 🤔

**Comment by nickytonline** [comment]
I saved the markup from view page source (SSR) and compared it to the markup in the devtools after a full client-side render (CSR) and the SSR version is missing usernames and potentially other stuff. I believe this is because there are calls to populate each row on the client side with additional info. I'm guessing potentially some client-side only hooks that aren't kicking in properly during SSR. 🤔 

![CleanShot 2023-09-28 at 17 17 45](https://github.com/pmndrs/zustand/assets/833231/afc0416b-39d0-4709-940f-0142ef2683b5)

**Comment by BismarkCodes** [comment]
This worked for me.
Follow this link on how to manage states in nextjs app:
https://vercel.com/guides/react-context-state-management-nextjs#rendering-third-party-context-providers-in-server-components

**Comment by Leandro-Albano** [comment]
I am also getting this same error using NextJs 14.0.4 and Zustand 4.4.7
