### ISSUE TITLE
[test] add spec with ssr

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/zustand#903]
#886 was reported and fixed, but we don't have a test for it.

https://github.com/reduxjs/react-redux/pull/1888 can be a good reference.

**Comment by amareshsm** [comment]
I would like to give it a try. I might need some time to complete it. Can I pick this?

**Comment by arnaugomez** [comment]
Hi, because more than a year has passed since last activity, I will give it a try and make a PR

**Comment by qqqzhch** [comment]
This is to write a demo, such as using zustand in next13？

**Comment by dai-shi** [comment]
This is about adding a new test in https://github.com/pmndrs/zustand/tree/main/tests.

**Comment by NaamuKim** [comment]
@dai-shi I would like to adding a test for this issue.
Can you assign me?
I will upload the PR before October 3rd.
