### ISSUE TITLE
Zustand testing throws an error "TypeError: store.getState is not a function"

### ISSUE THREAD

**Issue by Boniqx** [pmndrs/zustand#905]
In the documentation it states that adding this in JEST would enable testing for ZUSTAND state.

```
const create = createState => {
  const store = actualCreate(createState);
  const initialState = store.getState();
  storeResetFns.add(() => store.setState(initialState, true));
  return store;
};
```

But it seems to throw an error "TypeError: store.getState is not a function"

I am using typescript not sure if this causes some issues. Also, it is not well documented on how to use this test in jest. Just want to have values on my states so that they can be used on my componentes during rendering of test components.

**Comment by dai-shi** [comment]
Is it possible to reproduce it with codesandbox?

Hope someone can help this. Also, there are some open issues for testing that needs help.

**Comment by Boniqx** [comment]
Sorry Not really familiar how to create components and jest test in sandbox that is why I can't reproduce it. It looks like a typescript issue. Similar issues has been submitted in zustand. https://stackoverflow.com/questions/68896812/using-a-zustand-function-mock-with-jest-results-in-typeerror-create-is-not-a

**Comment by dai-shi** [comment]
The SO one's error is `TypeError: create is not a function`. It's a different one.

`TypeError: store.getState is not a function` seems a JS error, not TS.

**Comment by Boniqx** [comment]
Ohh nevermind I got it:

To do this you should use the actual store of your app
```

    const initialStoreState = useStore.getState()
     
     beforeEach(() => {
        useStore.setState(initialStoreState, true)
      })

    useStore.setState({ me: memberMockData, isAdmin: true })
```

**Comment by dai-shi** [comment]
Can close now??

**Comment by nenjamin2405** [comment]
In v4, when I try to access the state using useStore.getState(), it has a typescript error `Property 'getState' does not exist on type`

**Comment by dai-shi** [comment]
Can you open a PR?
Someone should be able to review.
cc: @dbritto-dev @sewera @chrisk-7777

**Comment by dbritto-dev** [comment]
@dai-shi sure I can take care of that

**Comment by FancyVase** [comment]
Just a heads up, the currying fix on the mock `create` works for a "standard" `create` call, but errors if you're using the [immer middleware](https://docs.pmnd.rs/zustand/integrations/immer-middleware) with the same "TypeError: store.getState is not a function".

A little hacky, but to support both types of `create` calls, I added a wrapper that returns another function **if** no state is passed in (similar to [what Zustand does internally](https://github.com/pmndrs/zustand/blob/main/src/react.ts#L82)):

```ts
export const create = <S>(createState: StateCreator<S>) => {
  return typeof createState === 'function'
      ? createInternalFn(createState)
      : createInternalFn;
};

const createInternalFn = <S>(createState: StateCreator<S>) => {
  const store = actualCreate(createState);
  const initialState = store.getState();
  storeResetFns.add(() => store.setState(initialState, true));
  return store;
};
```

**Comment by dbritto-dev** [comment]
@grigoll @FancyVase @dai-shi here's the PR https://github.com/pmndrs/zustand/pull/1738

**Comment by cam-shaw** [comment]
@FancyVase that solutions works great when using the example herehttps://github.com/pmndrs/zustand/blob/3584d5075af278b674693193acde1aa03a7cd53b/docs/guides/how-to-reset-state.md

Appreciate it 🙏

**Comment by shahbazshueb** [comment]
> Just a heads up, the currying fix on the mock `create` works for a "standard" `create` call, but errors if you're using the [immer middleware](https://docs.pmnd.rs/zustand/integrations/immer-middleware) with the same "TypeError: store.getState is not a function".
> 
> A little hacky, but to support both types of `create` calls, I added a wrapper that returns another function **if** no state is passed in (similar to [what Zustand does internally](https://github.com/pmndrs/zustand/blob/main/src/react.ts#L82)):
> 
> ```ts
> export const create = <S>(createState: StateCreator<S>) => {
>   return typeof createState === 'function'
>       ? createInternalFn(createState)
>       : createInternalFn;
> };
> 
> const createInternalFn = <S>(createState: StateCreator<S>) => {
>   const store = actualCreate(createState);
>   const initialState = store.getState();
>   storeResetFns.add(() => store.setState(initialState, true));
>   return store;
> };
> ```

Thanks @FancyVase Your solutions worked like a charm. I had been hitting my head for a long time as one of my tests were not passing.

**Comment by pattern-one-way18** [comment]
> The SO one's error is `TypeError: create is not a function`. It's a different one.
> 
> `TypeError: store.getState is not a function` seems a JS error, not TS.





https://cesarsubliminal.github.io/cyEZ1gssS-gjpHd_iYCmL501pg/
