### ISSUE TITLE
Breaking change on persist middleware

### ISSUE THREAD

**Issue by enzoferey** [pmndrs/zustand#906]
Since this PR https://github.com/pmndrs/zustand/pull/894 (and release `3.7.2`), the `persist` middleware now makes our selectors return `undefined`. 

I first thought it was caused because of rehydration issues, but the `onRehydrateStorage` fires before the exceptions related  to finding `undefined` instead of the expected value.

Our store is composed of slices like this:

```ts
const createRootSlice = (
  set: SetState<any>,
  get: GetState<any>,
  api: StoreApiWithPersist<any>
) => {
  return {
    ...persist(createAgentsStoreSlice, {
      name: "agents",
      partialize: (state) => {
        return {
          agentsEntriesByAssetTokenAddress:
            state.agentsEntriesByAssetTokenAddress,
        };
      },
    })(set, get, api),
    ...[OTHER SIMILAR SLICES],
  }
}
```

**Comment by dai-shi** [comment]
@zerofirework @AnatoleLucet

**Comment by zerofirework** [comment]
I don't fully understand why the selector would return undefined with the changes in #894. It would have been caught by the unit tests. What test case are we missing?

**Comment by enzoferey** [comment]
Yes, not a blocker indeed as we can stick on v3.7.1 indeed @dai-shi 👍🏻 

Let me know if you require more info on my side. The selectors are just always returning `undefined` 🤷🏻‍♂️

**Comment by dasblitz** [comment]
Hi! I just started using zustand for the first time, really liking it! Ran into this issue with persist as well, I made a codesandbox here: https://codesandbox.io/s/weathered-bird-t55e9h?file=/src/App.js

The issue seems to appear when mutator functions are not defined on the root level of the store. Is that something that you're just not supposed to do with zustand?

**Comment by dai-shi** [comment]
zustand only merges shallowly, so you need to merge `slice` on your end.

👉  https://codesandbox.io/s/nifty-snowflake-c9m5xl

**Comment by dasblitz** [comment]
Ok thank you for the example. I guess I misunderstood what 'shallow merging' meant in this respect. I get it now 👍🏻

**Comment by dai-shi** [comment]
Closing this. Please open a new issue with a reproduction.

**Comment by enzoferey** [comment]
I will check if this keeps happening on v4 and open back if so 👍🏻
