### ISSUE TITLE
Suspicious compatibility issue with Fast Refresh

### ISSUE THREAD

**Issue by Sixzero** [pmndrs/zustand#908]
I would like to ask, whether any of you guys experience the fact, that fast refresh is doing hot reload sometimes when editing code.

There are some lines about the limitations of Fast refresh.
https://reactnative.dev/docs/fast-refresh#limitations

In this issue, I would like to propose a possible issue, which we all could have experienced, if this is a nonissue for most of us, then just close it. 
When our project project switched to zustand from redux, (while also got a little bigger). We sometimes experienced hot reload, instead of fast refresh, but for the first occurences we didn't bother ourselves with this, and thought it is just a rare bug, but later on it became more consistent, and now files which has many imports into many packages, if we change some specific lines in them, then the states of the application just resets. 

What could cause such an issue, we separated functional component exports from the "other" exports, mentioned in the limitations sections, into separate files, I feel like it is now happening fewer times, but still this state resetting reload is happening in our application while development, when editin files imported to more files. 

So my question is, do you guys also experience this? Also do you guys have ideas why this could happen?

**Comment by Sixzero** [comment]
We have selectors and useStores exported from the same file, could that happen it doesn't meet the fast refresh limitations?

**Comment by Sixzero** [comment]
I think if none is experiencing problems with fast refresh doing a hot reload or state reset, then I just close it tomorrow or when I get back to this issue the next time.

**Comment by dai-shi** [comment]
Generally speaking, module state like zustand doesn't work well with fast refresh.

If you have store file separately, and you don't modify the store file, fast refresh works well. If you modify store file (or its dependencies), state will reset.

Try modifying App.js and see state is preserved.
https://codesandbox.io/s/blissful-wave-ggbpkt?file=/src/App.js

**Comment by Sixzero** [comment]
Would be interesting to see a good scaling solution, to have even fewer state resets, when states could stay unchanged. :)

**Comment by dai-shi** [comment]
You could try store without actions pattern https://github.com/pmndrs/zustand/wiki/Practice-with-no-store-actions, and define functions in separate files. It will do the best. I don't think it's something you want ideally though.

**Comment by Sixzero** [comment]
Great idea! Will test how much it can help. :)

**Comment by zhouccccc** [comment]
> You could try store without actions pattern https://github.com/pmndrs/zustand/wiki/Practice-with-no-store-actions, and define functions in separate files. It will do the best. I don't think it's something you want ideally though.

I met the  same issue.  And the solution you provided is not working

**Comment by dai-shi** [comment]
Is "not working" meaning it doesn't refresh keeping the state? Did you create a separate file?

**Comment by zhouccccc** [comment]
> separate

Not State loss

> Is "not working" meaning it doesn't refresh keeping the state? Did you create a separate file?

It's not that the state is lost, it's that the state-associated component doesn't receive a state update after the update method is called after HMR。The following is partical code in the separate store file


```javascript
const useEditorStore = create(() => ({
  manual: false,
}));

export function updateManual(v) {
  console.log(v);
  useEditorStore.setState(() => ({
    manual: v,
  }));
}
```

And in the Component file, I use `const manual = useStore((state) => state.manual);` for state using

**Comment by dai-shi** [comment]
Interesting. Can you create a full reproduction but as minimal as possible with StackBlitz?

**Comment by zhouccccc** [comment]
> Interesting. Can you create a full reproduction but as minimal as possible with StackBlitz?

sorry, I tried to do that, but it cannot reproduce. I'll check my code in case it's a personal problem.

**Comment by Vali-98** [comment]
> > Is "not working" meaning it doesn't refresh keeping the state? Did you create a separate file?
> 
> It's not that the state is lost, it's that the state-associated component doesn't receive a state update after the update method is called after HMR。The following is partical code in the separate store file
> 
> ```js
> const useEditorStore = create(() => ({
>   manual: false,
> }));
> 
> export function updateManual(v) {
>   console.log(v);
>   useEditorStore.setState(() => ({
>     manual: v,
>   }));
> }
> ```
> 
> And in the Component file, I use `const manual = useEditorStore((state) => state.manual);` for state using

I was pulling my hair out on this issue, but I think I found a possible cause. Placing zustand stores in folders outside the entry point folder seems to break it.

I'm currently using Expo SDK51 for React Native, and most components for the app are contained within the `/app` directory.

In my project, I had the directories as follows:

```
- /app
- /constants (zustand store is here)
- /components  
```

I had the same issue with my zustand store not updating via function call after a HMR, but after refactoring my app to the following, it seemed to work:

```
- /app
- /app/constants (zustand store is here)
- /app/components  
```

If you have the same file structure, try to refactor it as described above.

**Comment by zhouccccc** [comment]
> > > Is "not working" meaning it doesn't refresh keeping the state? Did you create a separate file?
> > 
> > 
> > It's not that the state is lost, it's that the state-associated component doesn't receive a state update after the update method is called after HMR。The following is partical code in the separate store file
> > ```js
> > const useEditorStore = create(() => ({
> >   manual: false,
> > }));
> > 
> > export function updateManual(v) {
> >   console.log(v);
> >   useEditorStore.setState(() => ({
> >     manual: v,
> >   }));
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And in the Component file, I use `const manual = useEditorStore((state) => state.manual);` for state using
> 
> I was pulling my hair out on this issue, but I think I found a possible cause. Placing zustand stores in folders outside the entry point folder seems to break it.
> 
> I'm currently using Expo SDK51 for React Native, and most components for the app are contained within the `/app` directory.
> 
> In my project, I had the directories as follows:
> 
> ```
> - /app
> - /constants (zustand store is here)
> - /components  
> ```
> 
> I had the same issue with my zustand store not updating via function call after a HMR, but after refactoring my app to the following, it seemed to work:
> 
> ```
> - /app
> - /app/constants (zustand store is here)
> - /app/components  
> ```
> 
> If you have the same file structure, try to refactor it as described above.

nice suggestion！
Earlier, I checked my code and realized that a circular dependency was causing the error. But I didn't delve into why the circular dependency was causing this error ^_^
