### ISSUE TITLE
Proposal: Use NamedSet everywhere

### ISSUE THREAD

**Issue by funwithtriangles** [pmndrs/zustand#909]
`NamedSet` is a variation of `SetState` that accepts a third argument for passing in a string, for naming actions. This is used by the devtools middleware to have named logs.

Unfortunately having these two different types for `SetState` can cause all sorts of problems when chaining middlewares, where that third argument gets lost in the mix, etc.

What's the reason for not just using `NamedSet` by default? Why can't that optional argument always be there and we can get rid of an entire type? It doesn't always have to be consumed by other middlewares but it should always be passed on

**Comment by dai-shi** [comment]
Is this an issue only about TypeScript? (If so, v4 will address it.)
Or, do you see any issue with JavaScript without types?

**Comment by funwithtriangles** [comment]
It's about Typescript

**Comment by dai-shi** [comment]
We have a [few more PRs](https://github.com/pmndrs/zustand/milestone/1) to be merged before releasing v4.0.0-rc.0.
Meanwhile, you can try #725. https://ci.codesandbox.io/status/pmndrs/zustand/pr/725 👈 Find "Local Install Instructions"
