### ISSUE TITLE
createContext Typescript example broken?

### ISSUE THREAD

**Issue by chrisvasz** [pmndrs/zustand#919]
If I copy and paste the `createContext` Typescript example into a new file, I get several errors. I'm using 4.0.0-rc0. Here's the example for reference, annotated with the errors I get from typescript. What is the recommended way to use the `createContext` pattern now?

```tsx
import create from "zustand";
import createContext from "zustand/context";

type BearState = {
  bears: number
  increase: () => void
}

const { Provider, useStore } = createContext<BearState>();
// Type 'BearState' does not satisfy the constraint 'StoreApi<object>'.
//   Type 'BearState' is missing the following properties from type 'StoreApi<object>': setState, getState, subscribe, destroy ts(2344)

export default function App({ initialBears }: { initialBears: number }) {
  return (
    <Provider
      createStore={() =>
        create((set) => ({
          bears: initialBears,
          increase: () => set((state) => ({ bears: state.bears + 1 })),
        }))
        // Type 'UseBoundStore<StoreApi<object>>' is missing the following properties from type 'BearState': bears, increase ts(2739)
      }
    >
      <Button />
    </Provider>
  )
}
```

Also, FWIW, I get the following errors on zustand@3.7.2. If I add an annotation to create like `create<BearState>(set => ...` then everything works.
```tsx
    <Provider
      createStore={() =>
        create(set => ({
          bears: initialBears,
          increase: () => set(state => ({ bears: state.bears + 1 })),
          // for `set`: Object is of type 'unknown'. ts(2571)
          // Parameter 'state' implicitly has an 'any' type. ts(7006)
        }))
      }
    >
      <div />
    </Provider>
```

**Comment by dai-shi** [comment]
> If I copy and paste the `createContext` Typescript example into a new file, I get several errors. I'm using 4.0.0-rc0. Here's the example for reference, annotated with the errors I get from typescript. What is the recommended way to use the `createContext` pattern now?

Oops, we failed to fix the readme.

```js
import create, { StoreApi } from "zustand";

const { Provider, useStore } = createContext<StoreApi<BearState>>();
```
should work. Can you confirm?

It's described in docs/v4-migration.md. We should remove it from readme.md (and maybe add it in docs/typescript.md.)

> Also, FWIW, I get the following errors on zustand@3.7.2. If I add an annotation to create like `create<BearState>(set => ...` then everything works.

Yeah, so the example in readme was wrong for v3.
Even with v4, you need the annotation, right?

**Comment by chrisvasz** [comment]
> It's described in docs/v4-migration.md.

Ah, I should have checked the migration instructions!

> Can you confirm?

Yep, the `StoreApi` annotation works. Here's the final working version for me (note that I don't need the second annotation on the `create()` call):
```tsx
import type { StoreApi } from 'zustand';
import create from 'zustand';
import createContext from 'zustand/context';

type BearState = {
  bears: number;
  increase: () => void;
};

const { Provider, useStore } = createContext<StoreApi<BearState>>();

export default function App({ initialBears }: { initialBears: number }) {
  return (
    <Provider
      createStore={() =>
        create(set => ({
          bears: initialBears,
          increase: () => set(state => ({ bears: state.bears + 1 })),
        }))
      }
    >
      <Button />
    </Provider>
  );
}
```

**Comment by dai-shi** [comment]
Thanks for confirming. Good to know that you don't even need the second annotation.
Let's remove it from readme.
