### ISSUE TITLE
Unable to edit values in React devtools

### ISSUE THREAD

**Issue by crevulus** [pmndrs/zustand#928]
More of a feature request than an issue:

As with context, local state etc., it would be great if we could directly edit state variables that appear in React devtools under zustand's `BoundStore` hook name. Currently they are read-only, so it's tough to toggle states and change the UI.

**Comment by dai-shi** [comment]
@Aslemammad I think we did something for this, did we?

**Comment by crevulus** [comment]
@dai-shi Is it this? https://www.npmjs.com/package/simple-zustand-devtools

**Comment by Aslemammad** [comment]
@crevulus Hey, for now, I don't think it's possible to edit values from React devtools (hence you can do from redux devtools), but if it's a feature that you want us to implement, we're happy to do it if Daishi agrees! 

cc @dai-shi

**Comment by dai-shi** [comment]
@crevulus I confused React devtools with Redux devtools ext.
Our recommendation is to use Redux devtools ext.
We use [useDebugValue](https://reactjs.org/docs/hooks-reference.html#usedebugvalue) to show a value in React devtools, but it's read only as you se. I don't think any api is exposed to make it writable.

Closing as it's not actionable.
