### ISSUE TITLE
TypeScript 4.0.0 migration confusion.  

### ISSUE THREAD

**Issue by scott-lc** [pmndrs/zustand#935]
This is not a bug.  I just want to leave a trail of breadcrumbs for future travelers like myself that fail to thoroughly read the TypeScript [release notes](https://github.com/pmndrs/zustand/blob/main/docs/typescript.md).

If you are seeing this compiler error after upgrading to Zustand 4.0.0:

```
...
Types of property '$$storeMutators' are incompatible.
      Type '[["zustand/immer", never]] | undefined' is not assignable to type '[] | undefined'.
        Type '[["zustand/immer", never]]' is not assignable to type '[]'.
          Source has 1 element(s) but target allows only 0.ts
```

You need an extra set of parenthesis after your `create<T>(...)` call.  From the [release notes](https://github.com/pmndrs/zustand/blob/main/docs/typescript.md):

> When using TypeScript you just have to make a tiny change that instead of writing create(...) you'll have to write create<T>()(...) where T would be type of the state so as to annotate it.

**Comment by dai-shi** [comment]
We also have a section in readme. https://github.com/pmndrs/zustand#typescript-usage
Do you have any idea to mitigate your experience without introducing too much things in readme?
