### ISSUE TITLE
Calling action from inside action doesn't work with immer middleware (v4.0.0-rc.1)

### ISSUE THREAD

**Issue by julienben** [pmndrs/zustand#946]
Hey there!

Having a great time so far with Zustand but running into a major issue at the moment. As stated in the title, calling an action from inside another action isn't working for me. Here's a very basic example:

```js
const useStore = create(
  immer((set, get) => ({
    list: [],
    addToList: () =>
      set((state) => {
        state.list.push('a');
      }),
    addToListAction: () =>
      set((state) => {
        get().addToList();
      }),
  }))
);
```

Calling `addToList` from a component works but calling `addToListAction` has no effect. When you call `addToListAction`, the `addToList` function is actually called (checked with a `console.log`) but it has no effect on the state.

`state.addToList()` doesn't work either.

Am I doing something wrong or is this a bug?

Thanks for your help!!

**Comment by dai-shi** [comment]
```js
    addToListAction: () =>
      set((state) => {
        get().addToList();
      }),
```

That ☝️ looks strange. You shouldn't call actions inside `set`. Try this 👇 instead.

```js
    addToListAction: () => get().addToList()
```

**Comment by julienben** [comment]
Thanks for the advice! Tried it just now but it still doesn't work unfortunately :(

**Comment by dai-shi** [comment]
Actions are just functions. Not sure how the last line breaks. Can you show more code?

In such a complicated use case, I think using `produce` directly might be better than the middleware.

**Comment by dai-shi** [comment]
If you have further questions, please open a [new discussion](https://github.com/pmndrs/zustand/discussions/new).
