### ISSUE TITLE
What's new in 4.0？

### ISSUE THREAD

**Issue by siyi98** [pmndrs/zustand#948]
Hi, I am using zustand@3.x, and I see that zustand recently released 4.0.0-rc.1, so I wanna ask what new features will be in the 4.x version?

**Comment by dai-shi** [comment]
Thanks for asking. It has been asked in Discord too. So, I made a wiki page.
https://github.com/pmndrs/zustand/wiki/What-is-new-in-v4
Let me know if you have questions.

**Comment by siyi98** [comment]
Thanks
