### ISSUE TITLE
Type safety regression for set() in 4.0.0-rc.0+

### ISSUE THREAD

**Issue by ryanmcbrideusf** [pmndrs/zustand#952]
Hi, just started using this library. I noticed that within a `set()` function, I can set a variable to `undefined` even though `undefined` isn't supposed to be allowed. This can lead to bugs at runtime.

```ts
interface BearState {
  bears: number;
  breakBears: () => void;
}

const useStore = create<BearState>()((set) => ({
  bears: 0,
  breakBears: () => set({ bears: undefined }) // This should be illegal
}));
```

Demo: https://codesandbox.io/s/friendly-snowflake-n3c64k?file=/src/App.tsx

It seems like #317 is closely related, so this problem has been fixed in the past, but has now resurfaced. If I downgrade the library to v4.0.0-beta.3 or lower, then Typescript correctly warns me about the illegal type.

**Comment by dai-shi** [comment]
This is intentional. Please see https://github.com/pmndrs/zustand/blob/main/docs/v4-migration.md#partialstate-from-zustand-and-zustandvanilla
A little more context in #628.
