### ISSUE TITLE
multiple middleware

### ISSUE THREAD

**Issue by dancixx** [pmndrs/zustand#957]
Hi guys!

I tried to find it in prev issues and in the docs but couldn't find any information about the usage of multiple middlewares.
So I think something like below:

```ts
const useStorage = create<IStateProps>()(persist(immer(set => {})))
```

Will this work, or should I use the produce locally in the set method?

**Comment by dai-shi** [comment]
It should work in v4. Please have a try.

**Comment by dancixx** [comment]
@dai-shi okay. I check it and send some feedback about the result.

**Comment by dancixx** [comment]
@dai-shi It seems that is working fine.

**Comment by FrankFang** [comment]
Could you show your final code?
