### ISSUE TITLE
Warning: ReactDOM.render is no longer supported in React 18

### ISSUE THREAD

**Issue by alveshelio** [pmndrs/zustand#961]
When using Zustand 4.0.0-rc.1 with Nextjs 12.1.6 ,Chakra-ui 2.0.0 and React 18.01

I'm getting this error in the console:
**Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot**

In this codesandox: https://codesandbox.io/s/nextjs-chakra-ui-zustand-forked-0s8s0p?file=/pages/_document.tsx where I've commented all code related to Chakra-UI I have the error

In this codebandbox: https://codesandbox.io/s/nextjs-chakra-ui-zustand-forked-gbyqcg?file=/pages/index.tsx which it's the same as the other but with Chakra-ui and the error is the same.

**Comment by dai-shi** [comment]
Hi, zustand itself doesn't depend on react-dom. So, there's nothing we can do on our end.
You need to use `createRoot` as the message says. Maybe nextjs does it?
To confirm, you can try removing zustand in your codesandbox.

Closing. Feel free to add comments.
