### ISSUE TITLE
 The requested module 'react' is expected to be of type CommonJS (NEXT JS / Node 18)

### ISSUE THREAD

**Issue by PeterGKafkakis** [pmndrs/zustand#962]
Using Zustand(typescript) W/ Next JS and when im grabbing global state, i get this error

SyntaxError: The requested module 'react' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'react';
const { useDebugValue } = pkg;

Call Stack
<unknown>
node_modules/zustand/esm/index.mjs (4)
ModuleJob._instantiate
internal/modules/esm/module_job.js (97:21)
async ModuleJob.run
internal/modules/esm/module_job.js (136:20)
async Loader.import
internal/modules/esm/loader.js (179:24)

**Comment by dai-shi** [comment]
This sounds like a tough one.
#953 can be related, but a different error.

It's a bit surprising not so many people report this in either zustand or valtio.
Does this only happen in a new version of nextjs?

**Comment by dai-shi** [comment]
Thanks for confirming.
How does zustand v3.7.2 work?

**Comment by PeterGKafkakis** [comment]
Can confirm that it does work on Zustand v3.7.2

Not sure why it doesn't work with Zustand V4+

**Comment by dai-shi** [comment]
Hmm, interesting. Don't know why. We have `useDebugValue` in v3.7.2 too.

Can you please try this https://github.com/pmndrs/zustand/pull/953#issuecomment-1123420482 just in case?

**Comment by PeterGKafkakis** [comment]
@dai-shi Found the issue, was using the current version of Node v18+, switched back to Node LTS v16.15.0

When running Node V18+ was getting this issue every time

(node:38888) ExperimentalWarning: The ESM module 
loader is experimental.

When i went back to the LTS, that issue dissapeared. But everything is good to go now!

**Comment by dai-shi** [comment]
Thanks for digging in it. So, is this issue not zustand specific?

**Comment by PeterGKafkakis** [comment]
You are absolutely welcome, and thank you for checking into the issue for me as well. The issue is not zustand specific.

**Comment by dai-shi** [comment]
Okay, let me close this as nothing is actionable, until react community come up with a solution.
