### ISSUE TITLE
Support for serializing ImmutableJS with devtools

### ISSUE THREAD

**Issue by MeanBoyCousin** [pmndrs/zustand#967]
Inspecting my state inside Redux Devtools, values that should be Immutable Maps are being shown as plain objects. I believe this is causing issues when attempting to replay events as the Map methods are being called on plain objects for which they don't exist.

![image](https://user-images.githubusercontent.com/54942744/169591578-67ef863f-1364-4f6d-937f-1f60159d97f8.png)

As you can see pictured, the data in the red box should be a Map but appears as an object. When I try to skip back in time one step, the shown error occurs.

Any help would be appreciated as from what I can tell, ImmutableJS has been fully [supported by dev tools since v2.12.1.](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.12.1)

Thanks and as a new Zustand user, must say I am loving it.

**Comment by dai-shi** [comment]
The link you pointed says this:
```js
  serialize: {
    immutable: Immutable
  }
```
Please try it.

If you are a TS user, note that type definition in devtools middleware has an issue. Related: #716 
You need to work around with `as any` for now.

**Comment by MeanBoyCousin** [comment]
So indeed, passing the below as the second arg to `devtools` does work for the Immutable data structures. 😄 

```
{
    serialize: {
        immutable: Immutable,
    } as any
}
```

However, this now appears to be attempting to serialize the getter/setter functions into the store with errors (as pictured below.)

![image](https://user-images.githubusercontent.com/54942744/169694802-35c2e9c6-b360-4eba-84a5-284b91e157e0.png)

It also sadly hasn't solved the error being thrown in the original image. Any suggestions?

Thanks! 👍

**Comment by MeanBoyCousin** [comment]
Update to the above.

```js
{
    serialize: {
        options: {
            function: false
        },
        immutable: Immutable
    } as any
}
```

This code block stops the functions from being serialised in as well. Still facing issues with the original error though. Perhaps this might be better aimed at redux-devtools repo?

**Comment by dai-shi** [comment]
Yeah, if the issue can be reproduced with redux, then you should report there.
