### ISSUE TITLE
State does not update 

### ISSUE THREAD

**Issue by NasirKhalidQ** [pmndrs/zustand#970]
Hello,
First of all, thank you so much for this wonderful library! It looks really promising and awesome. 
I have been trying to get the state to update but for some reason, none of the examples from docs are working. I am on latest react version 18+ and my application uses Vite for bundling. I am using TailwindCSS v3+. 
I tried the very simple example from https://zustand-demo.pmnd.rs/ which just updates a counter by 1 onclick of the button but it didn't work. The state remains the same which is the initial one. Here is my code:

```
import { useState } from 'react';
import create from 'zustand';

function App() {
  // const [count, setCount] = useState(0);
  const useStore = create((set) => ({
    count: 1,
    inc: () => set((state) => ({ count: state.count + 1 })),
  }));
  const inc = useStore((state) => state.inc);

  const count = useStore((state) => state.count);

  return (
    <div className="App">
      <header className="App-header">
        <p>Hello Vite + React!</p>
        <p>
          <button type="button" onClick={inc}>
            count is: {count}
          </button>
        </p>
        <p>
          Edit <code>App.jsx</code> and save to test HMR updates.
        </p>
        <p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
          {' | '}
          <a
            className="App-link"
            href="https://vitejs.dev/guide/features.html"
            target="_blank"
            rel="noopener noreferrer"
          >
            Vite Docs
          </a>
        </p>
      </header>
    </div>
  );
}

export default App;
```

Here is the stackblitz URL: https://stackblitz.com/edit/vitejs-vite-fkyr2s?file=src/App.jsx
I am missing something very basic. Any help would be really appreciated. Thanks!

**Comment by alekangelov** [comment]
you're creating the zustand store inside of the component, meaning it will re-initialize on each render.

hoist it outside of App like so:

```js
import { useState } from 'react';
import create from 'zustand';

const useStore = create((set) => ({
  count: 1,
  inc: () => set((state) => ({ count: state.count + 1 })),
}));

function App() {

  const inc = useStore((state) => state.inc);

  const count = useStore((state) => state.count);
}

export default App;
```

**Comment by NasirKhalidQ** [comment]
@alekangelov OMG thank you so much Alek! Silly me, it is working perfectly now!
Many thanks for the quick reply! <3
