### ISSUE TITLE
Error when using inside React Native (Android) / Works fine with React Native web.

### ISSUE THREAD

**Issue by OsamaAburabie** [pmndrs/zustand#975]
I'm using the latest version when I try use Zustand with React Native (Android) on [Expo](https://expo.dev/) or [Bare React Native](https://reactnative.dev/).

I get this Error **TypeError: Object is not a function (near '...(0, _zustand.default)...')**
Again this only happen on Android but when I open the same app on **Web** it runs without errors.

`import create from "zustand";`
`const useStore = create((set) => ({`
`  bears: 0,`
`}));`

`export default function App() {`
`const bears = useStore(state => state.bears)`
`  return (...)`
`}`

**Comment by dai-shi** [comment]
So, v3 works,  but v4 doesn't?
Sounds like it expects CJS, but uses ESM.
(I wonder how metro bundler reads "exports" in package.json.)

Does anyone have ideas?

**Comment by OsamaAburabie** [comment]
@dai-shi I tried v3.5.14 with same error.
Maybe this issue is related to **Android** onIy.

I don't have the resources to test on **IOS** right now so I'm not sure.

but I can confirm that when I open the same **Expo** app on web its working without any issues.

**Comment by dai-shi** [comment]
Thanks for confirming.
I assume people had used react native with zustand v3.
So, this issue is with later expo versions or RN versions, maybe?

(I have no ideas about the possible fix. Help wanted.)

**Comment by dai-shi** [comment]
Closing this for now. If someone can repro the issue, let's reopen.

**Comment by liukkm** [comment]
Hello, have you solved it yet? I also ran into compatibility issues with Android version 8.0

**Comment by dai-shi** [comment]
No, it's not. Let's continue discussion in #2714.
