### ISSUE TITLE
Persist middleware - migrate multiple versions?

### ISSUE THREAD

**Issue by Faithfinder** [pmndrs/zustand#984]
Reading the docs and have a question (think it's worth adding the answer to the docs):

How would migrating multiple versions work? Ideally migrations would be applied 1-by-1, but I guess 0 needs to go directly to 10 if that's how the stars aligned? So, with every update I would need to maintain the migration from every version? 

I don't think it's a _huge_ problem, but still, would be good to know

**Comment by AnatoleLucet** [comment]
This is really up to you.
If you don't want to bother making a function for every possible version upgrade, maybe you could chain upgrades.
Here's a rough example:
```ts
export const useStore = create(persist(
  (set, get) => ({
    newField: 0, // let's say this field was named otherwise in version 0
  }),
  {
    // ...
    version: 1, // a migration will be triggered if the version in the storage mismatches this one
    migrate: (persistedState, version) => {
      const migrations = [
        (state) => {
          state.newField = state.oldField;
          delete state.oldField;

         return state
        },
        (state) => {
          state.newNewField = state.newField ;
          delete state.newField ;

          return state
        },
      ]

      let state = persistedState;

      for (let i = version; i < migrations.length; i++) {
         state = migration[i](state)
      }
      
      return state;
    },
  }
))
```

**Comment by dai-shi** [comment]
Closing as resolved.
