### ISSUE TITLE
Error: Missing getServerSnapshot, which is required for server-rendered content. 

### ISSUE THREAD

**Issue by ZMonk91** [pmndrs/zustand#987]
It seems this error happens whenever I try to use any hooks in Next.js. I saw this error referenced earlier in the issues but it said it was fixed in`4.0.0-beta.3`, I am using `4.0.0-rc.1` which I believe is a later update. Regardless, switching to `4.0.0-beta.3` still causes the same issue.
#886 

This is my first time trying Zustand, so perhaps I've set it up wrong.

Store.jsx: 
```
import create from 'zustand'

const useStore = create((set) => ({
    particles: 0,
    increaseParticles: () => set((state) => ({particles: state.particles +1})),
    removeAllParticles: () => set((state) => ({particles: 0})),
}))
```
Particles.jsx:
```
import React from "react";
import { HStack, Heading, Box, Badge, Center } from "@chakra-ui/react";
import { useStore } from "zustand";

export default function Particles() {

    // State
    const particles = useStore((state) => state.particles);

    // Responsiveness
    const responsiveTypography = {
        base: "sm",
        md: "md",
        lg: "lg"
    }
  return (
		<Center>
			<Heading size={responsiveTypography} >
				{particles} Particles
				<Badge colorScheme="green" size="lg">
					0/s
				</Badge>
			</Heading>
		</Center>
	)
};
```
![zustand_error](https://user-images.githubusercontent.com/29440338/171723270-a81688a6-5427-4ba2-9673-4f6968ee9dbe.png)

**Comment by ZMonk91** [comment]
I have found the solution, as reported in an earlier issue. My linter automatically imported `useStore from 'zustand'`. This should be made more clearly in the docs though.

Please do not use `import { useStore } from 'zustand'`. That's for different use cases.

Here you are: https://codesandbox.io/s/suspicious-river-pxq7t5?file=/src/Home.jsx

_Originally posted by @dai-shi in https://github.com/pmndrs/zustand/issues/963#issuecomment-1133588639_

**Comment by dai-shi** [comment]
> My linter automatically imported

Wow, I overlooked this situation. How could it be made more clearly in docs? Suggestion PRs are welcome.

**Comment by appohfaiths** [comment]
@dai-shi It's my first time using Zustand today and I encountered the same error. Can the docs be clearer on specifying where 'useStore' should be imported from since 'useStore' is what's used as the example. I scanned several webpages before finding the solution here.

**Comment by dai-shi** [comment]
@appohfaiths I think we fixed most of `useStore` usage in examples, they should be `useBoundStore` or something else. If there's still something missing, please feel free to open a PR.
