### ISSUE TITLE
How to compose middleware with TypeScript

### ISSUE THREAD

**Issue by julianklumpers** [pmndrs/zustand#994]
in version 3 i could do something like this:

```ts
type CounterStore = {
  count: 0;
  increase(): void;
};

let store: StateCreator<
  CounterStore,
  SetState<CounterStore>,
  GetState<CounterStore>,
  StoreApiWithPersist<CounterStore> & StoreApiWithDevtools<CounterStore>
> = (set, get) => ({
  count: 0,
  increase: () => set(() => ({ count: get().count + 1 })),
});

store = devtools(store, 'counter');
store = persist(store, {
  name: 'store/counter',
  version: 1,
});

export const useCounter = create(store);
```

in my opinion, this is very readable. However, in version 4 with the new types i cannot get the store types properly anymore.

```ts
import create, { StateCreator } from 'zustand';
import { devtools, persist } from 'zustand/middleware';

type CountStore = {
  count: number;
  increase(): void;
};

let store: StateCreator<CountStore, [], [['zustand/persist', CountStore], ['zustand/devtools', CountStore]]> = (
  set,
  get,
) => ({
  count: 0,
  increase: () => set(() => ({ count: get().count + 1 })),
});

// ts error here
store = persist(store, { name: 'store/counter', version: 1 });
// ts error here
store = devtools(store, { name: 'counter' });

// here is everything fine and ts infers middleware properly
export const useCount = create(store);
```
it keeps compaining about the type of the store does not meet the middleware types.

`Argument of type 'StateCreator<CountStore, [], [["zustand/persist", CountStore], ["zustand/devtools", CountStore]], CountStore>' is not assignable to parameter of type 'StateCreator<CountStore, [["zustand/persist", unknown]], [["zustand/persist", CountStore], ["zustand/devtools", CountStore]], CountStore>'.`

Anyone know how to properly type this? any help is welcome. thank you!

**Comment by dai-shi** [comment]
@devanshj Please help on this.

**Comment by devanshj** [comment]
One can't write the above code for the same reason one can't write the following code...

```ts
let x: number = "a0"
x = x.replace("a", "")
x = Number(x)
```

A type of a variable can't be declared based on the future/final value. Moreover we also rely on contextual inference as the docs say. The older version probably works because it didn't have great types.

So it's not possible to write middlewares like so and make it compile. One can of course use `any` (ie `store = persist(store as any, ...`) or `// @ts-ignore` it that feels like a viable option.

**Comment by qmn-snowflake** [comment]
@devanshj I tried `as any` way for subscribeWithSelector middleware but `useStore.subscribe(selector, console.log)` will complain `Expected 1 arguments, but got 2.ts(2554)`

**Comment by qmn1711** [comment]
@devanshj I tried as any way for subscribeWithSelector middleware but useStore.subscribe(selector, console.log) will complain Expected 1 arguments, but got 2.ts(2554)

**Comment by devanshj** [comment]
> @devanshj I tried as any way for subscribeWithSelector middleware but useStore.subscribe(selector, console.log) will complain Expected 1 arguments, but got 2.ts(2554)

Can't help without a ts playground reproduction! Tip: When writing middlewares if possible stick with the way shown in the [typescript docs](https://github.com/pmndrs/zustand/blob/main/docs/typescript.md#using-middlewares).

**Comment by dai-shi** [comment]
Please open [a new discussion](https://github.com/pmndrs/zustand/discussions/new) with a small reproduction.
