### ISSUE TITLE
How to subscribe to rapid updates without performance loss using createContext()

### ISSUE THREAD

**Issue by ScarletJack** [pmndrs/zustand#996]
Hello

From one of the examples:  `const scratchRef = useRef(useStore.getState().scratches)`

The useStore imported from `zustand` has a `.getState()` method, whereas  the useStore method from `createContext()` imported from `zustand/context` does not. 

How would one handle rapid state updates using `createContext`?

**Comment by wuifdesign** [comment]
is this what you are looking for?

```js
const { useStoreApi } = createContext()

const Test = () => {
  const storeApi = useStoreApi()
  const scratchRef = useRef(storeApi.getState().scratches)

  return null
}

```

**Comment by ScarletJack** [comment]
That's exactly it, solves my issue perfectly. Thank you 👍
